// SPDX-License-Identifier: MIT
//! The adapter's table (wifi_osi_funcs_t), in the order and at the size
//! the libraries were built against: adapter version 9, 120 words, the
//! magic last. The libraries check the version and the magic when they
//! are handed it, and call every other entry by its place, so the checks
//! below keep the places where they must be.
//!
//! Every entry is a function of the adapter's, in the file for its group;
//! one (`coex_condition_set`) the libraries never call, and is null.

const sdk = @import("sdk");
const sync = @import("sync.zig");
const queue = @import("queue.zig");
const task = @import("task.zig");
const timer = @import("timer.zig");
const memory = @import("memory.zig");
const intr = @import("intr.zig");
const system = @import("system.zig");
const events = @import("../events.zig");

/// ESP_WIFI_OS_ADAPTER_VERSION and _MAGIC.
pub const adapter_version: i32 = 9;
pub const adapter_magic: i32 = @bitCast(@as(u32, 0xDEADBEAF));

pub const OsiFuncs = extern struct {
    version: i32,
    env_is_chip: ?*const anyopaque,
    set_intr: ?*const anyopaque,
    clear_intr: ?*const anyopaque,
    set_isr: ?*const anyopaque,
    ints_on: ?*const anyopaque,
    ints_off: ?*const anyopaque,
    is_from_isr: ?*const anyopaque,
    spin_lock_create: ?*const anyopaque,
    spin_lock_delete: ?*const anyopaque,
    wifi_int_disable: ?*const anyopaque,
    wifi_int_restore: ?*const anyopaque,
    task_yield_from_isr: ?*const anyopaque,
    semphr_create: ?*const anyopaque,
    semphr_delete: ?*const anyopaque,
    semphr_take: ?*const anyopaque,
    semphr_give: ?*const anyopaque,
    wifi_thread_semphr_get: ?*const anyopaque,
    mutex_create: ?*const anyopaque,
    recursive_mutex_create: ?*const anyopaque,
    mutex_delete: ?*const anyopaque,
    mutex_lock: ?*const anyopaque,
    mutex_unlock: ?*const anyopaque,
    queue_create: ?*const anyopaque,
    queue_delete: ?*const anyopaque,
    queue_send: ?*const anyopaque,
    queue_send_from_isr: ?*const anyopaque,
    queue_send_to_back: ?*const anyopaque,
    queue_send_to_front: ?*const anyopaque,
    queue_recv: ?*const anyopaque,
    queue_msg_waiting: ?*const anyopaque,
    event_group_create: ?*const anyopaque,
    event_group_delete: ?*const anyopaque,
    event_group_set_bits: ?*const anyopaque,
    event_group_clear_bits: ?*const anyopaque,
    event_group_wait_bits: ?*const anyopaque,
    task_create_pinned_to_core: ?*const anyopaque,
    task_create: ?*const anyopaque,
    task_delete: ?*const anyopaque,
    task_delay: ?*const anyopaque,
    task_ms_to_tick: ?*const anyopaque,
    task_get_current_task: ?*const anyopaque,
    task_get_max_priority: ?*const anyopaque,
    malloc: ?*const anyopaque,
    free: ?*const anyopaque,
    event_post: ?*const anyopaque,
    get_free_heap_size: ?*const anyopaque,
    rand: ?*const anyopaque,
    dport_access_stall_other_cpu_start_wrap: ?*const anyopaque,
    dport_access_stall_other_cpu_end_wrap: ?*const anyopaque,
    wifi_pm_sleep_lock_acquire: ?*const anyopaque,
    wifi_pm_sleep_lock_release: ?*const anyopaque,
    phy_disable: ?*const anyopaque,
    phy_enable: ?*const anyopaque,
    phy_update_country_info: ?*const anyopaque,
    read_mac: ?*const anyopaque,
    timer_arm: ?*const anyopaque,
    timer_disarm: ?*const anyopaque,
    timer_done: ?*const anyopaque,
    timer_setfn: ?*const anyopaque,
    timer_arm_us: ?*const anyopaque,
    wifi_reset_mac: ?*const anyopaque,
    wifi_clock_enable: ?*const anyopaque,
    wifi_clock_disable: ?*const anyopaque,
    wifi_rtc_enable_iso: ?*const anyopaque,
    wifi_rtc_disable_iso: ?*const anyopaque,
    esp_timer_get_time: ?*const anyopaque,
    nvs_set_i8: ?*const anyopaque,
    nvs_get_i8: ?*const anyopaque,
    nvs_set_u8: ?*const anyopaque,
    nvs_get_u8: ?*const anyopaque,
    nvs_set_u16: ?*const anyopaque,
    nvs_get_u16: ?*const anyopaque,
    nvs_open: ?*const anyopaque,
    nvs_close: ?*const anyopaque,
    nvs_commit: ?*const anyopaque,
    nvs_set_blob: ?*const anyopaque,
    nvs_get_blob: ?*const anyopaque,
    nvs_erase_key: ?*const anyopaque,
    get_random: ?*const anyopaque,
    get_time: ?*const anyopaque,
    random: ?*const anyopaque,
    slowclk_cal_get: ?*const anyopaque,
    log_write: ?*const anyopaque,
    log_writev: ?*const anyopaque,
    log_timestamp: ?*const anyopaque,
    malloc_internal: ?*const anyopaque,
    realloc_internal: ?*const anyopaque,
    calloc_internal: ?*const anyopaque,
    zalloc_internal: ?*const anyopaque,
    wifi_malloc: ?*const anyopaque,
    wifi_realloc: ?*const anyopaque,
    wifi_calloc: ?*const anyopaque,
    wifi_zalloc: ?*const anyopaque,
    wifi_create_queue: ?*const anyopaque,
    wifi_delete_queue: ?*const anyopaque,
    coex_init: ?*const anyopaque,
    coex_deinit: ?*const anyopaque,
    coex_enable: ?*const anyopaque,
    coex_disable: ?*const anyopaque,
    coex_status_get: ?*const anyopaque,
    coex_condition_set: ?*const anyopaque,
    coex_wifi_request: ?*const anyopaque,
    coex_wifi_release: ?*const anyopaque,
    coex_wifi_channel_set: ?*const anyopaque,
    coex_event_duration_get: ?*const anyopaque,
    coex_pti_get: ?*const anyopaque,
    coex_schm_status_bit_clear: ?*const anyopaque,
    coex_schm_status_bit_set: ?*const anyopaque,
    coex_schm_interval_set: ?*const anyopaque,
    coex_schm_interval_get: ?*const anyopaque,
    coex_schm_curr_period_get: ?*const anyopaque,
    coex_schm_curr_phase_get: ?*const anyopaque,
    coex_schm_process_restart: ?*const anyopaque,
    coex_schm_register_cb: ?*const anyopaque,
    coex_register_start_cb: ?*const anyopaque,
    coex_schm_flexible_period_set: ?*const anyopaque,
    coex_schm_flexible_period_get: ?*const anyopaque,
    coex_schm_get_phase_by_idx: ?*const anyopaque,
    magic: i32,
};

comptime {
    if (@sizeOf(OsiFuncs) != 120 * 4) @compileError("the adapter table must be 120 words");
    if (@offsetOf(OsiFuncs, "magic") != 0x1DC) @compileError("the adapter table's magic must be at 0x1DC");
}

pub const funcs: OsiFuncs = .{
    .version = adapter_version,
    .env_is_chip = &system.envIsChip,
    .set_intr = &intr.setIntr,
    .clear_intr = &intr.clearIntr,
    .set_isr = &intr.setIsr,
    .ints_on = &intr.intsOn,
    .ints_off = &intr.intsOff,
    .is_from_isr = &intr.isFromIsr,
    .spin_lock_create = &sync.spinLockCreate,
    .spin_lock_delete = &sync.spinLockDelete,
    .wifi_int_disable = &sync.intDisable,
    .wifi_int_restore = &sync.intRestore,
    .task_yield_from_isr = &task.taskYieldFromIsr,
    .semphr_create = &sync.semphrCreate,
    .semphr_delete = &sync.semphrDelete,
    .semphr_take = &sync.semphrTake,
    .semphr_give = &sync.semphrGive,
    .wifi_thread_semphr_get = &sync.threadSemphrGet,
    .mutex_create = &sync.mutexCreate,
    .recursive_mutex_create = &sync.mutexCreate,
    .mutex_delete = &sync.mutexDelete,
    .mutex_lock = &sync.mutexLock,
    .mutex_unlock = &sync.mutexUnlock,
    .queue_create = &queue.queueCreate,
    .queue_delete = &queue.queueDelete,
    .queue_send = &queue.queueSend,
    .queue_send_from_isr = &queue.queueSendFromIsr,
    .queue_send_to_back = &queue.queueSendToBack,
    .queue_send_to_front = &queue.queueSendToFront,
    .queue_recv = &queue.queueRecv,
    .queue_msg_waiting = &queue.queueMsgWaiting,
    .event_group_create = &sync.eventGroupCreate,
    .event_group_delete = &sync.eventGroupDelete,
    .event_group_set_bits = &sync.eventGroupSetBits,
    .event_group_clear_bits = &sync.eventGroupClearBits,
    .event_group_wait_bits = &sync.eventGroupWaitBits,
    .task_create_pinned_to_core = &task.taskCreatePinnedToCore,
    .task_create = &task.taskCreate,
    .task_delete = &task.taskDelete,
    .task_delay = &task.taskDelay,
    .task_ms_to_tick = &task.taskMsToTick,
    .task_get_current_task = &task.taskGetCurrentTask,
    .task_get_max_priority = &task.taskGetMaxPriority,
    .malloc = &memory.malloc,
    .free = &memory.free,
    .event_post = &events.post,
    .get_free_heap_size = &memory.freeHeapSize,
    .rand = &system.rand,
    .dport_access_stall_other_cpu_start_wrap = &system.nothing,
    .dport_access_stall_other_cpu_end_wrap = &system.nothing,
    .wifi_pm_sleep_lock_acquire = &system.nothing,
    .wifi_pm_sleep_lock_release = &system.nothing,
    .phy_disable = &system.phyDisable,
    .phy_enable = &system.phyEnable,
    .phy_update_country_info = &system.phyUpdateCountryInfo,
    .read_mac = &system.readMac,
    .timer_arm = &timer.timerArm,
    .timer_disarm = &timer.timerDisarm,
    .timer_done = &timer.timerDone,
    .timer_setfn = &timer.timerSetfn,
    .timer_arm_us = &timer.timerArmUs,
    .wifi_reset_mac = &system.wifiResetMac,
    .wifi_clock_enable = &system.nothing,
    .wifi_clock_disable = &system.nothing,
    .wifi_rtc_enable_iso = &system.nothing,
    .wifi_rtc_disable_iso = &system.nothing,
    .esp_timer_get_time = &system.timerGetTime,
    .nvs_set_i8 = &system.nvsSetI8,
    .nvs_get_i8 = &system.nvsGetI8,
    .nvs_set_u8 = &system.nvsSetU8,
    .nvs_get_u8 = &system.nvsGetU8,
    .nvs_set_u16 = &system.nvsSetU16,
    .nvs_get_u16 = &system.nvsGetU16,
    .nvs_open = &system.nvsOpen,
    .nvs_close = &system.nvsClose,
    .nvs_commit = &system.nvsCommit,
    .nvs_set_blob = &system.nvsSetBlob,
    .nvs_get_blob = &system.nvsGetBlob,
    .nvs_erase_key = &system.nvsEraseKey,
    .get_random = &system.getRandom,
    .get_time = &system.getTime,
    .random = &system.random,
    .slowclk_cal_get = &system.slowClockCal,
    .log_write = &system.logWrite,
    .log_writev = &system.logWritev,
    .log_timestamp = &system.logTimestamp,
    .malloc_internal = &memory.malloc,
    .realloc_internal = &memory.realloc,
    .calloc_internal = &memory.calloc,
    .zalloc_internal = &memory.zalloc,
    .wifi_malloc = &memory.malloc,
    .wifi_realloc = &memory.realloc,
    .wifi_calloc = &memory.calloc,
    .wifi_zalloc = &memory.zalloc,
    .wifi_create_queue = &queue.wifiCreateQueue,
    .wifi_delete_queue = &queue.wifiDeleteQueue,
    .coex_init = &system.coexZero,
    .coex_deinit = &system.nothing,
    .coex_enable = &system.coexZero,
    .coex_disable = &system.nothing,
    .coex_status_get = &system.coexStatusGet,
    .coex_condition_set = null,
    .coex_wifi_request = &system.coexRequest,
    .coex_wifi_release = &system.coexRelease,
    .coex_wifi_channel_set = &system.coexChannelSet,
    .coex_event_duration_get = &system.coexDurationGet,
    .coex_pti_get = &system.coexPtiGet,
    .coex_schm_status_bit_clear = &system.coexStatusBit,
    .coex_schm_status_bit_set = &system.coexStatusBit,
    .coex_schm_interval_set = &system.coexIntervalSet,
    .coex_schm_interval_get = &system.coexStatusGet,
    .coex_schm_curr_period_get = &system.coexPeriodGet,
    .coex_schm_curr_phase_get = &system.coexPhaseGet,
    .coex_schm_process_restart = &system.coexZero,
    .coex_schm_register_cb = &system.coexRegisterCb,
    .coex_register_start_cb = &system.coexRegisterStartCb,
    .coex_schm_flexible_period_set = &system.coexFlexiblePeriodSet,
    .coex_schm_flexible_period_get = &system.coexFlexiblePeriodGet,
    .coex_schm_get_phase_by_idx = &system.coexPhaseByIndex,
    .magic = adapter_magic,
};
