// SPDX-License-Identifier: MIT
//! Host tests of the modules on the disk: the parts of each that need no
//! hardware. Some of them bring up exec and utility.library the way the
//! ROM's own tests do, through the named import `host_rom`, which the
//! system's build hands this root when it runs them.

test {
    _ = @import("classes/gadgets/textedit/text.zig");
    _ = @import("classes/gadgets/textedit/undo.zig");
    _ = @import("devs/sdcard/card.zig");
    _ = @import("prefs/tests/prefs.zig");
    _ = @import("devs/sdcard/sdspi.zig");
    _ = @import("devs/networks/tests/api.zig");
    _ = @import("devs/networks/tests/openeth.zig");
    _ = @import("devs/networks/wifi/tests/wifi.zig");
    _ = @import("devs/networks/wifi/tests/wpa.zig");
    _ = @import("devs/networks/wifi/tests/ie.zig");
    _ = @import("devs/networks/wifi/tests/eapol.zig");
    _ = @import("devs/telnet/filter.zig");
    _ = @import("libs/bsdsocket/tests/bsdsocket.zig");
    _ = @import("libs/bsdsocket/tests/arp.zig");
    _ = @import("libs/bsdsocket/tests/icmp.zig");
    _ = @import("libs/bsdsocket/tests/tcp.zig");
    _ = @import("libs/bsdsocket/tests/netif.zig");
    _ = @import("libs/bsdsocket/tests/dhcp.zig");
    _ = @import("libs/bsdsocket/tests/names.zig");
    _ = @import("libs/bsdsocket/tests/address.zig");
    _ = @import("libs/bsdsocket/tests/ip6.zig");
    _ = @import("libs/bsdsocket/tests/nd.zig");
    _ = @import("libs/bsdsocket/tests/socket6.zig");
    _ = @import("libs/crypto/tests/crypto.zig");
    _ = @import("libs/crypto/tests/keys.zig");
    _ = @import("libs/tls/tests/x509.zig");
    _ = @import("libs/tls/tests/tls13.zig");
    _ = @import("libs/tls/tls_lvo.zig");
    _ = @import("libs/rdb/tests/rdb.zig");
    _ = @import("libs/modbus/tests/modbus.zig");
    _ = @import("libs/diskfont/tests/diskfont.zig");
    _ = @import("libs/truetype/tests/truetype.zig");
    _ = @import("libs/asl/tests/asl.zig");
    _ = @import("libs/iffparse/tests/iffparse.zig");
    _ = @import("libs/datatypes/tests/datatypes.zig");
    _ = @import("c/adddatatypes/tests/descriptor.zig");
    _ = @import("c/net/addnetinterface/config.zig");
    _ = @import("c/net/timesync/tests/zone.zig");
    _ = @import("c/net/httpget/http.zig");
    _ = @import("devs/handlers/fat/_fat.zig");
    _ = @import("devs/handlers/fat/testmedia.zig");
    _ = @import("devs/handlers/fat/cache.zig");
    _ = @import("devs/handlers/fat/fat32/layout.zig");
    _ = @import("devs/handlers/fat/fat32/table.zig");
    _ = @import("devs/handlers/fat/fat32/names.zig");
    _ = @import("devs/handlers/fat/fat32/dir.zig");
    _ = @import("devs/handlers/fat/fat32/fs.zig");
    _ = @import("devs/handlers/fat/exfat/layout.zig");
    _ = @import("devs/handlers/fat/exfat/table.zig");
    _ = @import("devs/handlers/fat/exfat/bitmap.zig");
    _ = @import("devs/handlers/fat/exfat/upcase.zig");
    _ = @import("devs/handlers/fat/exfat/names.zig");
    _ = @import("devs/handlers/fat/exfat/dir.zig");
    _ = @import("devs/handlers/fat/exfat/fs.zig");
    _ = @import("devs/handlers/fat/fat.zig");
    _ = @import("devs/handlers/fat/tests/_fat.zig");
    _ = @import("devs/handlers/fat/tests/names.zig");
    _ = @import("devs/handlers/fat/tests/dir.zig");
    _ = @import("devs/handlers/fat/tests/fs.zig");
    _ = @import("devs/handlers/fat/tests/exfat_dir.zig");
    _ = @import("devs/handlers/fat/tests/exfat_fs.zig");
    _ = @import("classes/datatypes/png/inflate.zig");
    _ = @import("classes/datatypes/png/decode.zig");
    _ = @import("classes/datatypes/gif/lzw.zig");
    _ = @import("classes/datatypes/gif/decode.zig");
    _ = @import("libs/modbus/protocol/pdu.zig");
    _ = @import("libs/modbus/protocol/rtu.zig");
    _ = @import("libs/modbus/protocol/mbap.zig");
    _ = @import("classes/datatypes/lottie/json.zig");
    _ = @import("classes/datatypes/lottie/property.zig");
    _ = @import("classes/datatypes/lottie/raster.zig");
    _ = @import("classes/datatypes/lottie/render.zig");
    _ = @import("classes/datatypes/ilbm/planes.zig");
    _ = @import("classes/datatypes/bmp/decode.zig");
    _ = @import("classes/datatypes/jpeg/idct.zig");
    _ = @import("classes/datatypes/jpeg/decode.zig");
    _ = @import("classes/datatypes/markdown/parse.zig");
    _ = @import("classes/gadgets/tests/classes.zig");
    _ = @import("classes/gadgets/colorwheel/_colour.zig");
}
