// SPDX-License-Identifier: MIT
//! The ESP32-P4's peripheral interrupt sources, by name: exec's interrupt
//! numbers (SetIntVector, AddIntServer): the interrupt matrix's sources,
//! 0 to 127, each routed to a CPU line of its own while a handler or server
//! is on it.
//!
//! From ESP-IDF v6.1's soc/esp32p4/include/soc/interrupts.h:
//! ETS_<name>_INTR_SOURCE is INTB_<name> (ETS_<name>_SOURCE too). The
//! sources only a v3.0 chip has (133 to 135) are left out: the boards'
//! chips are v1.3.

/// ETS_LP_RTC_INTR_SOURCE
pub const INTB_LP_RTC: u32 = 0;
/// ETS_LP_WDT_INTR_SOURCE
pub const INTB_LP_WDT: u32 = 1;
/// ETS_LP_TIMER_REG0_INTR_SOURCE
pub const INTB_LP_TIMER_REG0: u32 = 2;
/// ETS_LP_TIMER_REG1_INTR_SOURCE
pub const INTB_LP_TIMER_REG1: u32 = 3;
/// ETS_MB_HP_INTR_SOURCE
pub const INTB_MB_HP: u32 = 4;
/// ETS_MB_LP_INTR_SOURCE
pub const INTB_MB_LP: u32 = 5;
/// ETS_PMU_0_INTR_SOURCE
pub const INTB_PMU_0: u32 = 6;
/// ETS_PMU_1_INTR_SOURCE
pub const INTB_PMU_1: u32 = 7;
/// ETS_LP_ANAPERI_INTR_SOURCE
pub const INTB_LP_ANAPERI: u32 = 8;
/// ETS_LP_ADC_INTR_SOURCE
pub const INTB_LP_ADC: u32 = 9;
/// ETS_LP_GPIO_INTR_SOURCE
pub const INTB_LP_GPIO: u32 = 10;
/// ETS_LP_I2C_INTR_SOURCE
pub const INTB_LP_I2C: u32 = 11;
/// ETS_LP_I2S_INTR_SOURCE
pub const INTB_LP_I2S: u32 = 12;
/// ETS_LP_SPI_INTR_SOURCE
pub const INTB_LP_SPI: u32 = 13;
/// ETS_LP_TOUCH_INTR_SOURCE
pub const INTB_LP_TOUCH: u32 = 14;
/// ETS_LP_TSENS_INTR_SOURCE
pub const INTB_LP_TSENS: u32 = 15;
/// ETS_LP_UART_INTR_SOURCE
pub const INTB_LP_UART: u32 = 16;
/// ETS_LP_EFUSE_INTR_SOURCE
pub const INTB_LP_EFUSE: u32 = 17;
/// ETS_LP_SW_INTR_SOURCE
pub const INTB_LP_SW: u32 = 18;
/// ETS_LP_SYSREG_INTR_SOURCE
pub const INTB_LP_SYSREG: u32 = 19;
/// ETS_LP_HUK_INTR_SOURCE
pub const INTB_LP_HUK: u32 = 20;
/// ETS_SYS_ICM_INTR_SOURCE
pub const INTB_SYS_ICM: u32 = 21;
/// ETS_USB_SERIAL_JTAG_INTR_SOURCE
pub const INTB_USB_SERIAL_JTAG: u32 = 22;
/// ETS_SDIO_HOST_INTR_SOURCE
pub const INTB_SDIO_HOST: u32 = 23;
/// ETS_DW_GDMA_INTR_SOURCE
pub const INTB_DW_GDMA: u32 = 24;
/// ETS_SPI2_INTR_SOURCE
pub const INTB_SPI2: u32 = 25;
/// ETS_SPI3_INTR_SOURCE
pub const INTB_SPI3: u32 = 26;
/// ETS_I2S0_INTR_SOURCE
pub const INTB_I2S0: u32 = 27;
/// ETS_I2S1_INTR_SOURCE
pub const INTB_I2S1: u32 = 28;
/// ETS_I2S2_INTR_SOURCE
pub const INTB_I2S2: u32 = 29;
/// ETS_UHCI0_INTR_SOURCE
pub const INTB_UHCI0: u32 = 30;
/// ETS_UART0_INTR_SOURCE
pub const INTB_UART0: u32 = 31;
/// ETS_UART1_INTR_SOURCE
pub const INTB_UART1: u32 = 32;
/// ETS_UART2_INTR_SOURCE
pub const INTB_UART2: u32 = 33;
/// ETS_UART3_INTR_SOURCE
pub const INTB_UART3: u32 = 34;
/// ETS_UART4_INTR_SOURCE
pub const INTB_UART4: u32 = 35;
/// ETS_LCD_CAM_INTR_SOURCE
pub const INTB_LCD_CAM: u32 = 36;
/// ETS_ADC_INTR_SOURCE
pub const INTB_ADC: u32 = 37;
/// ETS_PWM0_INTR_SOURCE
pub const INTB_PWM0: u32 = 38;
/// ETS_PWM1_INTR_SOURCE
pub const INTB_PWM1: u32 = 39;
/// ETS_TWAI0_INTR_SOURCE
pub const INTB_TWAI0: u32 = 40;
/// ETS_TWAI1_INTR_SOURCE
pub const INTB_TWAI1: u32 = 41;
/// ETS_TWAI2_INTR_SOURCE
pub const INTB_TWAI2: u32 = 42;
/// ETS_RMT_INTR_SOURCE
pub const INTB_RMT: u32 = 43;
/// ETS_I2C0_INTR_SOURCE
pub const INTB_I2C0: u32 = 44;
/// ETS_I2C1_INTR_SOURCE
pub const INTB_I2C1: u32 = 45;
/// ETS_TG0_T0_INTR_SOURCE
pub const INTB_TG0_T0: u32 = 46;
/// ETS_TG0_T1_INTR_SOURCE
pub const INTB_TG0_T1: u32 = 47;
/// ETS_TG0_WDT_LEVEL_INTR_SOURCE
pub const INTB_TG0_WDT_LEVEL: u32 = 48;
/// ETS_TG1_T0_INTR_SOURCE
pub const INTB_TG1_T0: u32 = 49;
/// ETS_TG1_T1_INTR_SOURCE
pub const INTB_TG1_T1: u32 = 50;
/// ETS_TG1_WDT_LEVEL_INTR_SOURCE
pub const INTB_TG1_WDT_LEVEL: u32 = 51;
/// ETS_LEDC_INTR_SOURCE
pub const INTB_LEDC: u32 = 52;
/// ETS_SYSTIMER_TARGET0_INTR_SOURCE
pub const INTB_SYSTIMER_TARGET0: u32 = 53;
/// ETS_SYSTIMER_TARGET1_INTR_SOURCE
pub const INTB_SYSTIMER_TARGET1: u32 = 54;
/// ETS_SYSTIMER_TARGET2_INTR_SOURCE
pub const INTB_SYSTIMER_TARGET2: u32 = 55;
/// ETS_AHB_PDMA_IN_CH0_INTR_SOURCE
pub const INTB_AHB_PDMA_IN_CH0: u32 = 56;
/// ETS_AHB_PDMA_IN_CH1_INTR_SOURCE
pub const INTB_AHB_PDMA_IN_CH1: u32 = 57;
/// ETS_AHB_PDMA_IN_CH2_INTR_SOURCE
pub const INTB_AHB_PDMA_IN_CH2: u32 = 58;
/// ETS_AHB_PDMA_OUT_CH0_INTR_SOURCE
pub const INTB_AHB_PDMA_OUT_CH0: u32 = 59;
/// ETS_AHB_PDMA_OUT_CH1_INTR_SOURCE
pub const INTB_AHB_PDMA_OUT_CH1: u32 = 60;
/// ETS_AHB_PDMA_OUT_CH2_INTR_SOURCE
pub const INTB_AHB_PDMA_OUT_CH2: u32 = 61;
/// ETS_AXI_PDMA_IN_CH0_INTR_SOURCE
pub const INTB_AXI_PDMA_IN_CH0: u32 = 62;
/// ETS_AXI_PDMA_IN_CH1_INTR_SOURCE
pub const INTB_AXI_PDMA_IN_CH1: u32 = 63;
/// ETS_AXI_PDMA_IN_CH2_INTR_SOURCE
pub const INTB_AXI_PDMA_IN_CH2: u32 = 64;
/// ETS_AXI_PDMA_OUT_CH0_INTR_SOURCE
pub const INTB_AXI_PDMA_OUT_CH0: u32 = 65;
/// ETS_AXI_PDMA_OUT_CH1_INTR_SOURCE
pub const INTB_AXI_PDMA_OUT_CH1: u32 = 66;
/// ETS_AXI_PDMA_OUT_CH2_INTR_SOURCE
pub const INTB_AXI_PDMA_OUT_CH2: u32 = 67;
/// ETS_RSA_INTR_SOURCE
pub const INTB_RSA: u32 = 68;
/// ETS_AES_INTR_SOURCE
pub const INTB_AES: u32 = 69;
/// ETS_SHA_INTR_SOURCE
pub const INTB_SHA: u32 = 70;
/// ETS_ECC_INTR_SOURCE
pub const INTB_ECC: u32 = 71;
/// ETS_ECDSA_INTR_SOURCE
pub const INTB_ECDSA: u32 = 72;
/// ETS_KM_INTR_SOURCE
pub const INTB_KM: u32 = 73;
/// ETS_GPIO_INTR0_SOURCE
pub const INTB_GPIO_INTR0: u32 = 74;
/// ETS_GPIO_INTR1_SOURCE
pub const INTB_GPIO_INTR1: u32 = 75;
/// ETS_GPIO_INTR2_SOURCE
pub const INTB_GPIO_INTR2: u32 = 76;
/// ETS_GPIO_INTR3_SOURCE
pub const INTB_GPIO_INTR3: u32 = 77;
/// ETS_GPIO_PAD_COMP_INTR_SOURCE
pub const INTB_GPIO_PAD_COMP: u32 = 78;
/// ETS_FROM_CPU_INTR0_SOURCE
pub const INTB_FROM_CPU_INTR0: u32 = 79;
/// ETS_FROM_CPU_INTR1_SOURCE
pub const INTB_FROM_CPU_INTR1: u32 = 80;
/// ETS_FROM_CPU_INTR2_SOURCE
pub const INTB_FROM_CPU_INTR2: u32 = 81;
/// ETS_FROM_CPU_INTR3_SOURCE
pub const INTB_FROM_CPU_INTR3: u32 = 82;
/// ETS_CACHE_INTR_SOURCE
pub const INTB_CACHE: u32 = 83;
/// ETS_MSPI_INTR_SOURCE
pub const INTB_MSPI: u32 = 84;
/// ETS_CSI_BRIDGE_INTR_SOURCE
pub const INTB_CSI_BRIDGE: u32 = 85;
/// ETS_DSI_BRIDGE_INTR_SOURCE
pub const INTB_DSI_BRIDGE: u32 = 86;
/// ETS_CSI_INTR_SOURCE
pub const INTB_CSI: u32 = 87;
/// ETS_DSI_INTR_SOURCE
pub const INTB_DSI: u32 = 88;
/// ETS_GMII_PHY_INTR_SOURCE
pub const INTB_GMII_PHY: u32 = 89;
/// ETS_LPI_INTR_SOURCE
pub const INTB_LPI: u32 = 90;
/// ETS_PMT_INTR_SOURCE
pub const INTB_PMT: u32 = 91;
/// ETS_ETH_MAC_INTR_SOURCE
pub const INTB_ETH_MAC: u32 = 92;
/// ETS_USB_OTG_INTR_SOURCE
pub const INTB_USB_OTG: u32 = 93;
/// ETS_USB_OTG_ENDP_MULTI_PROC_INTR_SOURCE
pub const INTB_USB_OTG_ENDP_MULTI_PROC: u32 = 94;
/// ETS_JPEG_INTR_SOURCE
pub const INTB_JPEG: u32 = 95;
/// ETS_PPA_INTR_SOURCE
pub const INTB_PPA: u32 = 96;
/// ETS_CORE0_TRACE_INTR_SOURCE
pub const INTB_CORE0_TRACE: u32 = 97;
/// ETS_CORE1_TRACE_INTR_SOURCE
pub const INTB_CORE1_TRACE: u32 = 98;
/// ETS_HP_CORE_CTRL_INTR_SOURCE
pub const INTB_HP_CORE_CTRL: u32 = 99;
/// ETS_ISP_INTR_SOURCE
pub const INTB_ISP: u32 = 100;
/// ETS_I3C_MST_INTR_SOURCE
pub const INTB_I3C_MST: u32 = 101;
/// ETS_I3C_SLV_INTR_SOURCE
pub const INTB_I3C_SLV: u32 = 102;
/// ETS_USB_OTG11_CH0_INTR_SOURCE
pub const INTB_USB_OTG11_CH0: u32 = 103;
/// ETS_DMA2D_IN_CH0_INTR_SOURCE
pub const INTB_DMA2D_IN_CH0: u32 = 104;
/// ETS_DMA2D_IN_CH1_INTR_SOURCE
pub const INTB_DMA2D_IN_CH1: u32 = 105;
/// ETS_DMA2D_OUT_CH0_INTR_SOURCE
pub const INTB_DMA2D_OUT_CH0: u32 = 106;
/// ETS_DMA2D_OUT_CH1_INTR_SOURCE
pub const INTB_DMA2D_OUT_CH1: u32 = 107;
/// ETS_DMA2D_OUT_CH2_INTR_SOURCE
pub const INTB_DMA2D_OUT_CH2: u32 = 108;
/// ETS_PSRAM_MSPI_INTR_SOURCE
pub const INTB_PSRAM_MSPI: u32 = 109;
/// ETS_HP_SYSREG_INTR_SOURCE
pub const INTB_HP_SYSREG: u32 = 110;
/// ETS_PCNT_INTR_SOURCE
pub const INTB_PCNT: u32 = 111;
/// ETS_HP_PAU_INTR_SOURCE
pub const INTB_HP_PAU: u32 = 112;
/// ETS_HP_PARLIO_RX_INTR_SOURCE
pub const INTB_HP_PARLIO_RX: u32 = 113;
/// ETS_HP_PARLIO_TX_INTR_SOURCE
pub const INTB_HP_PARLIO_TX: u32 = 114;
/// ETS_H264_DMA2D_OUT_CH0_INTR_SOURCE
pub const INTB_H264_DMA2D_OUT_CH0: u32 = 115;
/// ETS_H264_DMA2D_OUT_CH1_INTR_SOURCE
pub const INTB_H264_DMA2D_OUT_CH1: u32 = 116;
/// ETS_H264_DMA2D_OUT_CH2_INTR_SOURCE
pub const INTB_H264_DMA2D_OUT_CH2: u32 = 117;
/// ETS_H264_DMA2D_OUT_CH3_INTR_SOURCE
pub const INTB_H264_DMA2D_OUT_CH3: u32 = 118;
/// ETS_H264_DMA2D_OUT_CH4_INTR_SOURCE
pub const INTB_H264_DMA2D_OUT_CH4: u32 = 119;
/// ETS_H264_DMA2D_IN_CH0_INTR_SOURCE
pub const INTB_H264_DMA2D_IN_CH0: u32 = 120;
/// ETS_H264_DMA2D_IN_CH1_INTR_SOURCE
pub const INTB_H264_DMA2D_IN_CH1: u32 = 121;
/// ETS_H264_DMA2D_IN_CH2_INTR_SOURCE
pub const INTB_H264_DMA2D_IN_CH2: u32 = 122;
/// ETS_H264_DMA2D_IN_CH3_INTR_SOURCE
pub const INTB_H264_DMA2D_IN_CH3: u32 = 123;
/// ETS_H264_DMA2D_IN_CH4_INTR_SOURCE
pub const INTB_H264_DMA2D_IN_CH4: u32 = 124;
/// ETS_H264_DMA2D_IN_CH5_INTR_SOURCE
pub const INTB_H264_DMA2D_IN_CH5: u32 = 125;
/// ETS_H264_REG_INTR_SOURCE
pub const INTB_H264_REG: u32 = 126;
/// ETS_ASSIST_DEBUG_INTR_SOURCE
pub const INTB_ASSIST_DEBUG: u32 = 127;

/// The GPIO interrupt `gpio.interruptOn` raises: the first of the GPIO
/// block's four lines.
pub const INTB_GPIO: u32 = INTB_GPIO_INTR0;

/// The number of sources: interrupt numbers are 0 to INTB_COUNT - 1.
pub const INTB_COUNT: u32 = 128;
