// SPDX-License-Identifier: MIT
//! anvil.library's functions: the desktop started, a file's information
//! shown, and the windows, icons and menu items programs add. Open it with
//! OpenLibrary("anvil.library", 1).
//!
//! The table is this library's own: it starts at the first slot after
//! the standard four and holds only what is here.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/anvil_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const anvil = @import("../libs/anvil/anvil.zig");
const icon = @import("../libs/icon/icon.zig");
const utility = @import("../libs/utility/utility.zig");
const dos = @import("../libs/dos/dos.zig");
const intuition = @import("../libs/intuition/intuition.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "anvil.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const StartAnvil = libraries.lvo(4);
    pub const Information = libraries.lvo(5);
    pub const AddAppWindow = libraries.lvo(6);
    pub const RemoveAppWindow = libraries.lvo(7);
    pub const AddAppIcon = libraries.lvo(8);
    pub const RemoveAppIcon = libraries.lvo(9);
    pub const AddAppMenuItem = libraries.lvo(10);
    pub const RemoveAppMenuItem = libraries.lvo(11);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const StartAnvil = *const fn (*AnvilBase, ?[*]const utility.TagItem) callconv(.c) bool;
    pub const Information = *const fn (*AnvilBase, ?*dos.FileLock, [*:0]const u8, ?*intuition.Screen) callconv(.c) bool;
    pub const AddAppWindow = *const fn (*AnvilBase, u32, usize, *intuition.Window, *exec.MsgPort, ?[*]const utility.TagItem) callconv(.c) ?*anvil.AppWindow;
    pub const RemoveAppWindow = *const fn (*AnvilBase, ?*anvil.AppWindow) callconv(.c) bool;
    pub const AddAppIcon = *const fn (*AnvilBase, u32, usize, [*:0]const u8, *exec.MsgPort, *const icon.DiskObject, ?[*]const utility.TagItem) callconv(.c) ?*anvil.AppIcon;
    pub const RemoveAppIcon = *const fn (*AnvilBase, ?*anvil.AppIcon) callconv(.c) bool;
    pub const AddAppMenuItem = *const fn (*AnvilBase, u32, usize, [*:0]const u8, *exec.MsgPort, ?[*]const utility.TagItem) callconv(.c) ?*anvil.AppMenuItem;
    pub const RemoveAppMenuItem = *const fn (*AnvilBase, ?*anvil.AppMenuItem) callconv(.c) bool;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const AnvilBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *AnvilBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The desktop started on its own process, or brought to the front when
    /// it runs already: true, or false with IoErr saying why.
    pub fn StartAnvil(self: *AnvilBase, tags: ?[*]const utility.TagItem) bool {
        return libraries.call(self, LVO.StartAnvil, Fn.StartAnvil, .{tags});
    }

    /// A window of what a file, a drawer or a disk is - and its icon's fields
    /// - to read and change, on a process of its own: `name` in the drawer
    /// `lock` (none: the current one), on `screen` (none: the default).
    pub fn Information(self: *AnvilBase, lock: ?*dos.FileLock, name: [*:0]const u8, screen: ?*intuition.Screen) bool {
        return libraries.call(self, LVO.Information, Fn.Information, .{ lock, name, screen });
    }

    /// A program's window made one that files can be dropped on: each drop
    /// an AppMessage to `port`. Null when the desktop does not run.
    pub fn AddAppWindow(self: *AnvilBase, id: u32, user_data: usize, window: *intuition.Window, port: *exec.MsgPort, tags: ?[*]const utility.TagItem) ?*anvil.AppWindow {
        return libraries.call(self, LVO.AddAppWindow, Fn.AddAppWindow, .{ id, user_data, window, port, tags });
    }

    /// The window taken off the desktop's list: no message is sent for it
    /// once this returns.
    pub fn RemoveAppWindow(self: *AnvilBase, app: ?*anvil.AppWindow) bool {
        return libraries.call(self, LVO.RemoveAppWindow, Fn.RemoveAppWindow, .{app});
    }

    /// An icon of a program's on the desktop's ground, named `text`, with
    /// `object`'s picture: a double click or a drop on it an AppMessage to
    /// `port`. Null when the desktop does not run.
    pub fn AddAppIcon(self: *AnvilBase, id: u32, user_data: usize, text: [*:0]const u8, port: *exec.MsgPort, object: *const icon.DiskObject, tags: ?[*]const utility.TagItem) ?*anvil.AppIcon {
        return libraries.call(self, LVO.AddAppIcon, Fn.AddAppIcon, .{ id, user_data, text, port, object, tags });
    }

    /// The icon taken off the desktop.
    pub fn RemoveAppIcon(self: *AnvilBase, app: ?*anvil.AppIcon) bool {
        return libraries.call(self, LVO.RemoveAppIcon, Fn.RemoveAppIcon, .{app});
    }

    /// An item `text` in the desktop's Tools menu: choosing it an AppMessage
    /// to `port` with the icons picked. Null when the desktop does not run.
    pub fn AddAppMenuItem(self: *AnvilBase, id: u32, user_data: usize, text: [*:0]const u8, port: *exec.MsgPort, tags: ?[*]const utility.TagItem) ?*anvil.AppMenuItem {
        return libraries.call(self, LVO.AddAppMenuItem, Fn.AddAppMenuItem, .{ id, user_data, text, port, tags });
    }

    /// The item taken out of the Tools menu.
    pub fn RemoveAppMenuItem(self: *AnvilBase, app: ?*anvil.AppMenuItem) bool {
        return libraries.call(self, LVO.RemoveAppMenuItem, Fn.RemoveAppMenuItem, .{app});
    }
};
