// SPDX-License-Identifier: MIT
//! asl.library's functions: the requesters a program asks a question
//! with. Open it with OpenLibrary("asl.library", 1).
//!
//! The table is this library's own: it is not on any other system's, so
//! it starts at the first slot after the standard four and holds only
//! what is here.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/asl_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const utility = @import("../libs/utility/utility.zig");
const asl = @import("../libs/asl/asl.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "asl.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const AllocAslRequest = libraries.lvo(4);
    pub const FreeAslRequest = libraries.lvo(5);
    pub const AslRequest = libraries.lvo(6);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const AllocAslRequest = *const fn (*AslBase, u32, ?[*]const utility.TagItem) callconv(.c) ?*anyopaque;
    pub const FreeAslRequest = *const fn (*AslBase, ?*anyopaque) callconv(.c) void;
    pub const AslRequest = *const fn (*AslBase, *anyopaque, ?[*]const utility.TagItem) callconv(.c) bool;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const AslBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *AslBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A requester of `kind` - ASL_FileRequest, ASL_FontRequest,
    /// ASL_ScreenModeRequest - set up from `tags`. Null for a kind it does
    /// not know or for no memory.
    pub fn AllocAslRequest(self: *AslBase, kind: u32, tags: ?[*]const utility.TagItem) ?*anyopaque {
        return libraries.call(self, LVO.AllocAslRequest, Fn.AllocAslRequest, .{ kind, tags });
    }

    /// A requester given back, with everything it answered. Null does
    /// nothing.
    pub fn FreeAslRequest(self: *AslBase, requester: ?*anyopaque) void {
        return libraries.call(self, LVO.FreeAslRequest, Fn.FreeAslRequest, .{requester});
    }

    /// The requester put up, `tags` changing it for this once; true when it
    /// was answered, false when it was given up or could not be shown. The
    /// answer is in the request structure until the next call on it.
    pub fn AslRequest(self: *AslBase, requester: *anyopaque, tags: ?[*]const utility.TagItem) bool {
        return libraries.call(self, LVO.AslRequest, Fn.AslRequest, .{ requester, tags });
    }
};
