// SPDX-License-Identifier: MIT
//! bsdsocket.library's functions: the TCP/IP stack's sockets. The base is
//! the opener's own, from OpenLibrary("bsdsocket.library", 1): its sockets,
//! its error number and its signals are its own and go with it when it
//! closes the library. A call that fails answers -1 and sets Errno().
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/bsdsocket_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const bsd = @import("../libs/bsdsocket/bsdsocket.zig");
const timer = @import("../devices/timer.zig");
const utility = @import("../libs/utility/utility.zig");
const exec = @import("../libs/exec/exec.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "bsdsocket.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const Socket = libraries.lvo(4);
    pub const Bind = libraries.lvo(5);
    pub const Connect = libraries.lvo(6);
    pub const SendTo = libraries.lvo(7);
    pub const Send = libraries.lvo(8);
    pub const RecvFrom = libraries.lvo(9);
    pub const Recv = libraries.lvo(10);
    pub const SetSockOpt = libraries.lvo(11);
    pub const GetSockOpt = libraries.lvo(12);
    pub const GetSockName = libraries.lvo(13);
    pub const GetPeerName = libraries.lvo(14);
    pub const IoctlSocket = libraries.lvo(15);
    pub const CloseSocket = libraries.lvo(16);
    pub const WaitSelect = libraries.lvo(17);
    pub const GetDTableSize = libraries.lvo(18);
    pub const Errno = libraries.lvo(19);
    pub const SetErrnoPtr = libraries.lvo(20);
    pub const Inet_NtoA = libraries.lvo(21);
    pub const Inet_Addr = libraries.lvo(22);
    pub const SocketBaseTagList = libraries.lvo(23);
    pub const AddInterfaceTagList = libraries.lvo(24);
    pub const RemoveInterface = libraries.lvo(25);
    pub const GetSocketEvents = libraries.lvo(26);
    pub const ReleaseSocket = libraries.lvo(27);
    pub const ObtainSocket = libraries.lvo(28);
    pub const Listen = libraries.lvo(29);
    pub const Accept = libraries.lvo(30);
    pub const Shutdown = libraries.lvo(31);
    pub const ConfigureInterfaceTagList = libraries.lvo(32);
    pub const QueryInterfaceTagList = libraries.lvo(33);
    pub const ObtainInterfaceList = libraries.lvo(34);
    pub const ReleaseInterfaceList = libraries.lvo(35);
    pub const AddRouteTagList = libraries.lvo(36);
    pub const DeleteRouteTagList = libraries.lvo(37);
    pub const AddDomainNameServer = libraries.lvo(38);
    pub const RemoveDomainNameServer = libraries.lvo(39);
    pub const GetHostByName = libraries.lvo(40);
    pub const GetHostByAddr = libraries.lvo(41);
    pub const GetHostName = libraries.lvo(42);
    pub const SetHostName = libraries.lvo(43);
    pub const GetNetworkStatistics = libraries.lvo(44);
    pub const Inet_NtoP = libraries.lvo(45);
    pub const Inet_PtoN = libraries.lvo(46);
    pub const If_NameToIndex = libraries.lvo(47);
    pub const If_IndexToName = libraries.lvo(48);
    pub const GetAddrInfo = libraries.lvo(49);
    pub const FreeAddrInfo = libraries.lvo(50);
    pub const GetNameInfo = libraries.lvo(51);
    pub const RecvMsg = libraries.lvo(52);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const Socket = *const fn (*SocketBase, i32, i32, i32) callconv(.c) i32;
    pub const Bind = *const fn (*SocketBase, i32, *const bsd.sockaddr, u32) callconv(.c) i32;
    pub const Connect = *const fn (*SocketBase, i32, *const bsd.sockaddr, u32) callconv(.c) i32;
    pub const SendTo = *const fn (*SocketBase, i32, *const anyopaque, u32, u32, ?*const bsd.sockaddr, u32) callconv(.c) i32;
    pub const Send = *const fn (*SocketBase, i32, *const anyopaque, u32, u32) callconv(.c) i32;
    pub const RecvFrom = *const fn (*SocketBase, i32, *anyopaque, u32, u32, ?*bsd.sockaddr, ?*u32) callconv(.c) i32;
    pub const Recv = *const fn (*SocketBase, i32, *anyopaque, u32, u32) callconv(.c) i32;
    pub const SetSockOpt = *const fn (*SocketBase, i32, i32, i32, *const anyopaque, u32) callconv(.c) i32;
    pub const GetSockOpt = *const fn (*SocketBase, i32, i32, i32, *anyopaque, *u32) callconv(.c) i32;
    pub const GetSockName = *const fn (*SocketBase, i32, *bsd.sockaddr, *u32) callconv(.c) i32;
    pub const GetPeerName = *const fn (*SocketBase, i32, *bsd.sockaddr, *u32) callconv(.c) i32;
    pub const IoctlSocket = *const fn (*SocketBase, i32, u32, *anyopaque) callconv(.c) i32;
    pub const CloseSocket = *const fn (*SocketBase, i32) callconv(.c) i32;
    pub const WaitSelect = *const fn (*SocketBase, i32, ?*bsd.fd_set, ?*bsd.fd_set, ?*bsd.fd_set, ?*timer.TimeVal, ?*u32) callconv(.c) i32;
    pub const GetDTableSize = *const fn (*SocketBase) callconv(.c) i32;
    pub const Errno = *const fn (*SocketBase) callconv(.c) i32;
    pub const SetErrnoPtr = *const fn (*SocketBase, ?*anyopaque, u32) callconv(.c) void;
    pub const Inet_NtoA = *const fn (*SocketBase, u32) callconv(.c) [*:0]const u8;
    pub const Inet_Addr = *const fn (*SocketBase, [*:0]const u8) callconv(.c) u32;
    pub const SocketBaseTagList = *const fn (*SocketBase, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const AddInterfaceTagList = *const fn (*SocketBase, [*:0]const u8, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const RemoveInterface = *const fn (*SocketBase, [*:0]const u8) callconv(.c) i32;
    pub const GetSocketEvents = *const fn (*SocketBase, *u32) callconv(.c) i32;
    pub const ReleaseSocket = *const fn (*SocketBase, i32, i32) callconv(.c) i32;
    pub const ObtainSocket = *const fn (*SocketBase, i32, i32, i32, i32) callconv(.c) i32;
    pub const Listen = *const fn (*SocketBase, i32, i32) callconv(.c) i32;
    pub const Accept = *const fn (*SocketBase, i32, ?*bsd.sockaddr, ?*u32) callconv(.c) i32;
    pub const Shutdown = *const fn (*SocketBase, i32, i32) callconv(.c) i32;
    pub const ConfigureInterfaceTagList = *const fn (*SocketBase, [*:0]const u8, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const QueryInterfaceTagList = *const fn (*SocketBase, [*:0]const u8, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const ObtainInterfaceList = *const fn (*SocketBase) callconv(.c) ?*exec.List;
    pub const ReleaseInterfaceList = *const fn (*SocketBase, ?*exec.List) callconv(.c) void;
    pub const AddRouteTagList = *const fn (*SocketBase, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const DeleteRouteTagList = *const fn (*SocketBase, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const AddDomainNameServer = *const fn (*SocketBase, u32) callconv(.c) i32;
    pub const RemoveDomainNameServer = *const fn (*SocketBase, u32) callconv(.c) i32;
    pub const GetHostByName = *const fn (*SocketBase, [*:0]const u8) callconv(.c) ?*bsd.hostent;
    pub const GetHostByAddr = *const fn (*SocketBase, *const anyopaque, u32, i32) callconv(.c) ?*bsd.hostent;
    pub const GetHostName = *const fn (*SocketBase, [*]u8, u32) callconv(.c) i32;
    pub const SetHostName = *const fn (*SocketBase, [*:0]const u8) callconv(.c) i32;
    pub const GetNetworkStatistics = *const fn (*SocketBase, u32, ?*anyopaque, u32) callconv(.c) i32;
    pub const Inet_NtoP = *const fn (*SocketBase, i32, *const anyopaque, [*]u8, u32) callconv(.c) ?[*:0]u8;
    pub const Inet_PtoN = *const fn (*SocketBase, i32, [*:0]const u8, *anyopaque) callconv(.c) i32;
    pub const If_NameToIndex = *const fn (*SocketBase, [*:0]const u8) callconv(.c) u32;
    pub const If_IndexToName = *const fn (*SocketBase, u32, [*]u8) callconv(.c) ?[*:0]u8;
    pub const GetAddrInfo = *const fn (*SocketBase, ?[*:0]const u8, ?[*:0]const u8, ?*const bsd.addrinfo, *?*bsd.addrinfo) callconv(.c) i32;
    pub const FreeAddrInfo = *const fn (*SocketBase, *bsd.addrinfo) callconv(.c) void;
    pub const GetNameInfo = *const fn (*SocketBase, *const bsd.sockaddr, u32, ?[*]u8, u32, ?[*]u8, u32, i32) callconv(.c) i32;
    pub const RecvMsg = *const fn (*SocketBase, i32, *bsd.msghdr, u32) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const SocketBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *SocketBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A new socket of `socket_type` (SOCK_DGRAM, ...) in `domain` (AF_INET):
    /// its descriptor, or -1.
    pub fn Socket(self: *SocketBase, domain: i32, socket_type: i32, protocol: i32) i32 {
        return libraries.call(self, LVO.Socket, Fn.Socket, .{ domain, socket_type, protocol });
    }

    /// The local address and port of `socket`; port 0 picks a free one.
    pub fn Bind(self: *SocketBase, socket: i32, address: *const bsd.sockaddr, address_length: u32) i32 {
        return libraries.call(self, LVO.Bind, Fn.Bind, .{ socket, address, address_length });
    }

    /// The peer a datagram socket sends to and only takes datagrams from.
    pub fn Connect(self: *SocketBase, socket: i32, address: *const bsd.sockaddr, address_length: u32) i32 {
        return libraries.call(self, LVO.Connect, Fn.Connect, .{ socket, address, address_length });
    }

    /// `length` bytes from `message` to `to` (or the connected peer): the bytes
    /// sent, or -1.
    pub fn SendTo(self: *SocketBase, socket: i32, message: *const anyopaque, length: u32, flags: u32, to: ?*const bsd.sockaddr, to_length: u32) i32 {
        return libraries.call(self, LVO.SendTo, Fn.SendTo, .{ socket, message, length, flags, to, to_length });
    }

    /// SendTo to the connected peer.
    pub fn Send(self: *SocketBase, socket: i32, message: *const anyopaque, length: u32, flags: u32) i32 {
        return libraries.call(self, LVO.Send, Fn.Send, .{ socket, message, length, flags });
    }

    /// The next datagram into `buffer`, and where it came from: the bytes
    /// taken, or -1.
    pub fn RecvFrom(self: *SocketBase, socket: i32, buffer: *anyopaque, length: u32, flags: u32, from: ?*bsd.sockaddr, from_length: ?*u32) i32 {
        return libraries.call(self, LVO.RecvFrom, Fn.RecvFrom, .{ socket, buffer, length, flags, from, from_length });
    }

    /// RecvFrom without the sender.
    pub fn Recv(self: *SocketBase, socket: i32, buffer: *anyopaque, length: u32, flags: u32) i32 {
        return libraries.call(self, LVO.Recv, Fn.Recv, .{ socket, buffer, length, flags });
    }

    /// One of the socket's options (SOL_SOCKET, SO_*) set.
    pub fn SetSockOpt(self: *SocketBase, socket: i32, level: i32, option: i32, value: *const anyopaque, value_length: u32) i32 {
        return libraries.call(self, LVO.SetSockOpt, Fn.SetSockOpt, .{ socket, level, option, value, value_length });
    }

    /// One of the socket's options read into `value`.
    pub fn GetSockOpt(self: *SocketBase, socket: i32, level: i32, option: i32, value: *anyopaque, value_length: *u32) i32 {
        return libraries.call(self, LVO.GetSockOpt, Fn.GetSockOpt, .{ socket, level, option, value, value_length });
    }

    /// The socket's local address.
    pub fn GetSockName(self: *SocketBase, socket: i32, address: *bsd.sockaddr, address_length: *u32) i32 {
        return libraries.call(self, LVO.GetSockName, Fn.GetSockName, .{ socket, address, address_length });
    }

    /// The address of the socket's connected peer.
    pub fn GetPeerName(self: *SocketBase, socket: i32, address: *bsd.sockaddr, address_length: *u32) i32 {
        return libraries.call(self, LVO.GetPeerName, Fn.GetPeerName, .{ socket, address, address_length });
    }

    /// FIONBIO or FIONREAD on the socket.
    pub fn IoctlSocket(self: *SocketBase, socket: i32, request: u32, argument: *anyopaque) i32 {
        return libraries.call(self, LVO.IoctlSocket, Fn.IoctlSocket, .{ socket, request, argument });
    }

    /// The socket closed and its descriptor free again.
    pub fn CloseSocket(self: *SocketBase, socket: i32) i32 {
        return libraries.call(self, LVO.CloseSocket, Fn.CloseSocket, .{socket});
    }

    /// Until a socket in the sets is ready, one of the signals in `*signals`
    /// comes, or `timeout` passes: how many sockets are ready, 0, or -1.
    pub fn WaitSelect(self: *SocketBase, count: i32, read: ?*bsd.fd_set, write: ?*bsd.fd_set, except: ?*bsd.fd_set, timeout: ?*timer.TimeVal, signals: ?*u32) i32 {
        return libraries.call(self, LVO.WaitSelect, Fn.WaitSelect, .{ count, read, write, except, timeout, signals });
    }

    /// How many descriptors the opener's table has.
    pub fn GetDTableSize(self: *SocketBase) i32 {
        return libraries.call(self, LVO.GetDTableSize, Fn.GetDTableSize, .{});
    }

    /// The error number of the last call that failed.
    pub fn Errno(self: *SocketBase) i32 {
        return libraries.call(self, LVO.Errno, Fn.Errno, .{});
    }

    /// Where to write the error number as well, and in how many bytes (1, 2
    /// or 4).
    pub fn SetErrnoPtr(self: *SocketBase, errno_pointer: ?*anyopaque, size: u32) void {
        return libraries.call(self, LVO.SetErrnoPtr, Fn.SetErrnoPtr, .{ errno_pointer, size });
    }

    /// An address as dotted text, in a buffer of the opener's that the next
    /// call overwrites.
    pub fn Inet_NtoA(self: *SocketBase, address: u32) [*:0]const u8 {
        return libraries.call(self, LVO.Inet_NtoA, Fn.Inet_NtoA, .{address});
    }

    /// Dotted text as an address in network order, or INADDR_NONE.
    pub fn Inet_Addr(self: *SocketBase, text: [*:0]const u8) u32 {
        return libraries.call(self, LVO.Inet_Addr, Fn.Inet_Addr, .{text});
    }

    /// The opener's settings (SBTM_SETVAL/SBTM_GETREF of SBTC_*): 0, or the
    /// position of the first tag it could not take, from 1.
    pub fn SocketBaseTagList(self: *SocketBase, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.SocketBaseTagList, Fn.SocketBaseTagList, .{tags});
    }

    /// An interface called `name` on a network device (IFA_Device, IFA_Unit),
    /// with its address, netmask and gateway: 0, or -1.
    pub fn AddInterfaceTagList(self: *SocketBase, name: [*:0]const u8, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.AddInterfaceTagList, Fn.AddInterfaceTagList, .{ name, tags });
    }

    /// The interface called `name` taken down and its device closed: 0, or -1.
    pub fn RemoveInterface(self: *SocketBase, name: [*:0]const u8) i32 {
        return libraries.call(self, LVO.RemoveInterface, Fn.RemoveInterface, .{name});
    }

    /// The next socket with events to tell of (SO_EVENTMASK), and which, into
    /// `events`: its descriptor, or -1 when none has any.
    pub fn GetSocketEvents(self: *SocketBase, events: *u32) i32 {
        return libraries.call(self, LVO.GetSocketEvents, Fn.GetSocketEvents, .{events});
    }

    /// The socket taken out of the opener's table and left with the stack
    /// under `id` (UNIQUE_ID: one the stack makes up): the id, or -1.
    pub fn ReleaseSocket(self: *SocketBase, socket: i32, id: i32) i32 {
        return libraries.call(self, LVO.ReleaseSocket, Fn.ReleaseSocket, .{ socket, id });
    }

    /// The socket left under `id`, taken into the opener's table: its
    /// descriptor, or -1.
    pub fn ObtainSocket(self: *SocketBase, id: i32, domain: i32, socket_type: i32, protocol: i32) i32 {
        return libraries.call(self, LVO.ObtainSocket, Fn.ObtainSocket, .{ id, domain, socket_type, protocol });
    }

    /// A stream socket made to take connections, `backlog` of them waiting
    /// for Accept at most: 0, or -1.
    pub fn Listen(self: *SocketBase, socket: i32, backlog: i32) i32 {
        return libraries.call(self, LVO.Listen, Fn.Listen, .{ socket, backlog });
    }

    /// The next connection a listener took, as a socket of the caller's, and
    /// its peer: the descriptor, or -1.
    pub fn Accept(self: *SocketBase, socket: i32, address: ?*bsd.sockaddr, address_length: ?*u32) i32 {
        return libraries.call(self, LVO.Accept, Fn.Accept, .{ socket, address, address_length });
    }

    /// No more receiving (SHUT_RD), sending (SHUT_WR) or either: 0, or -1.
    pub fn Shutdown(self: *SocketBase, socket: i32, how: i32) i32 {
        return libraries.call(self, LVO.Shutdown, Fn.Shutdown, .{ socket, how });
    }

    /// The interface called `name` changed while it runs: IFA_Address,
    /// IFA_NetMask, IFA_Gateway, IFA_MTU. 0, or -1.
    pub fn ConfigureInterfaceTagList(self: *SocketBase, name: [*:0]const u8, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.ConfigureInterfaceTagList, Fn.ConfigureInterfaceTagList, .{ name, tags });
    }

    /// What the interface called `name` is, into where each IFQ_ tag points:
    /// 0, or -1.
    pub fn QueryInterfaceTagList(self: *SocketBase, name: [*:0]const u8, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.QueryInterfaceTagList, Fn.QueryInterfaceTagList, .{ name, tags });
    }

    /// A list of every interface's name (InterfaceNode), the caller's until
    /// ReleaseInterfaceList; null when there is no memory.
    pub fn ObtainInterfaceList(self: *SocketBase) ?*exec.List {
        return libraries.call(self, LVO.ObtainInterfaceList, Fn.ObtainInterfaceList, .{});
    }

    /// A list ObtainInterfaceList made, freed.
    pub fn ReleaseInterfaceList(self: *SocketBase, list: ?*exec.List) void {
        return libraries.call(self, LVO.ReleaseInterfaceList, Fn.ReleaseInterfaceList, .{list});
    }

    /// A route (RTA_ tags) added: 0, or -1.
    pub fn AddRouteTagList(self: *SocketBase, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.AddRouteTagList, Fn.AddRouteTagList, .{tags});
    }

    /// The route to RTA_Destination with RTA_NetMask, or the default route
    /// with RTA_DefaultGateway, taken away: 0, or -1.
    pub fn DeleteRouteTagList(self: *SocketBase, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.DeleteRouteTagList, Fn.DeleteRouteTagList, .{tags});
    }

    /// A name server to ask, in network order: 0, or -1.
    pub fn AddDomainNameServer(self: *SocketBase, address: u32) i32 {
        return libraries.call(self, LVO.AddDomainNameServer, Fn.AddDomainNameServer, .{address});
    }

    /// A name server no longer asked: 0, or -1.
    pub fn RemoveDomainNameServer(self: *SocketBase, address: u32) i32 {
        return libraries.call(self, LVO.RemoveDomainNameServer, Fn.RemoveDomainNameServer, .{address});
    }

    /// The addresses a name has: from the hosts file, the cache or DNS. A
    /// hostent in the opener's buffer, or null (SBTC_HERRNO says why).
    pub fn GetHostByName(self: *SocketBase, name: [*:0]const u8) ?*bsd.hostent {
        return libraries.call(self, LVO.GetHostByName, Fn.GetHostByName, .{name});
    }

    /// The name an address has (`length` 4, `address_type` AF_INET): a
    /// hostent in the opener's buffer, or null.
    pub fn GetHostByAddr(self: *SocketBase, address: *const anyopaque, length: u32, address_type: i32) ?*bsd.hostent {
        return libraries.call(self, LVO.GetHostByAddr, Fn.GetHostByAddr, .{ address, length, address_type });
    }

    /// The machine's name into `name`, at most `length` bytes with its NUL:
    /// 0, or -1.
    pub fn GetHostName(self: *SocketBase, name: [*]u8, length: u32) i32 {
        return libraries.call(self, LVO.GetHostName, Fn.GetHostName, .{ name, length });
    }

    /// The machine's name set: 0, or -1.
    pub fn SetHostName(self: *SocketBase, name: [*:0]const u8) i32 {
        return libraries.call(self, LVO.SetHostName, Fn.SetHostName, .{name});
    }

    /// The stack's counters (NETSTATUS_COUNTS), routes, sockets or ARP
    /// cache, into `buffer`: how many there are, or -1.
    pub fn GetNetworkStatistics(self: *SocketBase, kind: u32, buffer: ?*anyopaque, size: u32) i32 {
        return libraries.call(self, LVO.GetNetworkStatistics, Fn.GetNetworkStatistics, .{ kind, buffer, size });
    }

    /// An address of `family` (AF_INET: an in_addr, AF_INET6: an in6_addr)
    /// as text in `destination`, `size` bytes: `destination`, or null (errno
    /// EAFNOSUPPORT, or ENOSPC when it does not fit).
    pub fn Inet_NtoP(self: *SocketBase, family: i32, source: *const anyopaque, destination: [*]u8, size: u32) ?[*:0]u8 {
        return libraries.call(self, LVO.Inet_NtoP, Fn.Inet_NtoP, .{ family, source, destination, size });
    }

    /// Text as an address of `family` in `destination` (an in_addr or an
    /// in6_addr): 1, 0 for text that is no address, -1 for a family there is
    /// none of (errno EAFNOSUPPORT).
    pub fn Inet_PtoN(self: *SocketBase, family: i32, text: [*:0]const u8, destination: *anyopaque) i32 {
        return libraries.call(self, LVO.Inet_PtoN, Fn.Inet_PtoN, .{ family, text, destination });
    }

    /// The index of the interface called `name`, as sin6_scope_id has it, or
    /// 0 (errno ENXIO).
    pub fn If_NameToIndex(self: *SocketBase, name: [*:0]const u8) u32 {
        return libraries.call(self, LVO.If_NameToIndex, Fn.If_NameToIndex, .{name});
    }

    /// The name of the interface at `index` in `name` (IFNAMSIZ bytes):
    /// `name`, or null (errno ENXIO).
    pub fn If_IndexToName(self: *SocketBase, index: u32, name: [*]u8) ?[*:0]u8 {
        return libraries.call(self, LVO.If_IndexToName, Fn.If_IndexToName, .{ index, name });
    }

    /// The addresses of `node` for `service` as a list of addrinfo in
    /// `*result`, in RFC 6724's order: 0, or an EAI_* code.
    pub fn GetAddrInfo(self: *SocketBase, node: ?[*:0]const u8, service: ?[*:0]const u8, hints: ?*const bsd.addrinfo, result: *?*bsd.addrinfo) i32 {
        return libraries.call(self, LVO.GetAddrInfo, Fn.GetAddrInfo, .{ node, service, hints, result });
    }

    /// A list GetAddrInfo made, given back whole with its first entry.
    pub fn FreeAddrInfo(self: *SocketBase, list: *bsd.addrinfo) void {
        return libraries.call(self, LVO.FreeAddrInfo, Fn.FreeAddrInfo, .{list});
    }

    /// A sockaddr as a host's name and a service's, GetAddrInfo's reverse: 0,
    /// or an EAI_* code.
    pub fn GetNameInfo(self: *SocketBase, address: *const bsd.sockaddr, address_length: u32, host: ?[*]u8, host_length: u32, service: ?[*]u8, service_length: u32, flags: i32) i32 {
        return libraries.call(self, LVO.GetNameInfo, Fn.GetNameInfo, .{ address, address_length, host, host_length, service, service_length, flags });
    }

    /// The next datagram in, spread over `message`'s buffers, with its sender
    /// and control messages: the bytes read, or -1.
    pub fn RecvMsg(self: *SocketBase, socket: i32, message: *bsd.msghdr, flags: u32) i32 {
        return libraries.call(self, LVO.RecvMsg, Fn.RecvMsg, .{ socket, message, flags });
    }
};
