// SPDX-License-Identifier: MIT
//! bsdsocket.library's functions: the TCP/IP stack's sockets. The base is
//! the opener's own, from OpenLibrary("bsdsocket.library", 1): its sockets,
//! its error number and its signals are its own and go with it when it
//! closes the library. A call that fails answers -1 and sets Errno().
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/bsdsocket_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const bsd = @import("../libs/bsdsocket/bsdsocket.zig");
const timer = @import("../devices/timer.zig");
const utility = @import("../libs/utility/utility.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "bsdsocket.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const Socket = libraries.lvo(4);
    pub const Bind = libraries.lvo(5);
    pub const Connect = libraries.lvo(6);
    pub const SendTo = libraries.lvo(7);
    pub const Send = libraries.lvo(8);
    pub const RecvFrom = libraries.lvo(9);
    pub const Recv = libraries.lvo(10);
    pub const SetSockOpt = libraries.lvo(11);
    pub const GetSockOpt = libraries.lvo(12);
    pub const GetSockName = libraries.lvo(13);
    pub const GetPeerName = libraries.lvo(14);
    pub const IoctlSocket = libraries.lvo(15);
    pub const CloseSocket = libraries.lvo(16);
    pub const WaitSelect = libraries.lvo(17);
    pub const GetDTableSize = libraries.lvo(18);
    pub const Errno = libraries.lvo(19);
    pub const SetErrnoPtr = libraries.lvo(20);
    pub const Inet_NtoA = libraries.lvo(21);
    pub const Inet_Addr = libraries.lvo(22);
    pub const SocketBaseTagList = libraries.lvo(23);
    pub const AddInterfaceTagList = libraries.lvo(24);
    pub const RemoveInterface = libraries.lvo(25);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const Socket = *const fn (*SocketBase, i32, i32, i32) callconv(.c) i32;
    pub const Bind = *const fn (*SocketBase, i32, *const bsd.sockaddr, u32) callconv(.c) i32;
    pub const Connect = *const fn (*SocketBase, i32, *const bsd.sockaddr, u32) callconv(.c) i32;
    pub const SendTo = *const fn (*SocketBase, i32, *const anyopaque, u32, u32, ?*const bsd.sockaddr, u32) callconv(.c) i32;
    pub const Send = *const fn (*SocketBase, i32, *const anyopaque, u32, u32) callconv(.c) i32;
    pub const RecvFrom = *const fn (*SocketBase, i32, *anyopaque, u32, u32, ?*bsd.sockaddr, ?*u32) callconv(.c) i32;
    pub const Recv = *const fn (*SocketBase, i32, *anyopaque, u32, u32) callconv(.c) i32;
    pub const SetSockOpt = *const fn (*SocketBase, i32, i32, i32, *const anyopaque, u32) callconv(.c) i32;
    pub const GetSockOpt = *const fn (*SocketBase, i32, i32, i32, *anyopaque, *u32) callconv(.c) i32;
    pub const GetSockName = *const fn (*SocketBase, i32, *bsd.sockaddr, *u32) callconv(.c) i32;
    pub const GetPeerName = *const fn (*SocketBase, i32, *bsd.sockaddr, *u32) callconv(.c) i32;
    pub const IoctlSocket = *const fn (*SocketBase, i32, u32, *anyopaque) callconv(.c) i32;
    pub const CloseSocket = *const fn (*SocketBase, i32) callconv(.c) i32;
    pub const WaitSelect = *const fn (*SocketBase, i32, ?*bsd.fd_set, ?*bsd.fd_set, ?*bsd.fd_set, ?*timer.TimeVal, ?*u32) callconv(.c) i32;
    pub const GetDTableSize = *const fn (*SocketBase) callconv(.c) i32;
    pub const Errno = *const fn (*SocketBase) callconv(.c) i32;
    pub const SetErrnoPtr = *const fn (*SocketBase, ?*anyopaque, u32) callconv(.c) void;
    pub const Inet_NtoA = *const fn (*SocketBase, u32) callconv(.c) [*:0]const u8;
    pub const Inet_Addr = *const fn (*SocketBase, [*:0]const u8) callconv(.c) u32;
    pub const SocketBaseTagList = *const fn (*SocketBase, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const AddInterfaceTagList = *const fn (*SocketBase, [*:0]const u8, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const RemoveInterface = *const fn (*SocketBase, [*:0]const u8) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const SocketBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *SocketBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A new socket of `socket_type` (SOCK_DGRAM, ...) in `domain` (AF_INET):
    /// its descriptor, or -1.
    pub fn Socket(self: *SocketBase, domain: i32, socket_type: i32, protocol: i32) i32 {
        return libraries.call(self, LVO.Socket, Fn.Socket, .{ domain, socket_type, protocol });
    }

    /// The local address and port of `socket`; port 0 picks a free one.
    pub fn Bind(self: *SocketBase, socket: i32, address: *const bsd.sockaddr, address_length: u32) i32 {
        return libraries.call(self, LVO.Bind, Fn.Bind, .{ socket, address, address_length });
    }

    /// The peer a datagram socket sends to and only takes datagrams from.
    pub fn Connect(self: *SocketBase, socket: i32, address: *const bsd.sockaddr, address_length: u32) i32 {
        return libraries.call(self, LVO.Connect, Fn.Connect, .{ socket, address, address_length });
    }

    /// `length` bytes from `message` to `to` (or the connected peer): the bytes
    /// sent, or -1.
    pub fn SendTo(self: *SocketBase, socket: i32, message: *const anyopaque, length: u32, flags: u32, to: ?*const bsd.sockaddr, to_length: u32) i32 {
        return libraries.call(self, LVO.SendTo, Fn.SendTo, .{ socket, message, length, flags, to, to_length });
    }

    /// SendTo to the connected peer.
    pub fn Send(self: *SocketBase, socket: i32, message: *const anyopaque, length: u32, flags: u32) i32 {
        return libraries.call(self, LVO.Send, Fn.Send, .{ socket, message, length, flags });
    }

    /// The next datagram into `buffer`, and where it came from: the bytes
    /// taken, or -1.
    pub fn RecvFrom(self: *SocketBase, socket: i32, buffer: *anyopaque, length: u32, flags: u32, from: ?*bsd.sockaddr, from_length: ?*u32) i32 {
        return libraries.call(self, LVO.RecvFrom, Fn.RecvFrom, .{ socket, buffer, length, flags, from, from_length });
    }

    /// RecvFrom without the sender.
    pub fn Recv(self: *SocketBase, socket: i32, buffer: *anyopaque, length: u32, flags: u32) i32 {
        return libraries.call(self, LVO.Recv, Fn.Recv, .{ socket, buffer, length, flags });
    }

    /// One of the socket's options (SOL_SOCKET, SO_*) set.
    pub fn SetSockOpt(self: *SocketBase, socket: i32, level: i32, option: i32, value: *const anyopaque, value_length: u32) i32 {
        return libraries.call(self, LVO.SetSockOpt, Fn.SetSockOpt, .{ socket, level, option, value, value_length });
    }

    /// One of the socket's options read into `value`.
    pub fn GetSockOpt(self: *SocketBase, socket: i32, level: i32, option: i32, value: *anyopaque, value_length: *u32) i32 {
        return libraries.call(self, LVO.GetSockOpt, Fn.GetSockOpt, .{ socket, level, option, value, value_length });
    }

    /// The socket's local address.
    pub fn GetSockName(self: *SocketBase, socket: i32, address: *bsd.sockaddr, address_length: *u32) i32 {
        return libraries.call(self, LVO.GetSockName, Fn.GetSockName, .{ socket, address, address_length });
    }

    /// The address of the socket's connected peer.
    pub fn GetPeerName(self: *SocketBase, socket: i32, address: *bsd.sockaddr, address_length: *u32) i32 {
        return libraries.call(self, LVO.GetPeerName, Fn.GetPeerName, .{ socket, address, address_length });
    }

    /// FIONBIO or FIONREAD on the socket.
    pub fn IoctlSocket(self: *SocketBase, socket: i32, request: u32, argument: *anyopaque) i32 {
        return libraries.call(self, LVO.IoctlSocket, Fn.IoctlSocket, .{ socket, request, argument });
    }

    /// The socket closed and its descriptor free again.
    pub fn CloseSocket(self: *SocketBase, socket: i32) i32 {
        return libraries.call(self, LVO.CloseSocket, Fn.CloseSocket, .{socket});
    }

    /// Until a socket in the sets is ready, one of the signals in `*signals`
    /// comes, or `timeout` passes: how many sockets are ready, 0, or -1.
    pub fn WaitSelect(self: *SocketBase, count: i32, read: ?*bsd.fd_set, write: ?*bsd.fd_set, except: ?*bsd.fd_set, timeout: ?*timer.TimeVal, signals: ?*u32) i32 {
        return libraries.call(self, LVO.WaitSelect, Fn.WaitSelect, .{ count, read, write, except, timeout, signals });
    }

    /// How many descriptors the opener's table has.
    pub fn GetDTableSize(self: *SocketBase) i32 {
        return libraries.call(self, LVO.GetDTableSize, Fn.GetDTableSize, .{});
    }

    /// The error number of the last call that failed.
    pub fn Errno(self: *SocketBase) i32 {
        return libraries.call(self, LVO.Errno, Fn.Errno, .{});
    }

    /// Where to write the error number as well, and in how many bytes (1, 2
    /// or 4).
    pub fn SetErrnoPtr(self: *SocketBase, errno_pointer: ?*anyopaque, size: u32) void {
        return libraries.call(self, LVO.SetErrnoPtr, Fn.SetErrnoPtr, .{ errno_pointer, size });
    }

    /// An address as dotted text, in a buffer of the opener's that the next
    /// call overwrites.
    pub fn Inet_NtoA(self: *SocketBase, address: u32) [*:0]const u8 {
        return libraries.call(self, LVO.Inet_NtoA, Fn.Inet_NtoA, .{address});
    }

    /// Dotted text as an address in network order, or INADDR_NONE.
    pub fn Inet_Addr(self: *SocketBase, text: [*:0]const u8) u32 {
        return libraries.call(self, LVO.Inet_Addr, Fn.Inet_Addr, .{text});
    }

    /// The opener's settings (SBTM_SETVAL/SBTM_GETREF of SBTC_*): 0, or the
    /// position of the first tag it could not take, from 1.
    pub fn SocketBaseTagList(self: *SocketBase, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.SocketBaseTagList, Fn.SocketBaseTagList, .{tags});
    }

    /// An interface called `name` on a network device (IFA_Device, IFA_Unit),
    /// with its address, netmask and gateway: 0, or -1.
    pub fn AddInterfaceTagList(self: *SocketBase, name: [*:0]const u8, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.AddInterfaceTagList, Fn.AddInterfaceTagList, .{ name, tags });
    }

    /// The interface called `name` taken down and its device closed: 0, or -1.
    pub fn RemoveInterface(self: *SocketBase, name: [*:0]const u8) i32 {
        return libraries.call(self, LVO.RemoveInterface, Fn.RemoveInterface, .{name});
    }
};
