// SPDX-License-Identifier: MIT
//! colorwheel.gadget's functions, besides its class: a colour between
//! hue, saturation and brightness and red, green and blue. The base is
//! the class library's, from OpenLibrary("gadgets/colorwheel.gadget", 0).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/colorwheel_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const colorwheel = @import("../libs/gadgets/colorwheel.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "colorwheel.gadget";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const ConvertHSBToRGB = libraries.lvo(4);
    pub const ConvertRGBToHSB = libraries.lvo(5);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const ConvertHSBToRGB = *const fn (*ColorWheelBase, *const colorwheel.ColorWheelHSB, *colorwheel.ColorWheelRGB) callconv(.c) void;
    pub const ConvertRGBToHSB = *const fn (*ColorWheelBase, *const colorwheel.ColorWheelRGB, *colorwheel.ColorWheelHSB) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ColorWheelBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ColorWheelBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The colour `hsb` as red, green and blue, into `rgb`.
    pub fn ConvertHSBToRGB(self: *ColorWheelBase, hsb: *const colorwheel.ColorWheelHSB, rgb: *colorwheel.ColorWheelRGB) void {
        return libraries.call(self, LVO.ConvertHSBToRGB, Fn.ConvertHSBToRGB, .{ hsb, rgb });
    }

    /// The colour `rgb` as hue, saturation and brightness, into `hsb`.
    pub fn ConvertRGBToHSB(self: *ColorWheelBase, rgb: *const colorwheel.ColorWheelRGB, hsb: *colorwheel.ColorWheelHSB) void {
        return libraries.call(self, LVO.ConvertRGBToHSB, Fn.ConvertRGBToHSB, .{ rgb, hsb });
    }
};
