// SPDX-License-Identifier: MIT
//! console.device's functions, after BeginIO and AbortIO. The base is the
//! device's: io_Device of a request opened on any unit, CONU_LIBRARY
//! included.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/console_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const ie = @import("../devices/inputevent.zig");
const keymap = @import("../libs/keymap/keymap.zig");
const hooks = @import("../libs/utility/hooks.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "console.device";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const CDInputHandler = libraries.lvo(6);
    pub const RawKeyConvert = libraries.lvo(7);
    pub const GetConSnip = libraries.lvo(8);
    pub const SetConSnip = libraries.lvo(9);
    pub const AddSnipHook = libraries.lvo(10);
    pub const RemSnipHook = libraries.lvo(11);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const CDInputHandler = *const fn (*ConsoleBase, ?*ie.InputEvent) callconv(.c) ?*ie.InputEvent;
    pub const RawKeyConvert = *const fn (*ConsoleBase, ?*const ie.InputEvent, [*]u8, i32, ?*const keymap.KeyMap) callconv(.c) i32;
    pub const GetConSnip = *const fn (*ConsoleBase) callconv(.c) ?[*:0]u8;
    pub const SetConSnip = *const fn (*ConsoleBase, ?[*:0]const u8) callconv(.c) bool;
    pub const AddSnipHook = *const fn (*ConsoleBase, *hooks.Hook) callconv(.c) void;
    pub const RemSnipHook = *const fn (*ConsoleBase, *hooks.Hook) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ConsoleBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ConsoleBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Hand input events to the consoles: a key goes to the console of the
    /// window that is active, through that unit's keymap, and a window event
    /// (`IECLASS_EVENT`, `IECLASS_ACTIVEWINDOW`, `IECLASS_INACTIVEWINDOW`) to
    /// the console of the window it names. Answers the events, so whoever is
    /// next on input.device's chain still sees them. The device's own handler
    /// is this call.
    pub fn CDInputHandler(self: *ConsoleBase, events: ?*ie.InputEvent) ?*ie.InputEvent {
        return libraries.call(self, LVO.CDInputHandler, Fn.CDInputHandler, .{events});
    }

    /// The characters a list of key events makes, into `buffer` (room for
    /// `length`): how many, or -1 when they did not fit. `key_map` null is
    /// keymap.library's default.
    pub fn RawKeyConvert(self: *ConsoleBase, events: ?*const ie.InputEvent, buffer: [*]u8, length: i32, key_map: ?*const keymap.KeyMap) i32 {
        return libraries.call(self, LVO.RawKeyConvert, Fn.RawKeyConvert, .{ events, buffer, length, key_map });
    }

    /// A copy of what was last selected in a console window, NUL terminated
    /// and allocated with AllocVec - the caller frees it - or null when
    /// nothing is selected and nothing was put there.
    pub fn GetConSnip(self: *ConsoleBase) ?[*:0]u8 {
        return libraries.call(self, LVO.GetConSnip, Fn.GetConSnip, .{});
    }

    /// What a paste is to give from now on; it is copied. Null empties it.
    /// False when there was no memory.
    pub fn SetConSnip(self: *ConsoleBase, snip: ?[*:0]const u8) bool {
        return libraries.call(self, LVO.SetConSnip, Fn.SetConSnip, .{snip});
    }

    /// Call `hook` whenever a console window's selection is finished, so that
    /// a program can carry the text away - to a clipboard, say. The hook is
    /// called on the console's own task, with the `ConUnit` the text came from
    /// as its object and a `SnipHookMsg` as its message; neither outlives the
    /// call, so a hook that wants the text copies it. The hook may call
    /// nothing that waits. Its node belongs to the device until it is removed.
    pub fn AddSnipHook(self: *ConsoleBase, hook: *hooks.Hook) void {
        return libraries.call(self, LVO.AddSnipHook, Fn.AddSnipHook, .{hook});
    }

    /// Take a hook off again. It is not called after this returns.
    pub fn RemSnipHook(self: *ConsoleBase, hook: *hooks.Hook) void {
        return libraries.call(self, LVO.RemSnipHook, Fn.RemSnipHook, .{hook});
    }
};
