// SPDX-License-Identifier: MIT
//! crypto.library's functions: random bytes, hashes, HMAC, AES and
//! modular exponentiation, on the chip's own engines. A hash, an HMAC or
//! a cipher under way is a context the caller keeps (sdk.crypto); a call
//! that can fail answers 0 or a CRYPTOERR_* code.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/crypto_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const crypto = @import("../libs/crypto/crypto.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "crypto.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const RandomBytes = libraries.lvo(4);
    pub const InitHash = libraries.lvo(5);
    pub const UpdateHash = libraries.lvo(6);
    pub const FinishHash = libraries.lvo(7);
    pub const InitHmac = libraries.lvo(8);
    pub const UpdateHmac = libraries.lvo(9);
    pub const FinishHmac = libraries.lvo(10);
    pub const InitCipher = libraries.lvo(11);
    pub const UpdateCipher = libraries.lvo(12);
    pub const SealGcm = libraries.lvo(13);
    pub const OpenGcm = libraries.lvo(14);
    pub const ModExp = libraries.lvo(15);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const RandomBytes = *const fn (*CryptoBase, *anyopaque, u32) callconv(.c) void;
    pub const InitHash = *const fn (*CryptoBase, *crypto.HashContext, u32) callconv(.c) i32;
    pub const UpdateHash = *const fn (*CryptoBase, *crypto.HashContext, ?*const anyopaque, u32) callconv(.c) void;
    pub const FinishHash = *const fn (*CryptoBase, *crypto.HashContext, *anyopaque) callconv(.c) u32;
    pub const InitHmac = *const fn (*CryptoBase, *crypto.HmacContext, u32, ?*const anyopaque, u32) callconv(.c) i32;
    pub const UpdateHmac = *const fn (*CryptoBase, *crypto.HmacContext, ?*const anyopaque, u32) callconv(.c) void;
    pub const FinishHmac = *const fn (*CryptoBase, *crypto.HmacContext, *anyopaque) callconv(.c) u32;
    pub const InitCipher = *const fn (*CryptoBase, *crypto.CipherContext, u32, *const anyopaque, u32, ?*const anyopaque) callconv(.c) i32;
    pub const UpdateCipher = *const fn (*CryptoBase, *crypto.CipherContext, ?*const anyopaque, ?*anyopaque, u32) callconv(.c) i32;
    pub const SealGcm = *const fn (*CryptoBase, *const crypto.GcmMessage) callconv(.c) i32;
    pub const OpenGcm = *const fn (*CryptoBase, *const crypto.GcmMessage) callconv(.c) i32;
    pub const ModExp = *const fn (*CryptoBase, *anyopaque, *const crypto.Number, *const crypto.Number, *const crypto.Number) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const CryptoBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *CryptoBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// `length` random bytes into `buffer`, from the chip's generator.
    pub fn RandomBytes(self: *CryptoBase, buffer: *anyopaque, length: u32) void {
        return libraries.call(self, LVO.RandomBytes, Fn.RandomBytes, .{ buffer, length });
    }

    /// `context` set up for a hash of `algorithm` (HASH_*).
    pub fn InitHash(self: *CryptoBase, context: *crypto.HashContext, algorithm: u32) i32 {
        return libraries.call(self, LVO.InitHash, Fn.InitHash, .{ context, algorithm });
    }

    /// `length` more bytes of `data` into the hash.
    pub fn UpdateHash(self: *CryptoBase, context: *crypto.HashContext, data: ?*const anyopaque, length: u32) void {
        return libraries.call(self, LVO.UpdateHash, Fn.UpdateHash, .{ context, data, length });
    }

    /// The digest into `digest`: its length in bytes.
    pub fn FinishHash(self: *CryptoBase, context: *crypto.HashContext, digest: *anyopaque) u32 {
        return libraries.call(self, LVO.FinishHash, Fn.FinishHash, .{ context, digest });
    }

    /// `context` set up for an HMAC with `algorithm` (HASH_*) and `key`.
    pub fn InitHmac(self: *CryptoBase, context: *crypto.HmacContext, algorithm: u32, key: ?*const anyopaque, key_length: u32) i32 {
        return libraries.call(self, LVO.InitHmac, Fn.InitHmac, .{ context, algorithm, key, key_length });
    }

    /// `length` more bytes of `data` into the HMAC.
    pub fn UpdateHmac(self: *CryptoBase, context: *crypto.HmacContext, data: ?*const anyopaque, length: u32) void {
        return libraries.call(self, LVO.UpdateHmac, Fn.UpdateHmac, .{ context, data, length });
    }

    /// The MAC into `mac`: its length in bytes.
    pub fn FinishHmac(self: *CryptoBase, context: *crypto.HmacContext, mac: *anyopaque) u32 {
        return libraries.call(self, LVO.FinishHmac, Fn.FinishHmac, .{ context, mac });
    }

    /// `context` set up for AES in `mode` (CIPHER_*, CIPHERF_DECRYPT) with
    /// `key` and, for CBC and CTR, `iv`.
    pub fn InitCipher(self: *CryptoBase, context: *crypto.CipherContext, mode: u32, key: *const anyopaque, key_length: u32, iv: ?*const anyopaque) i32 {
        return libraries.call(self, LVO.InitCipher, Fn.InitCipher, .{ context, mode, key, key_length, iv });
    }

    /// `length` bytes of `input` through the cipher into `output`.
    pub fn UpdateCipher(self: *CryptoBase, context: *crypto.CipherContext, input: ?*const anyopaque, output: ?*anyopaque, length: u32) i32 {
        return libraries.call(self, LVO.UpdateCipher, Fn.UpdateCipher, .{ context, input, output, length });
    }

    /// A message encrypted with AES-GCM, and its tag.
    pub fn SealGcm(self: *CryptoBase, message: *const crypto.GcmMessage) i32 {
        return libraries.call(self, LVO.SealGcm, Fn.SealGcm, .{message});
    }

    /// A message's tag checked with AES-GCM, and the message decrypted.
    pub fn OpenGcm(self: *CryptoBase, message: *const crypto.GcmMessage) i32 {
        return libraries.call(self, LVO.OpenGcm, Fn.OpenGcm, .{message});
    }

    /// `base_value` to the power of `exponent`, modulo `modulus`, into
    /// `result`: as many bytes as the modulus has.
    pub fn ModExp(self: *CryptoBase, result: *anyopaque, base_value: *const crypto.Number, exponent: *const crypto.Number, modulus: *const crypto.Number) i32 {
        return libraries.call(self, LVO.ModExp, Fn.ModExp, .{ result, base_value, exponent, modulus });
    }
};
