// SPDX-License-Identifier: MIT
//! datatypes.library's functions: a file opened by what is in it. Open
//! it with OpenLibrary("datatypes.library", 1).
//!
//! The table is this library's own: it is not on any other system's, so
//! it starts at the first slot after the standard four and holds only
//! what is here.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/datatypes_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const utility = @import("../libs/utility/utility.zig");
const graphics = @import("../libs/graphics/graphics.zig");
const intuition = @import("../libs/intuition/intuition.zig");
const classusr = @import("../libs/intuition/classusr.zig");
const gadgetclass = @import("../libs/intuition/gadgetclass.zig");
const datatypes = @import("../libs/datatypes/datatypes.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "datatypes.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const ObtainDataTypeA = libraries.lvo(4);
    pub const ReleaseDataType = libraries.lvo(5);
    pub const NewDTObjectA = libraries.lvo(6);
    pub const DisposeDTObject = libraries.lvo(7);
    pub const SetDTAttrsA = libraries.lvo(8);
    pub const GetDTAttrsA = libraries.lvo(9);
    pub const AddDTObject = libraries.lvo(10);
    pub const RemoveDTObject = libraries.lvo(11);
    pub const RefreshDTObjectA = libraries.lvo(12);
    pub const DoAsyncLayout = libraries.lvo(13);
    pub const DoDTMethodA = libraries.lvo(14);
    pub const GetDTMethods = libraries.lvo(15);
    pub const GetDTTriggerMethods = libraries.lvo(16);
    pub const ObtainDTDrawInfoA = libraries.lvo(17);
    pub const DrawDTObjectA = libraries.lvo(18);
    pub const ReleaseDTDrawInfo = libraries.lvo(19);
    pub const GetDTString = libraries.lvo(20);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const ObtainDataTypeA = *const fn (*DataTypesBase, u32, ?*anyopaque, ?[*]const utility.TagItem) callconv(.c) ?*datatypes.DataType;
    pub const ReleaseDataType = *const fn (*DataTypesBase, ?*datatypes.DataType) callconv(.c) void;
    pub const NewDTObjectA = *const fn (*DataTypesBase, ?[*:0]const u8, ?[*]const utility.TagItem) callconv(.c) ?*classusr.Object;
    pub const DisposeDTObject = *const fn (*DataTypesBase, ?*classusr.Object) callconv(.c) void;
    pub const SetDTAttrsA = *const fn (*DataTypesBase, ?*classusr.Object, ?*intuition.Window, ?*intuition.Requester, ?[*]const utility.TagItem) callconv(.c) u32;
    pub const GetDTAttrsA = *const fn (*DataTypesBase, ?*classusr.Object, ?[*]const utility.TagItem) callconv(.c) u32;
    pub const AddDTObject = *const fn (*DataTypesBase, ?*intuition.Window, ?*intuition.Requester, ?*classusr.Object, i32) callconv(.c) i32;
    pub const RemoveDTObject = *const fn (*DataTypesBase, ?*intuition.Window, ?*classusr.Object) callconv(.c) i32;
    pub const RefreshDTObjectA = *const fn (*DataTypesBase, ?*classusr.Object, ?*intuition.Window, ?*intuition.Requester, ?[*]const utility.TagItem) callconv(.c) void;
    pub const DoAsyncLayout = *const fn (*DataTypesBase, *classusr.Object, *gadgetclass.GpLayout) callconv(.c) u32;
    pub const DoDTMethodA = *const fn (*DataTypesBase, *classusr.Object, ?*intuition.Window, ?*intuition.Requester, *classusr.Msg) callconv(.c) u32;
    pub const GetDTMethods = *const fn (*DataTypesBase, *classusr.Object) callconv(.c) ?[*]const u32;
    pub const GetDTTriggerMethods = *const fn (*DataTypesBase, *classusr.Object) callconv(.c) ?[*]const datatypes.datatypesclass.DTMethod;
    pub const ObtainDTDrawInfoA = *const fn (*DataTypesBase, *classusr.Object, ?[*]const utility.TagItem) callconv(.c) ?*anyopaque;
    pub const DrawDTObjectA = *const fn (*DataTypesBase, *graphics.RastPort, *classusr.Object, i32, i32, i32, i32, i32, i32, ?[*]const utility.TagItem) callconv(.c) bool;
    pub const ReleaseDTDrawInfo = *const fn (*DataTypesBase, *classusr.Object, ?*anyopaque) callconv(.c) void;
    pub const GetDTString = *const fn (*DataTypesBase, u32) callconv(.c) [*:0]const u8;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const DataTypesBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *DataTypesBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// What kind of file `handle` is: a lock on a file (DTST_FILE), a
    /// ClipboardHandle (DTST_CLIPBOARD) or bytes in memory (DTST_RAM).
    /// `attrs` may hold DTA_GroupID to refuse anything of another group.
    /// Null when nothing recognises it, and IoErr is then
    /// DTERROR_UNKNOWN_DATATYPE.
    pub fn ObtainDataTypeA(self: *DataTypesBase, source_type: u32, handle: ?*anyopaque, attrs: ?[*]const utility.TagItem) ?*datatypes.DataType {
        return libraries.call(self, LVO.ObtainDataTypeA, Fn.ObtainDataTypeA, .{ source_type, handle, attrs });
    }

    /// A data type let go of. The list it is on is the system's and the
    /// descriptor is never freed here; this only lets go of the hold that
    /// keeps the list still. Null does nothing.
    pub fn ReleaseDataType(self: *DataTypesBase, dt: ?*datatypes.DataType) void {
        return libraries.call(self, LVO.ReleaseDataType, Fn.ReleaseDataType, .{dt});
    }

    /// An object for what `name` holds - a file name unless DTA_SourceType
    /// says otherwise - made of the class its kind names. Null when the
    /// kind is not known, the class cannot be loaded or the contents cannot
    /// be read; IoErr says which.
    pub fn NewDTObjectA(self: *DataTypesBase, name: ?[*:0]const u8, attrs: ?[*]const utility.TagItem) ?*classusr.Object {
        return libraries.call(self, LVO.NewDTObjectA, Fn.NewDTObjectA, .{ name, attrs });
    }

    /// An object given back, with the class library it belongs to. It must
    /// have been taken out of its window first. Null does nothing.
    pub fn DisposeDTObject(self: *DataTypesBase, object: ?*classusr.Object) void {
        return libraries.call(self, LVO.DisposeDTObject, Fn.DisposeDTObject, .{object});
    }

    /// Attributes set on an object, which draws itself again if it is in a
    /// window. Nonzero when something changed.
    pub fn SetDTAttrsA(self: *DataTypesBase, object: ?*classusr.Object, window: ?*intuition.Window, requester: ?*intuition.Requester, attrs: ?[*]const utility.TagItem) u32 {
        return libraries.call(self, LVO.SetDTAttrsA, Fn.SetDTAttrsA, .{ object, window, requester, attrs });
    }

    /// Attributes read from an object into the pointers the tags carry. How
    /// many were answered.
    pub fn GetDTAttrsA(self: *DataTypesBase, object: ?*classusr.Object, attrs: ?[*]const utility.TagItem) u32 {
        return libraries.call(self, LVO.GetDTAttrsA, Fn.GetDTAttrsA, .{ object, attrs });
    }

    /// An object put into a window at `position` in its gadget list, laid
    /// out and drawn. 0, or an error.
    pub fn AddDTObject(self: *DataTypesBase, window: ?*intuition.Window, requester: ?*intuition.Requester, object: ?*classusr.Object, position: i32) i32 {
        return libraries.call(self, LVO.AddDTObject, Fn.AddDTObject, .{ window, requester, object, position });
    }

    /// An object taken out of its window again, told so first
    /// (DTM_REMOVEDTOBJECT). 0, or an error.
    pub fn RemoveDTObject(self: *DataTypesBase, window: ?*intuition.Window, object: ?*classusr.Object) i32 {
        return libraries.call(self, LVO.RemoveDTObject, Fn.RemoveDTObject, .{ window, object });
    }

    /// An object drawn again, `attrs` changing it first.
    pub fn RefreshDTObjectA(self: *DataTypesBase, object: ?*classusr.Object, window: ?*intuition.Window, requester: ?*intuition.Requester, attrs: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.RefreshDTObjectA, Fn.RefreshDTObjectA, .{ object, window, requester, attrs });
    }

    /// The object laid out on a process of its own, so that whoever asked
    /// carries on. Nonzero when the process took it.
    pub fn DoAsyncLayout(self: *DataTypesBase, object: *classusr.Object, layout: *gadgetclass.GpLayout) u32 {
        return libraries.call(self, LVO.DoAsyncLayout, Fn.DoAsyncLayout, .{ object, layout });
    }

    /// A method sent to an object, with the window and requester it is in.
    /// What the object answered.
    pub fn DoDTMethodA(self: *DataTypesBase, object: *classusr.Object, window: ?*intuition.Window, requester: ?*intuition.Requester, msg: *classusr.Msg) u32 {
        return libraries.call(self, LVO.DoDTMethodA, Fn.DoDTMethodA, .{ object, window, requester, msg });
    }

    /// The methods an object answers: an array ending in ~0, or null.
    pub fn GetDTMethods(self: *DataTypesBase, object: *classusr.Object) ?[*]const u32 {
        return libraries.call(self, LVO.GetDTMethods, Fn.GetDTMethods, .{object});
    }

    /// What an object can be told to do, with a name for each: an array
    /// ending in a null label, or null.
    pub fn GetDTTriggerMethods(self: *DataTypesBase, object: *classusr.Object) ?[*]const datatypes.datatypesclass.DTMethod {
        return libraries.call(self, LVO.GetDTTriggerMethods, Fn.GetDTTriggerMethods, .{object});
    }

    /// The object made ready to be drawn into a RastPort that is not its
    /// window's. What it answers is given back to ReleaseDTDrawInfo.
    pub fn ObtainDTDrawInfoA(self: *DataTypesBase, object: *classusr.Object, attrs: ?[*]const utility.TagItem) ?*anyopaque {
        return libraries.call(self, LVO.ObtainDTDrawInfoA, Fn.ObtainDTDrawInfoA, .{ object, attrs });
    }

    /// An object drawn into `rast_port` at `left`, `top`, `width` by
    /// `height`, from `top_horiz` and `top_vert` of its own. True when it
    /// drew.
    pub fn DrawDTObjectA(self: *DataTypesBase, rast_port: *graphics.RastPort, object: *classusr.Object, left: i32, top: i32, width: i32, height: i32, top_horiz: i32, top_vert: i32, attrs: ?[*]const utility.TagItem) bool {
        return libraries.call(self, LVO.DrawDTObjectA, Fn.DrawDTObjectA, .{ rast_port, object, left, top, width, height, top_horiz, top_vert, attrs });
    }

    /// What ObtainDTDrawInfoA answered, given back.
    pub fn ReleaseDTDrawInfo(self: *DataTypesBase, object: *classusr.Object, handle: ?*anyopaque) void {
        return libraries.call(self, LVO.ReleaseDTDrawInfo, Fn.ReleaseDTDrawInfo, .{ object, handle });
    }

    /// The text of one of the library's messages (a DTERROR_ number, or a
    /// group's number for its name).
    pub fn GetDTString(self: *DataTypesBase, id: u32) [*:0]const u8 {
        return libraries.call(self, LVO.GetDTString, Fn.GetDTString, .{id});
    }
};
