// SPDX-License-Identifier: MIT
//! diskfont.library's functions: fonts from FONTS:, any size of them.
//! A font opened here is closed with graphics' CloseFont. Open it with
//! OpenLibrary("diskfont.library", 1).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/diskfont_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const utility = @import("../libs/utility/utility.zig");
const graphics = @import("../libs/graphics/graphics.zig");
const dos = @import("../libs/dos/dos.zig");
const diskfont = @import("../libs/diskfont/diskfont.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "diskfont.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const OpenDiskFont = libraries.lvo(4);
    pub const AvailFonts = libraries.lvo(5);
    pub const NewFontContents = libraries.lvo(6);
    pub const DisposeFontContents = libraries.lvo(7);
    pub const NewScaledDiskFont = libraries.lvo(8);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const OpenDiskFont = *const fn (*DiskfontBase, *const graphics.TextAttr) callconv(.c) ?*graphics.TextFont;
    pub const AvailFonts = *const fn (*DiskfontBase, *anyopaque, u32, u32) callconv(.c) u32;
    pub const NewFontContents = *const fn (*DiskfontBase, ?*dos.FileLock, [*:0]const u8) callconv(.c) ?*diskfont.fontfile.ContentsHeader;
    pub const DisposeFontContents = *const fn (*DiskfontBase, ?*diskfont.fontfile.ContentsHeader) callconv(.c) void;
    pub const NewScaledDiskFont = *const fn (*DiskfontBase, *graphics.TextFont, *const graphics.TextAttr) callconv(.c) ?*graphics.TextFont;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const DiskfontBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *DiskfontBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The font nearest to `text_attr`: from memory, loaded from FONTS:, or
    /// scaled from another size unless FPF_DESIGNED is asked. Null if the
    /// font has no size that will do.
    pub fn OpenDiskFont(self: *DiskfontBase, text_attr: *const graphics.TextAttr) ?*graphics.TextFont {
        return libraries.call(self, LVO.OpenDiskFont, Fn.OpenDiskFont, .{text_attr});
    }

    /// Every font in memory and in FONTS: (flags AFF_*) into `buffer`: an
    /// AvailFontsHeader, the entries, their names. 0, or the bytes more it
    /// needed.
    pub fn AvailFonts(self: *DiskfontBase, buffer: *anyopaque, buffer_size: u32, flags: u32) u32 {
        return libraries.call(self, LVO.AvailFonts, Fn.AvailFonts, .{ buffer, buffer_size, flags });
    }

    /// A family's contents file made from its directory beside `lock`'s
    /// directory; `name` ends in ".font". Null if there is nothing.
    pub fn NewFontContents(self: *DiskfontBase, lock: ?*dos.FileLock, name: [*:0]const u8) ?*diskfont.fontfile.ContentsHeader {
        return libraries.call(self, LVO.NewFontContents, Fn.NewFontContents, .{ lock, name });
    }

    /// Free what NewFontContents made. Null does nothing.
    pub fn DisposeFontContents(self: *DiskfontBase, contents: ?*diskfont.fontfile.ContentsHeader) void {
        return libraries.call(self, LVO.DisposeFontContents, Fn.DisposeFontContents, .{contents});
    }

    /// A new font of `text_attr`'s height from `font`, every glyph scaled.
    /// Nobody else's: FreeVec frees it, after RemFont if it was added.
    pub fn NewScaledDiskFont(self: *DiskfontBase, font: *graphics.TextFont, text_attr: *const graphics.TextAttr) ?*graphics.TextFont {
        return libraries.call(self, LVO.NewScaledDiskFont, Fn.NewScaledDiskFont, .{ font, text_attr });
    }
};
