// SPDX-License-Identifier: MIT
//! dma.resource's functions: the chip's general DMA engine (GDMA), its
//! channels handed out to one owner each. A
//! resource: no Open or Close, its first function in the first slot. The
//! base comes from OpenResource("dma.resource").
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/dma_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const dma = @import("../resources/dma.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "dma.resource";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const AllocDMAChannel = libraries.lvo(0);
    pub const FreeDMAChannel = libraries.lvo(1);
    pub const DMAChannelOwner = libraries.lvo(2);
    pub const ConnectDMAChannel = libraries.lvo(3);
    pub const StartDMA = libraries.lvo(4);
    pub const StopDMA = libraries.lvo(5);
    pub const ResetDMA = libraries.lvo(6);
    pub const EnableDMAInts = libraries.lvo(7);
    pub const DMAIntStatus = libraries.lvo(8);
    pub const DMARawIntStatus = libraries.lvo(9);
    pub const ClearDMAInts = libraries.lvo(10);
    pub const AllocDMAChain = libraries.lvo(11);
    pub const FreeDMAChain = libraries.lvo(12);
    pub const DMAEOFDescriptor = libraries.lvo(13);
    pub const SetDMAPriority = libraries.lvo(14);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const AllocDMAChannel = *const fn (*DmaBase, u32, [*:0]const u8) callconv(.c) ?[*:0]const u8;
    pub const FreeDMAChannel = *const fn (*DmaBase, u32) callconv(.c) void;
    pub const DMAChannelOwner = *const fn (*DmaBase, u32) callconv(.c) ?[*:0]const u8;
    pub const ConnectDMAChannel = *const fn (*DmaBase, u32, u32, u32) callconv(.c) bool;
    pub const StartDMA = *const fn (*DmaBase, u32, u32, *dma.DMADescriptor) callconv(.c) bool;
    pub const StopDMA = *const fn (*DmaBase, u32, u32) callconv(.c) void;
    pub const ResetDMA = *const fn (*DmaBase, u32, u32) callconv(.c) void;
    pub const EnableDMAInts = *const fn (*DmaBase, u32, u32, u32) callconv(.c) void;
    pub const DMAIntStatus = *const fn (*DmaBase, u32, u32) callconv(.c) u32;
    pub const DMARawIntStatus = *const fn (*DmaBase, u32, u32) callconv(.c) u32;
    pub const ClearDMAInts = *const fn (*DmaBase, u32, u32, u32) callconv(.c) void;
    pub const AllocDMAChain = *const fn (*DmaBase, u32, ?*anyopaque, u32, u32) callconv(.c) ?*dma.DMADescriptor;
    pub const FreeDMAChain = *const fn (*DmaBase, ?*dma.DMADescriptor) callconv(.c) void;
    pub const DMAEOFDescriptor = *const fn (*DmaBase, u32, u32) callconv(.c) ?*dma.DMADescriptor;
    pub const SetDMAPriority = *const fn (*DmaBase, u32, u32, u32) callconv(.c) bool;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const DmaBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *DmaBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Claim a channel (0-4) for `name`: null if it is now yours, else its
    /// owner's name. Not from interrupts.
    pub fn AllocDMAChannel(self: *DmaBase, channel: u32, name: [*:0]const u8) ?[*:0]const u8 {
        return libraries.call(self, LVO.AllocDMAChannel, Fn.AllocDMAChannel, .{ channel, name });
    }

    /// Give a channel back: it stops, is disconnected, its interrupts off.
    /// Remove your interrupt servers first. Not from interrupts.
    pub fn FreeDMAChannel(self: *DmaBase, channel: u32) void {
        return libraries.call(self, LVO.FreeDMAChannel, Fn.FreeDMAChannel, .{channel});
    }

    /// Who has a channel, or null.
    pub fn DMAChannelOwner(self: *DmaBase, channel: u32) ?[*:0]const u8 {
        return libraries.call(self, LVO.DMAChannelOwner, Fn.DMAChannelOwner, .{channel});
    }

    /// Connect a channel to a peripheral (DMAPERI_*), or DMAPERI_MEMORY for
    /// memory to memory, with DMACF_* flags. Resets the channel. False for a bad
    /// channel or peripheral, or a peripheral another channel is connected to.
    pub fn ConnectDMAChannel(self: *DmaBase, channel: u32, peripheral: u32, flags: u32) bool {
        return libraries.call(self, LVO.ConnectDMAChannel, Fn.ConnectDMAChannel, .{ channel, peripheral, flags });
    }

    /// Start a side (DMA_IN, DMA_OUT) on a descriptor chain. False unless the
    /// first descriptor is 4-byte aligned in internal RAM. Memory to memory:
    /// IN first, then OUT.
    pub fn StartDMA(self: *DmaBase, channel: u32, side: u32, list: *dma.DMADescriptor) bool {
        return libraries.call(self, LVO.StartDMA, Fn.StartDMA, .{ channel, side, list });
    }

    /// Stop a side.
    pub fn StopDMA(self: *DmaBase, channel: u32, side: u32) void {
        return libraries.call(self, LVO.StopDMA, Fn.StopDMA, .{ channel, side });
    }

    /// Reset a side: its FIFO and state machine, its connection and flags left
    /// as they are. Stopping a side does not empty it, and what it still holds
    /// goes out ahead of the next chain it is started on. From interrupts too.
    pub fn ResetDMA(self: *DmaBase, channel: u32, side: u32) void {
        return libraries.call(self, LVO.ResetDMA, Fn.ResetDMA, .{ channel, side });
    }

    /// Enable a side's interrupts (DMAINTF_*); 0: none.
    pub fn EnableDMAInts(self: *DmaBase, channel: u32, side: u32, mask: u32) void {
        return libraries.call(self, LVO.EnableDMAInts, Fn.EnableDMAInts, .{ channel, side, mask });
    }

    /// A side's pending, enabled interrupts. From interrupts too.
    pub fn DMAIntStatus(self: *DmaBase, channel: u32, side: u32) u32 {
        return libraries.call(self, LVO.DMAIntStatus, Fn.DMAIntStatus, .{ channel, side });
    }

    /// A side's interrupt bits as the hardware sets them, enabled or not: what
    /// a driver polls when it wants to know that something happened without
    /// being interrupted by it. From interrupts too.
    pub fn DMARawIntStatus(self: *DmaBase, channel: u32, side: u32) u32 {
        return libraries.call(self, LVO.DMARawIntStatus, Fn.DMARawIntStatus, .{ channel, side });
    }

    /// Clear a side's interrupts. From interrupts too.
    pub fn ClearDMAInts(self: *DmaBase, channel: u32, side: u32, mask: u32) void {
        return libraries.call(self, LVO.ClearDMAInts, Fn.ClearDMAInts, .{ channel, side, mask });
    }

    /// A descriptor chain over `length` bytes at `buffer`, for a side: DMA_OUT
    /// sends them all (EOF on the last descriptor), DMA_IN fills them. In
    /// internal memory, DMA_CHUNK (PSRAM: DMA_CHUNK_PSRAM) bytes per descriptor;
    /// DMACHF_LOOP links the last back to the first. Null if the buffer isn't
    /// in internal RAM or PSRAM, or without memory. Not from interrupts.
    pub fn AllocDMAChain(self: *DmaBase, side: u32, buffer: ?*anyopaque, length: u32, flags: u32) ?*dma.DMADescriptor {
        return libraries.call(self, LVO.AllocDMAChain, Fn.AllocDMAChain, .{ side, buffer, length, flags });
    }

    /// Free a chain from AllocDMAChain (null: nothing). Not from interrupts.
    pub fn FreeDMAChain(self: *DmaBase, chain: ?*dma.DMADescriptor) void {
        return libraries.call(self, LVO.FreeDMAChain, Fn.FreeDMAChain, .{chain});
    }

    /// The descriptor that ended a side's last frame: IN's with SUC_EOF, OUT's
    /// last with EOF sent. Null if none yet.
    pub fn DMAEOFDescriptor(self: *DmaBase, channel: u32, side: u32) ?*dma.DMADescriptor {
        return libraries.call(self, LVO.DMAEOFDescriptor, Fn.DMAEOFDescriptor, .{ channel, side });
    }

    /// A side's priority on the bus, 0 (lowest) to DMA_MAXPRI. False for a bad
    /// channel, side or priority.
    pub fn SetDMAPriority(self: *DmaBase, channel: u32, side: u32, priority: u32) bool {
        return libraries.call(self, LVO.SetDMAPriority, Fn.SetDMAPriority, .{ channel, side, priority });
    }
};
