// SPDX-License-Identifier: MIT
//! dos.library's functions: packets, dos objects, IoErr and processes,
//! the device list, paths, segments, locks, dates, files, examining, the
//! CLI, assigns, pattern searches, buffered I/O, argument parsing, faults,
//! variables and loading code. The functions come in the order they were
//! written.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/dos_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const dos = @import("../libs/dos/dos.zig");
const utility = @import("../libs/utility/utility.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "dos.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const DoPkt = libraries.lvo(4);
    pub const SendPkt = libraries.lvo(5);
    pub const WaitPkt = libraries.lvo(6);
    pub const ReplyPkt = libraries.lvo(7);
    pub const AbortPkt = libraries.lvo(8);
    pub const AllocDosObject = libraries.lvo(9);
    pub const FreeDosObject = libraries.lvo(10);
    pub const IoErr = libraries.lvo(11);
    pub const SetIoErr = libraries.lvo(12);
    pub const CreateNewProc = libraries.lvo(13);
    pub const LockDosList = libraries.lvo(14);
    pub const UnLockDosList = libraries.lvo(15);
    pub const AttemptLockDosList = libraries.lvo(16);
    pub const AddDosEntry = libraries.lvo(17);
    pub const RemDosEntry = libraries.lvo(18);
    pub const FindDosEntry = libraries.lvo(19);
    pub const NextDosEntry = libraries.lvo(20);
    pub const MakeDosEntry = libraries.lvo(21);
    pub const FreeDosEntry = libraries.lvo(22);
    pub const GetDeviceProc = libraries.lvo(23);
    pub const FreeDeviceProc = libraries.lvo(24);
    pub const AddPart = libraries.lvo(25);
    pub const FilePart = libraries.lvo(26);
    pub const PathPart = libraries.lvo(27);
    pub const SplitName = libraries.lvo(28);
    pub const ParsePath = libraries.lvo(29);
    pub const AddSegment = libraries.lvo(30);
    pub const FindSegment = libraries.lvo(31);
    pub const RemSegment = libraries.lvo(32);
    pub const LockSegmentList = libraries.lvo(33);
    pub const UnLockSegmentList = libraries.lvo(34);
    pub const Lock = libraries.lvo(35);
    pub const UnLock = libraries.lvo(36);
    pub const DupLock = libraries.lvo(37);
    pub const ParentDir = libraries.lvo(38);
    pub const SameLock = libraries.lvo(39);
    pub const CurrentDir = libraries.lvo(40);
    pub const CreateDir = libraries.lvo(41);
    pub const DeleteFile = libraries.lvo(42);
    pub const DateStamp = libraries.lvo(43);
    pub const CompareDates = libraries.lvo(44);
    pub const DateToStr = libraries.lvo(45);
    pub const StrToDate = libraries.lvo(46);
    pub const Open = libraries.lvo(47);
    pub const Close = libraries.lvo(48);
    pub const Read = libraries.lvo(49);
    pub const Write = libraries.lvo(50);
    pub const Seek = libraries.lvo(51);
    pub const Input = libraries.lvo(52);
    pub const Output = libraries.lvo(53);
    pub const SelectInput = libraries.lvo(54);
    pub const SelectOutput = libraries.lvo(55);
    pub const IsInteractive = libraries.lvo(56);
    pub const Examine = libraries.lvo(57);
    pub const ExNext = libraries.lvo(58);
    pub const ExamineFH = libraries.lvo(59);
    pub const ExAll = libraries.lvo(60);
    pub const ExAllEnd = libraries.lvo(61);
    pub const Cli = libraries.lvo(62);
    pub const SelectError = libraries.lvo(63);
    pub const ErrorOutput = libraries.lvo(64);
    pub const GetConsoleTask = libraries.lvo(65);
    pub const SetConsoleTask = libraries.lvo(66);
    pub const GetFileSysTask = libraries.lvo(67);
    pub const SetFileSysTask = libraries.lvo(68);
    pub const GetProgramDir = libraries.lvo(69);
    pub const SetProgramDir = libraries.lvo(70);
    pub const SetProgramName = libraries.lvo(71);
    pub const GetProgramName = libraries.lvo(72);
    pub const SetPrompt = libraries.lvo(73);
    pub const GetPrompt = libraries.lvo(74);
    pub const SetCurrentDirName = libraries.lvo(75);
    pub const GetCurrentDirName = libraries.lvo(76);
    pub const NameFromLock = libraries.lvo(77);
    pub const AssignLock = libraries.lvo(78);
    pub const AssignLate = libraries.lvo(79);
    pub const AssignPath = libraries.lvo(80);
    pub const AssignAdd = libraries.lvo(81);
    pub const RemAssignList = libraries.lvo(82);
    pub const MatchFirst = libraries.lvo(83);
    pub const MatchNext = libraries.lvo(84);
    pub const MatchEnd = libraries.lvo(85);
    pub const Rename = libraries.lvo(86);
    pub const SetProtection = libraries.lvo(87);
    pub const SetComment = libraries.lvo(88);
    pub const SetFileDate = libraries.lvo(89);
    pub const SetOwner = libraries.lvo(90);
    pub const SetFileSize = libraries.lvo(91);
    pub const DupLockFromFH = libraries.lvo(92);
    pub const ParentOfFH = libraries.lvo(93);
    pub const NameFromFH = libraries.lvo(94);
    pub const OpenFromLock = libraries.lvo(95);
    pub const ChangeMode = libraries.lvo(96);
    pub const Info = libraries.lvo(97);
    pub const IsFileSystem = libraries.lvo(98);
    pub const SameDevice = libraries.lvo(99);
    pub const Flush = libraries.lvo(100);
    pub const FGetC = libraries.lvo(101);
    pub const UnGetC = libraries.lvo(102);
    pub const FPutC = libraries.lvo(103);
    pub const FRead = libraries.lvo(104);
    pub const FWrite = libraries.lvo(105);
    pub const FGets = libraries.lvo(106);
    pub const FPuts = libraries.lvo(107);
    pub const SetVBuf = libraries.lvo(108);
    pub const VFPrintf = libraries.lvo(109);
    pub const VPrintf = libraries.lvo(110);
    pub const PutStr = libraries.lvo(111);
    pub const WriteChars = libraries.lvo(112);
    pub const ReadArgs = libraries.lvo(113);
    pub const FreeArgs = libraries.lvo(114);
    pub const ReadItem = libraries.lvo(115);
    pub const FindArg = libraries.lvo(116);
    pub const StrToLong = libraries.lvo(117);
    pub const SetMode = libraries.lvo(118);
    pub const WaitForChar = libraries.lvo(119);
    pub const Fault = libraries.lvo(120);
    pub const PrintFault = libraries.lvo(121);
    pub const SetVar = libraries.lvo(122);
    pub const GetVar = libraries.lvo(123);
    pub const DeleteVar = libraries.lvo(124);
    pub const FindVar = libraries.lvo(125);
    pub const CheckSignal = libraries.lvo(126);
    pub const Delay = libraries.lvo(127);
    pub const GetArgStr = libraries.lvo(128);
    pub const SetArgStr = libraries.lvo(129);
    pub const MaxCli = libraries.lvo(130);
    pub const FindCliProc = libraries.lvo(131);
    pub const RunCommand = libraries.lvo(132);
    pub const SystemTagList = libraries.lvo(133);
    pub const Execute = libraries.lvo(134);
    pub const LoadSeg = libraries.lvo(135);
    pub const UnLoadSeg = libraries.lvo(136);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const DoPkt = *const fn (*DosBase, *exec.MsgPort, i32, isize, isize, isize, isize, isize) callconv(.c) isize;
    pub const SendPkt = *const fn (*DosBase, *dos.DosPacket, *exec.MsgPort, *exec.MsgPort) callconv(.c) void;
    pub const WaitPkt = *const fn (*DosBase) callconv(.c) ?*dos.DosPacket;
    pub const ReplyPkt = *const fn (*DosBase, ?*dos.DosPacket, isize, i32) callconv(.c) void;
    pub const AbortPkt = *const fn (*DosBase, *exec.MsgPort, *dos.DosPacket) callconv(.c) void;
    pub const AllocDosObject = *const fn (*DosBase, u32, ?[*]const utility.TagItem) callconv(.c) ?*anyopaque;
    pub const FreeDosObject = *const fn (*DosBase, u32, ?*anyopaque) callconv(.c) void;
    pub const IoErr = *const fn (*DosBase) callconv(.c) i32;
    pub const SetIoErr = *const fn (*DosBase, i32) callconv(.c) i32;
    pub const CreateNewProc = *const fn (*DosBase, ?[*]const utility.TagItem) callconv(.c) ?*dos.Process;
    pub const LockDosList = *const fn (*DosBase, u32) callconv(.c) ?*dos.DosList;
    pub const UnLockDosList = *const fn (*DosBase, u32) callconv(.c) void;
    pub const AttemptLockDosList = *const fn (*DosBase, u32) callconv(.c) ?*dos.DosList;
    pub const AddDosEntry = *const fn (*DosBase, *dos.DosList) callconv(.c) bool;
    pub const RemDosEntry = *const fn (*DosBase, *dos.DosList) callconv(.c) bool;
    pub const FindDosEntry = *const fn (*DosBase, *dos.DosList, ?[*:0]const u8, u32) callconv(.c) ?*dos.DosList;
    pub const NextDosEntry = *const fn (*DosBase, *dos.DosList, u32) callconv(.c) ?*dos.DosList;
    pub const MakeDosEntry = *const fn (*DosBase, [*:0]const u8, i32) callconv(.c) ?*dos.DosList;
    pub const FreeDosEntry = *const fn (*DosBase, ?*dos.DosList) callconv(.c) void;
    pub const GetDeviceProc = *const fn (*DosBase, [*:0]const u8, ?*dos.DevProc) callconv(.c) ?*dos.DevProc;
    pub const FreeDeviceProc = *const fn (*DosBase, ?*dos.DevProc) callconv(.c) void;
    pub const AddPart = *const fn (*DosBase, [*:0]u8, [*:0]const u8, u32) callconv(.c) bool;
    pub const FilePart = *const fn (*DosBase, [*:0]const u8) callconv(.c) [*:0]const u8;
    pub const PathPart = *const fn (*DosBase, [*:0]const u8) callconv(.c) [*:0]const u8;
    pub const SplitName = *const fn (*DosBase, [*:0]const u8, u8, [*]u8, i32, u32) callconv(.c) i32;
    pub const ParsePath = *const fn (*DosBase, [*:0]const u8, *dos.ParsedPath) callconv(.c) bool;
    pub const AddSegment = *const fn (*DosBase, [*:0]const u8, ?*const dos.SegCode, i32) callconv(.c) bool;
    pub const FindSegment = *const fn (*DosBase, [*:0]const u8, ?*dos.Segment, bool) callconv(.c) ?*dos.Segment;
    pub const RemSegment = *const fn (*DosBase, *dos.Segment) callconv(.c) bool;
    pub const LockSegmentList = *const fn (*DosBase, bool) callconv(.c) ?*dos.Segment;
    pub const UnLockSegmentList = *const fn (*DosBase) callconv(.c) void;
    pub const Lock = *const fn (*DosBase, [*:0]const u8, i32) callconv(.c) ?*dos.FileLock;
    pub const UnLock = *const fn (*DosBase, ?*dos.FileLock) callconv(.c) void;
    pub const DupLock = *const fn (*DosBase, ?*dos.FileLock) callconv(.c) ?*dos.FileLock;
    pub const ParentDir = *const fn (*DosBase, ?*dos.FileLock) callconv(.c) ?*dos.FileLock;
    pub const SameLock = *const fn (*DosBase, ?*dos.FileLock, ?*dos.FileLock) callconv(.c) i32;
    pub const CurrentDir = *const fn (*DosBase, ?*dos.FileLock) callconv(.c) ?*dos.FileLock;
    pub const CreateDir = *const fn (*DosBase, [*:0]const u8) callconv(.c) ?*dos.FileLock;
    pub const DeleteFile = *const fn (*DosBase, [*:0]const u8) callconv(.c) bool;
    pub const DateStamp = *const fn (*DosBase, *dos.DateStamp) callconv(.c) *dos.DateStamp;
    pub const CompareDates = *const fn (*DosBase, *const dos.DateStamp, *const dos.DateStamp) callconv(.c) i32;
    pub const DateToStr = *const fn (*DosBase, *dos.DateTime) callconv(.c) bool;
    pub const StrToDate = *const fn (*DosBase, *dos.DateTime) callconv(.c) bool;
    pub const Open = *const fn (*DosBase, [*:0]const u8, i32) callconv(.c) ?*dos.FileHandle;
    pub const Close = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) bool;
    pub const Read = *const fn (*DosBase, ?*dos.FileHandle, [*]u8, isize) callconv(.c) isize;
    pub const Write = *const fn (*DosBase, ?*dos.FileHandle, [*]const u8, isize) callconv(.c) isize;
    pub const Seek = *const fn (*DosBase, ?*dos.FileHandle, isize, i32) callconv(.c) isize;
    pub const Input = *const fn (*DosBase) callconv(.c) ?*dos.FileHandle;
    pub const Output = *const fn (*DosBase) callconv(.c) ?*dos.FileHandle;
    pub const SelectInput = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) ?*dos.FileHandle;
    pub const SelectOutput = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) ?*dos.FileHandle;
    pub const IsInteractive = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) bool;
    pub const Examine = *const fn (*DosBase, ?*dos.FileLock, *dos.FileInfoBlock) callconv(.c) bool;
    pub const ExNext = *const fn (*DosBase, ?*dos.FileLock, *dos.FileInfoBlock) callconv(.c) bool;
    pub const ExamineFH = *const fn (*DosBase, ?*dos.FileHandle, *dos.FileInfoBlock) callconv(.c) bool;
    pub const ExAll = *const fn (*DosBase, ?*dos.FileLock, [*]u8, isize, i32, *dos.ExAllControl) callconv(.c) bool;
    pub const ExAllEnd = *const fn (*DosBase, ?*dos.FileLock, [*]u8, isize, i32, *dos.ExAllControl) callconv(.c) void;
    pub const Cli = *const fn (*DosBase) callconv(.c) ?*dos.CommandLineInterface;
    pub const SelectError = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) ?*dos.FileHandle;
    pub const ErrorOutput = *const fn (*DosBase) callconv(.c) ?*dos.FileHandle;
    pub const GetConsoleTask = *const fn (*DosBase) callconv(.c) ?*exec.MsgPort;
    pub const SetConsoleTask = *const fn (*DosBase, ?*exec.MsgPort) callconv(.c) ?*exec.MsgPort;
    pub const GetFileSysTask = *const fn (*DosBase) callconv(.c) ?*exec.MsgPort;
    pub const SetFileSysTask = *const fn (*DosBase, ?*exec.MsgPort) callconv(.c) ?*exec.MsgPort;
    pub const GetProgramDir = *const fn (*DosBase) callconv(.c) ?*dos.FileLock;
    pub const SetProgramDir = *const fn (*DosBase, ?*dos.FileLock) callconv(.c) ?*dos.FileLock;
    pub const SetProgramName = *const fn (*DosBase, [*:0]const u8) callconv(.c) bool;
    pub const GetProgramName = *const fn (*DosBase, [*]u8, u32) callconv(.c) bool;
    pub const SetPrompt = *const fn (*DosBase, [*:0]const u8) callconv(.c) bool;
    pub const GetPrompt = *const fn (*DosBase, [*]u8, u32) callconv(.c) bool;
    pub const SetCurrentDirName = *const fn (*DosBase, [*:0]const u8) callconv(.c) bool;
    pub const GetCurrentDirName = *const fn (*DosBase, [*]u8, u32) callconv(.c) bool;
    pub const NameFromLock = *const fn (*DosBase, ?*dos.FileLock, [*]u8, u32) callconv(.c) bool;
    pub const AssignLock = *const fn (*DosBase, [*:0]const u8, ?*dos.FileLock) callconv(.c) bool;
    pub const AssignLate = *const fn (*DosBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const AssignPath = *const fn (*DosBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const AssignAdd = *const fn (*DosBase, [*:0]const u8, *dos.FileLock) callconv(.c) bool;
    pub const RemAssignList = *const fn (*DosBase, [*:0]const u8, *dos.FileLock) callconv(.c) bool;
    pub const MatchFirst = *const fn (*DosBase, [*:0]const u8, *dos.AnchorPath) callconv(.c) i32;
    pub const MatchNext = *const fn (*DosBase, *dos.AnchorPath) callconv(.c) i32;
    pub const MatchEnd = *const fn (*DosBase, *dos.AnchorPath) callconv(.c) void;
    pub const Rename = *const fn (*DosBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const SetProtection = *const fn (*DosBase, [*:0]const u8, u32) callconv(.c) bool;
    pub const SetComment = *const fn (*DosBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const SetFileDate = *const fn (*DosBase, [*:0]const u8, *const dos.DateStamp) callconv(.c) bool;
    pub const SetOwner = *const fn (*DosBase, [*:0]const u8, u32) callconv(.c) bool;
    pub const SetFileSize = *const fn (*DosBase, ?*dos.FileHandle, isize, i32) callconv(.c) isize;
    pub const DupLockFromFH = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) ?*dos.FileLock;
    pub const ParentOfFH = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) ?*dos.FileLock;
    pub const NameFromFH = *const fn (*DosBase, ?*dos.FileHandle, [*]u8, u32) callconv(.c) bool;
    pub const OpenFromLock = *const fn (*DosBase, ?*dos.FileLock) callconv(.c) ?*dos.FileHandle;
    pub const ChangeMode = *const fn (*DosBase, i32, ?*anyopaque, i32) callconv(.c) bool;
    pub const Info = *const fn (*DosBase, ?*dos.FileLock, *dos.InfoData) callconv(.c) bool;
    pub const IsFileSystem = *const fn (*DosBase, [*:0]const u8) callconv(.c) bool;
    pub const SameDevice = *const fn (*DosBase, ?*dos.FileLock, ?*dos.FileLock) callconv(.c) bool;
    pub const Flush = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) bool;
    pub const FGetC = *const fn (*DosBase, ?*dos.FileHandle) callconv(.c) i32;
    pub const UnGetC = *const fn (*DosBase, ?*dos.FileHandle, i32) callconv(.c) bool;
    pub const FPutC = *const fn (*DosBase, ?*dos.FileHandle, i32) callconv(.c) i32;
    pub const FRead = *const fn (*DosBase, ?*dos.FileHandle, [*]u8, isize) callconv(.c) isize;
    pub const FWrite = *const fn (*DosBase, ?*dos.FileHandle, [*]const u8, isize) callconv(.c) isize;
    pub const FGets = *const fn (*DosBase, ?*dos.FileHandle, [*]u8, u32) callconv(.c) ?[*]u8;
    pub const FPuts = *const fn (*DosBase, ?*dos.FileHandle, [*:0]const u8) callconv(.c) i32;
    pub const SetVBuf = *const fn (*DosBase, ?*dos.FileHandle, ?[*]u8, i32, isize) callconv(.c) i32;
    pub const VFPrintf = *const fn (*DosBase, ?*dos.FileHandle, [*:0]const u8, ?*const anyopaque) callconv(.c) i32;
    pub const VPrintf = *const fn (*DosBase, [*:0]const u8, ?*const anyopaque) callconv(.c) i32;
    pub const PutStr = *const fn (*DosBase, [*:0]const u8) callconv(.c) i32;
    pub const WriteChars = *const fn (*DosBase, [*]const u8, isize) callconv(.c) isize;
    pub const ReadArgs = *const fn (*DosBase, [*:0]const u8, [*]usize, ?*dos.RDArgs) callconv(.c) ?*dos.RDArgs;
    pub const FreeArgs = *const fn (*DosBase, ?*dos.RDArgs) callconv(.c) void;
    pub const ReadItem = *const fn (*DosBase, [*]u8, i32, ?*dos.CSource) callconv(.c) i32;
    pub const FindArg = *const fn (*DosBase, [*:0]const u8, [*:0]const u8) callconv(.c) i32;
    pub const StrToLong = *const fn (*DosBase, [*:0]const u8, *i32) callconv(.c) i32;
    pub const SetMode = *const fn (*DosBase, ?*dos.FileHandle, i32) callconv(.c) bool;
    pub const WaitForChar = *const fn (*DosBase, ?*dos.FileHandle, isize) callconv(.c) bool;
    pub const Fault = *const fn (*DosBase, i32, ?[*:0]const u8, [*]u8, i32) callconv(.c) i32;
    pub const PrintFault = *const fn (*DosBase, i32, ?[*:0]const u8) callconv(.c) bool;
    pub const SetVar = *const fn (*DosBase, [*:0]const u8, ?[*]const u8, isize, u32) callconv(.c) bool;
    pub const GetVar = *const fn (*DosBase, [*:0]const u8, [*]u8, isize, u32) callconv(.c) isize;
    pub const DeleteVar = *const fn (*DosBase, [*:0]const u8, u32) callconv(.c) bool;
    pub const FindVar = *const fn (*DosBase, [*:0]const u8, u32) callconv(.c) ?*dos.LocalVar;
    pub const CheckSignal = *const fn (*DosBase, u32) callconv(.c) u32;
    pub const Delay = *const fn (*DosBase, u32) callconv(.c) void;
    pub const GetArgStr = *const fn (*DosBase) callconv(.c) ?[*:0]const u8;
    pub const SetArgStr = *const fn (*DosBase, ?[*:0]const u8) callconv(.c) ?[*:0]const u8;
    pub const MaxCli = *const fn (*DosBase) callconv(.c) u32;
    pub const FindCliProc = *const fn (*DosBase, u32) callconv(.c) ?*dos.Process;
    pub const RunCommand = *const fn (*DosBase, ?*const dos.SegCode, u32, [*]const u8, isize) callconv(.c) i32;
    pub const SystemTagList = *const fn (*DosBase, ?[*:0]const u8, ?[*]const utility.TagItem) callconv(.c) i32;
    pub const Execute = *const fn (*DosBase, [*:0]const u8, ?*dos.FileHandle, ?*dos.FileHandle) callconv(.c) bool;
    pub const LoadSeg = *const fn (*DosBase, [*:0]const u8) callconv(.c) ?*dos.SegList;
    pub const UnLoadSeg = *const fn (*DosBase, ?*dos.SegList) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const DosBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *DosBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Send a packet (action, up to five arguments) to the handler at `port`
    /// and wait for it to come back. Returns dp_Res1; a process gets dp_Res2
    /// from IoErr(). Works from a plain task too, with a port of its own for
    /// the reply. Other packets that come back meanwhile are kept for the
    /// caller.
    pub fn DoPkt(self: *DosBase, port: *exec.MsgPort, action: i32, arg1: isize, arg2: isize, arg3: isize, arg4: isize, arg5: isize) isize {
        return libraries.call(self, LVO.DoPkt, Fn.DoPkt, .{ port, action, arg1, arg2, arg3, arg4, arg5 });
    }

    /// Send a packet to `port` without waiting; it comes back to `reply_port`
    /// (your process's msg_port, to get it with WaitPkt). Callable from tasks.
    pub fn SendPkt(self: *DosBase, packet: *dos.DosPacket, port: *exec.MsgPort, reply_port: *exec.MsgPort) void {
        return libraries.call(self, LVO.SendPkt, Fn.SendPkt, .{ packet, port, reply_port });
    }

    /// Wait for a packet at your process's msg_port (through pr_PktWait if
    /// set) and take it off the port. Null from a plain task.
    pub fn WaitPkt(self: *DosBase) ?*dos.DosPacket {
        return libraries.call(self, LVO.WaitPkt, Fn.WaitPkt, .{});
    }

    /// Send a packet back to its sender with res1 and res2. Its dp_Port becomes
    /// your msg_port, so a ReplyPkt from there returns it to you. Null does
    /// nothing.
    pub fn ReplyPkt(self: *DosBase, packet: ?*dos.DosPacket, res1: isize, res2: i32) void {
        return libraries.call(self, LVO.ReplyPkt, Fn.ReplyPkt, .{ packet, res1, res2 });
    }

    /// Ask for a packet sent with SendPkt to be aborted. Does nothing: wait
    /// for the packet to come back all the same.
    pub fn AbortPkt(self: *DosBase, port: *exec.MsgPort, packet: *dos.DosPacket) void {
        return libraries.call(self, LVO.AbortPkt, Fn.AbortPkt, .{ port, packet });
    }

    /// A dos object of `obj_type` (DOS_*): so far DOS_STDPKT, a cleared
    /// DosPacket. Null for no memory (ERROR_NO_FREE_STORE), a type not done
    /// yet (ERROR_NOT_IMPLEMENTED) or an unknown one.
    pub fn AllocDosObject(self: *DosBase, obj_type: u32, tags: ?[*]const utility.TagItem) ?*anyopaque {
        return libraries.call(self, LVO.AllocDosObject, Fn.AllocDosObject, .{ obj_type, tags });
    }

    /// Free an object from AllocDosObject, given its type. Null does nothing.
    pub fn FreeDosObject(self: *DosBase, obj_type: u32, ptr: ?*anyopaque) void {
        return libraries.call(self, LVO.FreeDosObject, Fn.FreeDosObject, .{ obj_type, ptr });
    }

    /// The secondary result of the last dos call (pr_Result2);
    /// ERROR_NO_PROCESS from a plain task.
    pub fn IoErr(self: *DosBase) i32 {
        return libraries.call(self, LVO.IoErr, Fn.IoErr, .{});
    }

    /// Set what IoErr() returns, and return the old value (0 from a task).
    pub fn SetIoErr(self: *DosBase, code: i32) i32 {
        return libraries.call(self, LVO.SetIoErr, Fn.SetIoErr, .{code});
    }

    /// Start a process: NP_Entry (required), NP_Name, NP_StackSize,
    /// NP_Priority, NP_ConsoleTask, NP_WindowPtr. Null on failure; IoErr()
    /// says why.
    pub fn CreateNewProc(self: *DosBase, tags: ?[*]const utility.TagItem) ?*dos.Process {
        return libraries.call(self, LVO.CreateNewProc, Fn.CreateNewProc, .{tags});
    }

    /// Lock the device list (LDF_ALL, or some of LDF_DEVICES, LDF_VOLUMES,
    /// LDF_ASSIGNS) and/or LDF_ENTRY, LDF_DELETE, with exactly one of LDF_READ
    /// and LDF_WRITE. Returns the start for FindDosEntry and NextDosEntry;
    /// null for bad flags. Handlers must not LDF_WRITE it (use
    /// AttemptLockDosList).
    pub fn LockDosList(self: *DosBase, flags: u32) ?*dos.DosList {
        return libraries.call(self, LVO.LockDosList, Fn.LockDosList, .{flags});
    }

    /// Unlock what LockDosList locked, with the same flags.
    pub fn UnLockDosList(self: *DosBase, flags: u32) void {
        return libraries.call(self, LVO.UnLockDosList, Fn.UnLockDosList, .{flags});
    }

    /// LockDosList without waiting: null if it can't have it at once.
    pub fn AttemptLockDosList(self: *DosBase, flags: u32) ?*dos.DosList {
        return libraries.call(self, LVO.AttemptLockDosList, Fn.AttemptLockDosList, .{flags});
    }

    /// Add a node (from MakeDosEntry). False and ERROR_OBJECT_EXISTS if a node
    /// of the name is there: a volume only shadows a device or assign, or a
    /// volume with another date.
    pub fn AddDosEntry(self: *DosBase, dlist: *dos.DosList) bool {
        return libraries.call(self, LVO.AddDosEntry, Fn.AddDosEntry, .{dlist});
    }

    /// Take a node off the list (the caller holds it with LDF_WRITE); it is
    /// not freed. False if it isn't on the list.
    pub fn RemDosEntry(self: *DosBase, dlist: *dos.DosList) bool {
        return libraries.call(self, LVO.RemDosEntry, Fn.RemDosEntry, .{dlist});
    }

    /// The first node from `dlist` on of the types in `flags` (LDF_DEVICES,
    /// ...) with that name (without colon, any case; null: any name). The
    /// list must be locked.
    pub fn FindDosEntry(self: *DosBase, dlist: *dos.DosList, name: ?[*:0]const u8, flags: u32) ?*dos.DosList {
        return libraries.call(self, LVO.FindDosEntry, Fn.FindDosEntry, .{ dlist, name, flags });
    }

    /// The node after `dlist` of the types in `flags`. The list must be locked.
    pub fn NextDosEntry(self: *DosBase, dlist: *dos.DosList, flags: u32) ?*dos.DosList {
        return libraries.call(self, LVO.NextDosEntry, Fn.NextDosEntry, .{ dlist, flags });
    }

    /// A cleared node of type `dlt` (DLT_*) with a copy of the name (without
    /// colon), not yet on the list. Null for no memory.
    pub fn MakeDosEntry(self: *DosBase, name: [*:0]const u8, dlt: i32) ?*dos.DosList {
        return libraries.call(self, LVO.MakeDosEntry, Fn.MakeDosEntry, .{ name, dlt });
    }

    /// Free a node from MakeDosEntry (off the list). Null does nothing.
    pub fn FreeDosEntry(self: *DosBase, dlist: ?*dos.DosList) void {
        return libraries.call(self, LVO.FreeDosEntry, Fn.FreeDosEntry, .{dlist});
    }

    /// The handler for a name ("NIL:", "DF0:file", "CONSOLE:", or a path
    /// without device for the current file system), starting a device's
    /// handler if it isn't running. With the previous DevProc of a
    /// multi-assign, the next directory. Null on failure; IoErr() says why.
    /// Free it with FreeDeviceProc.
    pub fn GetDeviceProc(self: *DosBase, name: [*:0]const u8, olddp: ?*dos.DevProc) ?*dos.DevProc {
        return libraries.call(self, LVO.GetDeviceProc, Fn.GetDeviceProc, .{ name, olddp });
    }

    /// Free a DevProc from GetDeviceProc. Null does nothing.
    pub fn FreeDeviceProc(self: *DosBase, dp: ?*dos.DevProc) void {
        return libraries.call(self, LVO.FreeDeviceProc, Fn.FreeDeviceProc, .{dp});
    }

    /// Add `filename` to the path in `dirname` (a buffer of `size` bytes), with
    /// a "/" if needed. A name with a colon replaces the path; one starting
    /// with ":" goes after the path's device. False and ERROR_LINE_TOO_LONG if
    /// it wouldn't fit; `dirname` is then unchanged.
    pub fn AddPart(self: *DosBase, dirname: [*:0]u8, filename: [*:0]const u8, size: u32) bool {
        return libraries.call(self, LVO.AddPart, Fn.AddPart, .{ dirname, filename, size });
    }

    /// The last component of a path: "xxx:yyy/zzz/qqq" gives "qqq", "xxx:yyy"
    /// gives "yyy". Points into `name`.
    pub fn FilePart(self: *DosBase, name: [*:0]const u8) [*:0]const u8 {
        return libraries.call(self, LVO.FilePart, Fn.FilePart, .{name});
    }

    /// Where the next-to-last component ends: "xxx:yyy/zzz/qqq" gives "/qqq",
    /// "xxx:yyy" gives "yyy". A slash after a slash or a colon stays in the
    /// path (a way up). Points into `name`.
    pub fn PathPart(self: *DosBase, name: [*:0]const u8) [*:0]const u8 {
        return libraries.call(self, LVO.PathPart, Fn.PathPart, .{name});
    }

    /// Copy the part of `name` from `oldpos` to `separator` into `buf` (at most
    /// size-1 characters and a NUL). Returns the position after the separator
    /// for the next call, or -1 for the last part.
    pub fn SplitName(self: *DosBase, name: [*:0]const u8, separator: u8, buf: [*]u8, oldpos: i32, size: u32) i32 {
        return libraries.call(self, LVO.SplitName, Fn.SplitName, .{ name, separator, buf, oldpos, size });
    }

    /// Split a path: "DEV:rest" is absolute (volume "DEV"), ":rest" from the
    /// current volume's root, anything else relative. False and
    /// ERROR_INVALID_COMPONENT_NAME for a device name over 30 characters.
    pub fn ParsePath(self: *DosBase, name: [*:0]const u8, parsed: *dos.ParsedPath) bool {
        return libraries.call(self, LVO.ParsePath, Fn.ParsePath, .{ name, parsed });
    }

    /// Add named code to dos's resident segments; `seg_type` is its seg_UC
    /// (CMD_SYSTEM for system code, 0 for a user command nobody uses yet).
    /// Names already there aren't checked. False and ERROR_NO_FREE_STORE for no
    /// memory. Not while holding LockSegmentList.
    pub fn AddSegment(self: *DosBase, name: [*:0]const u8, code: ?*const dos.SegCode, seg_type: i32) bool {
        return libraries.call(self, LVO.AddSegment, Fn.AddSegment, .{ name, code, seg_type });
    }

    /// The next segment after `start` (null: from the first) with that name,
    /// in any case: with `system` one of the system's (seg_UC below 0), else a
    /// user segment (0 and up). The list must be locked (LockSegmentList);
    /// raise seg_UC under that lock while you use a user segment, and lower it
    /// when done. Null and ERROR_OBJECT_NOT_FOUND if there is none.
    pub fn FindSegment(self: *DosBase, name: [*:0]const u8, start: ?*dos.Segment, system: bool) ?*dos.Segment {
        return libraries.call(self, LVO.FindSegment, Fn.FindSegment, .{ name, start, system });
    }

    /// Take a segment off the list and free it: only a user segment nobody
    /// uses (seg_UC 0). False and ERROR_OBJECT_IN_USE otherwise, or
    /// ERROR_OBJECT_NOT_FOUND if it isn't on the list. Not while holding
    /// LockSegmentList.
    pub fn RemSegment(self: *DosBase, seg: *dos.Segment) bool {
        return libraries.call(self, LVO.RemSegment, Fn.RemSegment, .{seg});
    }

    /// Lock the resident segments, shared or exclusive; returns the first.
    pub fn LockSegmentList(self: *DosBase, shared: bool) ?*dos.Segment {
        return libraries.call(self, LVO.LockSegmentList, Fn.LockSegmentList, .{shared});
    }

    /// Unlock the resident segments.
    pub fn UnLockSegmentList(self: *DosBase) void {
        return libraries.call(self, LVO.UnLockSegmentList, Fn.UnLockSegmentList, .{});
    }

    /// A lock on a file or directory, SHARED_LOCK or EXCLUSIVE_LOCK: the name's
    /// handler (GetDeviceProc) is asked with ACTION_LOCATE_OBJECT, and along a
    /// multi-assign while the object isn't found. A name without a device is
    /// from the current directory. Null on failure; IoErr() says why.
    pub fn Lock(self: *DosBase, name: [*:0]const u8, mode: i32) ?*dos.FileLock {
        return libraries.call(self, LVO.Lock, Fn.Lock, .{ name, mode });
    }

    /// Give a lock back to its handler (ACTION_FREE_LOCK). Null does nothing;
    /// IoErr() stays as it was.
    pub fn UnLock(self: *DosBase, lock: ?*dos.FileLock) void {
        return libraries.call(self, LVO.UnLock, Fn.UnLock, .{lock});
    }

    /// Another shared lock on the same object (ACTION_COPY_DIR). DupLock(null)
    /// is null.
    pub fn DupLock(self: *DosBase, lock: ?*dos.FileLock) ?*dos.FileLock {
        return libraries.call(self, LVO.DupLock, Fn.DupLock, .{lock});
    }

    /// A lock on the directory the object is in (ACTION_PARENT); null at the
    /// root (IoErr() 0) or on failure. Null asks the current file system.
    pub fn ParentDir(self: *DosBase, lock: ?*dos.FileLock) ?*dos.FileLock {
        return libraries.call(self, LVO.ParentDir, Fn.ParentDir, .{lock});
    }

    /// LOCK_SAME if both lock the same object, LOCK_SAME_VOLUME if only the
    /// volume is the same, LOCK_DIFFERENT otherwise (also for null).
    pub fn SameLock(self: *DosBase, lock1: ?*dos.FileLock, lock2: ?*dos.FileLock) i32 {
        return libraries.call(self, LVO.SameLock, Fn.SameLock, .{ lock1, lock2 });
    }

    /// Make `lock` the process's current directory (null: the file system's
    /// root) and return the old one. Neither is duplicated or unlocked: the
    /// caller owns both. Null from a plain task, which has none.
    pub fn CurrentDir(self: *DosBase, lock: ?*dos.FileLock) ?*dos.FileLock {
        return libraries.call(self, LVO.CurrentDir, Fn.CurrentDir, .{lock});
    }

    /// Make a directory (ACTION_CREATE_DIR) and return an exclusive lock on it.
    pub fn CreateDir(self: *DosBase, name: [*:0]const u8) ?*dos.FileLock {
        return libraries.call(self, LVO.CreateDir, Fn.CreateDir, .{name});
    }

    /// Delete a file or an empty directory (ACTION_DELETE_OBJECT).
    pub fn DeleteFile(self: *DosBase, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.DeleteFile, Fn.DeleteFile, .{name});
    }

    /// The time now as a DateStamp (days since 1 Jan 1978, minutes past
    /// midnight, ticks of 1/50 s past the minute), from timer.device; all zero
    /// without it. Returns `date`.
    pub fn DateStamp(self: *DosBase, date: *dos.DateStamp) *dos.DateStamp {
        return libraries.call(self, LVO.DateStamp, Fn.DateStamp, .{date});
    }

    /// Which of two DateStamps is earlier: negative when `date1` is, zero when
    /// they are the same, positive when `date2` is.
    pub fn CompareDates(self: *DosBase, date1: *const dos.DateStamp, date2: *const dos.DateStamp) i32 {
        return libraries.call(self, LVO.CompareDates, Fn.CompareDates, .{ date1, date2 });
    }

    /// A DateStamp into the strings of a DateTime (sdk/libs/dos/datetime.zig):
    /// dat_StrDay the weekday, dat_StrDate the date in dat_Format, dat_StrTime
    /// "hh:mm:ss"; a null buffer is skipped. With DTF_SUBST and FORMAT_DOS the
    /// date of the last week or the next day comes out as "Today",
    /// "Yesterday", "Tomorrow", "Future" or a weekday name. False on a
    /// DateStamp that is no date. Each buffer holds LEN_DATSTRING bytes.
    pub fn DateToStr(self: *DosBase, datetime: *dos.DateTime) bool {
        return libraries.call(self, LVO.DateToStr, Fn.DateToStr, .{datetime});
    }

    /// The strings of a DateTime into its DateStamp: dat_StrDate the date, in
    /// dat_Format or as "Today", "Monday", ...; dat_StrTime "hh:mm[:ss]". A
    /// null string leaves that part of the stamp alone. DTF_FUTURE reads a
    /// weekday name as the coming one. False when a string is no date.
    pub fn StrToDate(self: *DosBase, datetime: *dos.DateTime) bool {
        return libraries.call(self, LVO.StrToDate, Fn.StrToDate, .{datetime});
    }

    /// Open a file: MODE_OLDFILE (an existing one), MODE_NEWFILE (a new one, or
    /// an existing one emptied), MODE_READWRITE (an existing one, or a new one,
    /// shared). "*" is the console (NIL: without one). Null on failure; IoErr()
    /// says why.
    pub fn Open(self: *DosBase, name: [*:0]const u8, mode: i32) ?*dos.FileHandle {
        return libraries.call(self, LVO.Open, Fn.Open, .{ name, mode });
    }

    /// Close a file (ACTION_END) and free the handle, even when that fails.
    /// Close each file once. False for null or when the handler says so.
    pub fn Close(self: *DosBase, file: ?*dos.FileHandle) bool {
        return libraries.call(self, LVO.Close, Fn.Close, .{file});
    }

    /// Read up to `length` bytes: the number read, 0 at the end, -1 on error.
    pub fn Read(self: *DosBase, file: ?*dos.FileHandle, buffer: [*]u8, length: isize) isize {
        return libraries.call(self, LVO.Read, Fn.Read, .{ file, buffer, length });
    }

    /// Write `length` bytes: the number written, -1 on error.
    pub fn Write(self: *DosBase, file: ?*dos.FileHandle, buffer: [*]const u8, length: isize) isize {
        return libraries.call(self, LVO.Write, Fn.Write, .{ file, buffer, length });
    }

    /// Move to `position` from OFFSET_BEGINNING, OFFSET_CURRENT or OFFSET_END:
    /// the old position, -1 on error. Not past the end.
    pub fn Seek(self: *DosBase, file: ?*dos.FileHandle, position: isize, mode: i32) isize {
        return libraries.call(self, LVO.Seek, Fn.Seek, .{ file, position, mode });
    }

    /// The process's input (pr_CIS); don't close it. Null from a plain task.
    pub fn Input(self: *DosBase) ?*dos.FileHandle {
        return libraries.call(self, LVO.Input, Fn.Input, .{});
    }

    /// The process's output (pr_COS); don't close it. Null from a plain task.
    pub fn Output(self: *DosBase) ?*dos.FileHandle {
        return libraries.call(self, LVO.Output, Fn.Output, .{});
    }

    /// Make `file` the process's input; returns the old one.
    pub fn SelectInput(self: *DosBase, file: ?*dos.FileHandle) ?*dos.FileHandle {
        return libraries.call(self, LVO.SelectInput, Fn.SelectInput, .{file});
    }

    /// Make `file` the process's output; returns the old one.
    pub fn SelectOutput(self: *DosBase, file: ?*dos.FileHandle) ?*dos.FileHandle {
        return libraries.call(self, LVO.SelectOutput, Fn.SelectOutput, .{file});
    }

    /// Whether the file is a console (a virtual terminal).
    pub fn IsInteractive(self: *DosBase, file: ?*dos.FileHandle) bool {
        return libraries.call(self, LVO.IsInteractive, Fn.IsInteractive, .{file});
    }

    /// Fill in the FileInfoBlock about the lock's object (lock 0: the current
    /// file system's root). Examine a directory before ExNext with the same
    /// FIB.
    pub fn Examine(self: *DosBase, lock: ?*dos.FileLock, fib: *dos.FileInfoBlock) bool {
        return libraries.call(self, LVO.Examine, Fn.Examine, .{ lock, fib });
    }

    /// The next entry of the directory Examine was called on, with the same
    /// lock and FIB. False at the end (IoErr() ERROR_NO_MORE_ENTRIES) or on
    /// error; not for lock 0.
    pub fn ExNext(self: *DosBase, lock: ?*dos.FileLock, fib: *dos.FileInfoBlock) bool {
        return libraries.call(self, LVO.ExNext, Fn.ExNext, .{ lock, fib });
    }

    /// Fill in the FileInfoBlock about an open file.
    pub fn ExamineFH(self: *DosBase, file: ?*dos.FileHandle, fib: *dos.FileInfoBlock) bool {
        return libraries.call(self, LVO.ExamineFH, Fn.ExamineFH, .{ file, fib });
    }

    /// Several entries of a directory into `buffer` as ExAllData records of
    /// level `data_type` (ED_NAME .. ED_OWNER); `control` (AllocDosObject,
    /// last_key 0) keeps the place. True: call again (control.entries may be
    /// 0); false: done (IoErr() ERROR_NO_MORE_ENTRIES) or failed. dos does it
    /// with Examine/ExNext for handlers that don't know EXAMINE_ALL.
    pub fn ExAll(self: *DosBase, lock: ?*dos.FileLock, buffer: [*]u8, size: isize, data_type: i32, control: *dos.ExAllControl) bool {
        return libraries.call(self, LVO.ExAll, Fn.ExAll, .{ lock, buffer, size, data_type, control });
    }

    /// Stop an ExAll before it is done, with the same arguments.
    pub fn ExAllEnd(self: *DosBase, lock: ?*dos.FileLock, buffer: [*]u8, size: isize, data_type: i32, control: *dos.ExAllControl) void {
        return libraries.call(self, LVO.ExAllEnd, Fn.ExAllEnd, .{ lock, buffer, size, data_type, control });
    }

    /// The process's CommandLineInterface; null when it isn't a CLI, or for a
    /// plain task.
    pub fn Cli(self: *DosBase) ?*dos.CommandLineInterface {
        return libraries.call(self, LVO.Cli, Fn.Cli, .{});
    }

    /// Make `file` the error stream (pr_CES; null: none, use Output()) and
    /// return the old one.
    pub fn SelectError(self: *DosBase, file: ?*dos.FileHandle) ?*dos.FileHandle {
        return libraries.call(self, LVO.SelectError, Fn.SelectError, .{file});
    }

    /// The error stream (pr_CES), null if none is set.
    pub fn ErrorOutput(self: *DosBase) ?*dos.FileHandle {
        return libraries.call(self, LVO.ErrorOutput, Fn.ErrorOutput, .{});
    }

    /// The console handler's port (pr_ConsoleTask), for "*" and CONSOLE:.
    pub fn GetConsoleTask(self: *DosBase) ?*exec.MsgPort {
        return libraries.call(self, LVO.GetConsoleTask, Fn.GetConsoleTask, .{});
    }

    /// Set pr_ConsoleTask; returns the old one.
    pub fn SetConsoleTask(self: *DosBase, port: ?*exec.MsgPort) ?*exec.MsgPort {
        return libraries.call(self, LVO.SetConsoleTask, Fn.SetConsoleTask, .{port});
    }

    /// The default file system's port (pr_FileSystemTask), for lock 0.
    pub fn GetFileSysTask(self: *DosBase) ?*exec.MsgPort {
        return libraries.call(self, LVO.GetFileSysTask, Fn.GetFileSysTask, .{});
    }

    /// Set pr_FileSystemTask; returns the old one.
    pub fn SetFileSysTask(self: *DosBase, port: ?*exec.MsgPort) ?*exec.MsgPort {
        return libraries.call(self, LVO.SetFileSysTask, Fn.SetFileSysTask, .{port});
    }

    /// The program's directory (pr_HomeDir, PROGDIR:); don't UnLock it.
    pub fn GetProgramDir(self: *DosBase) ?*dos.FileLock {
        return libraries.call(self, LVO.GetProgramDir, Fn.GetProgramDir, .{});
    }

    /// Set pr_HomeDir; returns the old lock, the caller's to UnLock.
    pub fn SetProgramDir(self: *DosBase, lock: ?*dos.FileLock) ?*dos.FileLock {
        return libraries.call(self, LVO.SetProgramDir, Fn.SetProgramDir, .{lock});
    }

    /// The CLI's command name. False without a CLI, or if it doesn't fit
    /// (IoErr() ERROR_LINE_TOO_LONG; nothing changes).
    pub fn SetProgramName(self: *DosBase, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.SetProgramName, Fn.SetProgramName, .{name});
    }

    /// The CLI's command name into `buffer`. False without a CLI, or cut to
    /// fit (IoErr() ERROR_LINE_TOO_LONG).
    pub fn GetProgramName(self: *DosBase, buffer: [*]u8, size: u32) bool {
        return libraries.call(self, LVO.GetProgramName, Fn.GetProgramName, .{ buffer, size });
    }

    /// The CLI's prompt, as SetProgramName.
    pub fn SetPrompt(self: *DosBase, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.SetPrompt, Fn.SetPrompt, .{name});
    }

    /// The CLI's prompt, as GetProgramName.
    pub fn GetPrompt(self: *DosBase, buffer: [*]u8, size: u32) bool {
        return libraries.call(self, LVO.GetPrompt, Fn.GetPrompt, .{ buffer, size });
    }

    /// The CLI's name for its current directory, as SetProgramName (dos
    /// doesn't check it against the current directory).
    pub fn SetCurrentDirName(self: *DosBase, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.SetCurrentDirName, Fn.SetCurrentDirName, .{name});
    }

    /// The CLI's name for its current directory, as GetProgramName; without a
    /// CLI, NameFromLock of the current directory.
    pub fn GetCurrentDirName(self: *DosBase, buffer: [*]u8, size: u32) bool {
        return libraries.call(self, LVO.GetCurrentDirName, Fn.GetCurrentDirName, .{ buffer, size });
    }

    /// The full name of a lock's object ("Ram Disk:d/file"; lock 0: the file
    /// system's root). False on error or if it doesn't fit (IoErr()
    /// ERROR_LINE_TOO_LONG), with an empty buffer.
    pub fn NameFromLock(self: *DosBase, lock: ?*dos.FileLock, buffer: [*]u8, size: u32) bool {
        return libraries.call(self, LVO.NameFromLock, Fn.NameFromLock, .{ lock, buffer, size });
    }

    /// Make `name` (without the colon, up to 30 characters) an assign to the
    /// directory `lock`, which dos keeps; on failure it stays yours. An assign
    /// of that name is replaced and its locks unlocked; a null lock removes
    /// it. A device's or volume's name is ERROR_OBJECT_EXISTS.
    pub fn AssignLock(self: *DosBase, name: [*:0]const u8, lock: ?*dos.FileLock) bool {
        return libraries.call(self, LVO.AssignLock, Fn.AssignLock, .{ name, lock });
    }

    /// A late-binding assign: `path` is locked the first time the assign is
    /// used, and from then on it is an assign to that directory.
    pub fn AssignLate(self: *DosBase, name: [*:0]const u8, path: [*:0]const u8) bool {
        return libraries.call(self, LVO.AssignLate, Fn.AssignLate, .{ name, path });
    }

    /// A non-binding assign: `path` is locked each time the assign is used.
    pub fn AssignPath(self: *DosBase, name: [*:0]const u8, path: [*:0]const u8) bool {
        return libraries.call(self, LVO.AssignPath, Fn.AssignPath, .{ name, path });
    }

    /// Add a directory after the others of the assign `name` (a plain one,
    /// not late or non-binding); dos keeps the lock.
    pub fn AssignAdd(self: *DosBase, name: [*:0]const u8, lock: *dos.FileLock) bool {
        return libraries.call(self, LVO.AssignAdd, Fn.AssignAdd, .{ name, lock });
    }

    /// Remove the directory that SameLock finds the same as `lock` from the
    /// assign `name`, the first one too (the next moves up; the last takes
    /// the assign with it). `lock` stays yours.
    pub fn RemAssignList(self: *DosBase, name: [*:0]const u8, lock: *dos.FileLock) bool {
        return libraries.call(self, LVO.RemAssignList, Fn.RemAssignList, .{ name, lock });
    }

    /// The first object a pattern names ("RAM:d/#?.txt": utility.library's
    /// patterns, the device part literal): in anchor.info, and its full path
    /// in the anchor.strlen bytes after the AnchorPath when strlen isn't 0.
    /// 0, or an error (ERROR_NO_MORE_ENTRIES for none; also in IoErr()). "*"
    /// and handlers that aren't file systems give one entry, the name itself.
    pub fn MatchFirst(self: *DosBase, pattern: [*:0]const u8, anchor: *dos.AnchorPath) i32 {
        return libraries.call(self, LVO.MatchFirst, Fn.MatchFirst, .{ pattern, anchor });
    }

    /// The next object, as MatchFirst. Set APF_DODIR first to go into the
    /// directory just found; it comes again with APF_DIDDIR when it is done.
    /// Any error but ERROR_BUFFER_OVERFLOW ends the search.
    pub fn MatchNext(self: *DosBase, anchor: *dos.AnchorPath) i32 {
        return libraries.call(self, LVO.MatchNext, Fn.MatchNext, .{anchor});
    }

    /// Free what MatchFirst and MatchNext hold.
    pub fn MatchEnd(self: *DosBase, anchor: *dos.AnchorPath) void {
        return libraries.call(self, LVO.MatchEnd, Fn.MatchEnd, .{anchor});
    }

    /// Rename or move `from` to `to` on the same volume ("RAM:a" to
    /// "RAM:d/b"): ERROR_RENAME_ACROSS_DEVICES for another handler,
    /// ERROR_OBJECT_EXISTS if `to` is there.
    pub fn Rename(self: *DosBase, from: [*:0]const u8, to: [*:0]const u8) bool {
        return libraries.call(self, LVO.Rename, Fn.Rename, .{ from, to });
    }

    /// Set the protection bits (FIBF_*; the low four are set to forbid).
    pub fn SetProtection(self: *DosBase, name: [*:0]const u8, bits: u32) bool {
        return libraries.call(self, LVO.SetProtection, Fn.SetProtection, .{ name, bits });
    }

    /// Set the comment: at most 79 characters, "" removes it.
    pub fn SetComment(self: *DosBase, name: [*:0]const u8, comment: [*:0]const u8) bool {
        return libraries.call(self, LVO.SetComment, Fn.SetComment, .{ name, comment });
    }

    /// Set the date (DateStamp()'s, say).
    pub fn SetFileDate(self: *DosBase, name: [*:0]const u8, date: *const dos.DateStamp) bool {
        return libraries.call(self, LVO.SetFileDate, Fn.SetFileDate, .{ name, date });
    }

    /// Set the owner: user << 16 | group.
    pub fn SetOwner(self: *DosBase, name: [*:0]const u8, owner_info: u32) bool {
        return libraries.call(self, LVO.SetOwner, Fn.SetOwner, .{ name, owner_info });
    }

    /// Cut or grow an open file to `offset` from OFFSET_BEGINNING,
    /// OFFSET_CURRENT or OFFSET_END; new bytes are 0. The new size, or -1.
    pub fn SetFileSize(self: *DosBase, file: ?*dos.FileHandle, offset: isize, mode: i32) isize {
        return libraries.call(self, LVO.SetFileSize, Fn.SetFileSize, .{ file, offset, mode });
    }

    /// A shared lock on an open file.
    pub fn DupLockFromFH(self: *DosBase, file: ?*dos.FileHandle) ?*dos.FileLock {
        return libraries.call(self, LVO.DupLockFromFH, Fn.DupLockFromFH, .{file});
    }

    /// A shared lock on the directory an open file is in.
    pub fn ParentOfFH(self: *DosBase, file: ?*dos.FileHandle) ?*dos.FileLock {
        return libraries.call(self, LVO.ParentOfFH, Fn.ParentOfFH, .{file});
    }

    /// The full name of an open file, as NameFromLock.
    pub fn NameFromFH(self: *DosBase, file: ?*dos.FileHandle, buffer: [*]u8, size: u32) bool {
        return libraries.call(self, LVO.NameFromFH, Fn.NameFromFH, .{ file, buffer, size });
    }

    /// An open file from a lock on a file; the lock is the file's from then
    /// on (on failure it stays yours).
    pub fn OpenFromLock(self: *DosBase, lock: ?*dos.FileLock) ?*dos.FileHandle {
        return libraries.call(self, LVO.OpenFromLock, Fn.OpenFromLock, .{lock});
    }

    /// A lock (CHANGE_LOCK: SHARED_LOCK or EXCLUSIVE_LOCK) or an open file
    /// (CHANGE_FH: MODE_NEWFILE exclusive, else shared) to another access;
    /// ERROR_OBJECT_IN_USE while others hold it.
    pub fn ChangeMode(self: *DosBase, kind: i32, object: ?*anyopaque, mode: i32) bool {
        return libraries.call(self, LVO.ChangeMode, Fn.ChangeMode, .{ kind, object, mode });
    }

    /// The volume a lock is on, in `data` (lock 0: the current file system).
    pub fn Info(self: *DosBase, lock: ?*dos.FileLock, data: *dos.InfoData) bool {
        return libraries.call(self, LVO.Info, Fn.Info, .{ lock, data });
    }

    /// Whether a name's handler is a file system ("*" isn't; a name without a
    /// device is).
    pub fn IsFileSystem(self: *DosBase, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.IsFileSystem, Fn.IsFileSystem, .{name});
    }

    /// Whether two locks are on one device: the same volume or handler.
    pub fn SameDevice(self: *DosBase, lock1: ?*dos.FileLock, lock2: ?*dos.FileLock) bool {
        return libraries.call(self, LVO.SameDevice, Fn.SameDevice, .{ lock1, lock2 });
    }

    /// Hand back what the buffer holds: waiting bytes are written, bytes read
    /// ahead given back (seeked back over). False, with
    /// IoErr, when writing fails.
    pub fn Flush(self: *DosBase, file: ?*dos.FileHandle) bool {
        return libraries.call(self, LVO.Flush, Fn.Flush, .{file});
    }

    /// The next byte (0-255), or -1 at the end (IoErr 0) or on an error.
    pub fn FGetC(self: *DosBase, file: ?*dos.FileHandle) i32 {
        return libraries.call(self, LVO.FGetC, Fn.FGetC, .{file});
    }

    /// Push `character` back for the next FGetC; -1 pushes back the last one
    /// FGetC gave (the end too). Up to 4; false when full or nothing to push.
    pub fn UnGetC(self: *DosBase, file: ?*dos.FileHandle, character: i32) bool {
        return libraries.call(self, LVO.UnGetC, Fn.UnGetC, .{ file, character });
    }

    /// Write a byte (the low 8 bits): the byte, or -1 on an error.
    pub fn FPutC(self: *DosBase, file: ?*dos.FileHandle, character: i32) i32 {
        return libraries.call(self, LVO.FPutC, Fn.FPutC, .{ file, character });
    }

    /// Read up to `length` bytes through the buffer: the number read, 0 at the
    /// end, -1 on an error before any byte. A console gives what it has.
    pub fn FRead(self: *DosBase, file: ?*dos.FileHandle, buffer: [*]u8, length: isize) isize {
        return libraries.call(self, LVO.FRead, Fn.FRead, .{ file, buffer, length });
    }

    /// Write `length` bytes through the buffer: `length`, or -1 on an error.
    pub fn FWrite(self: *DosBase, file: ?*dos.FileHandle, buffer: [*]const u8, length: isize) isize {
        return libraries.call(self, LVO.FWrite, Fn.FWrite, .{ file, buffer, length });
    }

    /// A line into `buffer`: at most size-1 bytes, the newline kept, then a
    /// NUL. Null at the end (or on an error) before any byte.
    pub fn FGets(self: *DosBase, file: ?*dos.FileHandle, buffer: [*]u8, size: u32) ?[*]u8 {
        return libraries.call(self, LVO.FGets, Fn.FGets, .{ file, buffer, size });
    }

    /// Write a C string: 0, or -1 on an error.
    pub fn FPuts(self: *DosBase, file: ?*dos.FileHandle, string: [*:0]const u8) i32 {
        return libraries.call(self, LVO.FPuts, Fn.FPuts, .{ file, string });
    }

    /// The buffer's mode (BUF_LINE, BUF_FULL, BUF_NONE) and, unless size is
    /// -1, its size, in `buffer` (the caller's, kept until Close) or allocated
    /// (buffer null). What the old one held is flushed. 0, or -1 with IoErr.
    pub fn SetVBuf(self: *DosBase, file: ?*dos.FileHandle, buffer: ?[*]u8, mode: i32, size: isize) i32 {
        return libraries.call(self, LVO.SetVBuf, Fn.SetVBuf, .{ file, buffer, mode, size });
    }

    /// RawDoFmt's format with its data stream, through FPutC: the bytes
    /// written, or -1. sdk.dos.stdio.FPrintf packs the values.
    pub fn VFPrintf(self: *DosBase, file: ?*dos.FileHandle, format: [*:0]const u8, args: ?*const anyopaque) i32 {
        return libraries.call(self, LVO.VFPrintf, Fn.VFPrintf, .{ file, format, args });
    }

    /// VFPrintf to Output() (sdk.dos.stdio.Printf).
    pub fn VPrintf(self: *DosBase, format: [*:0]const u8, args: ?*const anyopaque) i32 {
        return libraries.call(self, LVO.VPrintf, Fn.VPrintf, .{ format, args });
    }

    /// FPuts to Output().
    pub fn PutStr(self: *DosBase, string: [*:0]const u8) i32 {
        return libraries.call(self, LVO.PutStr, Fn.PutStr, .{string});
    }

    /// FWrite to Output().
    pub fn WriteChars(self: *DosBase, buffer: [*]const u8, length: isize) isize {
        return libraries.call(self, LVO.WriteChars, Fn.WriteChars, .{ buffer, length });
    }

    /// Parse arguments by a template ("FROM/M/A,TO/A,Q=QUIET/S"): /A required,
    /// /K only with its keyword, /S switch, /N number, /T toggle (YES, NO, ON,
    /// OFF), /M many, /F the rest of the line; '=' names aliases. Into `argv`,
    /// one pointer-sized slot per item, set by the caller to defaults: a
    /// string, an i32's address (/N), DOSTRUE (/S, /T), or a null-terminated
    /// array (/M). From `rdargs`'s CSource, else Input(); a null `rdargs`
    /// makes one. Null on failure (IoErr); FreeArgs the result.
    pub fn ReadArgs(self: *DosBase, template: [*:0]const u8, argv: [*]usize, rdargs: ?*dos.RDArgs) ?*dos.RDArgs {
        return libraries.call(self, LVO.ReadArgs, Fn.ReadArgs, .{ template, argv, rdargs });
    }

    /// Free what ReadArgs allocated (its RDArgs too, if it made it). Null is
    /// fine, and so is a second call.
    pub fn FreeArgs(self: *DosBase, rdargs: ?*dos.RDArgs) void {
        return libraries.call(self, LVO.FreeArgs, Fn.FreeArgs, .{rdargs});
    }

    /// The next item from `csource` (Input() without a buffer) into `buffer`
    /// (`maxchars` bytes with the NUL): ITEM_QUOTED, ITEM_UNQUOTED,
    /// ITEM_NOTHING (the line's end), ITEM_EQUAL (a leading '='), ITEM_ERROR.
    pub fn ReadItem(self: *DosBase, buffer: [*]u8, maxchars: i32, csource: ?*dos.CSource) i32 {
        return libraries.call(self, LVO.ReadItem, Fn.ReadItem, .{ buffer, maxchars, csource });
    }

    /// The number of the template item `keyword` names (any alias, any case),
    /// or -1.
    pub fn FindArg(self: *DosBase, template: [*:0]const u8, keyword: [*:0]const u8) i32 {
        return libraries.call(self, LVO.FindArg, Fn.FindArg, .{ template, keyword });
    }

    /// A decimal number (after spaces, with an optional '-') into `value`: the
    /// characters used, or -1 (value 0) without one or beyond an i32.
    pub fn StrToLong(self: *DosBase, string: [*:0]const u8, value: *i32) i32 {
        return libraries.call(self, LVO.StrToLong, Fn.StrToLong, .{ string, value });
    }

    /// A console's mode: 1 raw (bytes as typed, no echo or editing), 0 cooked
    /// (edited lines). What waits in the buffer is written first. False, with
    /// IoErr, when the handler can't.
    pub fn SetMode(self: *DosBase, file: ?*dos.FileHandle, mode: i32) bool {
        return libraries.call(self, LVO.SetMode, Fn.SetMode, .{ file, mode });
    }

    /// Whether a console has input within `timeout` microseconds (cooked: a
    /// whole line); bytes in the handle's buffer count.
    pub fn WaitForChar(self: *DosBase, file: ?*dos.FileHandle, timeout: isize) bool {
        return libraries.call(self, LVO.WaitForChar, Fn.WaitForChar, .{ file, timeout });
    }

    /// The text for an error code (IoErr's; the shell's are negative) after
    /// `header` and ": " into `buffer` (`len` bytes with the NUL, cut to
    /// fit); "Error <n>" for one without a text; nothing for 0. The length.
    pub fn Fault(self: *DosBase, code: i32, header: ?[*:0]const u8, buffer: [*]u8, len: i32) i32 {
        return libraries.call(self, LVO.Fault, Fn.Fault, .{ code, header, buffer, len });
    }

    /// Fault's text and a newline to Output(); IoErr is left at the code.
    /// False without an Output() or when the write fails.
    pub fn PrintFault(self: *DosBase, code: i32, header: ?[*:0]const u8) bool {
        return libraries.call(self, LVO.PrintFault, Fn.PrintFault, .{ code, header });
    }

    /// Set a local variable or alias (LV_VAR or LV_ALIAS in the low byte of
    /// `flags`), or a global one in ENV: with GVF_GLOBAL_ONLY; `size` -1 is
    /// strlen. A null `buffer` deletes it. False, with IoErr, on failure.
    pub fn SetVar(self: *DosBase, name: [*:0]const u8, buffer: ?[*]const u8, size: isize, flags: u32) bool {
        return libraries.call(self, LVO.SetVar, Fn.SetVar, .{ name, buffer, size, flags });
    }

    /// A variable's value into `buffer` (`size` bytes): the local one, else
    /// ENV:'s (unless GVF_LOCAL_ONLY); text is cut at a newline and ends in a
    /// NUL. The bytes copied (IoErr: the whole length), or -1 with IoErr.
    pub fn GetVar(self: *DosBase, name: [*:0]const u8, buffer: [*]u8, size: isize, flags: u32) isize {
        return libraries.call(self, LVO.GetVar, Fn.GetVar, .{ name, buffer, size, flags });
    }

    /// SetVar(name, null, 0, flags).
    pub fn DeleteVar(self: *DosBase, name: [*:0]const u8, flags: u32) bool {
        return libraries.call(self, LVO.DeleteVar, Fn.DeleteVar, .{ name, flags });
    }

    /// A local variable or alias of `var_type` (LV_VAR, LV_ALIAS), or null.
    pub fn FindVar(self: *DosBase, name: [*:0]const u8, var_type: u32) ?*dos.LocalVar {
        return libraries.call(self, LVO.FindVar, Fn.FindVar, .{ name, var_type });
    }

    /// Which of `mask`'s signals came (SIGBREAKF_CTRL_C..F); they are cleared.
    pub fn CheckSignal(self: *DosBase, mask: u32) u32 {
        return libraries.call(self, LVO.CheckSignal, Fn.CheckSignal, .{mask});
    }

    /// Wait `ticks` fiftieths of a second.
    pub fn Delay(self: *DosBase, ticks: u32) void {
        return libraries.call(self, LVO.Delay, Fn.Delay, .{ticks});
    }

    /// The running command's argument line (pr_Arguments), or null.
    pub fn GetArgStr(self: *DosBase) ?[*:0]const u8 {
        return libraries.call(self, LVO.GetArgStr, Fn.GetArgStr, .{});
    }

    /// Set pr_Arguments; the old one.
    pub fn SetArgStr(self: *DosBase, string: ?[*:0]const u8) ?[*:0]const u8 {
        return libraries.call(self, LVO.SetArgStr, Fn.SetArgStr, .{string});
    }

    /// The highest CLI number in use (0: none).
    pub fn MaxCli(self: *DosBase) u32 {
        return libraries.call(self, LVO.MaxCli, Fn.MaxCli, .{});
    }

    /// The CLI process with number `num` (pr_TaskNum), or null.
    pub fn FindCliProc(self: *DosBase, num: u32) ?*dos.Process {
        return libraries.call(self, LVO.FindCliProc, Fn.FindCliProc, .{num});
    }

    /// Run a segment's command on this process, on a stack of its own of
    /// `stack_size` bytes: `args` (`length` bytes, a line ending in a newline)
    /// are Input()'s read-ahead and pr_Arguments meanwhile. The command's
    /// return code, or -1 (IoErr) when it can't run.
    pub fn RunCommand(self: *DosBase, code: ?*const dos.SegCode, stack_size: u32, args: [*]const u8, length: isize) i32 {
        return libraries.call(self, LVO.RunCommand, Fn.RunCommand, .{ code, stack_size, args, length });
    }

    /// Run `command` (a line, or several) in a new shell ("BootShell";
    /// SYS_UserShell: "shell"; SYS_CustomShell: another resident) with
    /// SYS_Input and SYS_Output (default Input(), Output()). Waits and returns
    /// the last return code (IoErr: its Result2), or -1 when it can't start;
    /// with SYS_Asynch it returns at once, with the new CLI's number, and the
    /// shell closes the streams. A null command starts an interactive shell on
    /// SYS_Input. CreateNewProc's tags pass through.
    pub fn SystemTagList(self: *DosBase, command: ?[*:0]const u8, tags: ?[*]const utility.TagItem) i32 {
        return libraries.call(self, LVO.SystemTagList, Fn.SystemTagList, .{ command, tags });
    }

    /// Run `command` in a new shell, then the commands from `input` (if any),
    /// with `output` (null: Output()). True if the shell ran.
    pub fn Execute(self: *DosBase, command: [*:0]const u8, input: ?*dos.FileHandle, output: ?*dos.FileHandle) bool {
        return libraries.call(self, LVO.Execute, Fn.Execute, .{ command, input, output });
    }

    /// Load a program or module file (sdk/libs/dos/loadfile.zig, made by
    /// sdk/tools/elf2seg): its segments into memory the CPU can run, the
    /// addresses in them relocated. Returns the seglist for UnLoadSeg, or null
    /// with IoErr.
    pub fn LoadSeg(self: *DosBase, name: [*:0]const u8) ?*dos.SegList {
        return libraries.call(self, LVO.LoadSeg, Fn.LoadSeg, .{name});
    }

    /// Free what LoadSeg made. Null is allowed.
    pub fn UnLoadSeg(self: *DosBase, seg_list: ?*dos.SegList) void {
        return libraries.call(self, LVO.UnLoadSeg, Fn.UnLoadSeg, .{seg_list});
    }
};
