// SPDX-License-Identifier: MIT
//! exec.library's jump table: libraries, lists, task switching and
//! interrupts, memory, tasks and signals, messages and ports, semaphores,
//! devices and I/O, and resident modules. New functions only ever go at
//! the end, so a slot never moves.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/exec_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "exec.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const MakeLibrary = libraries.lvo(4);
    pub const AddLibrary = libraries.lvo(5);
    pub const RemLibrary = libraries.lvo(6);
    pub const OpenLibrary = libraries.lvo(7);
    pub const CloseLibrary = libraries.lvo(8);
    pub const SetFunction = libraries.lvo(9);
    pub const CreateLibrary = libraries.lvo(10);
    pub const FindName = libraries.lvo(11);
    pub const Forbid = libraries.lvo(12);
    pub const Permit = libraries.lvo(13);
    pub const Insert = libraries.lvo(14);
    pub const AddHead = libraries.lvo(15);
    pub const AddTail = libraries.lvo(16);
    pub const Remove = libraries.lvo(17);
    pub const RemHead = libraries.lvo(18);
    pub const RemTail = libraries.lvo(19);
    pub const Enqueue = libraries.lvo(20);
    pub const NewList = libraries.lvo(21);
    pub const CreateMemHeader = libraries.lvo(22);
    pub const AddMemList = libraries.lvo(23);
    pub const Allocate = libraries.lvo(24);
    pub const Deallocate = libraries.lvo(25);
    pub const AllocMem = libraries.lvo(26);
    pub const FreeMem = libraries.lvo(27);
    pub const AvailMem = libraries.lvo(28);
    pub const AddMemHandler = libraries.lvo(29);
    pub const RemMemHandler = libraries.lvo(30);
    pub const SetIntVector = libraries.lvo(31);
    pub const AddIntServer = libraries.lvo(32);
    pub const RemIntServer = libraries.lvo(33);
    pub const Disable = libraries.lvo(34);
    pub const Enable = libraries.lvo(35);
    pub const Cause = libraries.lvo(36);
    pub const Alert = libraries.lvo(37);
    pub const SetTrapCode = libraries.lvo(38);
    pub const AddTask = libraries.lvo(39);
    pub const RemTask = libraries.lvo(40);
    pub const FindTask = libraries.lvo(41);
    pub const SetTaskPri = libraries.lvo(42);
    pub const Signal = libraries.lvo(43);
    pub const Wait = libraries.lvo(44);
    pub const SetSignal = libraries.lvo(45);
    pub const AllocSignal = libraries.lvo(46);
    pub const FreeSignal = libraries.lvo(47);
    pub const CreateTask = libraries.lvo(48);
    pub const SetExcept = libraries.lvo(49);
    pub const PutMsg = libraries.lvo(50);
    pub const GetMsg = libraries.lvo(51);
    pub const ReplyMsg = libraries.lvo(52);
    pub const WaitPort = libraries.lvo(53);
    pub const AddPort = libraries.lvo(54);
    pub const RemPort = libraries.lvo(55);
    pub const FindPort = libraries.lvo(56);
    pub const CreateMsgPort = libraries.lvo(57);
    pub const DeleteMsgPort = libraries.lvo(58);
    pub const InitSemaphore = libraries.lvo(59);
    pub const ObtainSemaphore = libraries.lvo(60);
    pub const ReleaseSemaphore = libraries.lvo(61);
    pub const AttemptSemaphore = libraries.lvo(62);
    pub const ObtainSemaphoreList = libraries.lvo(63);
    pub const ReleaseSemaphoreList = libraries.lvo(64);
    pub const FindSemaphore = libraries.lvo(65);
    pub const AddSemaphore = libraries.lvo(66);
    pub const RemSemaphore = libraries.lvo(67);
    pub const ObtainSemaphoreShared = libraries.lvo(68);
    pub const AttemptSemaphoreShared = libraries.lvo(69);
    pub const Procure = libraries.lvo(70);
    pub const Vacate = libraries.lvo(71);
    pub const AllocVec = libraries.lvo(72);
    pub const FreeVec = libraries.lvo(73);
    pub const CopyMem = libraries.lvo(74);
    pub const CopyMemQuick = libraries.lvo(75);
    pub const SetMem = libraries.lvo(76);
    pub const AddDevice = libraries.lvo(77);
    pub const RemDevice = libraries.lvo(78);
    pub const OpenDevice = libraries.lvo(79);
    pub const CloseDevice = libraries.lvo(80);
    pub const DoIO = libraries.lvo(81);
    pub const SendIO = libraries.lvo(82);
    pub const WaitIO = libraries.lvo(83);
    pub const ReplyIO = libraries.lvo(84);
    pub const CheckIO = libraries.lvo(85);
    pub const AbortIO = libraries.lvo(86);
    pub const FindResident = libraries.lvo(87);
    pub const InitCode = libraries.lvo(88);
    pub const InitResident = libraries.lvo(89);
    pub const CreateIORequest = libraries.lvo(90);
    pub const DeleteIORequest = libraries.lvo(91);
    pub const RawDoFmt = libraries.lvo(92);
    pub const RawPutChar = libraries.lvo(93);
    pub const RawMayGetChar = libraries.lvo(94);
    pub const RawIOInit = libraries.lvo(95);
    pub const AddResource = libraries.lvo(96);
    pub const RemResource = libraries.lvo(97);
    pub const OpenResource = libraries.lvo(98);
    pub const ColdReboot = libraries.lvo(99);
    pub const CacheClearU = libraries.lvo(100);
    pub const CacheClearE = libraries.lvo(101);
    pub const CachePreDMA = libraries.lvo(102);
    pub const CachePostDMA = libraries.lvo(103);
    pub const NewStackRun = libraries.lvo(104);
    pub const CodeAddress = libraries.lvo(105);
    pub const ExecList = libraries.lvo(106);
    pub const IntVector = libraries.lvo(107);
    pub const ResModules = libraries.lvo(108);
    pub const SetRamLib = libraries.lvo(109);
    pub const RamLib = libraries.lvo(110);
    pub const CreatePool = libraries.lvo(111);
    pub const DeletePool = libraries.lvo(112);
    pub const AllocPooled = libraries.lvo(113);
    pub const FreePooled = libraries.lvo(114);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const MakeLibrary = *const fn (*ExecBase, [*]const *const anyopaque, usize, usize, ?exec.InitFn, ?*anyopaque) callconv(.c) ?*exec.Library;
    pub const AddLibrary = *const fn (*ExecBase, *exec.Library) callconv(.c) void;
    pub const RemLibrary = *const fn (*ExecBase, *exec.Library) callconv(.c) ?*anyopaque;
    pub const OpenLibrary = *const fn (*ExecBase, [*:0]const u8, u32) callconv(.c) ?*exec.Library;
    pub const CloseLibrary = *const fn (*ExecBase, ?*exec.Library) callconv(.c) void;
    pub const SetFunction = *const fn (*ExecBase, *exec.Library, isize, *const anyopaque) callconv(.c) *const anyopaque;
    pub const CreateLibrary = *const fn (*ExecBase, *const exec.LibraryInit) callconv(.c) ?*exec.Library;
    pub const FindName = *const fn (*ExecBase, *exec.List, [*:0]const u8) callconv(.c) ?*exec.Node;
    pub const Forbid = *const fn (*ExecBase) callconv(.c) void;
    pub const Permit = *const fn (*ExecBase) callconv(.c) void;
    pub const Insert = *const fn (*ExecBase, *exec.List, *exec.Node, ?*exec.Node) callconv(.c) void;
    pub const AddHead = *const fn (*ExecBase, *exec.List, *exec.Node) callconv(.c) void;
    pub const AddTail = *const fn (*ExecBase, *exec.List, *exec.Node) callconv(.c) void;
    pub const Remove = *const fn (*ExecBase, *exec.Node) callconv(.c) void;
    pub const RemHead = *const fn (*ExecBase, *exec.List) callconv(.c) ?*exec.Node;
    pub const RemTail = *const fn (*ExecBase, *exec.List) callconv(.c) ?*exec.Node;
    pub const Enqueue = *const fn (*ExecBase, *exec.List, *exec.Node) callconv(.c) void;
    pub const NewList = *const fn (*ExecBase, *exec.List) callconv(.c) void;
    pub const CreateMemHeader = *const fn (*ExecBase, usize, u32, i8, *anyopaque, ?[*:0]const u8) callconv(.c) ?*exec.MemHeader;
    pub const AddMemList = *const fn (*ExecBase, usize, u32, i8, *anyopaque, ?[*:0]const u8) callconv(.c) ?*exec.MemHeader;
    pub const Allocate = *const fn (*ExecBase, *exec.MemHeader, usize) callconv(.c) ?*anyopaque;
    pub const Deallocate = *const fn (*ExecBase, *exec.MemHeader, ?*anyopaque, usize) callconv(.c) void;
    pub const AllocMem = *const fn (*ExecBase, usize, u32) callconv(.c) ?*anyopaque;
    pub const FreeMem = *const fn (*ExecBase, ?*anyopaque, usize) callconv(.c) void;
    pub const AvailMem = *const fn (*ExecBase, u32) callconv(.c) usize;
    pub const AddMemHandler = *const fn (*ExecBase, *exec.Interrupt) callconv(.c) void;
    pub const RemMemHandler = *const fn (*ExecBase, *exec.Interrupt) callconv(.c) void;
    pub const SetIntVector = *const fn (*ExecBase, u32, ?*exec.Interrupt) callconv(.c) ?*exec.Interrupt;
    pub const AddIntServer = *const fn (*ExecBase, u32, *exec.Interrupt) callconv(.c) void;
    pub const RemIntServer = *const fn (*ExecBase, u32, *exec.Interrupt) callconv(.c) void;
    pub const Disable = *const fn (*ExecBase) callconv(.c) void;
    pub const Enable = *const fn (*ExecBase) callconv(.c) void;
    pub const Cause = *const fn (*ExecBase, *exec.Interrupt) callconv(.c) void;
    pub const Alert = *const fn (*ExecBase, u32) callconv(.c) void;
    pub const SetTrapCode = *const fn (*ExecBase, ?exec.TrapFn, ?*anyopaque) callconv(.c) ?exec.TrapFn;
    pub const AddTask = *const fn (*ExecBase, *exec.Task, exec.TaskFn, ?exec.TaskFn) callconv(.c) *exec.Task;
    pub const RemTask = *const fn (*ExecBase, ?*exec.Task) callconv(.c) void;
    pub const FindTask = *const fn (*ExecBase, ?[*:0]const u8) callconv(.c) ?*exec.Task;
    pub const SetTaskPri = *const fn (*ExecBase, *exec.Task, i8) callconv(.c) i8;
    pub const Signal = *const fn (*ExecBase, *exec.Task, u32) callconv(.c) void;
    pub const Wait = *const fn (*ExecBase, u32) callconv(.c) u32;
    pub const SetSignal = *const fn (*ExecBase, u32, u32) callconv(.c) u32;
    pub const AllocSignal = *const fn (*ExecBase, i8) callconv(.c) i8;
    pub const FreeSignal = *const fn (*ExecBase, i8) callconv(.c) void;
    pub const CreateTask = *const fn (*ExecBase, [*:0]const u8, i8, exec.TaskFn, usize) callconv(.c) ?*exec.Task;
    pub const SetExcept = *const fn (*ExecBase, u32, u32) callconv(.c) u32;
    pub const PutMsg = *const fn (*ExecBase, *exec.MsgPort, *exec.Message) callconv(.c) void;
    pub const GetMsg = *const fn (*ExecBase, *exec.MsgPort) callconv(.c) ?*exec.Message;
    pub const ReplyMsg = *const fn (*ExecBase, *exec.Message) callconv(.c) void;
    pub const WaitPort = *const fn (*ExecBase, *exec.MsgPort) callconv(.c) *exec.Message;
    pub const AddPort = *const fn (*ExecBase, *exec.MsgPort) callconv(.c) void;
    pub const RemPort = *const fn (*ExecBase, *exec.MsgPort) callconv(.c) void;
    pub const FindPort = *const fn (*ExecBase, [*:0]const u8) callconv(.c) ?*exec.MsgPort;
    pub const CreateMsgPort = *const fn (*ExecBase) callconv(.c) ?*exec.MsgPort;
    pub const DeleteMsgPort = *const fn (*ExecBase, ?*exec.MsgPort) callconv(.c) void;
    pub const InitSemaphore = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) void;
    pub const ObtainSemaphore = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) void;
    pub const ReleaseSemaphore = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) void;
    pub const AttemptSemaphore = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) bool;
    pub const ObtainSemaphoreList = *const fn (*ExecBase, *exec.List) callconv(.c) void;
    pub const ReleaseSemaphoreList = *const fn (*ExecBase, *exec.List) callconv(.c) void;
    pub const FindSemaphore = *const fn (*ExecBase, [*:0]const u8) callconv(.c) ?*exec.SignalSemaphore;
    pub const AddSemaphore = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) void;
    pub const RemSemaphore = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) void;
    pub const ObtainSemaphoreShared = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) void;
    pub const AttemptSemaphoreShared = *const fn (*ExecBase, *exec.SignalSemaphore) callconv(.c) bool;
    pub const Procure = *const fn (*ExecBase, *exec.SignalSemaphore, *exec.SemaphoreMessage) callconv(.c) void;
    pub const Vacate = *const fn (*ExecBase, *exec.SignalSemaphore, *exec.SemaphoreMessage) callconv(.c) void;
    pub const AllocVec = *const fn (*ExecBase, usize, u32) callconv(.c) ?*anyopaque;
    pub const FreeVec = *const fn (*ExecBase, ?*anyopaque) callconv(.c) void;
    pub const CopyMem = *const fn (*ExecBase, *const anyopaque, *anyopaque, usize) callconv(.c) void;
    pub const CopyMemQuick = *const fn (*ExecBase, *const anyopaque, *anyopaque, usize) callconv(.c) void;
    pub const SetMem = *const fn (*ExecBase, *anyopaque, u8, usize) callconv(.c) void;
    pub const AddDevice = *const fn (*ExecBase, *exec.Device) callconv(.c) void;
    pub const RemDevice = *const fn (*ExecBase, *exec.Device) callconv(.c) ?*anyopaque;
    pub const OpenDevice = *const fn (*ExecBase, [*:0]const u8, u32, *exec.IORequest, u32) callconv(.c) i32;
    pub const CloseDevice = *const fn (*ExecBase, *exec.IORequest) callconv(.c) void;
    pub const DoIO = *const fn (*ExecBase, *exec.IORequest) callconv(.c) i32;
    pub const SendIO = *const fn (*ExecBase, *exec.IORequest) callconv(.c) void;
    pub const WaitIO = *const fn (*ExecBase, *exec.IORequest) callconv(.c) i32;
    pub const ReplyIO = *const fn (*ExecBase, *exec.IORequest) callconv(.c) void;
    pub const CheckIO = *const fn (*ExecBase, *exec.IORequest) callconv(.c) ?*exec.IORequest;
    pub const AbortIO = *const fn (*ExecBase, *exec.IORequest) callconv(.c) i32;
    pub const FindResident = *const fn (*ExecBase, [*:0]const u8) callconv(.c) ?*const exec.Resident;
    pub const InitCode = *const fn (*ExecBase, u32, u32) callconv(.c) ?*anyopaque;
    pub const InitResident = *const fn (*ExecBase, *const exec.Resident, ?*anyopaque) callconv(.c) ?*anyopaque;
    pub const CreateIORequest = *const fn (*ExecBase, ?*exec.MsgPort, u32) callconv(.c) ?*exec.IORequest;
    pub const DeleteIORequest = *const fn (*ExecBase, ?*exec.IORequest) callconv(.c) void;
    pub const RawDoFmt = *const fn (*ExecBase, [*:0]const u8, ?*const anyopaque, ?exec.PutChProc, ?*anyopaque) callconv(.c) ?*const anyopaque;
    pub const RawPutChar = *const fn (*ExecBase, u8) callconv(.c) void;
    pub const RawMayGetChar = *const fn (*ExecBase) callconv(.c) i32;
    pub const RawIOInit = *const fn (*ExecBase) callconv(.c) void;
    pub const AddResource = *const fn (*ExecBase, *anyopaque) callconv(.c) void;
    pub const RemResource = *const fn (*ExecBase, *anyopaque) callconv(.c) void;
    pub const OpenResource = *const fn (*ExecBase, [*:0]const u8) callconv(.c) ?*anyopaque;
    pub const ColdReboot = *const fn (*ExecBase) callconv(.c) noreturn;
    pub const CacheClearU = *const fn (*ExecBase) callconv(.c) void;
    pub const CacheClearE = *const fn (*ExecBase, *anyopaque, u32, u32) callconv(.c) void;
    pub const CachePreDMA = *const fn (*ExecBase, *anyopaque, *u32, u32) callconv(.c) *anyopaque;
    pub const CachePostDMA = *const fn (*ExecBase, *anyopaque, *u32, u32) callconv(.c) void;
    pub const NewStackRun = *const fn (*ExecBase, exec.StackFn, ?*anyopaque, u32) callconv(.c) i32;
    pub const CodeAddress = *const fn (*ExecBase, *anyopaque, u32) callconv(.c) ?*anyopaque;
    pub const ExecList = *const fn (*ExecBase, u32) callconv(.c) ?*exec.List;
    pub const IntVector = *const fn (*ExecBase, u32) callconv(.c) ?*exec.IntVector;
    pub const ResModules = *const fn (*ExecBase) callconv(.c) ?[*]const ?*const exec.Resident;
    pub const SetRamLib = *const fn (*ExecBase, ?*anyopaque) callconv(.c) void;
    pub const RamLib = *const fn (*ExecBase) callconv(.c) ?*anyopaque;
    pub const CreatePool = *const fn (*ExecBase, u32, usize, usize) callconv(.c) ?*anyopaque;
    pub const DeletePool = *const fn (*ExecBase, ?*anyopaque) callconv(.c) void;
    pub const AllocPooled = *const fn (*ExecBase, ?*anyopaque, usize) callconv(.c) ?*anyopaque;
    pub const FreePooled = *const fn (*ExecBase, ?*anyopaque, ?*anyopaque, usize) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ExecBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ExecBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    pub fn MakeLibrary(self: *ExecBase, vectors: [*]const *const anyopaque, count: usize, data_size: usize, init: ?exec.InitFn, seg_list: ?*anyopaque) ?*exec.Library {
        return libraries.call(self, LVO.MakeLibrary, Fn.MakeLibrary, .{ vectors, count, data_size, init, seg_list });
    }

    pub fn AddLibrary(self: *ExecBase, library: *exec.Library) void {
        return libraries.call(self, LVO.AddLibrary, Fn.AddLibrary, .{library});
    }

    pub fn RemLibrary(self: *ExecBase, library: *exec.Library) ?*anyopaque {
        return libraries.call(self, LVO.RemLibrary, Fn.RemLibrary, .{library});
    }

    pub fn OpenLibrary(self: *ExecBase, name: [*:0]const u8, version: u32) ?*exec.Library {
        return libraries.call(self, LVO.OpenLibrary, Fn.OpenLibrary, .{ name, version });
    }

    pub fn CloseLibrary(self: *ExecBase, library: ?*exec.Library) void {
        return libraries.call(self, LVO.CloseLibrary, Fn.CloseLibrary, .{library});
    }

    pub fn SetFunction(self: *ExecBase, library: *exec.Library, offset: isize, new: *const anyopaque) *const anyopaque {
        return libraries.call(self, LVO.SetFunction, Fn.SetFunction, .{ library, offset, new });
    }

    pub fn CreateLibrary(self: *ExecBase, desc: *const exec.LibraryInit) ?*exec.Library {
        return libraries.call(self, LVO.CreateLibrary, Fn.CreateLibrary, .{desc});
    }

    pub fn FindName(self: *ExecBase, list: *exec.List, name: [*:0]const u8) ?*exec.Node {
        return libraries.call(self, LVO.FindName, Fn.FindName, .{ list, name });
    }

    pub fn Forbid(self: *ExecBase) void {
        return libraries.call(self, LVO.Forbid, Fn.Forbid, .{});
    }

    pub fn Permit(self: *ExecBase) void {
        return libraries.call(self, LVO.Permit, Fn.Permit, .{});
    }

    pub fn Insert(self: *ExecBase, list: *exec.List, node: *exec.Node, pred: ?*exec.Node) void {
        return libraries.call(self, LVO.Insert, Fn.Insert, .{ list, node, pred });
    }

    pub fn AddHead(self: *ExecBase, list: *exec.List, node: *exec.Node) void {
        return libraries.call(self, LVO.AddHead, Fn.AddHead, .{ list, node });
    }

    pub fn AddTail(self: *ExecBase, list: *exec.List, node: *exec.Node) void {
        return libraries.call(self, LVO.AddTail, Fn.AddTail, .{ list, node });
    }

    pub fn Remove(self: *ExecBase, node: *exec.Node) void {
        return libraries.call(self, LVO.Remove, Fn.Remove, .{node});
    }

    pub fn RemHead(self: *ExecBase, list: *exec.List) ?*exec.Node {
        return libraries.call(self, LVO.RemHead, Fn.RemHead, .{list});
    }

    pub fn RemTail(self: *ExecBase, list: *exec.List) ?*exec.Node {
        return libraries.call(self, LVO.RemTail, Fn.RemTail, .{list});
    }

    pub fn Enqueue(self: *ExecBase, list: *exec.List, node: *exec.Node) void {
        return libraries.call(self, LVO.Enqueue, Fn.Enqueue, .{ list, node });
    }

    pub fn NewList(self: *ExecBase, list: *exec.List) void {
        return libraries.call(self, LVO.NewList, Fn.NewList, .{list});
    }

    pub fn CreateMemHeader(self: *ExecBase, size: usize, attributes: u32, pri: i8, base: *anyopaque, name: ?[*:0]const u8) ?*exec.MemHeader {
        return libraries.call(self, LVO.CreateMemHeader, Fn.CreateMemHeader, .{ size, attributes, pri, base, name });
    }

    pub fn AddMemList(self: *ExecBase, size: usize, attributes: u32, pri: i8, base: *anyopaque, name: ?[*:0]const u8) ?*exec.MemHeader {
        return libraries.call(self, LVO.AddMemList, Fn.AddMemList, .{ size, attributes, pri, base, name });
    }

    pub fn Allocate(self: *ExecBase, mh: *exec.MemHeader, byte_size: usize) ?*anyopaque {
        return libraries.call(self, LVO.Allocate, Fn.Allocate, .{ mh, byte_size });
    }

    pub fn Deallocate(self: *ExecBase, mh: *exec.MemHeader, memory_block: ?*anyopaque, byte_size: usize) void {
        return libraries.call(self, LVO.Deallocate, Fn.Deallocate, .{ mh, memory_block, byte_size });
    }

    pub fn AllocMem(self: *ExecBase, byte_size: usize, requirements: u32) ?*anyopaque {
        return libraries.call(self, LVO.AllocMem, Fn.AllocMem, .{ byte_size, requirements });
    }

    pub fn FreeMem(self: *ExecBase, memory_block: ?*anyopaque, byte_size: usize) void {
        return libraries.call(self, LVO.FreeMem, Fn.FreeMem, .{ memory_block, byte_size });
    }

    pub fn AvailMem(self: *ExecBase, requirements: u32) usize {
        return libraries.call(self, LVO.AvailMem, Fn.AvailMem, .{requirements});
    }

    pub fn AddMemHandler(self: *ExecBase, handler: *exec.Interrupt) void {
        return libraries.call(self, LVO.AddMemHandler, Fn.AddMemHandler, .{handler});
    }

    pub fn RemMemHandler(self: *ExecBase, handler: *exec.Interrupt) void {
        return libraries.call(self, LVO.RemMemHandler, Fn.RemMemHandler, .{handler});
    }

    pub fn SetIntVector(self: *ExecBase, int_number: u32, interrupt: ?*exec.Interrupt) ?*exec.Interrupt {
        return libraries.call(self, LVO.SetIntVector, Fn.SetIntVector, .{ int_number, interrupt });
    }

    pub fn AddIntServer(self: *ExecBase, int_number: u32, interrupt: *exec.Interrupt) void {
        return libraries.call(self, LVO.AddIntServer, Fn.AddIntServer, .{ int_number, interrupt });
    }

    pub fn RemIntServer(self: *ExecBase, int_number: u32, interrupt: *exec.Interrupt) void {
        return libraries.call(self, LVO.RemIntServer, Fn.RemIntServer, .{ int_number, interrupt });
    }

    pub fn Disable(self: *ExecBase) void {
        return libraries.call(self, LVO.Disable, Fn.Disable, .{});
    }

    pub fn Enable(self: *ExecBase) void {
        return libraries.call(self, LVO.Enable, Fn.Enable, .{});
    }

    pub fn Cause(self: *ExecBase, interrupt: *exec.Interrupt) void {
        return libraries.call(self, LVO.Cause, Fn.Cause, .{interrupt});
    }

    pub fn Alert(self: *ExecBase, alert_num: u32) void {
        return libraries.call(self, LVO.Alert, Fn.Alert, .{alert_num});
    }

    pub fn SetTrapCode(self: *ExecBase, code: ?exec.TrapFn, data: ?*anyopaque) ?exec.TrapFn {
        return libraries.call(self, LVO.SetTrapCode, Fn.SetTrapCode, .{ code, data });
    }

    pub fn AddTask(self: *ExecBase, task: *exec.Task, init_pc: exec.TaskFn, final_pc: ?exec.TaskFn) *exec.Task {
        return libraries.call(self, LVO.AddTask, Fn.AddTask, .{ task, init_pc, final_pc });
    }

    pub fn RemTask(self: *ExecBase, task: ?*exec.Task) void {
        return libraries.call(self, LVO.RemTask, Fn.RemTask, .{task});
    }

    pub fn FindTask(self: *ExecBase, name: ?[*:0]const u8) ?*exec.Task {
        return libraries.call(self, LVO.FindTask, Fn.FindTask, .{name});
    }

    pub fn SetTaskPri(self: *ExecBase, task: *exec.Task, pri: i8) i8 {
        return libraries.call(self, LVO.SetTaskPri, Fn.SetTaskPri, .{ task, pri });
    }

    pub fn Signal(self: *ExecBase, task: *exec.Task, signals: u32) void {
        return libraries.call(self, LVO.Signal, Fn.Signal, .{ task, signals });
    }

    pub fn Wait(self: *ExecBase, signal_set: u32) u32 {
        return libraries.call(self, LVO.Wait, Fn.Wait, .{signal_set});
    }

    pub fn SetSignal(self: *ExecBase, new_signals: u32, signal_mask: u32) u32 {
        return libraries.call(self, LVO.SetSignal, Fn.SetSignal, .{ new_signals, signal_mask });
    }

    pub fn AllocSignal(self: *ExecBase, signal_num: i8) i8 {
        return libraries.call(self, LVO.AllocSignal, Fn.AllocSignal, .{signal_num});
    }

    pub fn FreeSignal(self: *ExecBase, signal_num: i8) void {
        return libraries.call(self, LVO.FreeSignal, Fn.FreeSignal, .{signal_num});
    }

    pub fn CreateTask(self: *ExecBase, name: [*:0]const u8, pri: i8, init_pc: exec.TaskFn, stack_size: usize) ?*exec.Task {
        return libraries.call(self, LVO.CreateTask, Fn.CreateTask, .{ name, pri, init_pc, stack_size });
    }

    pub fn SetExcept(self: *ExecBase, new_signals: u32, signal_set: u32) u32 {
        return libraries.call(self, LVO.SetExcept, Fn.SetExcept, .{ new_signals, signal_set });
    }

    pub fn PutMsg(self: *ExecBase, port: *exec.MsgPort, msg: *exec.Message) void {
        return libraries.call(self, LVO.PutMsg, Fn.PutMsg, .{ port, msg });
    }

    pub fn GetMsg(self: *ExecBase, port: *exec.MsgPort) ?*exec.Message {
        return libraries.call(self, LVO.GetMsg, Fn.GetMsg, .{port});
    }

    pub fn ReplyMsg(self: *ExecBase, msg: *exec.Message) void {
        return libraries.call(self, LVO.ReplyMsg, Fn.ReplyMsg, .{msg});
    }

    pub fn WaitPort(self: *ExecBase, port: *exec.MsgPort) *exec.Message {
        return libraries.call(self, LVO.WaitPort, Fn.WaitPort, .{port});
    }

    pub fn AddPort(self: *ExecBase, port: *exec.MsgPort) void {
        return libraries.call(self, LVO.AddPort, Fn.AddPort, .{port});
    }

    pub fn RemPort(self: *ExecBase, port: *exec.MsgPort) void {
        return libraries.call(self, LVO.RemPort, Fn.RemPort, .{port});
    }

    pub fn FindPort(self: *ExecBase, name: [*:0]const u8) ?*exec.MsgPort {
        return libraries.call(self, LVO.FindPort, Fn.FindPort, .{name});
    }

    pub fn CreateMsgPort(self: *ExecBase) ?*exec.MsgPort {
        return libraries.call(self, LVO.CreateMsgPort, Fn.CreateMsgPort, .{});
    }

    pub fn DeleteMsgPort(self: *ExecBase, port: ?*exec.MsgPort) void {
        return libraries.call(self, LVO.DeleteMsgPort, Fn.DeleteMsgPort, .{port});
    }

    pub fn InitSemaphore(self: *ExecBase, sem: *exec.SignalSemaphore) void {
        return libraries.call(self, LVO.InitSemaphore, Fn.InitSemaphore, .{sem});
    }

    pub fn ObtainSemaphore(self: *ExecBase, sem: *exec.SignalSemaphore) void {
        return libraries.call(self, LVO.ObtainSemaphore, Fn.ObtainSemaphore, .{sem});
    }

    pub fn ReleaseSemaphore(self: *ExecBase, sem: *exec.SignalSemaphore) void {
        return libraries.call(self, LVO.ReleaseSemaphore, Fn.ReleaseSemaphore, .{sem});
    }

    pub fn AttemptSemaphore(self: *ExecBase, sem: *exec.SignalSemaphore) bool {
        return libraries.call(self, LVO.AttemptSemaphore, Fn.AttemptSemaphore, .{sem});
    }

    pub fn ObtainSemaphoreList(self: *ExecBase, list: *exec.List) void {
        return libraries.call(self, LVO.ObtainSemaphoreList, Fn.ObtainSemaphoreList, .{list});
    }

    pub fn ReleaseSemaphoreList(self: *ExecBase, list: *exec.List) void {
        return libraries.call(self, LVO.ReleaseSemaphoreList, Fn.ReleaseSemaphoreList, .{list});
    }

    pub fn FindSemaphore(self: *ExecBase, name: [*:0]const u8) ?*exec.SignalSemaphore {
        return libraries.call(self, LVO.FindSemaphore, Fn.FindSemaphore, .{name});
    }

    pub fn AddSemaphore(self: *ExecBase, sem: *exec.SignalSemaphore) void {
        return libraries.call(self, LVO.AddSemaphore, Fn.AddSemaphore, .{sem});
    }

    pub fn RemSemaphore(self: *ExecBase, sem: *exec.SignalSemaphore) void {
        return libraries.call(self, LVO.RemSemaphore, Fn.RemSemaphore, .{sem});
    }

    pub fn ObtainSemaphoreShared(self: *ExecBase, sem: *exec.SignalSemaphore) void {
        return libraries.call(self, LVO.ObtainSemaphoreShared, Fn.ObtainSemaphoreShared, .{sem});
    }

    pub fn AttemptSemaphoreShared(self: *ExecBase, sem: *exec.SignalSemaphore) bool {
        return libraries.call(self, LVO.AttemptSemaphoreShared, Fn.AttemptSemaphoreShared, .{sem});
    }

    pub fn Procure(self: *ExecBase, sem: *exec.SignalSemaphore, bid: *exec.SemaphoreMessage) void {
        return libraries.call(self, LVO.Procure, Fn.Procure, .{ sem, bid });
    }

    pub fn Vacate(self: *ExecBase, sem: *exec.SignalSemaphore, bid: *exec.SemaphoreMessage) void {
        return libraries.call(self, LVO.Vacate, Fn.Vacate, .{ sem, bid });
    }

    pub fn AllocVec(self: *ExecBase, byte_size: usize, requirements: u32) ?*anyopaque {
        return libraries.call(self, LVO.AllocVec, Fn.AllocVec, .{ byte_size, requirements });
    }

    pub fn FreeVec(self: *ExecBase, memory_block: ?*anyopaque) void {
        return libraries.call(self, LVO.FreeVec, Fn.FreeVec, .{memory_block});
    }

    pub fn CopyMem(self: *ExecBase, source: *const anyopaque, dest: *anyopaque, size: usize) void {
        return libraries.call(self, LVO.CopyMem, Fn.CopyMem, .{ source, dest, size });
    }

    pub fn CopyMemQuick(self: *ExecBase, source: *const anyopaque, dest: *anyopaque, size: usize) void {
        return libraries.call(self, LVO.CopyMemQuick, Fn.CopyMemQuick, .{ source, dest, size });
    }

    pub fn SetMem(self: *ExecBase, dest: *anyopaque, value: u8, size: usize) void {
        return libraries.call(self, LVO.SetMem, Fn.SetMem, .{ dest, value, size });
    }

    pub fn AddDevice(self: *ExecBase, dev: *exec.Device) void {
        return libraries.call(self, LVO.AddDevice, Fn.AddDevice, .{dev});
    }

    pub fn RemDevice(self: *ExecBase, dev: *exec.Device) ?*anyopaque {
        return libraries.call(self, LVO.RemDevice, Fn.RemDevice, .{dev});
    }

    pub fn OpenDevice(self: *ExecBase, name: [*:0]const u8, unit: u32, io: *exec.IORequest, flags: u32) i32 {
        return libraries.call(self, LVO.OpenDevice, Fn.OpenDevice, .{ name, unit, io, flags });
    }

    pub fn CloseDevice(self: *ExecBase, io: *exec.IORequest) void {
        return libraries.call(self, LVO.CloseDevice, Fn.CloseDevice, .{io});
    }

    pub fn DoIO(self: *ExecBase, io: *exec.IORequest) i32 {
        return libraries.call(self, LVO.DoIO, Fn.DoIO, .{io});
    }

    pub fn SendIO(self: *ExecBase, io: *exec.IORequest) void {
        return libraries.call(self, LVO.SendIO, Fn.SendIO, .{io});
    }

    pub fn WaitIO(self: *ExecBase, io: *exec.IORequest) i32 {
        return libraries.call(self, LVO.WaitIO, Fn.WaitIO, .{io});
    }

    pub fn ReplyIO(self: *ExecBase, io: *exec.IORequest) void {
        return libraries.call(self, LVO.ReplyIO, Fn.ReplyIO, .{io});
    }

    pub fn CheckIO(self: *ExecBase, io: *exec.IORequest) ?*exec.IORequest {
        return libraries.call(self, LVO.CheckIO, Fn.CheckIO, .{io});
    }

    pub fn AbortIO(self: *ExecBase, io: *exec.IORequest) i32 {
        return libraries.call(self, LVO.AbortIO, Fn.AbortIO, .{io});
    }

    pub fn FindResident(self: *ExecBase, name: [*:0]const u8) ?*const exec.Resident {
        return libraries.call(self, LVO.FindResident, Fn.FindResident, .{name});
    }

    pub fn InitCode(self: *ExecBase, start_class: u32, version: u32) ?*anyopaque {
        return libraries.call(self, LVO.InitCode, Fn.InitCode, .{ start_class, version });
    }

    pub fn InitResident(self: *ExecBase, tag: *const exec.Resident, seg_list: ?*anyopaque) ?*anyopaque {
        return libraries.call(self, LVO.InitResident, Fn.InitResident, .{ tag, seg_list });
    }

    pub fn CreateIORequest(self: *ExecBase, reply_port: ?*exec.MsgPort, size: u32) ?*exec.IORequest {
        return libraries.call(self, LVO.CreateIORequest, Fn.CreateIORequest, .{ reply_port, size });
    }

    pub fn DeleteIORequest(self: *ExecBase, io: ?*exec.IORequest) void {
        return libraries.call(self, LVO.DeleteIORequest, Fn.DeleteIORequest, .{io});
    }

    pub fn RawDoFmt(self: *ExecBase, format_string: [*:0]const u8, data_stream: ?*const anyopaque, put_ch_proc: ?exec.PutChProc, put_ch_data: ?*anyopaque) ?*const anyopaque {
        return libraries.call(self, LVO.RawDoFmt, Fn.RawDoFmt, .{ format_string, data_stream, put_ch_proc, put_ch_data });
    }

    pub fn RawPutChar(self: *ExecBase, ch: u8) void {
        return libraries.call(self, LVO.RawPutChar, Fn.RawPutChar, .{ch});
    }

    pub fn RawMayGetChar(self: *ExecBase) i32 {
        return libraries.call(self, LVO.RawMayGetChar, Fn.RawMayGetChar, .{});
    }

    pub fn RawIOInit(self: *ExecBase) void {
        return libraries.call(self, LVO.RawIOInit, Fn.RawIOInit, .{});
    }

    pub fn AddResource(self: *ExecBase, resource: *anyopaque) void {
        return libraries.call(self, LVO.AddResource, Fn.AddResource, .{resource});
    }

    pub fn RemResource(self: *ExecBase, resource: *anyopaque) void {
        return libraries.call(self, LVO.RemResource, Fn.RemResource, .{resource});
    }

    pub fn OpenResource(self: *ExecBase, res_name: [*:0]const u8) ?*anyopaque {
        return libraries.call(self, LVO.OpenResource, Fn.OpenResource, .{res_name});
    }

    pub fn ColdReboot(self: *ExecBase) noreturn {
        return libraries.call(self, LVO.ColdReboot, Fn.ColdReboot, .{});
    }

    pub fn CacheClearU(self: *ExecBase) void {
        return libraries.call(self, LVO.CacheClearU, Fn.CacheClearU, .{});
    }

    pub fn CacheClearE(self: *ExecBase, address: *anyopaque, length: u32, caches: u32) void {
        return libraries.call(self, LVO.CacheClearE, Fn.CacheClearE, .{ address, length, caches });
    }

    pub fn CachePreDMA(self: *ExecBase, address: *anyopaque, length: *u32, flags: u32) *anyopaque {
        return libraries.call(self, LVO.CachePreDMA, Fn.CachePreDMA, .{ address, length, flags });
    }

    pub fn CachePostDMA(self: *ExecBase, address: *anyopaque, length: *u32, flags: u32) void {
        return libraries.call(self, LVO.CachePostDMA, Fn.CachePostDMA, .{ address, length, flags });
    }

    /// `code(arg)` on a stack of its own of
    /// `stack_size` bytes; its answer, or -1 without memory for the stack.
    pub fn NewStackRun(self: *ExecBase, code: exec.StackFn, arg: ?*anyopaque, stack_size: u32) i32 {
        return libraries.call(self, LVO.NewStackRun, Fn.NewStackRun, .{ code, arg, stack_size });
    }

    /// Where `length` bytes at `address` can be run, i.e. the same
    /// memory on the instruction bus, or null when the CPU can't reach it there
    /// (only memory behind the caches has both views). Code written through the
    /// data bus needs CacheClearU before it is run.
    pub fn CodeAddress(self: *ExecBase, address: *anyopaque, length: u32) ?*anyopaque {
        return libraries.call(self, LVO.CodeAddress, Fn.CodeAddress, .{ address, length });
    }

    /// One of exec's own lists (EXECLIST_*), or null for a number it has not
    /// got. It is exec's list, not a copy: hold Forbid while walking it - or
    /// Disable for the two task queues, which the scheduler moves from
    /// interrupts - and write nothing into it. The header itself never moves,
    /// so the answer stays good for as long as exec does.
    pub fn ExecList(self: *ExecBase, which: u32) ?*exec.List {
        return libraries.call(self, LVO.ExecList, Fn.ExecList, .{which});
    }

    /// What exec does when one interrupt number fires: the handler, the server
    /// chain and how often it has been dispatched. Null for a number this chip
    /// has not got. Read under Disable; the vector itself never moves.
    pub fn IntVector(self: *ExecBase, int_number: u32) ?*exec.IntVector {
        return libraries.call(self, LVO.IntVector, Fn.IntVector, .{int_number});
    }

    /// The ROM tags of this image, in the order they were started, ending with
    /// a null. Null before the scan at boot has run. They are in the image and
    /// never move.
    pub fn ResModules(self: *ExecBase) ?[*]const ?*const exec.Resident {
        return libraries.call(self, LVO.ResModules, Fn.ResModules, .{});
    }

    /// Keep the loader's base for it. Whatever patches OpenLibrary has one
    /// pointer its replacement needs - the vectors it replaced, and where to
    /// send the work - and nowhere of its own to put it, since a module may
    /// keep nothing in its image and this base is opaque. exec holds it and
    /// never looks at what it points to. Null until something sets it.
    pub fn SetRamLib(self: *ExecBase, base: ?*anyopaque) void {
        return libraries.call(self, LVO.SetRamLib, Fn.SetRamLib, .{base});
    }

    /// What SetRamLib was given, or null.
    pub fn RamLib(self: *ExecBase) ?*anyopaque {
        return libraries.call(self, LVO.RamLib, Fn.RamLib, .{});
    }

    /// A pool to take many small blocks from, which come back together.
    /// `puddle_size` is how much the pool takes from the system at a time and
    /// `thresh_size` the request that gets memory of its own instead, or 0 for
    /// no threshold at all. Null if there is no memory. A pool made with MEMF_CLEAR clears every block it
    /// hands out, not only the first.
    pub fn CreatePool(self: *ExecBase, requirements: u32, puddle_size: usize, thresh_size: usize) ?*anyopaque {
        return libraries.call(self, LVO.CreatePool, Fn.CreatePool, .{ requirements, puddle_size, thresh_size });
    }

    /// Free everything a pool holds, and the pool with it. Null is ignored.
    pub fn DeletePool(self: *ExecBase, pool: ?*anyopaque) void {
        return libraries.call(self, LVO.DeletePool, Fn.DeletePool, .{pool});
    }

    /// `byte_size` bytes from a pool. Null if there is no memory.
    pub fn AllocPooled(self: *ExecBase, pool: ?*anyopaque, byte_size: usize) ?*anyopaque {
        return libraries.call(self, LVO.AllocPooled, Fn.AllocPooled, .{ pool, byte_size });
    }

    /// Give a block from AllocPooled back. `byte_size` must be what was asked
    /// for: a pooled block carries no header of its own, which is the point.
    pub fn FreePooled(self: *ExecBase, pool: ?*anyopaque, memory_block: ?*anyopaque, byte_size: usize) void {
        return libraries.call(self, LVO.FreePooled, Fn.FreePooled, .{ pool, memory_block, byte_size });
    }
};
