// SPDX-License-Identifier: MIT
//! expansion.library's functions: the board this machine is, and the parts
//! soldered on it. The board's ROM carries a description of it - the system
//! tag list (sdk/libs/expansion/systemtags.zig) - and this library hands
//! each part out as a BoardPart, so a module asks for its part rather than
//! knowing any board. A disk's driver hands it the device nodes of the
//! disk's partitions, which dos.library takes in once it is up. Open it
//! with OpenLibrary("expansion.library", 1).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/expansion_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const utility = @import("../libs/utility/utility.zig");
const dos = @import("../libs/dos/dos.zig");
const expansion = @import("../libs/expansion/expansion.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "expansion.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const FindBoardPart = libraries.lvo(4);
    pub const SystemTags = libraries.lvo(5);
    pub const MakeDosNode = libraries.lvo(6);
    pub const AddBootNode = libraries.lvo(7);
    pub const EnterBootNodes = libraries.lvo(8);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const FindBoardPart = *const fn (*ExpansionBase, ?*const expansion.BoardPart, u32, u32) callconv(.c) ?*const expansion.BoardPart;
    pub const SystemTags = *const fn (*ExpansionBase) callconv(.c) [*]const utility.TagItem;
    pub const MakeDosNode = *const fn (*ExpansionBase, [*:0]const u8, [*:0]const u8, u32, u32, *const dos.DosEnvec) callconv(.c) ?*dos.DosList;
    pub const AddBootNode = *const fn (*ExpansionBase, i32, *dos.DosList) callconv(.c) bool;
    pub const EnterBootNodes = *const fn (*ExpansionBase) callconv(.c) ?*dos.DosList;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ExpansionBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ExpansionBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The next part after `old` (null: the first) whose kind is `kind` and
    /// whose chip is `chip`, in the order the board lists them. PARTKIND_ANY
    /// and CHIP_ANY match every kind and every chip. Null when there is none.
    pub fn FindBoardPart(self: *ExpansionBase, old: ?*const expansion.BoardPart, kind: u32, chip: u32) ?*const expansion.BoardPart {
        return libraries.call(self, LVO.FindBoardPart, Fn.FindBoardPart, .{ old, kind, chip });
    }

    /// The system tag list's root: the board's name, its memory and its
    /// console, and a SYSTAG_Part per part. Never null on a machine that
    /// started; the list lives as long as the machine does.
    pub fn SystemTags(self: *ExpansionBase) [*]const utility.TagItem {
        return libraries.call(self, LVO.SystemTags, Fn.SystemTags, .{});
    }

    /// A device node for a disk's partition, made before dos.library is up:
    /// the node named `dos_name`, its FileSysStartupMsg (`device_name`, `unit`,
    /// `flags`) and a copy of `environ`, in one allocation. Null when there is
    /// no memory.
    pub fn MakeDosNode(self: *ExpansionBase, dos_name: [*:0]const u8, device_name: [*:0]const u8, unit: u32, flags: u32, environ: *const dos.DosEnvec) ?*dos.DosList {
        return libraries.call(self, LVO.MakeDosNode, Fn.MakeDosNode, .{ dos_name, device_name, unit, flags, environ });
    }

    /// A node from MakeDosNode into the system: on dos's list at once if dos is
    /// up, else kept until it is. `boot_pri` -128 is never booted from. False
    /// when there is no memory or dos refused the node, which is the caller's
    /// again.
    pub fn AddBootNode(self: *ExpansionBase, boot_pri: i32, node: *dos.DosList) bool {
        return libraries.call(self, LVO.AddBootNode, Fn.AddBootNode, .{ boot_pri, node });
    }

    /// dos.library's, at its start: every node AddBootNode kept, onto dos's
    /// list in boot priority order. The one to boot from, or null.
    pub fn EnterBootNodes(self: *ExpansionBase) ?*dos.DosList {
        return libraries.call(self, LVO.EnterBootNodes, Fn.EnterBootNodes, .{});
    }
};
