// SPDX-License-Identifier: MIT
//! expander.resource's functions: the board's IO expander - the pins the
//! panel, the touch controller and the SD card are held by, the backlight
//! and an analogue input. A resource: no Open or Close, its first function
//! in the first slot. The base comes from OpenResource("expander.resource").
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/expander_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const expander = @import("../resources/expander.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "expander.resource";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const ClaimPin = libraries.lvo(0);
    pub const ReleasePin = libraries.lvo(1);
    pub const PinOwner = libraries.lvo(2);
    pub const SetPin = libraries.lvo(3);
    pub const GetPin = libraries.lvo(4);
    pub const SetBacklight = libraries.lvo(5);
    pub const Backlight = libraries.lvo(6);
    pub const ReadADC = libraries.lvo(7);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const ClaimPin = *const fn (*ExpanderBase, u32, [*:0]const u8) callconv(.c) bool;
    pub const ReleasePin = *const fn (*ExpanderBase, u32) callconv(.c) void;
    pub const PinOwner = *const fn (*ExpanderBase, u32) callconv(.c) ?[*:0]const u8;
    pub const SetPin = *const fn (*ExpanderBase, u32, bool) callconv(.c) bool;
    pub const GetPin = *const fn (*ExpanderBase, u32) callconv(.c) i32;
    pub const SetBacklight = *const fn (*ExpanderBase, u32) callconv(.c) bool;
    pub const Backlight = *const fn (*ExpanderBase) callconv(.c) u32;
    pub const ReadADC = *const fn (*ExpanderBase) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ExpanderBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ExpanderBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Take `pin` (0 to PIN_COUNT-1) for `name`, which is kept for the listing
    /// and must outlive the claim. False if the pin is out of range or someone
    /// else already holds it. A driver claims the pins it is going to drive so
    /// that two of them fighting over one is an error at claim time rather than
    /// a light that goes out when an unrelated card is initialised.
    pub fn ClaimPin(self: *ExpanderBase, pin: u32, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.ClaimPin, Fn.ClaimPin, .{ pin, name });
    }

    /// Give `pin` back. Its level is left as it is.
    pub fn ReleasePin(self: *ExpanderBase, pin: u32) void {
        return libraries.call(self, LVO.ReleasePin, Fn.ReleasePin, .{pin});
    }

    /// Who holds `pin`, or null if nobody does.
    pub fn PinOwner(self: *ExpanderBase, pin: u32) ?[*:0]const u8 {
        return libraries.call(self, LVO.PinOwner, Fn.PinOwner, .{pin});
    }

    /// Drive `pin` high or low. The pin becomes an output if it was not one,
    /// its value being written before the direction changes so that it never
    /// drives the wrong level first. False if the pin is out of range or the
    /// part does not answer.
    pub fn SetPin(self: *ExpanderBase, pin: u32, high: bool) bool {
        return libraries.call(self, LVO.SetPin, Fn.SetPin, .{ pin, high });
    }

    /// What `pin` reads: 0 or 1, or -1 if the pin is out of range or the part
    /// does not answer.
    pub fn GetPin(self: *ExpanderBase, pin: u32) i32 {
        return libraries.call(self, LVO.GetPin, Fn.GetPin, .{pin});
    }

    /// The backlight, BACKLIGHT_OFF (0) to BACKLIGHT_FULL (100). The register
    /// behind it counts the other way, which this hides. False if the part does
    /// not answer.
    pub fn SetBacklight(self: *ExpanderBase, percent: u32) bool {
        return libraries.call(self, LVO.SetBacklight, Fn.SetBacklight, .{percent});
    }

    /// What SetBacklight was last given.
    pub fn Backlight(self: *ExpanderBase) u32 {
        return libraries.call(self, LVO.Backlight, Fn.Backlight, .{});
    }

    /// The analogue input, 0 to 65535, or -1 if the part does not answer.
    pub fn ReadADC(self: *ExpanderBase) i32 {
        return libraries.call(self, LVO.ReadADC, Fn.ReadADC, .{});
    }
};
