// SPDX-License-Identifier: MIT
//! expansion.library's functions: the board this machine is, and the parts
//! soldered on it. The board's ROM carries a description of it - the system
//! tag list (sdk/libs/expansion/systemtags.zig) - and this library hands
//! each part out as a BoardPart, so a module asks for its part rather than
//! knowing any board. Open it with OpenLibrary("expansion.library", 1).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/expansion_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const utility = @import("../libs/utility/utility.zig");
const expansion = @import("../libs/expansion/expansion.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "expansion.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const FindBoardPart = libraries.lvo(4);
    pub const SystemTags = libraries.lvo(5);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const FindBoardPart = *const fn (*ExpansionBase, ?*const expansion.BoardPart, u32, u32) callconv(.c) ?*const expansion.BoardPart;
    pub const SystemTags = *const fn (*ExpansionBase) callconv(.c) [*]const utility.TagItem;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ExpansionBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ExpansionBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The next part after `old` (null: the first) whose kind is `kind` and
    /// whose chip is `chip`, in the order the board lists them. PARTKIND_ANY
    /// and CHIP_ANY match every kind and every chip. Null when there is none.
    pub fn FindBoardPart(self: *ExpansionBase, old: ?*const expansion.BoardPart, kind: u32, chip: u32) ?*const expansion.BoardPart {
        return libraries.call(self, LVO.FindBoardPart, Fn.FindBoardPart, .{ old, kind, chip });
    }

    /// The system tag list's root: the board's name, its memory and its
    /// console, and a SYSTAG_Part per part. Never null on a machine that
    /// started; the list lives as long as the machine does.
    pub fn SystemTags(self: *ExpansionBase) [*]const utility.TagItem {
        return libraries.call(self, LVO.SystemTags, Fn.SystemTags, .{});
    }
};
