// SPDX-License-Identifier: MIT
//! gpio.resource's functions: who holds which of the chip's pads. A driver
//! takes each pad it routes and gives it back when it is done, so two of
//! them wanting one pad is a refusal at the take rather than a line two
//! drivers fight over. A resource: no Open or Close, its first function in
//! the first slot. The base comes from OpenResource("gpio.resource").
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/gpio_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const gpio = @import("../resources/gpio.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "gpio.resource";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const AllocGPIO = libraries.lvo(0);
    pub const FreeGPIO = libraries.lvo(1);
    pub const GPIOOwner = libraries.lvo(2);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const AllocGPIO = *const fn (*GpioBase, u32, [*:0]const u8) callconv(.c) ?[*:0]const u8;
    pub const FreeGPIO = *const fn (*GpioBase, u32) callconv(.c) void;
    pub const GPIOOwner = *const fn (*GpioBase, u32) callconv(.c) ?[*:0]const u8;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const GpioBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *GpioBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Take `pad` for `name`, which must outlive the claim: null if it is now
    /// yours, else who has it. Not from interrupts.
    pub fn AllocGPIO(self: *GpioBase, pad: u32, name: [*:0]const u8) ?[*:0]const u8 {
        return libraries.call(self, LVO.AllocGPIO, Fn.AllocGPIO, .{ pad, name });
    }

    /// Give `pad` back. Its setting is left as it is. Not from interrupts.
    pub fn FreeGPIO(self: *GpioBase, pad: u32) void {
        return libraries.call(self, LVO.FreeGPIO, Fn.FreeGPIO, .{pad});
    }

    /// Who holds `pad`, or null if nobody does.
    pub fn GPIOOwner(self: *GpioBase, pad: u32) ?[*:0]const u8 {
        return libraries.call(self, LVO.GPIOOwner, Fn.GPIOOwner, .{pad});
    }
};
