// SPDX-License-Identifier: MIT
//! graphics.library's functions: the layer that draws. What it draws into
//! is rtg.library's - a board's display memory, handed out as RtgBitMaps -
//! and it opens rtg itself, so a caller that only wants to draw on the
//! display never touches it. Ask for a RastPort with no tags and one comes
//! back on the display; ask with RPTAG_BitMap or RPTAG_Surface and it is
//! on that buffer instead. Open it with OpenLibrary("graphics.library", 0).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/graphics_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const utility = @import("../libs/utility/utility.zig");
const graphics = @import("../libs/graphics/graphics.zig");
const rtg = @import("../libs/rtg/rtg.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "graphics.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const CreateRastPortTagList = libraries.lvo(4);
    pub const FreeRastPort = libraries.lvo(5);
    pub const RectFill = libraries.lvo(6);
    pub const SetRPAttrs = libraries.lvo(7);
    pub const GetRPAttrs = libraries.lvo(8);
    pub const AllocBitMapTagList = libraries.lvo(9);
    pub const FreeBitMap = libraries.lvo(10);
    pub const BltRastPort = libraries.lvo(11);
    pub const Move = libraries.lvo(12);
    pub const Draw = libraries.lvo(13);
    pub const WritePixel = libraries.lvo(14);
    pub const ReadPixel = libraries.lvo(15);
    pub const DrawHLine = libraries.lvo(16);
    pub const DrawVLine = libraries.lvo(17);
    pub const DrawRect = libraries.lvo(18);
    pub const DrawCircle = libraries.lvo(19);
    pub const DrawEllipse = libraries.lvo(20);
    pub const DrawArc = libraries.lvo(21);
    pub const DrawPoly = libraries.lvo(22);
    pub const InitArea = libraries.lvo(23);
    pub const AreaMove = libraries.lvo(24);
    pub const AreaDraw = libraries.lvo(25);
    pub const AreaEllipse = libraries.lvo(26);
    pub const AreaCircle = libraries.lvo(27);
    pub const AreaArc = libraries.lvo(28);
    pub const AreaEnd = libraries.lvo(29);
    pub const OpenFont = libraries.lvo(30);
    pub const CloseFont = libraries.lvo(31);
    pub const Text = libraries.lvo(32);
    pub const TextLength = libraries.lvo(33);
    pub const BltTemplate = libraries.lvo(34);
    pub const BltPattern = libraries.lvo(35);
    pub const BltMaskRastPort = libraries.lvo(36);
    pub const BltBitMap = libraries.lvo(37);
    pub const BltBitMapRastPort = libraries.lvo(38);
    pub const BltMaskBitMapRastPort = libraries.lvo(39);
    pub const BitMapScale = libraries.lvo(40);
    pub const TextExtent = libraries.lvo(41);
    pub const TextFit = libraries.lvo(42);
    pub const AddFont = libraries.lvo(43);
    pub const RemFont = libraries.lvo(44);
    pub const FontExtent = libraries.lvo(45);
    pub const AskSoftStyle = libraries.lvo(46);
    pub const SetSoftStyle = libraries.lvo(47);
    pub const GraphicsErrorText = libraries.lvo(48);
    pub const NewRegion = libraries.lvo(49);
    pub const DisposeRegion = libraries.lvo(50);
    pub const ClearRegion = libraries.lvo(51);
    pub const PointInRegion = libraries.lvo(52);
    pub const OffsetRegion = libraries.lvo(53);
    pub const OrRectRegion = libraries.lvo(54);
    pub const AndRectRegion = libraries.lvo(55);
    pub const ClearRectRegion = libraries.lvo(56);
    pub const XorRectRegion = libraries.lvo(57);
    pub const OrRegionRegion = libraries.lvo(58);
    pub const AndRegionRegion = libraries.lvo(59);
    pub const SubRegionRegion = libraries.lvo(60);
    pub const XorRegionRegion = libraries.lvo(61);
    pub const RegionRectangles = libraries.lvo(62);
    pub const ScrollRaster = libraries.lvo(63);
    pub const EraseRect = libraries.lvo(64);
    pub const WritePixelArray = libraries.lvo(65);
    pub const WriteLUTPixelArray = libraries.lvo(66);
    pub const BeginDraw = libraries.lvo(67);
    pub const EndDraw = libraries.lvo(68);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const CreateRastPortTagList = *const fn (*GraphicsBase, ?[*]const utility.TagItem) callconv(.c) ?*graphics.RastPort;
    pub const FreeRastPort = *const fn (*GraphicsBase, ?*graphics.RastPort) callconv(.c) void;
    pub const RectFill = *const fn (*GraphicsBase, *graphics.RastPort, *const graphics.Rect) callconv(.c) void;
    pub const SetRPAttrs = *const fn (*GraphicsBase, *graphics.RastPort, ?[*]const utility.TagItem) callconv(.c) void;
    pub const GetRPAttrs = *const fn (*GraphicsBase, *graphics.RastPort, ?[*]const utility.TagItem) callconv(.c) void;
    pub const AllocBitMapTagList = *const fn (*GraphicsBase, ?[*]const utility.TagItem) callconv(.c) ?*rtg.Surface;
    pub const FreeBitMap = *const fn (*GraphicsBase, ?*rtg.Surface) callconv(.c) void;
    pub const BltRastPort = *const fn (*GraphicsBase, *graphics.RastPort, *graphics.RastPort, *const graphics.Rect, i32, i32) callconv(.c) void;
    pub const Move = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32) callconv(.c) void;
    pub const Draw = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32) callconv(.c) void;
    pub const WritePixel = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32) callconv(.c) void;
    pub const ReadPixel = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, *graphics.Pen) callconv(.c) bool;
    pub const DrawHLine = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32) callconv(.c) void;
    pub const DrawVLine = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32) callconv(.c) void;
    pub const DrawRect = *const fn (*GraphicsBase, *graphics.RastPort, *const graphics.Rect) callconv(.c) void;
    pub const DrawCircle = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32) callconv(.c) void;
    pub const DrawEllipse = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32, i32) callconv(.c) void;
    pub const DrawArc = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32, i32, i32) callconv(.c) void;
    pub const DrawPoly = *const fn (*GraphicsBase, *graphics.RastPort, u32, [*]const graphics.Point) callconv(.c) void;
    pub const InitArea = *const fn (*GraphicsBase, *graphics.RastPort, u32) callconv(.c) bool;
    pub const AreaMove = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32) callconv(.c) bool;
    pub const AreaDraw = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32) callconv(.c) bool;
    pub const AreaEllipse = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32, i32) callconv(.c) bool;
    pub const AreaCircle = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32) callconv(.c) bool;
    pub const AreaArc = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, i32, i32, i32) callconv(.c) bool;
    pub const AreaEnd = *const fn (*GraphicsBase, *graphics.RastPort) callconv(.c) bool;
    pub const OpenFont = *const fn (*GraphicsBase, [*:0]const u8, u32) callconv(.c) ?*graphics.TextFont;
    pub const CloseFont = *const fn (*GraphicsBase, ?*graphics.TextFont) callconv(.c) void;
    pub const Text = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32) callconv(.c) void;
    pub const TextLength = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32) callconv(.c) i32;
    pub const BltTemplate = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32, i32, i32, *const graphics.Rect) callconv(.c) void;
    pub const BltPattern = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32, u32, u32, *const graphics.Rect) callconv(.c) void;
    pub const BltMaskRastPort = *const fn (*GraphicsBase, *graphics.RastPort, *graphics.RastPort, *const graphics.Rect, i32, i32, [*]const u8, u32) callconv(.c) void;
    pub const BltBitMap = *const fn (*GraphicsBase, *const rtg.Surface, i32, i32, *rtg.Surface, i32, i32, i32, i32) callconv(.c) i32;
    pub const BltBitMapRastPort = *const fn (*GraphicsBase, *const rtg.Surface, i32, i32, *graphics.RastPort, i32, i32, i32, i32) callconv(.c) void;
    pub const BltMaskBitMapRastPort = *const fn (*GraphicsBase, *const rtg.Surface, i32, i32, *graphics.RastPort, i32, i32, i32, i32, [*]const u8, u32) callconv(.c) void;
    pub const BitMapScale = *const fn (*GraphicsBase, *const rtg.Surface, *const graphics.Rect, *graphics.RastPort, *const graphics.Rect) callconv(.c) void;
    pub const TextExtent = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32, *graphics.TextExtent) callconv(.c) void;
    pub const TextFit = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32, *graphics.TextExtent, ?*const graphics.TextExtent, i32, i32, i32) callconv(.c) u32;
    pub const AddFont = *const fn (*GraphicsBase, *graphics.TextFont) callconv(.c) bool;
    pub const RemFont = *const fn (*GraphicsBase, *graphics.TextFont) callconv(.c) bool;
    pub const FontExtent = *const fn (*GraphicsBase, *graphics.TextFont, *graphics.FontExtent) callconv(.c) void;
    pub const AskSoftStyle = *const fn (*GraphicsBase, *graphics.RastPort) callconv(.c) u32;
    pub const SetSoftStyle = *const fn (*GraphicsBase, *graphics.RastPort, u32, u32) callconv(.c) u32;
    pub const GraphicsErrorText = *const fn (*GraphicsBase, i32) callconv(.c) [*:0]const u8;
    pub const NewRegion = *const fn (*GraphicsBase) callconv(.c) ?*graphics.Region;
    pub const DisposeRegion = *const fn (*GraphicsBase, ?*graphics.Region) callconv(.c) void;
    pub const ClearRegion = *const fn (*GraphicsBase, *graphics.Region) callconv(.c) void;
    pub const PointInRegion = *const fn (*GraphicsBase, *graphics.Region, i32, i32) callconv(.c) bool;
    pub const OffsetRegion = *const fn (*GraphicsBase, *graphics.Region, i32, i32) callconv(.c) void;
    pub const OrRectRegion = *const fn (*GraphicsBase, *graphics.Region, *const graphics.Rect) callconv(.c) bool;
    pub const AndRectRegion = *const fn (*GraphicsBase, *graphics.Region, *const graphics.Rect) callconv(.c) bool;
    pub const ClearRectRegion = *const fn (*GraphicsBase, *graphics.Region, *const graphics.Rect) callconv(.c) bool;
    pub const XorRectRegion = *const fn (*GraphicsBase, *graphics.Region, *const graphics.Rect) callconv(.c) bool;
    pub const OrRegionRegion = *const fn (*GraphicsBase, *const graphics.Region, *graphics.Region) callconv(.c) bool;
    pub const AndRegionRegion = *const fn (*GraphicsBase, *const graphics.Region, *graphics.Region) callconv(.c) bool;
    pub const SubRegionRegion = *const fn (*GraphicsBase, *const graphics.Region, *graphics.Region) callconv(.c) bool;
    pub const XorRegionRegion = *const fn (*GraphicsBase, *const graphics.Region, *graphics.Region) callconv(.c) bool;
    pub const RegionRectangles = *const fn (*GraphicsBase, *const graphics.Region, ?[*]graphics.Rect, u32) callconv(.c) u32;
    pub const ScrollRaster = *const fn (*GraphicsBase, *graphics.RastPort, i32, i32, *const graphics.Rect) callconv(.c) bool;
    pub const EraseRect = *const fn (*GraphicsBase, *graphics.RastPort, *const graphics.Rect) callconv(.c) void;
    pub const WritePixelArray = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32, u32, i32, i32, *const graphics.Rect) callconv(.c) void;
    pub const WriteLUTPixelArray = *const fn (*GraphicsBase, *graphics.RastPort, [*]const u8, u32, [*]const graphics.Pen, i32, i32, *const graphics.Rect) callconv(.c) void;
    pub const BeginDraw = *const fn (*GraphicsBase, *graphics.RastPort) callconv(.c) void;
    pub const EndDraw = *const fn (*GraphicsBase, *graphics.RastPort) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const GraphicsBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *GraphicsBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A surface to draw into and the state to draw it with. With no tags it
    /// is the display: the first board rtg lists, and the buffer it is
    /// showing. RPTAG_BitMap, RPTAG_Surface or RPTAG_Board name another, and
    /// RPTAG_APen, RPTAG_BPen and RPTAG_DrMd set the state at birth. Null if
    /// there is no memory, or no display and no buffer was named.
    pub fn CreateRastPortTagList(self: *GraphicsBase, tags: ?[*]const utility.TagItem) ?*graphics.RastPort {
        return libraries.call(self, LVO.CreateRastPortTagList, Fn.CreateRastPortTagList, .{tags});
    }

    /// Give a RastPort back. Null is allowed. The buffer it drew into is not
    /// touched: a board's belongs to rtg.library and memory to whoever lent
    /// it.
    pub fn FreeRastPort(self: *GraphicsBase, rp: ?*graphics.RastPort) void {
        return libraries.call(self, LVO.FreeRastPort, Fn.FreeRastPort, .{rp});
    }

    /// Fill a rectangle with the RastPort's pen, clipped to its clip and to
    /// the surface. An opaque pen is handed to the board's engine where there
    /// is one; anything less is composed pixel by pixel. What was written is
    /// handed on to the display before it returns.
    pub fn RectFill(self: *GraphicsBase, rp: *graphics.RastPort, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.RectFill, Fn.RectFill, .{ rp, area });
    }

    /// Change a RastPort: RPTAG_APen, RPTAG_BPen, RPTAG_DrMd and
    /// RPTAG_ClipRect, the same tags that make one. A tag it does not know is
    /// passed over, and the buffer cannot be changed - a RastPort draws into
    /// the one it was made on.
    pub fn SetRPAttrs(self: *GraphicsBase, rp: *graphics.RastPort, tags: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.SetRPAttrs, Fn.SetRPAttrs, .{ rp, tags });
    }

    /// Read a RastPort. Each ti_Data is a pointer to where that value goes:
    /// a *u32 for a pen, the draw mode or the format, and a *Rect for the clip
    /// or the bounds. A tag it does not know is passed over and nothing is
    /// written for it.
    pub fn GetRPAttrs(self: *GraphicsBase, rp: *graphics.RastPort, tags: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.GetRPAttrs, Fn.GetRPAttrs, .{ rp, tags });
    }

    /// A bitmap of one's own, in system memory, to draw into and move to the
    /// screen from. BMTAG_Width and BMTAG_Height are required; BMTAG_Format or
    /// BMTAG_Friend says what a pixel looks like, and BMTAG_Clear zeroes it.
    /// Null if it cannot be had. Free it with FreeBitMap.
    pub fn AllocBitMapTagList(self: *GraphicsBase, tags: ?[*]const utility.TagItem) ?*rtg.Surface {
        return libraries.call(self, LVO.AllocBitMapTagList, Fn.AllocBitMapTagList, .{tags});
    }

    /// Give one back. Null is allowed. A surface this library did not allocate
    /// must not be passed.
    pub fn FreeBitMap(self: *GraphicsBase, bitmap: ?*rtg.Surface) void {
        return libraries.call(self, LVO.FreeBitMap, Fn.FreeBitMap, .{bitmap});
    }

    /// Move a rectangle from one RastPort to another, its top left landing at
    /// (dest_x, dest_y). Clipped by the destination, and the two may be the
    /// same RastPort. Both must be in the same format.
    pub fn BltRastPort(self: *GraphicsBase, src: *graphics.RastPort, dest: *graphics.RastPort, area: *const graphics.Rect, dest_x: i32, dest_y: i32) void {
        return libraries.call(self, LVO.BltRastPort, Fn.BltRastPort, .{ src, dest, area, dest_x, dest_y });
    }

    /// Put the current point at (x, y) without drawing anything. Where Draw
    /// starts from.
    pub fn Move(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32) void {
        return libraries.call(self, LVO.Move, Fn.Move, .{ rp, x, y });
    }

    /// A line from the current point to (x, y), which then becomes the current
    /// point. Both ends are drawn. Clipped, and composed with what is under it
    /// when the pen is not opaque.
    pub fn Draw(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32) void {
        return libraries.call(self, LVO.Draw, Fn.Draw, .{ rp, x, y });
    }

    /// One pixel in the foreground pen, clipped like everything else.
    pub fn WritePixel(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32) void {
        return libraries.call(self, LVO.WritePixel, Fn.WritePixel, .{ rp, x, y });
    }

    /// The colour of one pixel, as 0xAARRGGBB. False if it is outside the
    /// surface, and `out` is then untouched. The clip is not consulted:
    /// a clip says what may be written.
    pub fn ReadPixel(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32, out: *graphics.Pen) bool {
        return libraries.call(self, LVO.ReadPixel, Fn.ReadPixel, .{ rp, x, y, out });
    }

    /// `length` pixels rightward from (x, y).
    pub fn DrawHLine(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32, length: i32) void {
        return libraries.call(self, LVO.DrawHLine, Fn.DrawHLine, .{ rp, x, y, length });
    }

    /// `length` pixels downward from (x, y).
    pub fn DrawVLine(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32, length: i32) void {
        return libraries.call(self, LVO.DrawVLine, Fn.DrawVLine, .{ rp, x, y, length });
    }

    /// The outline of a rectangle, half-open like every rectangle here, with
    /// no pixel drawn twice.
    pub fn DrawRect(self: *GraphicsBase, rp: *graphics.RastPort, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.DrawRect, Fn.DrawRect, .{ rp, area });
    }

    /// A circle's outline about (cx, cy).
    pub fn DrawCircle(self: *GraphicsBase, rp: *graphics.RastPort, cx: i32, cy: i32, radius: i32) void {
        return libraries.call(self, LVO.DrawCircle, Fn.DrawCircle, .{ rp, cx, cy, radius });
    }

    /// An ellipse's outline about (cx, cy), `rx` wide and `ry` tall.
    pub fn DrawEllipse(self: *GraphicsBase, rp: *graphics.RastPort, cx: i32, cy: i32, rx: i32, ry: i32) void {
        return libraries.call(self, LVO.DrawEllipse, Fn.DrawEllipse, .{ rp, cx, cy, rx, ry });
    }

    /// Part of a circle's outline, from `from` degrees to `to` degrees the way
    /// the numbers increase, with 0 to the right and 90 upward.
    pub fn DrawArc(self: *GraphicsBase, rp: *graphics.RastPort, cx: i32, cy: i32, radius: i32, from: i32, to: i32) void {
        return libraries.call(self, LVO.DrawArc, Fn.DrawArc, .{ rp, cx, cy, radius, from, to });
    }

    /// A line from the current point through each of `points` in turn, which
    /// then ends at the last of them. A closed shape repeats its first point.
    pub fn DrawPoly(self: *GraphicsBase, rp: *graphics.RastPort, count: u32, points: [*]const graphics.Point) void {
        return libraries.call(self, LVO.DrawPoly, Fn.DrawPoly, .{ rp, count, points });
    }

    /// Room to collect a filled shape in, for the Area calls: as many corners
    /// as will be needed, curves included. 0 gives the room back. False if
    /// there was no memory. The room goes with the RastPort.
    pub fn InitArea(self: *GraphicsBase, rp: *graphics.RastPort, max_points: u32) bool {
        return libraries.call(self, LVO.InitArea, Fn.InitArea, .{ rp, max_points });
    }

    /// Begin a shape at (x, y). A shape already begun is left to be filled
    /// with this one, so several shapes can be filled at once - one inside
    /// another is a hole.
    pub fn AreaMove(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32) bool {
        return libraries.call(self, LVO.AreaMove, Fn.AreaMove, .{ rp, x, y });
    }

    /// The next corner of the shape being collected.
    pub fn AreaDraw(self: *GraphicsBase, rp: *graphics.RastPort, x: i32, y: i32) bool {
        return libraries.call(self, LVO.AreaDraw, Fn.AreaDraw, .{ rp, x, y });
    }

    /// A whole ellipse as a shape of its own.
    pub fn AreaEllipse(self: *GraphicsBase, rp: *graphics.RastPort, cx: i32, cy: i32, rx: i32, ry: i32) bool {
        return libraries.call(self, LVO.AreaEllipse, Fn.AreaEllipse, .{ rp, cx, cy, rx, ry });
    }

    /// A whole circle as a shape of its own.
    pub fn AreaCircle(self: *GraphicsBase, rp: *graphics.RastPort, cx: i32, cy: i32, radius: i32) bool {
        return libraries.call(self, LVO.AreaCircle, Fn.AreaCircle, .{ rp, cx, cy, radius });
    }

    /// A wedge: out from the middle, round the arc from `from` to `to`
    /// degrees, and back.
    pub fn AreaArc(self: *GraphicsBase, rp: *graphics.RastPort, cx: i32, cy: i32, radius: i32, from: i32, to: i32) bool {
        return libraries.call(self, LVO.AreaArc, Fn.AreaArc, .{ rp, cx, cy, radius, from, to });
    }

    /// Fill everything collected and begin again. Nothing collected fills
    /// nothing, which is not a failure.
    pub fn AreaEnd(self: *GraphicsBase, rp: *graphics.RastPort) bool {
        return libraries.call(self, LVO.AreaEnd, Fn.AreaEnd, .{rp});
    }

    /// A font of that name and height, or null if there is none. The fonts in
    /// this ROM are all POSPAZNAME, at heights 8 and 16.
    pub fn OpenFont(self: *GraphicsBase, name: [*:0]const u8, height: u32) ?*graphics.TextFont {
        return libraries.call(self, LVO.OpenFont, Fn.OpenFont, .{ name, height });
    }

    /// Give a font back. Null is allowed. A font in the ROM stays whatever
    /// happens, so this only counts.
    pub fn CloseFont(self: *GraphicsBase, font: ?*graphics.TextFont) void {
        return libraries.call(self, LVO.CloseFont, Fn.CloseFont, .{font});
    }

    /// Draw `count` characters at the current point, which moves to the end of
    /// them. The point is the **left of the baseline**, as it has always been,
    /// so letters sit above it and tails hang below.
    pub fn Text(self: *GraphicsBase, rp: *graphics.RastPort, string: [*]const u8, count: u32) void {
        return libraries.call(self, LVO.Text, Fn.Text, .{ rp, string, count });
    }

    /// How far `Text` would move along, in pixels, without drawing anything.
    pub fn TextLength(self: *GraphicsBase, rp: *graphics.RastPort, string: [*]const u8, count: u32) i32 {
        return libraries.call(self, LVO.TextLength, Fn.TextLength, .{ rp, string, count });
    }

    /// Stencil a shape of one bit to a pixel onto the surface in the pens.
    /// `bits` is rows of `pitch` bytes, the leftmost pixel in the highest bit;
    /// (src_x, src_y) is where in it the shape starts. The draw mode says what
    /// a clear bit means.
    pub fn BltTemplate(self: *GraphicsBase, rp: *graphics.RastPort, bits: [*]const u8, pitch: u32, src_x: i32, src_y: i32, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.BltTemplate, Fn.BltTemplate, .{ rp, bits, pitch, src_x, src_y, area });
    }

    /// Fill a rectangle with a tile of one bit to a pixel, repeated. The tile
    /// is anchored to the surface, so two rectangles of one pattern line up
    /// where they meet.
    pub fn BltPattern(self: *GraphicsBase, rp: *graphics.RastPort, bits: [*]const u8, pitch: u32, width: u32, height: u32, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.BltPattern, Fn.BltPattern, .{ rp, bits, pitch, width, height, area });
    }

    /// Move a rectangle from one RastPort to another, leaving alone the pixels
    /// whose mask bit is clear. The mask is read where the source is read, so
    /// it travels with the shape.
    pub fn BltMaskRastPort(self: *GraphicsBase, src: *graphics.RastPort, dest: *graphics.RastPort, area: *const graphics.Rect, dest_x: i32, dest_y: i32, mask: [*]const u8, mask_pitch: u32) void {
        return libraries.call(self, LVO.BltMaskRastPort, Fn.BltMaskRastPort, .{ src, dest, area, dest_x, dest_y, mask, mask_pitch });
    }

    /// Move a rectangle of pixels from one surface to another. Neither side
    /// has any drawing state, so nothing is clipped and no draw mode applies:
    /// this is the move itself. Both must be in one format; overlapping is
    /// safe. An RtgBitMap is a Surface by pointer.
    pub fn BltBitMap(self: *GraphicsBase, src: *const rtg.Surface, src_x: i32, src_y: i32, dest: *rtg.Surface, dest_x: i32, dest_y: i32, width: i32, height: i32) i32 {
        return libraries.call(self, LVO.BltBitMap, Fn.BltBitMap, .{ src, src_x, src_y, dest, dest_x, dest_y, width, height });
    }

    /// The same, landing in a RastPort - so the destination's clip and draw
    /// mode apply and the rows are handed on. The source is a surface because
    /// the source of a blit has no drawing state.
    pub fn BltBitMapRastPort(self: *GraphicsBase, src: *const rtg.Surface, src_x: i32, src_y: i32, dest: *graphics.RastPort, dest_x: i32, dest_y: i32, width: i32, height: i32) void {
        return libraries.call(self, LVO.BltBitMapRastPort, Fn.BltBitMapRastPort, .{ src, src_x, src_y, dest, dest_x, dest_y, width, height });
    }

    /// The same again, leaving alone the pixels whose mask bit is clear. The
    /// mask is one bit to a pixel, rows of `mask_pitch` bytes, read from the
    /// source's corner.
    pub fn BltMaskBitMapRastPort(self: *GraphicsBase, src: *const rtg.Surface, src_x: i32, src_y: i32, dest: *graphics.RastPort, dest_x: i32, dest_y: i32, width: i32, height: i32, mask: [*]const u8, mask_pitch: u32) void {
        return libraries.call(self, LVO.BltMaskBitMapRastPort, Fn.BltMaskBitMapRastPort, .{ src, src_x, src_y, dest, dest_x, dest_y, width, height, mask, mask_pitch });
    }

    /// Stretch a rectangle of a surface to fill a rectangle of a RastPort,
    /// taking the nearest pixel for each. Clipped and handed on like any
    /// drawing call.
    pub fn BitMapScale(self: *GraphicsBase, src: *const rtg.Surface, src_area: *const graphics.Rect, dest: *graphics.RastPort, dest_area: *const graphics.Rect) void {
        return libraries.call(self, LVO.BitMapScale, Fn.BitMapScale, .{ src, src_area, dest, dest_area });
    }

    /// How much room `count` characters would take, without drawing them.
    pub fn TextExtent(self: *GraphicsBase, rp: *graphics.RastPort, string: [*]const u8, count: u32, out: *graphics.TextExtent) void {
        return libraries.call(self, LVO.TextExtent, Fn.TextExtent, .{ rp, string, count, out });
    }

    /// How many characters fit in the room given, and how much room those
    /// take. `constraining` is a box to fit inside, or null; `width` and
    /// `height` override it when either is above 0. `direction` is
    /// TEXT_FORWARD, or TEXT_BACKWARD with `string` pointing at the last
    /// character. 0 when the font is taller than the room.
    pub fn TextFit(self: *GraphicsBase, rp: *graphics.RastPort, string: [*]const u8, count: u32, out: *graphics.TextExtent, constraining: ?*const graphics.TextExtent, direction: i32, width: i32, height: i32) u32 {
        return libraries.call(self, LVO.TextFit, Fn.TextFit, .{ rp, string, count, out, constraining, direction, width, height });
    }

    /// Put a font on the library's list, so OpenFont can find it. What
    /// something that loads a font from a file calls once it has built one.
    /// False if it is already there.
    pub fn AddFont(self: *GraphicsBase, font: *graphics.TextFont) bool {
        return libraries.call(self, LVO.AddFont, Fn.AddFont, .{font});
    }

    /// Take one off again. False while anything still has it open.
    pub fn RemFont(self: *GraphicsBase, font: *graphics.TextFont) bool {
        return libraries.call(self, LVO.RemFont, Fn.RemFont, .{font});
    }

    /// What a font is: its width, height, baseline, the styles it was drawn
    /// with, and where one character's ink lands relative to the point.
    pub fn FontExtent(self: *GraphicsBase, font: *graphics.TextFont, out: *graphics.FontExtent) void {
        return libraries.call(self, LVO.FontExtent, Fn.FontExtent, .{ font, out });
    }

    /// Which styles can still be asked for on the RastPort's font - the ones
    /// it was not already drawn with. 0 with no font.
    pub fn AskSoftStyle(self: *GraphicsBase, rp: *graphics.RastPort) u32 {
        return libraries.call(self, LVO.AskSoftStyle, Fn.AskSoftStyle, .{rp});
    }

    /// Set the styles to `style`, keeping only the bits `enable` allows and
    /// only those AskSoftStyle offers. Answers what the style became.
    pub fn SetSoftStyle(self: *GraphicsBase, rp: *graphics.RastPort, style: u32, enable: u32) u32 {
        return libraries.call(self, LVO.SetSoftStyle, Fn.SetSoftStyle, .{ rp, style, enable });
    }

    /// What a GERR_ code means, in words, for a program that wants to say so.
    /// A code it does not know is "unknown error"; it never answers null.
    pub fn GraphicsErrorText(self: *GraphicsBase, code: i32) [*:0]const u8 {
        return libraries.call(self, LVO.GraphicsErrorText, Fn.GraphicsErrorText, .{code});
    }

    /// An empty region. Null if there was no memory. Free it with
    /// DisposeRegion.
    pub fn NewRegion(self: *GraphicsBase) ?*graphics.Region {
        return libraries.call(self, LVO.NewRegion, Fn.NewRegion, .{});
    }

    /// Give a region back, with every rectangle in it. Null is allowed.
    pub fn DisposeRegion(self: *GraphicsBase, region: ?*graphics.Region) void {
        return libraries.call(self, LVO.DisposeRegion, Fn.DisposeRegion, .{region});
    }

    /// Make it empty again, keeping the region itself.
    pub fn ClearRegion(self: *GraphicsBase, region: *graphics.Region) void {
        return libraries.call(self, LVO.ClearRegion, Fn.ClearRegion, .{region});
    }

    /// Whether the point is inside.
    pub fn PointInRegion(self: *GraphicsBase, region: *graphics.Region, x: i32, y: i32) bool {
        return libraries.call(self, LVO.PointInRegion, Fn.PointInRegion, .{ region, x, y });
    }

    /// Move the whole region by (dx, dy).
    pub fn OffsetRegion(self: *GraphicsBase, region: *graphics.Region, dx: i32, dy: i32) void {
        return libraries.call(self, LVO.OffsetRegion, Fn.OffsetRegion, .{ region, dx, dy });
    }

    /// Add the rectangle to the region. False if there was no memory, and the
    /// region is then unchanged.
    pub fn OrRectRegion(self: *GraphicsBase, region: *graphics.Region, rect: *const graphics.Rect) bool {
        return libraries.call(self, LVO.OrRectRegion, Fn.OrRectRegion, .{ region, rect });
    }

    /// Cut the region down to what is also inside the rectangle. False if
    /// there was no memory.
    pub fn AndRectRegion(self: *GraphicsBase, region: *graphics.Region, rect: *const graphics.Rect) bool {
        return libraries.call(self, LVO.AndRectRegion, Fn.AndRectRegion, .{ region, rect });
    }

    /// Take the rectangle out of the region. False if there was no memory.
    pub fn ClearRectRegion(self: *GraphicsBase, region: *graphics.Region, rect: *const graphics.Rect) bool {
        return libraries.call(self, LVO.ClearRectRegion, Fn.ClearRectRegion, .{ region, rect });
    }

    /// Everything in the rectangle that is not in the region, and everything
    /// in the region that is not in the rectangle. False if there was no
    /// memory.
    pub fn XorRectRegion(self: *GraphicsBase, region: *graphics.Region, rect: *const graphics.Rect) bool {
        return libraries.call(self, LVO.XorRectRegion, Fn.XorRectRegion, .{ region, rect });
    }

    /// Add everything in `source` to `dest`. False if there was no memory.
    pub fn OrRegionRegion(self: *GraphicsBase, source: *const graphics.Region, dest: *graphics.Region) bool {
        return libraries.call(self, LVO.OrRegionRegion, Fn.OrRegionRegion, .{ source, dest });
    }

    /// Cut `dest` down to what is also in `source`. False if there was no
    /// memory.
    pub fn AndRegionRegion(self: *GraphicsBase, source: *const graphics.Region, dest: *graphics.Region) bool {
        return libraries.call(self, LVO.AndRegionRegion, Fn.AndRegionRegion, .{ source, dest });
    }

    /// Take everything in `source` out of `dest`. False if there was no
    /// memory.
    pub fn SubRegionRegion(self: *GraphicsBase, source: *const graphics.Region, dest: *graphics.Region) bool {
        return libraries.call(self, LVO.SubRegionRegion, Fn.SubRegionRegion, .{ source, dest });
    }

    /// What is in one of the two but not both. False if there was no memory.
    pub fn XorRegionRegion(self: *GraphicsBase, source: *const graphics.Region, dest: *graphics.Region) bool {
        return libraries.call(self, LVO.XorRegionRegion, Fn.XorRegionRegion, .{ source, dest });
    }

    /// The rectangles a region is made of, which is how anything outside can
    /// see the shape of one. It answers how many there are and fills up to
    /// `max` of them, so a caller asks once with no room to find out how much
    /// it needs. They do not overlap and they are in order of min_y, then
    /// min_x. 0 means the region is empty.
    pub fn RegionRectangles(self: *GraphicsBase, region: *const graphics.Region, into: ?[*]graphics.Rect, max: u32) u32 {
        return libraries.call(self, LVO.RegionRectangles, Fn.RegionRectangles, .{ region, into, max });
    }

    /// Moves what is inside `area` of the RastPort itself: the contents go
    /// `dx` to the left and `dy` up, so a terminal scrolling its text up by a
    /// row asks for `dy` of one row. What the move vacates is left as it was -
    /// whoever scrolled is about to draw there. The pixels are read through
    /// the same clip the RastPort is drawn through, so a window moves its own
    /// pixels and not whatever is on the display at those coordinates. False
    /// when part of what was to be moved could not be read - a window covered
    /// by another keeps nothing of what is under it - and then nothing was
    /// moved at all, so the caller draws that area again.
    pub fn ScrollRaster(self: *GraphicsBase, rp: *graphics.RastPort, dx: i32, dy: i32, area: *const graphics.Rect) bool {
        return libraries.call(self, LVO.ScrollRaster, Fn.ScrollRaster, .{ rp, dx, dy, area });
    }

    /// Paints `area` of the RastPort the way an area with nothing in it yet is
    /// meant to look: through the hook `RPTAG_BackFill` names, or in the
    /// RastPort's own background pen when it names none, or not at all when it
    /// says `BACKFILL_NONE`.
    ///
    /// What that hook is, is set by whatever manages windows - it is what knows
    /// how a window's ground looks. This library only calls it, and learns
    /// nothing about windows or layers by doing so. A hook draws through this
    /// same RastPort, so what it puts down is clipped as anything else drawn
    /// through it would be.
    ///
    /// This is what an image erases with: a picture taken off a window leaves
    /// the window's own ground behind, pattern and all, rather than a flat
    /// rectangle of whichever pen happened to be set.
    pub fn EraseRect(self: *GraphicsBase, rp: *graphics.RastPort, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.EraseRect, Fn.EraseRect, .{ rp, area });
    }

    /// A rectangle of pixels of one's own put down as they are, in any
    /// rtg.library format with colours (`format`, a PixelFormat) - converted to
    /// the surface's when the two differ, a row copied whole when they do not.
    /// `pixels` is rows of `pitch` bytes; (src_x, src_y) is where in them to
    /// start, and `area` where it lands, half-open. Clipped like any drawing;
    /// the pens and the draw mode are not used.
    pub fn WritePixelArray(self: *GraphicsBase, rp: *graphics.RastPort, pixels: [*]const u8, pitch: u32, format: u32, src_x: i32, src_y: i32, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.WritePixelArray, Fn.WritePixelArray, .{ rp, pixels, pitch, format, src_x, src_y, area });
    }

    /// A rectangle of 8-bit colour numbers put down through `table`, 256 pens
    /// as 0xAARRGGBB: each byte is the pen at that place in it. Otherwise as
    /// WritePixelArray - the chunky picture of an old game, or a decoder's
    /// indexed frame, on a surface of any format.
    pub fn WriteLUTPixelArray(self: *GraphicsBase, rp: *graphics.RastPort, pixels: [*]const u8, pitch: u32, table: [*]const graphics.Pen, src_x: i32, src_y: i32, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.WriteLUTPixelArray, Fn.WriteLUTPixelArray, .{ rp, pixels, pitch, table, src_x, src_y, area });
    }

    /// The drawing from here to the matching EndDraw is one piece of work:
    /// the rows it writes are gathered and handed to the display once, at
    /// the end, instead of after every call. What is drawn in two steps - a
    /// thing rubbed out and drawn again - is never shown half done.
    pub fn BeginDraw(self: *GraphicsBase, rp: *graphics.RastPort) void {
        return libraries.call(self, LVO.BeginDraw, Fn.BeginDraw, .{rp});
    }

    /// The end of that piece of work: the rows gathered since BeginDraw go
    /// to the display, in one. Nested BeginDraws need one of these each, and
    /// nothing goes until the last.
    pub fn EndDraw(self: *GraphicsBase, rp: *graphics.RastPort) void {
        return libraries.call(self, LVO.EndDraw, Fn.EndDraw, .{rp});
    }
};
