// SPDX-License-Identifier: MIT
//! icon.library's functions: icons read, written and freed, the default
//! icon of each kind, and the tool types. Open it with
//! OpenLibrary("icon.library", 1).
//!
//! The table is this library's own: it starts at the first slot after
//! the standard four and holds only what is here.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/icon_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const icon = @import("../libs/icon/icon.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "icon.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const GetDiskObject = libraries.lvo(4);
    pub const PutDiskObject = libraries.lvo(5);
    pub const FreeDiskObject = libraries.lvo(6);
    pub const GetDiskObjectNew = libraries.lvo(7);
    pub const DeleteDiskObject = libraries.lvo(8);
    pub const GetDefDiskObject = libraries.lvo(9);
    pub const PutDefDiskObject = libraries.lvo(10);
    pub const FindToolType = libraries.lvo(11);
    pub const MatchToolValue = libraries.lvo(12);
    pub const BumpRevision = libraries.lvo(13);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const GetDiskObject = *const fn (*IconBase, ?[*:0]const u8) callconv(.c) ?*icon.DiskObject;
    pub const PutDiskObject = *const fn (*IconBase, [*:0]const u8, *const icon.DiskObject) callconv(.c) bool;
    pub const FreeDiskObject = *const fn (*IconBase, ?*icon.DiskObject) callconv(.c) void;
    pub const GetDiskObjectNew = *const fn (*IconBase, [*:0]const u8) callconv(.c) ?*icon.DiskObject;
    pub const DeleteDiskObject = *const fn (*IconBase, [*:0]const u8) callconv(.c) bool;
    pub const GetDefDiskObject = *const fn (*IconBase, u32) callconv(.c) ?*icon.DiskObject;
    pub const PutDefDiskObject = *const fn (*IconBase, *const icon.DiskObject) callconv(.c) bool;
    pub const FindToolType = *const fn (*IconBase, ?[*]const ?[*:0]const u8, [*:0]const u8) callconv(.c) ?[*:0]const u8;
    pub const MatchToolValue = *const fn (*IconBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const BumpRevision = *const fn (*IconBase, [*]u8, [*:0]const u8) callconv(.c) [*:0]u8;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const IconBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *IconBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// `<name>.info` read. A null name makes an empty icon to fill in. Null
    /// when there is no such icon or it cannot be read, with IoErr saying why.
    pub fn GetDiskObject(self: *IconBase, name: ?[*:0]const u8) ?*icon.DiskObject {
        return libraries.call(self, LVO.GetDiskObject, Fn.GetDiskObject, .{name});
    }

    /// `<name>.info` written from `object`: true, or false with IoErr saying
    /// why.
    pub fn PutDiskObject(self: *IconBase, name: [*:0]const u8, object: *const icon.DiskObject) bool {
        return libraries.call(self, LVO.PutDiskObject, Fn.PutDiskObject, .{ name, object });
    }

    /// An icon given back: what the library made for it freed. Null does
    /// nothing.
    pub fn FreeDiskObject(self: *IconBase, object: ?*icon.DiskObject) void {
        return libraries.call(self, LVO.FreeDiskObject, Fn.FreeDiskObject, .{object});
    }

    /// `name`'s icon, or else the default icon that fits what `name` is.
    pub fn GetDiskObjectNew(self: *IconBase, name: [*:0]const u8) ?*icon.DiskObject {
        return libraries.call(self, LVO.GetDiskObjectNew, Fn.GetDiskObjectNew, .{name});
    }

    /// `<name>.info` deleted: true, also when there was none.
    pub fn DeleteDiskObject(self: *IconBase, name: [*:0]const u8) bool {
        return libraries.call(self, LVO.DeleteDiskObject, Fn.DeleteDiskObject, .{name});
    }

    /// The default icon of a kind (WBDISK to WBGARBAGE), without a place.
    pub fn GetDefDiskObject(self: *IconBase, kind: u32) ?*icon.DiskObject {
        return libraries.call(self, LVO.GetDefDiskObject, Fn.GetDefDiskObject, .{kind});
    }

    /// `object` made the default icon of its kind.
    pub fn PutDefDiskObject(self: *IconBase, object: *const icon.DiskObject) bool {
        return libraries.call(self, LVO.PutDefDiskObject, Fn.PutDefDiskObject, .{object});
    }

    /// The value of the tool type `name` in `types`: what follows its `=`,
    /// an empty string for one without, null when it is not there.
    pub fn FindToolType(self: *IconBase, types: ?[*]const ?[*:0]const u8, name: [*:0]const u8) ?[*:0]const u8 {
        return libraries.call(self, LVO.FindToolType, Fn.FindToolType, .{ types, name });
    }

    /// Whether `value` names `wanted` among its alternatives, `|` between
    /// them, in any case.
    pub fn MatchToolValue(self: *IconBase, value: [*:0]const u8, wanted: [*:0]const u8) bool {
        return libraries.call(self, LVO.MatchToolValue, Fn.MatchToolValue, .{ value, wanted });
    }

    /// The name for a copy of `name` written into `into` (256 bytes):
    /// `Copy_of_x`, then `Copy_2_of_x`. `into` back.
    pub fn BumpRevision(self: *IconBase, into: [*]u8, name: [*:0]const u8) [*:0]u8 {
        return libraries.call(self, LVO.BumpRevision, Fn.BumpRevision, .{ into, name });
    }
};
