// SPDX-License-Identifier: MIT
//! iffparse.library's functions: reading and writing IFF - chunks inside
//! chunks, each named by four characters. Open it with
//! OpenLibrary("iffparse.library", 1).
//!
//! The table is this library's own: it is not on any other system's, so
//! it starts at the first slot after the standard four and holds only
//! what is here.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/iffparse_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const utility = @import("../libs/utility/utility.zig");
const iffparse = @import("../libs/iffparse/iffparse.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "iffparse.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const AllocIFF = libraries.lvo(4);
    pub const FreeIFF = libraries.lvo(5);
    pub const InitIFF = libraries.lvo(6);
    pub const InitIFFasDOS = libraries.lvo(7);
    pub const InitIFFasClip = libraries.lvo(8);
    pub const OpenIFF = libraries.lvo(9);
    pub const CloseIFF = libraries.lvo(10);
    pub const ParseIFF = libraries.lvo(11);
    pub const ReadChunkBytes = libraries.lvo(12);
    pub const ReadChunkRecords = libraries.lvo(13);
    pub const WriteChunkBytes = libraries.lvo(14);
    pub const WriteChunkRecords = libraries.lvo(15);
    pub const PushChunk = libraries.lvo(16);
    pub const PopChunk = libraries.lvo(17);
    pub const EntryHandler = libraries.lvo(18);
    pub const ExitHandler = libraries.lvo(19);
    pub const PropChunk = libraries.lvo(20);
    pub const PropChunks = libraries.lvo(21);
    pub const StopChunk = libraries.lvo(22);
    pub const StopChunks = libraries.lvo(23);
    pub const CollectionChunk = libraries.lvo(24);
    pub const CollectionChunks = libraries.lvo(25);
    pub const StopOnExit = libraries.lvo(26);
    pub const FindProp = libraries.lvo(27);
    pub const FindCollection = libraries.lvo(28);
    pub const FindPropContext = libraries.lvo(29);
    pub const CurrentChunk = libraries.lvo(30);
    pub const ParentChunk = libraries.lvo(31);
    pub const AllocLocalItem = libraries.lvo(32);
    pub const FreeLocalItem = libraries.lvo(33);
    pub const LocalItemData = libraries.lvo(34);
    pub const SetLocalItemPurge = libraries.lvo(35);
    pub const FindLocalItem = libraries.lvo(36);
    pub const StoreLocalItem = libraries.lvo(37);
    pub const StoreItemInContext = libraries.lvo(38);
    pub const OpenClipboard = libraries.lvo(39);
    pub const CloseClipboard = libraries.lvo(40);
    pub const GoodID = libraries.lvo(41);
    pub const GoodType = libraries.lvo(42);
    pub const IDtoStr = libraries.lvo(43);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const AllocIFF = *const fn (*IFFParseBase) callconv(.c) ?*iffparse.IFFHandle;
    pub const FreeIFF = *const fn (*IFFParseBase, ?*iffparse.IFFHandle) callconv(.c) void;
    pub const InitIFF = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, *utility.Hook) callconv(.c) void;
    pub const InitIFFasDOS = *const fn (*IFFParseBase, *iffparse.IFFHandle) callconv(.c) void;
    pub const InitIFFasClip = *const fn (*IFFParseBase, *iffparse.IFFHandle) callconv(.c) void;
    pub const OpenIFF = *const fn (*IFFParseBase, *iffparse.IFFHandle, i32) callconv(.c) i32;
    pub const CloseIFF = *const fn (*IFFParseBase, *iffparse.IFFHandle) callconv(.c) void;
    pub const ParseIFF = *const fn (*IFFParseBase, *iffparse.IFFHandle, i32) callconv(.c) i32;
    pub const ReadChunkBytes = *const fn (*IFFParseBase, *iffparse.IFFHandle, *anyopaque, i32) callconv(.c) i32;
    pub const ReadChunkRecords = *const fn (*IFFParseBase, *iffparse.IFFHandle, *anyopaque, i32, i32) callconv(.c) i32;
    pub const WriteChunkBytes = *const fn (*IFFParseBase, *iffparse.IFFHandle, *const anyopaque, i32) callconv(.c) i32;
    pub const WriteChunkRecords = *const fn (*IFFParseBase, *iffparse.IFFHandle, *const anyopaque, i32, i32) callconv(.c) i32;
    pub const PushChunk = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32, i32) callconv(.c) i32;
    pub const PopChunk = *const fn (*IFFParseBase, *iffparse.IFFHandle) callconv(.c) i32;
    pub const EntryHandler = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32, i32, *utility.Hook, ?*anyopaque) callconv(.c) i32;
    pub const ExitHandler = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32, i32, *utility.Hook, ?*anyopaque) callconv(.c) i32;
    pub const PropChunk = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32) callconv(.c) i32;
    pub const PropChunks = *const fn (*IFFParseBase, *iffparse.IFFHandle, [*]const u32, i32) callconv(.c) i32;
    pub const StopChunk = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32) callconv(.c) i32;
    pub const StopChunks = *const fn (*IFFParseBase, *iffparse.IFFHandle, [*]const u32, i32) callconv(.c) i32;
    pub const CollectionChunk = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32) callconv(.c) i32;
    pub const CollectionChunks = *const fn (*IFFParseBase, *iffparse.IFFHandle, [*]const u32, i32) callconv(.c) i32;
    pub const StopOnExit = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32) callconv(.c) i32;
    pub const FindProp = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32) callconv(.c) ?*iffparse.StoredProperty;
    pub const FindCollection = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32) callconv(.c) ?*iffparse.CollectionItem;
    pub const FindPropContext = *const fn (*IFFParseBase, *iffparse.IFFHandle) callconv(.c) ?*iffparse.ContextNode;
    pub const CurrentChunk = *const fn (*IFFParseBase, *iffparse.IFFHandle) callconv(.c) ?*iffparse.ContextNode;
    pub const ParentChunk = *const fn (*IFFParseBase, *iffparse.ContextNode) callconv(.c) ?*iffparse.ContextNode;
    pub const AllocLocalItem = *const fn (*IFFParseBase, u32, u32, u32, i32) callconv(.c) ?*iffparse.LocalContextItem;
    pub const FreeLocalItem = *const fn (*IFFParseBase, ?*iffparse.LocalContextItem) callconv(.c) void;
    pub const LocalItemData = *const fn (*IFFParseBase, ?*iffparse.LocalContextItem) callconv(.c) ?*anyopaque;
    pub const SetLocalItemPurge = *const fn (*IFFParseBase, *iffparse.LocalContextItem, *utility.Hook) callconv(.c) void;
    pub const FindLocalItem = *const fn (*IFFParseBase, *iffparse.IFFHandle, u32, u32, u32) callconv(.c) ?*iffparse.LocalContextItem;
    pub const StoreLocalItem = *const fn (*IFFParseBase, *iffparse.IFFHandle, *iffparse.LocalContextItem, i32) callconv(.c) i32;
    pub const StoreItemInContext = *const fn (*IFFParseBase, *iffparse.IFFHandle, *iffparse.LocalContextItem, *iffparse.ContextNode) callconv(.c) void;
    pub const OpenClipboard = *const fn (*IFFParseBase, u32) callconv(.c) ?*iffparse.ClipboardHandle;
    pub const CloseClipboard = *const fn (*IFFParseBase, ?*iffparse.ClipboardHandle) callconv(.c) void;
    pub const GoodID = *const fn (*IFFParseBase, u32) callconv(.c) bool;
    pub const GoodType = *const fn (*IFFParseBase, u32) callconv(.c) bool;
    pub const IDtoStr = *const fn (*IFFParseBase, u32, *[5]u8) callconv(.c) [*:0]u8;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const IFFParseBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *IFFParseBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A handle for one IFF file, with nothing in it yet. Give it a stream
    /// (`InitIFFasDOS`, `InitIFFasClip`, `InitIFF`) before opening it. Null
    /// for no memory.
    pub fn AllocIFF(self: *IFFParseBase) ?*iffparse.IFFHandle {
        return libraries.call(self, LVO.AllocIFF, Fn.AllocIFF, .{});
    }

    /// A handle given back. It must be closed first (`CloseIFF`), and the
    /// stream behind it is the caller's to close. Null does nothing.
    pub fn FreeIFF(self: *IFFParseBase, iff: ?*iffparse.IFFHandle) void {
        return libraries.call(self, LVO.FreeIFF, Fn.FreeIFF, .{iff});
    }

    /// Where the bytes come from: `hook` is called with the handle and an
    /// IFFStreamCmd, and `flags` says what the stream can do (IFFF_FSEEK,
    /// IFFF_RSEEK).
    pub fn InitIFF(self: *IFFParseBase, iff: *iffparse.IFFHandle, flags: u32, hook: *utility.Hook) void {
        return libraries.call(self, LVO.InitIFF, Fn.InitIFF, .{ iff, flags, hook });
    }

    /// The stream is a dos file handle in `iff.stream`, which seeks both
    /// ways.
    pub fn InitIFFasDOS(self: *IFFParseBase, iff: *iffparse.IFFHandle) void {
        return libraries.call(self, LVO.InitIFFasDOS, Fn.InitIFFasDOS, .{iff});
    }

    /// The stream is a ClipboardHandle in `iff.stream`, from OpenClipboard.
    pub fn InitIFFasClip(self: *IFFParseBase, iff: *iffparse.IFFHandle) void {
        return libraries.call(self, LVO.InitIFFasClip, Fn.InitIFFasClip, .{iff});
    }

    /// The file opened for reading (IFFF_READ) or writing (IFFF_WRITE): the
    /// stream is told to begin and the walk starts at the top. 0, or an
    /// IFFERR_.
    pub fn OpenIFF(self: *IFFParseBase, iff: *iffparse.IFFHandle, rw_mode: i32) i32 {
        return libraries.call(self, LVO.OpenIFF, Fn.OpenIFF, .{ iff, rw_mode });
    }

    /// The file done with: every chunk still open is popped, a write is
    /// finished off, and the stream is told so. The stream itself is the
    /// caller's to close.
    pub fn CloseIFF(self: *IFFParseBase, iff: *iffparse.IFFHandle) void {
        return libraries.call(self, LVO.CloseIFF, Fn.CloseIFF, .{iff});
    }

    /// The walk carried on: to the next chunk asked for with StopChunk and
    /// its like (IFFPARSE_SCAN), one chunk with the handlers run
    /// (IFFPARSE_STEP), or one chunk with none run (IFFPARSE_RAWSTEP). 0
    /// when it stopped where it was asked to, or an IFFERR_ - IFFERR_EOF at
    /// the end of the file.
    pub fn ParseIFF(self: *IFFParseBase, iff: *iffparse.IFFHandle, control: i32) i32 {
        return libraries.call(self, LVO.ParseIFF, Fn.ParseIFF, .{ iff, control });
    }

    /// Bytes of the chunk the walk is in, never past its end. How many were
    /// read, or an IFFERR_.
    pub fn ReadChunkBytes(self: *IFFParseBase, iff: *iffparse.IFFHandle, buf: *anyopaque, bytes: i32) i32 {
        return libraries.call(self, LVO.ReadChunkBytes, Fn.ReadChunkBytes, .{ iff, buf, bytes });
    }

    /// The same in records of `record_size` bytes, so that a part record is
    /// not read. How many whole records were read, or an IFFERR_.
    pub fn ReadChunkRecords(self: *IFFParseBase, iff: *iffparse.IFFHandle, buf: *anyopaque, record_size: i32, records: i32) i32 {
        return libraries.call(self, LVO.ReadChunkRecords, Fn.ReadChunkRecords, .{ iff, buf, record_size, records });
    }

    /// Bytes into the chunk being written. How many were written, or an
    /// IFFERR_.
    pub fn WriteChunkBytes(self: *IFFParseBase, iff: *iffparse.IFFHandle, buf: *const anyopaque, bytes: i32) i32 {
        return libraries.call(self, LVO.WriteChunkBytes, Fn.WriteChunkBytes, .{ iff, buf, bytes });
    }

    /// The same in records. How many whole records were written, or an
    /// IFFERR_.
    pub fn WriteChunkRecords(self: *IFFParseBase, iff: *iffparse.IFFHandle, buf: *const anyopaque, record_size: i32, records: i32) i32 {
        return libraries.call(self, LVO.WriteChunkRecords, Fn.WriteChunkRecords, .{ iff, buf, record_size, records });
    }

    /// A chunk started, for writing: `id` its four characters, `form_type` the
    /// kind of a generic chunk (FORM, LIST, CAT) and ignored otherwise, and
    /// `size` how many bytes it will hold or IFFSIZE_UNKNOWN to have it
    /// written back at PopChunk. 0, or an IFFERR_.
    pub fn PushChunk(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32, size: i32) i32 {
        return libraries.call(self, LVO.PushChunk, Fn.PushChunk, .{ iff, form_type, id, size });
    }

    /// The chunk ended: its size written back if it was unknown, the pad
    /// byte written if it needs one, and the walk back in its parent. 0, or
    /// an IFFERR_.
    pub fn PopChunk(self: *IFFParseBase, iff: *iffparse.IFFHandle) i32 {
        return libraries.call(self, LVO.PopChunk, Fn.PopChunk, .{iff});
    }

    /// `hook` called whenever the walk enters a `form_type`.`id` chunk, stored at
    /// `position` (IFFSLI_). The hook is called with the handle and an
    /// IFFCMD_ENTRY command; IFF_RETURN2CLIENT from it stops the walk. 0, or
    /// an IFFERR_.
    pub fn EntryHandler(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32, position: i32, hook: *utility.Hook, object: ?*anyopaque) i32 {
        return libraries.call(self, LVO.EntryHandler, Fn.EntryHandler, .{ iff, form_type, id, position, hook, object });
    }

    /// The same for leaving a chunk (IFFCMD_EXIT).
    pub fn ExitHandler(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32, position: i32, hook: *utility.Hook, object: ?*anyopaque) i32 {
        return libraries.call(self, LVO.ExitHandler, Fn.ExitHandler, .{ iff, form_type, id, position, hook, object });
    }

    /// The contents of every `form_type`.`id` chunk kept as it is walked past, to
    /// be read back with FindProp. 0, or an IFFERR_.
    pub fn PropChunk(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32) i32 {
        return libraries.call(self, LVO.PropChunk, Fn.PropChunk, .{ iff, form_type, id });
    }

    /// PropChunk for each of `pairs` type-and-id pairs.
    pub fn PropChunks(self: *IFFParseBase, iff: *iffparse.IFFHandle, list: [*]const u32, pairs: i32) i32 {
        return libraries.call(self, LVO.PropChunks, Fn.PropChunks, .{ iff, list, pairs });
    }

    /// The walk stops when it reaches a `form_type`.`id` chunk, with that chunk
    /// the current one and nothing of it read. 0, or an IFFERR_.
    pub fn StopChunk(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32) i32 {
        return libraries.call(self, LVO.StopChunk, Fn.StopChunk, .{ iff, form_type, id });
    }

    /// StopChunk for each of `pairs` type-and-id pairs.
    pub fn StopChunks(self: *IFFParseBase, iff: *iffparse.IFFHandle, list: [*]const u32, pairs: i32) i32 {
        return libraries.call(self, LVO.StopChunks, Fn.StopChunks, .{ iff, list, pairs });
    }

    /// Every `form_type`.`id` chunk kept, newest first, to be read back with
    /// FindCollection. 0, or an IFFERR_.
    pub fn CollectionChunk(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32) i32 {
        return libraries.call(self, LVO.CollectionChunk, Fn.CollectionChunk, .{ iff, form_type, id });
    }

    /// CollectionChunk for each of `pairs` type-and-id pairs.
    pub fn CollectionChunks(self: *IFFParseBase, iff: *iffparse.IFFHandle, list: [*]const u32, pairs: i32) i32 {
        return libraries.call(self, LVO.CollectionChunks, Fn.CollectionChunks, .{ iff, list, pairs });
    }

    /// The walk stops when it reaches the end of a `form_type`.`id` chunk, with
    /// that chunk still the current one. 0, or an IFFERR_.
    pub fn StopOnExit(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32) i32 {
        return libraries.call(self, LVO.StopOnExit, Fn.StopOnExit, .{ iff, form_type, id });
    }

    /// The stored contents of a `form_type`.`id` property chunk, or null if none
    /// was stored where the walk now is.
    pub fn FindProp(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32) ?*iffparse.StoredProperty {
        return libraries.call(self, LVO.FindProp, Fn.FindProp, .{ iff, form_type, id });
    }

    /// The newest of the kept `form_type`.`id` chunks, each linked to the one
    /// before it; null if none were kept.
    pub fn FindCollection(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32) ?*iffparse.CollectionItem {
        return libraries.call(self, LVO.FindCollection, Fn.FindCollection, .{ iff, form_type, id });
    }

    /// The FORM or LIST the walk is inside, which is where properties are
    /// stored; null if there is none.
    pub fn FindPropContext(self: *IFFParseBase, iff: *iffparse.IFFHandle) ?*iffparse.ContextNode {
        return libraries.call(self, LVO.FindPropContext, Fn.FindPropContext, .{iff});
    }

    /// The chunk the walk is in, or null before it has entered one.
    pub fn CurrentChunk(self: *IFFParseBase, iff: *iffparse.IFFHandle) ?*iffparse.ContextNode {
        return libraries.call(self, LVO.CurrentChunk, Fn.CurrentChunk, .{iff});
    }

    /// The chunk `context` is in, or null if it is the outermost.
    pub fn ParentChunk(self: *IFFParseBase, context: *iffparse.ContextNode) ?*iffparse.ContextNode {
        return libraries.call(self, LVO.ParentChunk, Fn.ParentChunk, .{context});
    }

    /// A local item of `data_size` bytes for a `form_type`.`id` chunk, named by
    /// `ident`. Store it with StoreLocalItem or free it with FreeLocalItem;
    /// null for no memory.
    pub fn AllocLocalItem(self: *IFFParseBase, form_type: u32, id: u32, ident: u32, data_size: i32) ?*iffparse.LocalContextItem {
        return libraries.call(self, LVO.AllocLocalItem, Fn.AllocLocalItem, .{ form_type, id, ident, data_size });
    }

    /// A local item freed. It must not be stored. Null does nothing.
    pub fn FreeLocalItem(self: *IFFParseBase, item: ?*iffparse.LocalContextItem) void {
        return libraries.call(self, LVO.FreeLocalItem, Fn.FreeLocalItem, .{item});
    }

    /// The `data_size` bytes of a local item; null for a null item.
    pub fn LocalItemData(self: *IFFParseBase, item: ?*iffparse.LocalContextItem) ?*anyopaque {
        return libraries.call(self, LVO.LocalItemData, Fn.LocalItemData, .{item});
    }

    /// The hook called instead of freeing the item when its chunk is left.
    /// It is called with the item and an IFFCMD_PURGELCI command, and frees
    /// the item itself.
    pub fn SetLocalItemPurge(self: *IFFParseBase, item: *iffparse.LocalContextItem, hook: *utility.Hook) void {
        return libraries.call(self, LVO.SetLocalItemPurge, Fn.SetLocalItemPurge, .{ item, hook });
    }

    /// The nearest stored `form_type`.`id`.`ident` item, looking from the chunk
    /// the walk is in outwards; null if there is none.
    pub fn FindLocalItem(self: *IFFParseBase, iff: *iffparse.IFFHandle, form_type: u32, id: u32, ident: u32) ?*iffparse.LocalContextItem {
        return libraries.call(self, LVO.FindLocalItem, Fn.FindLocalItem, .{ iff, form_type, id, ident });
    }

    /// An item stored at `position`: IFFSLI_ROOT with the handle,
    /// IFFSLI_TOP with the chunk the walk is in, IFFSLI_PROP with the FORM
    /// or LIST it is inside. 0, or an IFFERR_.
    pub fn StoreLocalItem(self: *IFFParseBase, iff: *iffparse.IFFHandle, item: *iffparse.LocalContextItem, position: i32) i32 {
        return libraries.call(self, LVO.StoreLocalItem, Fn.StoreLocalItem, .{ iff, item, position });
    }

    /// An item stored with a chunk named outright. Any item already there
    /// with the same type, id and ident goes.
    pub fn StoreItemInContext(self: *IFFParseBase, iff: *iffparse.IFFHandle, item: *iffparse.LocalContextItem, context: *iffparse.ContextNode) void {
        return libraries.call(self, LVO.StoreItemInContext, Fn.StoreItemInContext, .{ iff, item, context });
    }

    /// clipboard.device opened on `unit` (PRIMARY_CLIP), ready to be a
    /// handle's stream. Null if it could not be opened.
    pub fn OpenClipboard(self: *IFFParseBase, unit: u32) ?*iffparse.ClipboardHandle {
        return libraries.call(self, LVO.OpenClipboard, Fn.OpenClipboard, .{unit});
    }

    /// A clipboard handle given back. Null does nothing.
    pub fn CloseClipboard(self: *IFFParseBase, clip: ?*iffparse.ClipboardHandle) void {
        return libraries.call(self, LVO.CloseClipboard, Fn.CloseClipboard, .{clip});
    }

    /// Whether an id is four characters an IFF chunk may be named by:
    /// printable, and no leading space except for ID_NULL.
    pub fn GoodID(self: *IFFParseBase, id: u32) bool {
        return libraries.call(self, LVO.GoodID, Fn.GoodID, .{id});
    }

    /// Whether an id is four characters a generic chunk's type may be:
    /// GoodID, and upper case, digits or spaces only.
    pub fn GoodType(self: *IFFParseBase, form_type: u32) bool {
        return libraries.call(self, LVO.GoodType, Fn.GoodType, .{form_type});
    }

    /// An id written into `buf` as five bytes: its four characters and a
    /// NUL. `buf` again.
    pub fn IDtoStr(self: *IFFParseBase, id: u32, buf: *[5]u8) [*:0]u8 {
        return libraries.call(self, LVO.IDtoStr, Fn.IDtoStr, .{ id, buf });
    }
};
