// SPDX-License-Identifier: MIT
//! input.device's function, after BeginIO and AbortIO. The base is the
//! device's: io_Device of an open request.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/input_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "input.device";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const PeekQualifier = libraries.lvo(6);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const PeekQualifier = *const fn (*InputBase) callconv(.c) u32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const InputBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *InputBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The qualifiers as the device has them now: the shifts, Caps Lock,
    /// Control, the Alts and the Amiga keys, and the pointer's buttons.
    pub fn PeekQualifier(self: *InputBase) u32 {
        return libraries.call(self, LVO.PeekQualifier, Fn.PeekQualifier, .{});
    }
};
