// SPDX-License-Identifier: MIT
//! intuition.library's functions. So far the object system: classes made
//! and freed, objects made from them, and messages sent to those objects.
//! Every object's class is a Hook that is handed each message; a class
//! passes what it does not handle on to the class it was made from, up to
//! rootclass. Open it with OpenLibrary("intuition.library", 0).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/intuition_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const utility = @import("../libs/utility/utility.zig");
const graphics = @import("../libs/graphics/graphics.zig");
const intuition = @import("../libs/intuition/intuition.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "intuition.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const MakeClass = libraries.lvo(4);
    pub const FreeClass = libraries.lvo(5);
    pub const AddClass = libraries.lvo(6);
    pub const RemoveClass = libraries.lvo(7);
    pub const FindClass = libraries.lvo(8);
    pub const LockClassList = libraries.lvo(9);
    pub const UnlockClassList = libraries.lvo(10);
    pub const NewObjectTagList = libraries.lvo(11);
    pub const DisposeObject = libraries.lvo(12);
    pub const SetAttrsTagList = libraries.lvo(13);
    pub const GetAttr = libraries.lvo(14);
    pub const NextObject = libraries.lvo(15);
    pub const SendMessage = libraries.lvo(16);
    pub const SendSuperMessage = libraries.lvo(17);
    pub const CoerceMessage = libraries.lvo(18);
    pub const DrawImage = libraries.lvo(19);
    pub const DrawImageState = libraries.lvo(20);
    pub const EraseImage = libraries.lvo(21);
    pub const PointInImage = libraries.lvo(22);
    pub const OpenScreenTagList = libraries.lvo(23);
    pub const CloseScreen = libraries.lvo(24);
    pub const GetScreenAttrs = libraries.lvo(25);
    pub const ScreenToFront = libraries.lvo(26);
    pub const ScreenToBack = libraries.lvo(27);
    pub const GetScreenDrawInfo = libraries.lvo(28);
    pub const FreeScreenDrawInfo = libraries.lvo(29);
    pub const LockPubScreen = libraries.lvo(30);
    pub const UnlockPubScreen = libraries.lvo(31);
    pub const OpenWindowTagList = libraries.lvo(32);
    pub const CloseWindow = libraries.lvo(33);
    pub const GetWindowAttrs = libraries.lvo(34);
    pub const MoveWindow = libraries.lvo(35);
    pub const SizeWindow = libraries.lvo(36);
    pub const ChangeWindowBox = libraries.lvo(37);
    pub const WindowToFront = libraries.lvo(38);
    pub const WindowToBack = libraries.lvo(39);
    pub const ActivateWindow = libraries.lvo(40);
    pub const ModifyIDCMP = libraries.lvo(41);
    pub const BeginRefresh = libraries.lvo(42);
    pub const EndRefresh = libraries.lvo(43);
    pub const RefreshWindowFrame = libraries.lvo(44);
    pub const AddGList = libraries.lvo(45);
    pub const RemoveGList = libraries.lvo(46);
    pub const RefreshGList = libraries.lvo(47);
    pub const SetGadgetAttrsTagList = libraries.lvo(48);
    pub const ObtainGIRPort = libraries.lvo(49);
    pub const ReleaseGIRPort = libraries.lvo(50);
    pub const PrintIText = libraries.lvo(51);
    pub const DrawBorder = libraries.lvo(52);
    pub const IntuiTextLength = libraries.lvo(53);
    pub const LockIBase = libraries.lvo(54);
    pub const UnlockIBase = libraries.lvo(55);
    pub const ZipWindow = libraries.lvo(56);
    pub const SetWindowTitles = libraries.lvo(57);
    pub const WindowLimits = libraries.lvo(58);
    pub const OnGadget = libraries.lvo(59);
    pub const OffGadget = libraries.lvo(60);
    pub const EasyRequestArgs = libraries.lvo(61);
    pub const BuildEasyRequestArgs = libraries.lvo(62);
    pub const SysReqHandler = libraries.lvo(63);
    pub const FreeSysRequest = libraries.lvo(64);
    pub const SetMenuStrip = libraries.lvo(65);
    pub const ClearMenuStrip = libraries.lvo(66);
    pub const ResetMenuStrip = libraries.lvo(67);
    pub const ItemAddress = libraries.lvo(68);
    pub const OnMenu = libraries.lvo(69);
    pub const OffMenu = libraries.lvo(70);
    pub const LendMenus = libraries.lvo(71);
    pub const ActivateGadget = libraries.lvo(72);
    pub const DoGadgetMethodA = libraries.lvo(73);
    pub const InitRequester = libraries.lvo(74);
    pub const Request = libraries.lvo(75);
    pub const EndRequest = libraries.lvo(76);
    pub const SetDMRequest = libraries.lvo(77);
    pub const ClearDMRequest = libraries.lvo(78);
    pub const AutoRequestTagList = libraries.lvo(79);
    pub const BuildSysRequestTagList = libraries.lvo(80);
    pub const DoubleClick = libraries.lvo(81);
    pub const GetIMsg = libraries.lvo(82);
    pub const ReplyIMsg = libraries.lvo(83);
    pub const WaitIMsg = libraries.lvo(84);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const MakeClass = *const fn (*IntuitionBase, ?[*:0]const u8, ?[*:0]const u8, ?*intuition.Class, u32) callconv(.c) ?*intuition.Class;
    pub const FreeClass = *const fn (*IntuitionBase, ?*intuition.Class) callconv(.c) bool;
    pub const AddClass = *const fn (*IntuitionBase, *intuition.Class) callconv(.c) void;
    pub const RemoveClass = *const fn (*IntuitionBase, *intuition.Class) callconv(.c) void;
    pub const FindClass = *const fn (*IntuitionBase, [*:0]const u8) callconv(.c) ?*intuition.Class;
    pub const LockClassList = *const fn (*IntuitionBase) callconv(.c) *exec.MinList;
    pub const UnlockClassList = *const fn (*IntuitionBase) callconv(.c) void;
    pub const NewObjectTagList = *const fn (*IntuitionBase, ?*intuition.Class, ?[*:0]const u8, ?[*]const utility.TagItem) callconv(.c) ?*intuition.Object;
    pub const DisposeObject = *const fn (*IntuitionBase, ?*intuition.Object) callconv(.c) void;
    pub const SetAttrsTagList = *const fn (*IntuitionBase, ?*intuition.Object, ?[*]const utility.TagItem) callconv(.c) u32;
    pub const GetAttr = *const fn (*IntuitionBase, utility.Tag, ?*intuition.Object, *usize) callconv(.c) u32;
    pub const NextObject = *const fn (*IntuitionBase, *?*exec.MinNode) callconv(.c) ?*intuition.Object;
    pub const SendMessage = *const fn (*IntuitionBase, ?*intuition.Object, *intuition.Msg) callconv(.c) usize;
    pub const SendSuperMessage = *const fn (*IntuitionBase, *intuition.Class, ?*intuition.Object, *intuition.Msg) callconv(.c) usize;
    pub const CoerceMessage = *const fn (*IntuitionBase, *intuition.Class, ?*intuition.Object, *intuition.Msg) callconv(.c) usize;
    pub const DrawImage = *const fn (*IntuitionBase, *graphics.RastPort, ?*intuition.Object, i32, i32) callconv(.c) void;
    pub const DrawImageState = *const fn (*IntuitionBase, *graphics.RastPort, ?*intuition.Object, i32, i32, u32, ?*intuition.imageclass.DrawInfo) callconv(.c) void;
    pub const EraseImage = *const fn (*IntuitionBase, *graphics.RastPort, ?*intuition.Object, i32, i32) callconv(.c) void;
    pub const PointInImage = *const fn (*IntuitionBase, i32, i32, ?*intuition.Object) callconv(.c) bool;
    pub const OpenScreenTagList = *const fn (*IntuitionBase, ?[*]const utility.TagItem) callconv(.c) ?*intuition.Screen;
    pub const CloseScreen = *const fn (*IntuitionBase, ?*intuition.Screen) callconv(.c) bool;
    pub const GetScreenAttrs = *const fn (*IntuitionBase, *intuition.Screen, ?[*]const utility.TagItem) callconv(.c) void;
    pub const ScreenToFront = *const fn (*IntuitionBase, *intuition.Screen) callconv(.c) void;
    pub const ScreenToBack = *const fn (*IntuitionBase, *intuition.Screen) callconv(.c) void;
    pub const GetScreenDrawInfo = *const fn (*IntuitionBase, *intuition.Screen) callconv(.c) *intuition.DrawInfo;
    pub const FreeScreenDrawInfo = *const fn (*IntuitionBase, *intuition.Screen, ?*intuition.DrawInfo) callconv(.c) void;
    pub const LockPubScreen = *const fn (*IntuitionBase, ?[*:0]const u8) callconv(.c) ?*intuition.Screen;
    pub const UnlockPubScreen = *const fn (*IntuitionBase, ?[*:0]const u8, ?*intuition.Screen) callconv(.c) void;
    pub const OpenWindowTagList = *const fn (*IntuitionBase, ?[*]const utility.TagItem) callconv(.c) ?*intuition.Window;
    pub const CloseWindow = *const fn (*IntuitionBase, ?*intuition.Window) callconv(.c) void;
    pub const GetWindowAttrs = *const fn (*IntuitionBase, *intuition.Window, ?[*]const utility.TagItem) callconv(.c) void;
    pub const MoveWindow = *const fn (*IntuitionBase, *intuition.Window, i32, i32) callconv(.c) void;
    pub const SizeWindow = *const fn (*IntuitionBase, *intuition.Window, i32, i32) callconv(.c) void;
    pub const ChangeWindowBox = *const fn (*IntuitionBase, *intuition.Window, i32, i32, i32, i32) callconv(.c) void;
    pub const WindowToFront = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const WindowToBack = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const ActivateWindow = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const ModifyIDCMP = *const fn (*IntuitionBase, *intuition.Window, u32) callconv(.c) bool;
    pub const BeginRefresh = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const EndRefresh = *const fn (*IntuitionBase, *intuition.Window, bool) callconv(.c) void;
    pub const RefreshWindowFrame = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const AddGList = *const fn (*IntuitionBase, *intuition.Window, *intuition.Object, i32, i32) callconv(.c) u32;
    pub const RemoveGList = *const fn (*IntuitionBase, *intuition.Window, *intuition.Object, i32) callconv(.c) i32;
    pub const RefreshGList = *const fn (*IntuitionBase, *intuition.Object, *intuition.Window, i32) callconv(.c) void;
    pub const SetGadgetAttrsTagList = *const fn (*IntuitionBase, *intuition.Object, ?*intuition.Window, ?[*]const utility.TagItem) callconv(.c) usize;
    pub const ObtainGIRPort = *const fn (*IntuitionBase, ?*intuition.GadgetInfo) callconv(.c) ?*graphics.RastPort;
    pub const ReleaseGIRPort = *const fn (*IntuitionBase, ?*graphics.RastPort) callconv(.c) void;
    pub const PrintIText = *const fn (*IntuitionBase, *graphics.RastPort, ?*const intuition.IntuiText, i32, i32) callconv(.c) void;
    pub const DrawBorder = *const fn (*IntuitionBase, *graphics.RastPort, ?*const intuition.Border, i32, i32) callconv(.c) void;
    pub const IntuiTextLength = *const fn (*IntuitionBase, *const intuition.IntuiText) callconv(.c) i32;
    pub const LockIBase = *const fn (*IntuitionBase, u32) callconv(.c) u32;
    pub const UnlockIBase = *const fn (*IntuitionBase, u32) callconv(.c) void;
    pub const ZipWindow = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const SetWindowTitles = *const fn (*IntuitionBase, *intuition.Window, ?[*:0]const u8, ?[*:0]const u8) callconv(.c) void;
    pub const WindowLimits = *const fn (*IntuitionBase, *intuition.Window, i32, i32, i32, i32) callconv(.c) bool;
    pub const OnGadget = *const fn (*IntuitionBase, *intuition.Object, *intuition.Window, ?*intuition.Requester) callconv(.c) void;
    pub const OffGadget = *const fn (*IntuitionBase, *intuition.Object, *intuition.Window, ?*intuition.Requester) callconv(.c) void;
    pub const EasyRequestArgs = *const fn (*IntuitionBase, ?*intuition.Window, *const intuition.EasyStruct, ?*u32, ?*const anyopaque) callconv(.c) i32;
    pub const BuildEasyRequestArgs = *const fn (*IntuitionBase, ?*intuition.Window, *const intuition.EasyStruct, u32, ?*const anyopaque) callconv(.c) ?*intuition.Window;
    pub const SysReqHandler = *const fn (*IntuitionBase, ?*intuition.Window, ?*u32, bool) callconv(.c) i32;
    pub const FreeSysRequest = *const fn (*IntuitionBase, ?*intuition.Window) callconv(.c) void;
    pub const SetMenuStrip = *const fn (*IntuitionBase, *intuition.Window, *intuition.Menu) callconv(.c) bool;
    pub const ClearMenuStrip = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) void;
    pub const ResetMenuStrip = *const fn (*IntuitionBase, *intuition.Window, *intuition.Menu) callconv(.c) bool;
    pub const ItemAddress = *const fn (*IntuitionBase, ?*intuition.Menu, u32) callconv(.c) ?*intuition.MenuItem;
    pub const OnMenu = *const fn (*IntuitionBase, *intuition.Window, u32) callconv(.c) void;
    pub const OffMenu = *const fn (*IntuitionBase, *intuition.Window, u32) callconv(.c) void;
    pub const LendMenus = *const fn (*IntuitionBase, *intuition.Window, ?*intuition.Window) callconv(.c) void;
    pub const ActivateGadget = *const fn (*IntuitionBase, *intuition.Object, *intuition.Window, ?*intuition.Requester) callconv(.c) bool;
    pub const DoGadgetMethodA = *const fn (*IntuitionBase, *intuition.Object, ?*intuition.Window, ?*intuition.Requester, *intuition.Msg) callconv(.c) usize;
    pub const InitRequester = *const fn (*IntuitionBase, *intuition.Requester) callconv(.c) void;
    pub const Request = *const fn (*IntuitionBase, *intuition.Requester, *intuition.Window) callconv(.c) bool;
    pub const EndRequest = *const fn (*IntuitionBase, *intuition.Requester, *intuition.Window) callconv(.c) void;
    pub const SetDMRequest = *const fn (*IntuitionBase, *intuition.Window, *intuition.Requester) callconv(.c) bool;
    pub const ClearDMRequest = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) bool;
    pub const AutoRequestTagList = *const fn (*IntuitionBase, ?*intuition.Window, ?[*]const utility.TagItem) callconv(.c) bool;
    pub const BuildSysRequestTagList = *const fn (*IntuitionBase, ?*intuition.Window, ?[*]const utility.TagItem) callconv(.c) ?*intuition.Window;
    pub const DoubleClick = *const fn (*IntuitionBase, u32, u32, u32, u32) callconv(.c) bool;
    pub const GetIMsg = *const fn (*IntuitionBase, *intuition.Window) callconv(.c) ?*intuition.IntuiMessage;
    pub const ReplyIMsg = *const fn (*IntuitionBase, *intuition.IntuiMessage) callconv(.c) void;
    pub const WaitIMsg = *const fn (*IntuitionBase, *intuition.Window, u32) callconv(.c) u32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const IntuitionBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *IntuitionBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A new class made from a superclass, named `class_id`, or private when
    /// that is null. The superclass is the public one named `super_id`, or
    /// else `super_class`; only rootclass has neither. Null if the name is
    /// taken, the superclass is not found, or there is no memory. The class
    /// comes back with a dispatcher that answers 0 to everything and off the
    /// public list: set its dispatcher, then AddClass it if it is public.
    pub fn MakeClass(self: *IntuitionBase, class_id: ?[*:0]const u8, super_id: ?[*:0]const u8, super_class: ?*intuition.Class, inst_size: u32) ?*intuition.Class {
        return libraries.call(self, LVO.MakeClass, Fn.MakeClass, .{ class_id, super_id, super_class, inst_size });
    }

    /// Take a class off the public list and free it. False, with the class
    /// off the list and still there, while it has objects or subclasses. Null
    /// is true.
    pub fn FreeClass(self: *IntuitionBase, cl: ?*intuition.Class) bool {
        return libraries.call(self, LVO.FreeClass, Fn.FreeClass, .{cl});
    }

    /// Put a named class on the public list. A private one, or one already
    /// there, is left alone.
    pub fn AddClass(self: *IntuitionBase, cl: *intuition.Class) void {
        return libraries.call(self, LVO.AddClass, Fn.AddClass, .{cl});
    }

    /// Take a class off the public list. One not on it is left alone.
    pub fn RemoveClass(self: *IntuitionBase, cl: *intuition.Class) void {
        return libraries.call(self, LVO.RemoveClass, Fn.RemoveClass, .{cl});
    }

    /// The public class of that name, or null.
    pub fn FindClass(self: *IntuitionBase, class_id: [*:0]const u8) ?*intuition.Class {
        return libraries.call(self, LVO.FindClass, Fn.FindClass, .{class_id});
    }

    /// Hold the public class list, and answer it. Nothing is added to it or
    /// taken off it until UnlockClassList.
    pub fn LockClassList(self: *IntuitionBase) *exec.MinList {
        return libraries.call(self, LVO.LockClassList, Fn.LockClassList, .{});
    }

    /// Let the public class list go again.
    pub fn UnlockClassList(self: *IntuitionBase) void {
        return libraries.call(self, LVO.UnlockClassList, Fn.UnlockClassList, .{});
    }

    /// A new object of the class `cl`, or of the public class named
    /// `class_id` when `cl` is null, with `tags` as its first attributes.
    /// Null if there is no such class, or it would not make one.
    pub fn NewObjectTagList(self: *IntuitionBase, cl: ?*intuition.Class, class_id: ?[*:0]const u8, tags: ?[*]const utility.TagItem) ?*intuition.Object {
        return libraries.call(self, LVO.NewObjectTagList, Fn.NewObjectTagList, .{ cl, class_id, tags });
    }

    /// Free an object, and what its classes had it hold. Null does nothing.
    pub fn DisposeObject(self: *IntuitionBase, object: ?*intuition.Object) void {
        return libraries.call(self, LVO.DisposeObject, Fn.DisposeObject, .{object});
    }

    /// Change an object's attributes. Nonzero when something that shows
    /// changed, as its class decides.
    pub fn SetAttrsTagList(self: *IntuitionBase, object: ?*intuition.Object, tags: ?[*]const utility.TagItem) u32 {
        return libraries.call(self, LVO.SetAttrsTagList, Fn.SetAttrsTagList, .{ object, tags });
    }

    /// Read one attribute into `storage`. 0 when its class does not know it.
    pub fn GetAttr(self: *IntuitionBase, attr_id: utility.Tag, object: ?*intuition.Object, storage: *usize) u32 {
        return libraries.call(self, LVO.GetAttr, Fn.GetAttr, .{ attr_id, object, storage });
    }

    /// The next object on a list of objects (OM_ADDTAIL), from a node pointer
    /// that starts at the list's head and is moved along. Null at the end.
    pub fn NextObject(self: *IntuitionBase, state: *?*exec.MinNode) ?*intuition.Object {
        return libraries.call(self, LVO.NextObject, Fn.NextObject, .{state});
    }

    /// Send a message to an object, to be handled by its own class. 0 for a
    /// null object; otherwise whatever the class answers.
    pub fn SendMessage(self: *IntuitionBase, object: ?*intuition.Object, msg: *intuition.Msg) usize {
        return libraries.call(self, LVO.SendMessage, Fn.SendMessage, .{ object, msg });
    }

    /// Send a message to an object as `cl`'s superclass would handle it: how
    /// a dispatcher passes on what it does not handle itself.
    pub fn SendSuperMessage(self: *IntuitionBase, cl: *intuition.Class, object: ?*intuition.Object, msg: *intuition.Msg) usize {
        return libraries.call(self, LVO.SendSuperMessage, Fn.SendSuperMessage, .{ cl, object, msg });
    }

    /// Send a message to an object as `cl` would handle it, whatever the
    /// object's own class is.
    pub fn CoerceMessage(self: *IntuitionBase, cl: *intuition.Class, object: ?*intuition.Object, msg: *intuition.Msg) usize {
        return libraries.call(self, LVO.CoerceMessage, Fn.CoerceMessage, .{ cl, object, msg });
    }

    /// Draw an image at (left, top) in the RastPort, added to the image's own
    /// left and top: IM_DRAW in the normal state. Null does nothing.
    pub fn DrawImage(self: *IntuitionBase, rp: *graphics.RastPort, image: ?*intuition.Object, left: i32, top: i32) void {
        return libraries.call(self, LVO.DrawImage, Fn.DrawImage, .{ rp, image, left, top });
    }

    /// The same in a state (IDS_), with a screen's pens where the image wants
    /// them (may be null).
    pub fn DrawImageState(self: *IntuitionBase, rp: *graphics.RastPort, image: ?*intuition.Object, left: i32, top: i32, state: u32, draw_info: ?*intuition.imageclass.DrawInfo) void {
        return libraries.call(self, LVO.DrawImageState, Fn.DrawImageState, .{ rp, image, left, top, state, draw_info });
    }

    /// Clear what an image covers at (left, top): IM_ERASE. Null does nothing.
    pub fn EraseImage(self: *IntuitionBase, rp: *graphics.RastPort, image: ?*intuition.Object, left: i32, top: i32) void {
        return libraries.call(self, LVO.EraseImage, Fn.EraseImage, .{ rp, image, left, top });
    }

    /// Whether a point is in an image, in the coordinates of its left and top:
    /// IM_HITTEST. A null image contains every point.
    pub fn PointInImage(self: *IntuitionBase, x: i32, y: i32, image: ?*intuition.Object) bool {
        return libraries.call(self, LVO.PointInImage, Fn.PointInImage, .{ x, y, image });
    }

    /// A screen on a display: its whole size, its own buffer, a title bar and
    /// the pens and font its parts are drawn in (SA_ tags). Null, with the
    /// reason in SA_ErrorCode, when there is no display, the display already
    /// shows a screen, the public name is taken, or there is no memory.
    pub fn OpenScreenTagList(self: *IntuitionBase, tags: ?[*]const utility.TagItem) ?*intuition.Screen {
        return libraries.call(self, LVO.OpenScreenTagList, Fn.OpenScreenTagList, .{tags});
    }

    /// Close a screen. False, and it stays open, while a public screen is
    /// locked by anyone. Null is true.
    pub fn CloseScreen(self: *IntuitionBase, screen: ?*intuition.Screen) bool {
        return libraries.call(self, LVO.CloseScreen, Fn.CloseScreen, .{screen});
    }

    /// Read a screen: each tag's data is a *usize the value is written to.
    pub fn GetScreenAttrs(self: *IntuitionBase, screen: *intuition.Screen, tags: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.GetScreenAttrs, Fn.GetScreenAttrs, .{ screen, tags });
    }

    /// Bring a screen in front of the others on its display. A display shows
    /// one screen, so there is nothing to change yet.
    pub fn ScreenToFront(self: *IntuitionBase, screen: *intuition.Screen) void {
        return libraries.call(self, LVO.ScreenToFront, Fn.ScreenToFront, .{screen});
    }

    /// Put a screen behind the others on its display. The same.
    pub fn ScreenToBack(self: *IntuitionBase, screen: *intuition.Screen) void {
        return libraries.call(self, LVO.ScreenToBack, Fn.ScreenToBack, .{screen});
    }

    /// The pens and font a screen's parts are drawn in. Give it back with
    /// FreeScreenDrawInfo.
    pub fn GetScreenDrawInfo(self: *IntuitionBase, screen: *intuition.Screen) *intuition.DrawInfo {
        return libraries.call(self, LVO.GetScreenDrawInfo, Fn.GetScreenDrawInfo, .{screen});
    }

    /// Give back what GetScreenDrawInfo handed out. Null does nothing.
    pub fn FreeScreenDrawInfo(self: *IntuitionBase, screen: *intuition.Screen, draw_info: ?*intuition.DrawInfo) void {
        return libraries.call(self, LVO.FreeScreenDrawInfo, Fn.FreeScreenDrawInfo, .{ screen, draw_info });
    }

    /// A public screen by name, kept open until UnlockPubScreen. Null names
    /// the default public screen, which is opened if it is not open yet.
    /// Null if there is no such screen.
    pub fn LockPubScreen(self: *IntuitionBase, name: ?[*:0]const u8) ?*intuition.Screen {
        return libraries.call(self, LVO.LockPubScreen, Fn.LockPubScreen, .{name});
    }

    /// Let a locked public screen go: `screen` if given, else the one named.
    pub fn UnlockPubScreen(self: *IntuitionBase, name: ?[*:0]const u8, screen: ?*intuition.Screen) void {
        return libraries.call(self, LVO.UnlockPubScreen, Fn.UnlockPubScreen, .{ name, screen });
    }

    /// A window on a screen (WA_ tags): a layer with a border, and a message
    /// port when WA_IDCMP asks for one. Null if there is no screen to open it
    /// on, or no memory.
    pub fn OpenWindowTagList(self: *IntuitionBase, tags: ?[*]const utility.TagItem) ?*intuition.Window {
        return libraries.call(self, LVO.OpenWindowTagList, Fn.OpenWindowTagList, .{tags});
    }

    /// Close a window: its layer, its border, and its port with any messages
    /// still waiting on it. Null does nothing.
    pub fn CloseWindow(self: *IntuitionBase, window: ?*intuition.Window) void {
        return libraries.call(self, LVO.CloseWindow, Fn.CloseWindow, .{window});
    }

    /// Read a window: each tag's data is a *usize the value is written to.
    pub fn GetWindowAttrs(self: *IntuitionBase, window: *intuition.Window, tags: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.GetWindowAttrs, Fn.GetWindowAttrs, .{ window, tags });
    }

    /// Move a window by (dx, dy), kept on its screen.
    pub fn MoveWindow(self: *IntuitionBase, window: *intuition.Window, dx: i32, dy: i32) void {
        return libraries.call(self, LVO.MoveWindow, Fn.MoveWindow, .{ window, dx, dy });
    }

    /// Size a window by (dw, dh), kept within its limits and its screen.
    pub fn SizeWindow(self: *IntuitionBase, window: *intuition.Window, dw: i32, dh: i32) void {
        return libraries.call(self, LVO.SizeWindow, Fn.SizeWindow, .{ window, dw, dh });
    }

    /// Move and size a window at once, to an absolute box.
    pub fn ChangeWindowBox(self: *IntuitionBase, window: *intuition.Window, left: i32, top: i32, width: i32, height: i32) void {
        return libraries.call(self, LVO.ChangeWindowBox, Fn.ChangeWindowBox, .{ window, left, top, width, height });
    }

    /// Bring a window in front of the others on its screen.
    pub fn WindowToFront(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.WindowToFront, Fn.WindowToFront, .{window});
    }

    /// Put a window behind the others on its screen.
    pub fn WindowToBack(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.WindowToBack, Fn.WindowToBack, .{window});
    }

    /// Make a window the active one: its border is drawn in the fill pen, and
    /// the one it takes over from is told.
    pub fn ActivateWindow(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.ActivateWindow, Fn.ActivateWindow, .{window});
    }

    /// Change which IDCMP classes a window is told about. 0 takes its port
    /// away; from 0, it gets one. False if a port could not be made.
    pub fn ModifyIDCMP(self: *IntuitionBase, window: *intuition.Window, flags: u32) bool {
        return libraries.call(self, LVO.ModifyIDCMP, Fn.ModifyIDCMP, .{ window, flags });
    }

    /// Begin redrawing what IDCMP_REFRESHWINDOW reported: until EndRefresh,
    /// drawing reaches only the part that needs it.
    pub fn BeginRefresh(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.BeginRefresh, Fn.BeginRefresh, .{window});
    }

    /// End it. `complete` false keeps the damage for another BeginRefresh.
    pub fn EndRefresh(self: *IntuitionBase, window: *intuition.Window, complete: bool) void {
        return libraries.call(self, LVO.EndRefresh, Fn.EndRefresh, .{ window, complete });
    }

    /// Draw a window's border again.
    pub fn RefreshWindowFrame(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.RefreshWindowFrame, Fn.RefreshWindowFrame, .{window});
    }

    /// Put `count` gadgets (-1: all, following their links) into a window's
    /// list after `position` of its own (-1: at the end). Answers where they
    /// went. Nothing is drawn: RefreshGList does that.
    pub fn AddGList(self: *IntuitionBase, window: *intuition.Window, gadget: *intuition.Object, position: i32, count: i32) u32 {
        return libraries.call(self, LVO.AddGList, Fn.AddGList, .{ window, gadget, position, count });
    }

    /// Take `count` gadgets (-1: the rest of the list) out of a window, from
    /// `gadget` on. Answers the position it had, or -1 if it was not there.
    pub fn RemoveGList(self: *IntuitionBase, window: *intuition.Window, gadget: *intuition.Object, count: i32) i32 {
        return libraries.call(self, LVO.RemoveGList, Fn.RemoveGList, .{ window, gadget, count });
    }

    /// Draw `count` gadgets of a window (-1: the rest of the list) from
    /// `gadget` on.
    pub fn RefreshGList(self: *IntuitionBase, gadget: *intuition.Object, window: *intuition.Window, count: i32) void {
        return libraries.call(self, LVO.RefreshGList, Fn.RefreshGList, .{ gadget, window, count });
    }

    /// OM_SET on a gadget, told its window so it can show the change. Answers
    /// what OM_SET answered.
    pub fn SetGadgetAttrsTagList(self: *IntuitionBase, gadget: *intuition.Object, window: ?*intuition.Window, tags: ?[*]const utility.TagItem) usize {
        return libraries.call(self, LVO.SetGadgetAttrsTagList, Fn.SetGadgetAttrsTagList, .{ gadget, window, tags });
    }

    /// The RastPort of a gadget's window, its layer held, for drawing; null
    /// for a null GadgetInfo. Give it back with ReleaseGIRPort.
    pub fn ObtainGIRPort(self: *IntuitionBase, gadget_info: ?*intuition.GadgetInfo) ?*graphics.RastPort {
        return libraries.call(self, LVO.ObtainGIRPort, Fn.ObtainGIRPort, .{gadget_info});
    }

    /// Give back what ObtainGIRPort lent.
    pub fn ReleaseGIRPort(self: *IntuitionBase, rp: ?*graphics.RastPort) void {
        return libraries.call(self, LVO.ReleaseGIRPort, Fn.ReleaseGIRPort, .{rp});
    }

    /// Draw a run of text and every run linked after it, at (left, top) added
    /// to each run's own place, in its pens, draw mode and font. The
    /// RastPort keeps its own pens, mode and font. Null does nothing.
    pub fn PrintIText(self: *IntuitionBase, rp: *graphics.RastPort, itext: ?*const intuition.IntuiText, left: i32, top: i32) void {
        return libraries.call(self, LVO.PrintIText, Fn.PrintIText, .{ rp, itext, left, top });
    }

    /// Draw a line through a Border's points and every Border linked after
    /// it, at (left, top) added to each one's own place, in its pens and draw
    /// mode. The RastPort keeps its own. Null does nothing.
    pub fn DrawBorder(self: *IntuitionBase, rp: *graphics.RastPort, border: ?*const intuition.Border, left: i32, top: i32) void {
        return libraries.call(self, LVO.DrawBorder, Fn.DrawBorder, .{ rp, border, left, top });
    }

    /// How wide one run of text is in pixels, in its own font or, without
    /// one, in the font a screen has when it is given none. The runs linked
    /// after it are not counted.
    pub fn IntuiTextLength(self: *IntuitionBase, itext: *const intuition.IntuiText) i32 {
        return libraries.call(self, LVO.IntuiTextLength, Fn.IntuiTextLength, .{itext});
    }

    /// Hold the screens, their windows and which one is active, so that
    /// several reads of them agree. Answers what to hand to UnlockIBase.
    pub fn LockIBase(self: *IntuitionBase, lock_number: u32) u32 {
        return libraries.call(self, LVO.LockIBase, Fn.LockIBase, .{lock_number});
    }

    /// Let go what LockIBase took.
    pub fn UnlockIBase(self: *IntuitionBase, lock_number: u32) void {
        return libraries.call(self, LVO.UnlockIBase, Fn.UnlockIBase, .{lock_number});
    }

    /// Flip a window to its other box and back: the one WA_Zoom gave it, or
    /// its smallest or largest size, as its zoom gadget does.
    pub fn ZipWindow(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.ZipWindow, Fn.ZipWindow, .{window});
    }

    /// Change a window's title and the screen title it shows while active.
    /// TITLE_UNCHANGED leaves either as it is; null clears it.
    pub fn SetWindowTitles(self: *IntuitionBase, window: *intuition.Window, window_title: ?[*:0]const u8, screen_title: ?[*:0]const u8) void {
        return libraries.call(self, LVO.SetWindowTitles, Fn.SetWindowTitles, .{ window, window_title, screen_title });
    }

    /// Set the smallest and largest a window may be sized to. 0 leaves a limit
    /// as it is and a negative maximum is the screen's size. False, with the
    /// others taken, when a limit would not fit the size it has now.
    pub fn WindowLimits(self: *IntuitionBase, window: *intuition.Window, min_width: i32, min_height: i32, max_width: i32, max_height: i32) bool {
        return libraries.call(self, LVO.WindowLimits, Fn.WindowLimits, .{ window, min_width, min_height, max_width, max_height });
    }

    /// Let a gadget be pressed again, and show it so: one of the window's own,
    /// or with `requester` one of that requester's.
    pub fn OnGadget(self: *IntuitionBase, gadget: *intuition.Object, window: *intuition.Window, requester: ?*intuition.Requester) void {
        return libraries.call(self, LVO.OnGadget, Fn.OnGadget, .{ gadget, window, requester });
    }

    /// Keep a gadget from being pressed, and show it so: one of the window's
    /// own, or with `requester` one of that requester's.
    pub fn OffGadget(self: *IntuitionBase, gadget: *intuition.Object, window: *intuition.Window, requester: ?*intuition.Requester) void {
        return libraries.call(self, LVO.OffGadget, Fn.OffGadget, .{ gadget, window, requester });
    }

    /// Ask something and wait for the answer: a requester window with the
    /// message and its buttons (EasyStruct), formatted from `args`, on the
    /// window's screen or the default public one. 1, 2, ... for the buttons
    /// from the left and 0 for the rightmost; -1 when one of `*idcmp_ptr`'s
    /// classes arrived, with the class written back there.
    pub fn EasyRequestArgs(self: *IntuitionBase, window: ?*intuition.Window, easy_struct: *const intuition.EasyStruct, idcmp_ptr: ?*u32, args: ?*const anyopaque) i32 {
        return libraries.call(self, LVO.EasyRequestArgs, Fn.EasyRequestArgs, .{ window, easy_struct, idcmp_ptr, args });
    }

    /// The same requester, opened and handed back to be answered with
    /// SysReqHandler and closed with FreeSysRequest. Null when it could not be
    /// made; a process's IoErr then says why.
    pub fn BuildEasyRequestArgs(self: *IntuitionBase, window: ?*intuition.Window, easy_struct: *const intuition.EasyStruct, idcmp: u32, args: ?*const anyopaque) ?*intuition.Window {
        return libraries.call(self, LVO.BuildEasyRequestArgs, Fn.BuildEasyRequestArgs, .{ window, easy_struct, idcmp, args });
    }

    /// Read what arrived at a requester: a button's answer, -1 for one of the
    /// caller's IDCMP classes, or -2 when nothing answered it. With
    /// `wait_input` it waits for something first. Null answers 0.
    pub fn SysReqHandler(self: *IntuitionBase, window: ?*intuition.Window, idcmp_ptr: ?*u32, wait_input: bool) i32 {
        return libraries.call(self, LVO.SysReqHandler, Fn.SysReqHandler, .{ window, idcmp_ptr, wait_input });
    }

    /// Close a requester BuildEasyRequestArgs opened, and free what it made.
    /// Null does nothing.
    pub fn FreeSysRequest(self: *IntuitionBase, window: ?*intuition.Window) void {
        return libraries.call(self, LVO.FreeSysRequest, Fn.FreeSysRequest, .{window});
    }

    /// Give a window its menus: a strip of Menus the program keeps, laid out
    /// here from the items it holds. Always true.
    pub fn SetMenuStrip(self: *IntuitionBase, window: *intuition.Window, menu_strip: *intuition.Menu) bool {
        return libraries.call(self, LVO.SetMenuStrip, Fn.SetMenuStrip, .{ window, menu_strip });
    }

    /// Take a window's menus away, before the strip is changed or freed and
    /// before the window closes.
    pub fn ClearMenuStrip(self: *IntuitionBase, window: *intuition.Window) void {
        return libraries.call(self, LVO.ClearMenuStrip, Fn.ClearMenuStrip, .{window});
    }

    /// Give a window back the strip it had, changed only in which items are
    /// checked or enabled, without laying it out again. Always true.
    pub fn ResetMenuStrip(self: *IntuitionBase, window: *intuition.Window, menu_strip: *intuition.Menu) bool {
        return libraries.call(self, LVO.ResetMenuStrip, Fn.ResetMenuStrip, .{ window, menu_strip });
    }

    /// The item or subitem a menu number names in a strip, or null for a
    /// number that names only a title, or none.
    pub fn ItemAddress(self: *IntuitionBase, menu_strip: ?*intuition.Menu, menu_number: u32) ?*intuition.MenuItem {
        return libraries.call(self, LVO.ItemAddress, Fn.ItemAddress, .{ menu_strip, menu_number });
    }

    /// Let a menu, an item or a subitem be picked again, by its menu number.
    pub fn OnMenu(self: *IntuitionBase, window: *intuition.Window, menu_number: u32) void {
        return libraries.call(self, LVO.OnMenu, Fn.OnMenu, .{ window, menu_number });
    }

    /// Keep a menu, an item or a subitem from being picked, by its menu
    /// number: it is shown ghosted.
    pub fn OffMenu(self: *IntuitionBase, window: *intuition.Window, menu_number: u32) void {
        return libraries.call(self, LVO.OffMenu, Fn.OffMenu, .{ window, menu_number });
    }

    /// Make the menu button in one window show another window's menus, as
    /// though that window were active; null undoes it.
    pub fn LendMenus(self: *IntuitionBase, from_window: *intuition.Window, to_window: ?*intuition.Window) void {
        return libraries.call(self, LVO.LendMenus, Fn.LendMenus, .{ from_window, to_window });
    }

    /// Give a gadget of the active window the input without it being pressed,
    /// as a click would: a line of text takes the keys at once. False when
    /// the window is not active, something else has the input, or the gadget
    /// declines. With a requester up only its gadgets may be, and `requester`
    /// names it.
    pub fn ActivateGadget(self: *IntuitionBase, gadget: *intuition.Object, window: *intuition.Window, requester: ?*intuition.Requester) bool {
        return libraries.call(self, LVO.ActivateGadget, Fn.ActivateGadget, .{ gadget, window, requester });
    }

    /// Send a gadget a method with a GadgetInfo for its window filled in, so
    /// it can draw or lay itself out - measured in `requester` for one of its
    /// gadgets. What the method answers.
    pub fn DoGadgetMethodA(self: *IntuitionBase, gadget: *intuition.Object, window: ?*intuition.Window, requester: ?*intuition.Requester, message: *intuition.Msg) usize {
        return libraries.call(self, LVO.DoGadgetMethodA, Fn.DoGadgetMethodA, .{ gadget, window, requester, message });
    }

    /// Clear a Requester to be filled in.
    pub fn InitRequester(self: *IntuitionBase, requester: *intuition.Requester) void {
        return libraries.call(self, LVO.InitRequester, Fn.InitRequester, .{requester});
    }

    /// Put a requester up in a window: in front of it, its gadgets the only
    /// ones pressed until it comes down. The window gets IDCMP_REQSET. False
    /// when there was no memory for it.
    pub fn Request(self: *IntuitionBase, requester: *intuition.Requester, window: *intuition.Window) bool {
        return libraries.call(self, LVO.Request, Fn.Request, .{ requester, window });
    }

    /// Take a requester down, wherever it is in the window's stack. The window
    /// gets IDCMP_REQCLEAR.
    pub fn EndRequest(self: *IntuitionBase, requester: *intuition.Requester, window: *intuition.Window) void {
        return libraries.call(self, LVO.EndRequest, Fn.EndRequest, .{ requester, window });
    }

    /// The requester a double-click of the menu button puts up in the window.
    /// False, and nothing changed, while the one it has is up.
    pub fn SetDMRequest(self: *IntuitionBase, window: *intuition.Window, requester: *intuition.Requester) bool {
        return libraries.call(self, LVO.SetDMRequest, Fn.SetDMRequest, .{ window, requester });
    }

    /// No double-click requester any more. False while the one it has is up.
    pub fn ClearDMRequest(self: *IntuitionBase, window: *intuition.Window) bool {
        return libraries.call(self, LVO.ClearDMRequest, Fn.ClearDMRequest, .{window});
    }

    /// Ask with two buttons made from IntuiTexts and wait - the texts and the
    /// IDCMP classes that answer it in SYSREQ_ tags: true for the left button
    /// or a class of SYSREQ_PositiveFlags, false for the right one, a class of
    /// SYSREQ_NegativeFlags, or when it could not be made.
    pub fn AutoRequestTagList(self: *IntuitionBase, window: ?*intuition.Window, tags: ?[*]const utility.TagItem) bool {
        return libraries.call(self, LVO.AutoRequestTagList, Fn.AutoRequestTagList, .{ window, tags });
    }

    /// The requester AutoRequestTagList waits on, opened and handed back to be
    /// answered with SysReqHandler and closed with FreeSysRequest: 1 for the
    /// left button, 0 for the right. Null when it could not be made.
    pub fn BuildSysRequestTagList(self: *IntuitionBase, window: ?*intuition.Window, tags: ?[*]const utility.TagItem) ?*intuition.Window {
        return libraries.call(self, LVO.BuildSysRequestTagList, Fn.BuildSysRequestTagList, .{ window, tags });
    }

    /// Whether two moments are close enough together to be a double-click.
    pub fn DoubleClick(self: *IntuitionBase, start_seconds: u32, start_micros: u32, current_seconds: u32, current_micros: u32) bool {
        return libraries.call(self, LVO.DoubleClick, Fn.DoubleClick, .{ start_seconds, start_micros, current_seconds, current_micros });
    }

    /// The next message on a window's port, taken off it, or null when there
    /// is none or the window has no port. Never waits.
    pub fn GetIMsg(self: *IntuitionBase, window: *intuition.Window) ?*intuition.IntuiMessage {
        return libraries.call(self, LVO.GetIMsg, Fn.GetIMsg, .{window});
    }

    /// Hand a message from GetIMsg back.
    pub fn ReplyIMsg(self: *IntuitionBase, msg: *intuition.IntuiMessage) void {
        return libraries.call(self, LVO.ReplyIMsg, Fn.ReplyIMsg, .{msg});
    }

    /// Wait until the window has a message or a signal in `others` arrives,
    /// and answer the signals received.
    pub fn WaitIMsg(self: *IntuitionBase, window: *intuition.Window, others: u32) u32 {
        return libraries.call(self, LVO.WaitIMsg, Fn.WaitIMsg, .{ window, others });
    }
};
