// SPDX-License-Identifier: MIT
//! jpeg.resource's functions: the chip's JPEG codec, decoding a file into
//! pixels (sdk/resources/jpeg.zig). A resource: no Open or Close, its
//! first function in the first slot. The base comes from
//! OpenResource("jpeg.resource").
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/jpeg_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const jpeg = @import("../resources/jpeg.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "jpeg.resource";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const ExamineJPEG = libraries.lvo(0);
    pub const DecodeJPEG = libraries.lvo(1);
    pub const FreeJPEGPicture = libraries.lvo(2);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const ExamineJPEG = *const fn (*JpegBase, [*]const u8, u32, *jpeg.JPEGInfo) callconv(.c) u32;
    pub const DecodeJPEG = *const fn (*JpegBase, [*]const u8, u32, *jpeg.JPEGPicture) callconv(.c) u32;
    pub const FreeJPEGPicture = *const fn (*JpegBase, *jpeg.JPEGPicture) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const JpegBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *JpegBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// What the `length` bytes at `file` are and whether the codec decodes
    /// them: JPEGERR_OK and `info` filled in, or why not. Reads only.
    pub fn ExamineJPEG(self: *JpegBase, file: [*]const u8, length: u32, info: *jpeg.JPEGInfo) u32 {
        return libraries.call(self, LVO.ExamineJPEG, Fn.ExamineJPEG, .{ file, length, info });
    }

    /// The file decoded into a picture the resource allocates: JPEGERR_OK and
    /// `picture` filled in, or why not. Waits for the codec. Not from
    /// interrupts.
    pub fn DecodeJPEG(self: *JpegBase, file: [*]const u8, length: u32, picture: *jpeg.JPEGPicture) u32 {
        return libraries.call(self, LVO.DecodeJPEG, Fn.DecodeJPEG, .{ file, length, picture });
    }

    /// A picture DecodeJPEG made given back; one never made, or given back
    /// already, is left alone.
    pub fn FreeJPEGPicture(self: *JpegBase, picture: *jpeg.JPEGPicture) void {
        return libraries.call(self, LVO.FreeJPEGPicture, Fn.FreeJPEGPicture, .{picture});
    }
};
