// SPDX-License-Identifier: MIT
//! keymap.library's functions: rawkeys into characters and back. Open it
//! with OpenLibrary("keymap.library", 0).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/keymap_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const keymap = @import("../libs/keymap/keymap.zig");
const ie = @import("../devices/inputevent.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "keymap.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const SetKeyMapDefault = libraries.lvo(4);
    pub const AskKeyMapDefault = libraries.lvo(5);
    pub const MapRawKey = libraries.lvo(6);
    pub const MapANSI = libraries.lvo(7);
    pub const FindKeyMap = libraries.lvo(8);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const SetKeyMapDefault = *const fn (*KeymapBase, *keymap.KeyMap) callconv(.c) void;
    pub const AskKeyMapDefault = *const fn (*KeymapBase) callconv(.c) *keymap.KeyMap;
    pub const MapRawKey = *const fn (*KeymapBase, *const ie.InputEvent, [*]u8, i32, ?*const keymap.KeyMap) callconv(.c) i32;
    pub const MapANSI = *const fn (*KeymapBase, [*]const u8, i32, [*]keymap.KeyPair, i32, ?*const keymap.KeyMap) callconv(.c) i32;
    pub const FindKeyMap = *const fn (*KeymapBase, [*:0]const u8) callconv(.c) ?*keymap.KeyMap;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const KeymapBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *KeymapBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Make `key_map` the default, which every call given null uses.
    pub fn SetKeyMapDefault(self: *KeymapBase, key_map: *keymap.KeyMap) void {
        return libraries.call(self, LVO.SetKeyMapDefault, Fn.SetKeyMapDefault, .{key_map});
    }

    /// The default KeyMap.
    pub fn AskKeyMapDefault(self: *KeymapBase) *keymap.KeyMap {
        return libraries.call(self, LVO.AskKeyMapDefault, Fn.AskKeyMapDefault, .{});
    }

    /// The characters an IECLASS_RAWKEY event makes, into `buffer` (room for
    /// `length`): how many, 0 for none (a key going up, a dead key, a key that
    /// sends nothing, another class), or -1 when they did not fit. `key_map`
    /// null is the default. The event's x and y are the keys down before it,
    /// which is what a dead key changes.
    pub fn MapRawKey(self: *KeymapBase, event: *const ie.InputEvent, buffer: [*]u8, length: i32, key_map: ?*const keymap.KeyMap) i32 {
        return libraries.call(self, LVO.MapRawKey, Fn.MapRawKey, .{ event, buffer, length, key_map });
    }

    /// The keys that make `count` characters of `string`, into `buffer` (room
    /// for `length` pairs): how many pairs, 0 when a character cannot be made
    /// with this keymap, -1 when they did not fit.
    pub fn MapANSI(self: *KeymapBase, string: [*]const u8, count: i32, buffer: [*]keymap.KeyPair, length: i32, key_map: ?*const keymap.KeyMap) i32 {
        return libraries.call(self, LVO.MapANSI, Fn.MapANSI, .{ string, count, buffer, length, key_map });
    }

    /// The KeyMap of that name on the library's list - "usa", "deutsch" - or
    /// null.
    pub fn FindKeyMap(self: *KeymapBase, name: [*:0]const u8) ?*keymap.KeyMap {
        return libraries.call(self, LVO.FindKeyMap, Fn.FindKeyMap, .{name});
    }
};
