// SPDX-License-Identifier: MIT
//! layers.library's functions: windows that share one display buffer.
//! A layer is a rectangle of a display that something draws into without
//! having to know what is in front of it. This library works out which
//! pieces of each layer are visible and hands the answer to
//! graphics.library as a clip target list on the layer's RastPort, so a
//! layer draws in its own coordinates and graphics.library never learns
//! what a window is. Open it with OpenLibrary("layers.library", 0).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/layers_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const utility = @import("../libs/utility/utility.zig");
const graphics = @import("../libs/graphics/graphics.zig");
const layers = @import("../libs/layers/layers.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "layers.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const NewLayerInfo = libraries.lvo(4);
    pub const DisposeLayerInfo = libraries.lvo(5);
    pub const CreateLayerTagList = libraries.lvo(6);
    pub const DeleteLayer = libraries.lvo(7);
    pub const UpfrontLayer = libraries.lvo(8);
    pub const BehindLayer = libraries.lvo(9);
    pub const MoveLayerInFrontOf = libraries.lvo(10);
    pub const WhichLayer = libraries.lvo(11);
    pub const GetLayerAttrs = libraries.lvo(12);
    pub const InstallClipRegion = libraries.lvo(13);
    pub const BeginUpdate = libraries.lvo(14);
    pub const EndUpdate = libraries.lvo(15);
    pub const LockLayer = libraries.lvo(16);
    pub const UnlockLayer = libraries.lvo(17);
    pub const LockLayers = libraries.lvo(18);
    pub const UnlockLayers = libraries.lvo(19);
    pub const LockLayerInfo = libraries.lvo(20);
    pub const UnlockLayerInfo = libraries.lvo(21);
    pub const MoveLayer = libraries.lvo(22);
    pub const SizeLayer = libraries.lvo(23);
    pub const MoveSizeLayer = libraries.lvo(24);
    pub const ScrollLayer = libraries.lvo(25);
    pub const InstallLayerHook = libraries.lvo(26);
    pub const DoHookClipRects = libraries.lvo(27);
    pub const LayersErrorText = libraries.lvo(28);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const NewLayerInfo = *const fn (*LayersBase, *graphics.RastPort) callconv(.c) ?*layers.LayerInfo;
    pub const DisposeLayerInfo = *const fn (*LayersBase, ?*layers.LayerInfo) callconv(.c) void;
    pub const CreateLayerTagList = *const fn (*LayersBase, *layers.LayerInfo, ?[*]const utility.TagItem) callconv(.c) ?*layers.Layer;
    pub const DeleteLayer = *const fn (*LayersBase, ?*layers.Layer) callconv(.c) void;
    pub const UpfrontLayer = *const fn (*LayersBase, *layers.Layer) callconv(.c) bool;
    pub const BehindLayer = *const fn (*LayersBase, *layers.Layer) callconv(.c) bool;
    pub const MoveLayerInFrontOf = *const fn (*LayersBase, *layers.Layer, *layers.Layer) callconv(.c) bool;
    pub const WhichLayer = *const fn (*LayersBase, *layers.LayerInfo, i32, i32) callconv(.c) ?*layers.Layer;
    pub const GetLayerAttrs = *const fn (*LayersBase, *layers.Layer, ?[*]const utility.TagItem) callconv(.c) void;
    pub const InstallClipRegion = *const fn (*LayersBase, *layers.Layer, ?*graphics.Region) callconv(.c) ?*graphics.Region;
    pub const BeginUpdate = *const fn (*LayersBase, *layers.Layer) callconv(.c) bool;
    pub const EndUpdate = *const fn (*LayersBase, *layers.Layer, bool) callconv(.c) void;
    pub const LockLayer = *const fn (*LayersBase, *layers.Layer) callconv(.c) void;
    pub const UnlockLayer = *const fn (*LayersBase, *layers.Layer) callconv(.c) void;
    pub const LockLayers = *const fn (*LayersBase, *layers.LayerInfo) callconv(.c) void;
    pub const UnlockLayers = *const fn (*LayersBase, *layers.LayerInfo) callconv(.c) void;
    pub const LockLayerInfo = *const fn (*LayersBase, *layers.LayerInfo) callconv(.c) void;
    pub const UnlockLayerInfo = *const fn (*LayersBase, *layers.LayerInfo) callconv(.c) void;
    pub const MoveLayer = *const fn (*LayersBase, *layers.Layer, i32, i32) callconv(.c) bool;
    pub const SizeLayer = *const fn (*LayersBase, *layers.Layer, i32, i32) callconv(.c) bool;
    pub const MoveSizeLayer = *const fn (*LayersBase, *layers.Layer, i32, i32, i32, i32) callconv(.c) bool;
    pub const ScrollLayer = *const fn (*LayersBase, *layers.Layer, i32, i32) callconv(.c) bool;
    pub const InstallLayerHook = *const fn (*LayersBase, *layers.Layer, usize) callconv(.c) usize;
    pub const DoHookClipRects = *const fn (*LayersBase, *utility.Hook, *graphics.RastPort, *const graphics.Rect) callconv(.c) void;
    pub const LayersErrorText = *const fn (*LayersBase, i32) callconv(.c) [*:0]const u8;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const LayersBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *LayersBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Every layer of one display. `rp` is the RastPort the display is drawn
    /// on - what CreateRastPortTagList answers with no tags - and it says how
    /// big the display is and where its pixels are. It is not taken over.
    /// Null if there is no memory or no display behind `rp`.
    pub fn NewLayerInfo(self: *LayersBase, rp: *graphics.RastPort) ?*layers.LayerInfo {
        return libraries.call(self, LVO.NewLayerInfo, Fn.NewLayerInfo, .{rp});
    }

    /// Throw away a LayerInfo and every layer still in it. Null is ignored.
    pub fn DisposeLayerInfo(self: *LayersBase, info: ?*layers.LayerInfo) void {
        return libraries.call(self, LVO.DisposeLayerInfo, Fn.DisposeLayerInfo, .{info});
    }

    /// A new layer, in front of the others unless LATAG_Behind says otherwise.
    /// The tags are the LATAG_ block; LATAG_Bounds is required. Null if it
    /// could not be made, with the reason at LATAG_ErrorPtr if one was given.
    pub fn CreateLayerTagList(self: *LayersBase, info: *layers.LayerInfo, tags: ?[*]const utility.TagItem) ?*layers.Layer {
        return libraries.call(self, LVO.CreateLayerTagList, Fn.CreateLayerTagList, .{ info, tags });
    }

    /// Take a layer away and give its RastPort back. What was behind it is
    /// uncovered, which damages the layers that were. Null is ignored.
    pub fn DeleteLayer(self: *LayersBase, layer: ?*layers.Layer) void {
        return libraries.call(self, LVO.DeleteLayer, Fn.DeleteLayer, .{layer});
    }

    /// Put a layer in front of every other one.
    pub fn UpfrontLayer(self: *LayersBase, layer: *layers.Layer) bool {
        return libraries.call(self, LVO.UpfrontLayer, Fn.UpfrontLayer, .{layer});
    }

    /// Put a layer behind every other one.
    pub fn BehindLayer(self: *LayersBase, layer: *layers.Layer) bool {
        return libraries.call(self, LVO.BehindLayer, Fn.BehindLayer, .{layer});
    }

    /// Put `layer` directly in front of `other`, both being in the same
    /// LayerInfo.
    pub fn MoveLayerInFrontOf(self: *LayersBase, layer: *layers.Layer, other: *layers.Layer) bool {
        return libraries.call(self, LVO.MoveLayerInFrontOf, Fn.MoveLayerInFrontOf, .{ layer, other });
    }

    /// Which layer a point of the display is in - the frontmost one that
    /// covers it - or null for none.
    pub fn WhichLayer(self: *LayersBase, info: *layers.LayerInfo, x: i32, y: i32) ?*layers.Layer {
        return libraries.call(self, LVO.WhichLayer, Fn.WhichLayer, .{ info, x, y });
    }

    /// Read a layer: bounds, flags, its RastPort, its damage, its last error,
    /// through the LATAG_Get names. Each ti_Data is a pointer to where the
    /// value goes.
    pub fn GetLayerAttrs(self: *LayersBase, layer: *layers.Layer, tags: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.GetLayerAttrs, Fn.GetLayerAttrs, .{ layer, tags });
    }

    /// Narrow a layer to a region of the caller's own, in the layer's
    /// coordinates, or null to take one off again. What was installed before
    /// comes back, for the caller to dispose of.
    pub fn InstallClipRegion(self: *LayersBase, layer: *layers.Layer, region: ?*graphics.Region) ?*graphics.Region {
        return libraries.call(self, LVO.InstallClipRegion, Fn.InstallClipRegion, .{ layer, region });
    }

    /// Narrow a layer to what needs redrawing, so that drawing all of it
    /// touches only the damage. False if there was nothing to do.
    pub fn BeginUpdate(self: *LayersBase, layer: *layers.Layer) bool {
        return libraries.call(self, LVO.BeginUpdate, Fn.BeginUpdate, .{layer});
    }

    /// Put back what BeginUpdate narrowed. `done` true clears the damage,
    /// false keeps it for another go.
    pub fn EndUpdate(self: *LayersBase, layer: *layers.Layer, done: bool) void {
        return libraries.call(self, LVO.EndUpdate, Fn.EndUpdate, .{ layer, done });
    }

    /// Hold one layer still: its clipping cannot change while it is held, so
    /// a drawing call cannot have the ground move under it.
    pub fn LockLayer(self: *LayersBase, layer: *layers.Layer) void {
        return libraries.call(self, LVO.LockLayer, Fn.LockLayer, .{layer});
    }

    /// Let it go again.
    pub fn UnlockLayer(self: *LayersBase, layer: *layers.Layer) void {
        return libraries.call(self, LVO.UnlockLayer, Fn.UnlockLayer, .{layer});
    }

    /// Hold every layer of a LayerInfo still, in one go, without the deadlock
    /// that taking them one at a time would be.
    pub fn LockLayers(self: *LayersBase, info: *layers.LayerInfo) void {
        return libraries.call(self, LVO.LockLayers, Fn.LockLayers, .{info});
    }

    /// Let them all go again.
    pub fn UnlockLayers(self: *LayersBase, info: *layers.LayerInfo) void {
        return libraries.call(self, LVO.UnlockLayers, Fn.UnlockLayers, .{info});
    }

    /// Hold the list of layers itself still: which layers there are and in
    /// what order.
    pub fn LockLayerInfo(self: *LayersBase, info: *layers.LayerInfo) void {
        return libraries.call(self, LVO.LockLayerInfo, Fn.LockLayerInfo, .{info});
    }

    /// Let it go again.
    pub fn UnlockLayerInfo(self: *LayersBase, info: *layers.LayerInfo) void {
        return libraries.call(self, LVO.UnlockLayerInfo, Fn.UnlockLayerInfo, .{info});
    }

    /// Move a layer by a delta, carrying what is on the display with it where
    /// it can: the part that is visible before and after is copied to the new
    /// place, and only what could not be carried is a layer's to draw again.
    pub fn MoveLayer(self: *LayersBase, layer: *layers.Layer, dx: i32, dy: i32) bool {
        return libraries.call(self, LVO.MoveLayer, Fn.MoveLayer, .{ layer, dx, dy });
    }

    /// Change a layer's size by a delta, its top-left staying where it is.
    /// What is still inside it is carried; what is newly inside it is not.
    pub fn SizeLayer(self: *LayersBase, layer: *layers.Layer, dw: i32, dh: i32) bool {
        return libraries.call(self, LVO.SizeLayer, Fn.SizeLayer, .{ layer, dw, dh });
    }

    /// Move and resize in one go, which is one retile rather than two and one
    /// carry of the pixels rather than two.
    pub fn MoveSizeLayer(self: *LayersBase, layer: *layers.Layer, dx: i32, dy: i32, dw: i32, dh: i32) bool {
        return libraries.call(self, LVO.MoveSizeLayer, Fn.MoveSizeLayer, .{ layer, dx, dy, dw, dh });
    }

    /// Move the window a LAYERSUPER layer shows of its own bitmap. What is on
    /// the display is put back into the bitmap first, so nothing drawn while
    /// it was shown is lost, and the newly shown part is copied out. The
    /// scroll is held inside the bitmap, so scrolling past its edge stops
    /// there rather than showing memory that is not its.
    pub fn ScrollLayer(self: *LayersBase, layer: *layers.Layer, dx: i32, dy: i32) bool {
        return libraries.call(self, LVO.ScrollLayer, Fn.ScrollLayer, .{ layer, dx, dy });
    }

    /// Change what paints a part of a layer that has nothing in it yet, and
    /// answer what was there before. A `*Hook`, or 0 for the layer's own
    /// background pen, or LAYERS_NOBACKFILL for nothing at all - the same
    /// three things LATAG_BackFill takes. It paints nothing by itself; it
    /// says what the next painting will use.
    pub fn InstallLayerHook(self: *LayersBase, layer: *layers.Layer, hook: usize) usize {
        return libraries.call(self, LVO.InstallLayerHook, Fn.InstallLayerHook, .{ layer, hook });
    }

    /// Call a hook once for each piece of a RastPort that may be drawn on,
    /// with the part of `area` that piece covers. What a layer can draw on is
    /// several rectangles, in more than one surface once it is covered, and
    /// this is how something that wants to work over them one at a time gets
    /// them without knowing any of that. The hook is called with the RastPort
    /// and a BackFillMsg whose area is in the RastPort's own coordinates.
    pub fn DoHookClipRects(self: *LayersBase, hook: *utility.Hook, rp: *graphics.RastPort, area: *const graphics.Rect) void {
        return libraries.call(self, LVO.DoHookClipRects, Fn.DoHookClipRects, .{ hook, rp, area });
    }

    /// What an LERR_ code means, in words. A code this library does not know
    /// is "unknown error" rather than null.
    pub fn LayersErrorText(self: *LayersBase, code: i32) [*:0]const u8 {
        return libraries.call(self, LVO.LayersErrorText, Fn.LayersErrorText, .{code});
    }
};
