// SPDX-License-Identifier: MIT
//! modbus.library's functions: Modbus over RTU (an RS-485 bus, through
//! rs485.device) and TCP, as a client asking devices and as a server
//! answering from a program's tables. Open it with
//! OpenLibrary("modbus.library", 1); the structures are in sdk.modbus.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/modbus_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const modbus = @import("../libs/modbus/modbus.zig");
const utility = @import("../libs/utility/utility.zig");
const bsdsocket = @import("../interface/bsdsocket.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "modbus.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const OpenModbusRTU = libraries.lvo(4);
    pub const OpenModbusTCP = libraries.lvo(5);
    pub const CloseModbus = libraries.lvo(6);
    pub const ReadCoils = libraries.lvo(7);
    pub const ReadDiscreteInputs = libraries.lvo(8);
    pub const ReadHoldingRegisters = libraries.lvo(9);
    pub const ReadInputRegisters = libraries.lvo(10);
    pub const WriteCoil = libraries.lvo(11);
    pub const WriteRegister = libraries.lvo(12);
    pub const WriteCoils = libraries.lvo(13);
    pub const WriteRegisters = libraries.lvo(14);
    pub const ReadWriteRegisters = libraries.lvo(15);
    pub const ModbusTransaction = libraries.lvo(16);
    pub const StartModbusServer = libraries.lvo(17);
    pub const StopModbusServer = libraries.lvo(18);
    pub const ModbusErrorText = libraries.lvo(19);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const OpenModbusRTU = *const fn (*ModbusBase, ?[*]const utility.TagItem, ?*i32) callconv(.c) ?*modbus.ModbusContext;
    pub const OpenModbusTCP = *const fn (*ModbusBase, *bsdsocket.SocketBase, ?[*]const utility.TagItem, ?*i32) callconv(.c) ?*modbus.ModbusContext;
    pub const CloseModbus = *const fn (*ModbusBase, ?*modbus.ModbusContext) callconv(.c) void;
    pub const ReadCoils = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32, [*]u8) callconv(.c) i32;
    pub const ReadDiscreteInputs = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32, [*]u8) callconv(.c) i32;
    pub const ReadHoldingRegisters = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32, [*]u16) callconv(.c) i32;
    pub const ReadInputRegisters = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32, [*]u16) callconv(.c) i32;
    pub const WriteCoil = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32) callconv(.c) i32;
    pub const WriteRegister = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32) callconv(.c) i32;
    pub const WriteCoils = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32, [*]const u8) callconv(.c) i32;
    pub const WriteRegisters = *const fn (*ModbusBase, *modbus.ModbusContext, u32, u32, u32, [*]const u16) callconv(.c) i32;
    pub const ReadWriteRegisters = *const fn (*ModbusBase, *modbus.ModbusContext, u32, *const modbus.ModbusReadWrite) callconv(.c) i32;
    pub const ModbusTransaction = *const fn (*ModbusBase, *modbus.ModbusContext, u32, *const modbus.ModbusPdu, *modbus.ModbusPdu) callconv(.c) i32;
    pub const StartModbusServer = *const fn (*ModbusBase, ?[*]const utility.TagItem, ?*i32) callconv(.c) ?*modbus.ModbusServer;
    pub const StopModbusServer = *const fn (*ModbusBase, ?*modbus.ModbusServer) callconv(.c) void;
    pub const ModbusErrorText = *const fn (*ModbusBase, i32) callconv(.c) [*:0]const u8;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const ModbusBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *ModbusBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A client on an RTU bus: its device opened and the line set. Null,
    /// and why in `err` (MBERR_*), when it failed.
    pub fn OpenModbusRTU(self: *ModbusBase, tags: ?[*]const utility.TagItem, err: ?*i32) ?*modbus.ModbusContext {
        return libraries.call(self, LVO.OpenModbusRTU, Fn.OpenModbusRTU, .{ tags, err });
    }

    /// A client on a TCP connection, made with the program's `socket_base`.
    pub fn OpenModbusTCP(self: *ModbusBase, socket_base: *bsdsocket.SocketBase, tags: ?[*]const utility.TagItem, err: ?*i32) ?*modbus.ModbusContext {
        return libraries.call(self, LVO.OpenModbusTCP, Fn.OpenModbusTCP, .{ socket_base, tags, err });
    }

    /// The context closed and freed: its device, or its connection unless the
    /// program gave the socket.
    pub fn CloseModbus(self: *ModbusBase, context: ?*modbus.ModbusContext) void {
        return libraries.call(self, LVO.CloseModbus, Fn.CloseModbus, .{context});
    }

    /// `count` coils from `address` of `unit`, a byte each into `values`.
    pub fn ReadCoils(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, count: u32, values: [*]u8) i32 {
        return libraries.call(self, LVO.ReadCoils, Fn.ReadCoils, .{ context, unit, address, count, values });
    }

    /// `count` discrete inputs from `address`, a byte each into `values`.
    pub fn ReadDiscreteInputs(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, count: u32, values: [*]u8) i32 {
        return libraries.call(self, LVO.ReadDiscreteInputs, Fn.ReadDiscreteInputs, .{ context, unit, address, count, values });
    }

    /// `count` holding registers from `address` into `values`.
    pub fn ReadHoldingRegisters(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, count: u32, values: [*]u16) i32 {
        return libraries.call(self, LVO.ReadHoldingRegisters, Fn.ReadHoldingRegisters, .{ context, unit, address, count, values });
    }

    /// `count` input registers from `address` into `values`.
    pub fn ReadInputRegisters(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, count: u32, values: [*]u16) i32 {
        return libraries.call(self, LVO.ReadInputRegisters, Fn.ReadInputRegisters, .{ context, unit, address, count, values });
    }

    /// The coil at `address` set (`value` not 0) or cleared.
    pub fn WriteCoil(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, value: u32) i32 {
        return libraries.call(self, LVO.WriteCoil, Fn.WriteCoil, .{ context, unit, address, value });
    }

    /// The holding register at `address` set to `value`.
    pub fn WriteRegister(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, value: u32) i32 {
        return libraries.call(self, LVO.WriteRegister, Fn.WriteRegister, .{ context, unit, address, value });
    }

    /// `count` coils from `address` set from `values`, a byte each.
    pub fn WriteCoils(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, count: u32, values: [*]const u8) i32 {
        return libraries.call(self, LVO.WriteCoils, Fn.WriteCoils, .{ context, unit, address, count, values });
    }

    /// `count` holding registers from `address` set from `values`.
    pub fn WriteRegisters(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, address: u32, count: u32, values: [*]const u16) i32 {
        return libraries.call(self, LVO.WriteRegisters, Fn.WriteRegisters, .{ context, unit, address, count, values });
    }

    /// Holding registers written, then others read, in one exchange.
    pub fn ReadWriteRegisters(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, transfer: *const modbus.ModbusReadWrite) i32 {
        return libraries.call(self, LVO.ReadWriteRegisters, Fn.ReadWriteRegisters, .{ context, unit, transfer });
    }

    /// Any question, as its PDU, and the answer's PDU.
    pub fn ModbusTransaction(self: *ModbusBase, context: *modbus.ModbusContext, unit: u32, question: *const modbus.ModbusPdu, answer: *modbus.ModbusPdu) i32 {
        return libraries.call(self, LVO.ModbusTransaction, Fn.ModbusTransaction, .{ context, unit, question, answer });
    }

    /// A server answering from the program's tables, on a process of its own.
    pub fn StartModbusServer(self: *ModbusBase, tags: ?[*]const utility.TagItem, err: ?*i32) ?*modbus.ModbusServer {
        return libraries.call(self, LVO.StartModbusServer, Fn.StartModbusServer, .{ tags, err });
    }

    /// The server stopped, waited for, and freed.
    pub fn StopModbusServer(self: *ModbusBase, server: ?*modbus.ModbusServer) void {
        return libraries.call(self, LVO.StopModbusServer, Fn.StopModbusServer, .{server});
    }

    /// What an error or exception code means, in words.
    pub fn ModbusErrorText(self: *ModbusBase, code: i32) [*:0]const u8 {
        return libraries.call(self, LVO.ModbusErrorText, Fn.ModbusErrorText, .{code});
    }
};
