// SPDX-License-Identifier: MIT
//! motion.library's functions: a clock for things that move. One task runs
//! every animation and timer that is due, on timer.device's clock. Open it
//! with OpenLibrary("motion.library", 1).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/motion_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "motion.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const MotionBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *MotionBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }
};
