// SPDX-License-Identifier: MIT
//! platform.resource's functions: what machine this is - the chip, its
//! clocks, where the code and the stacks are, and whether there is PSRAM.
//! A resource: no Open or Close, its first function in the first slot. The
//! base comes from OpenResource("platform.resource").
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/platform_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const platform = @import("../resources/platform.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "platform.resource";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const GetPlatformInfo = libraries.lvo(0);
    pub const PlatformName = libraries.lvo(1);
    pub const CpuClock = libraries.lvo(2);
    pub const TickRate = libraries.lvo(3);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const GetPlatformInfo = *const fn (*PlatformBase, *platform.PlatformInfo, u32) callconv(.c) u32;
    pub const PlatformName = *const fn (*PlatformBase) callconv(.c) [*:0]const u8;
    pub const CpuClock = *const fn (*PlatformBase) callconv(.c) u32;
    pub const TickRate = *const fn (*PlatformBase) callconv(.c) u32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const PlatformBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *PlatformBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Fill in `info` (sdk/resources/platform.zig), of which `size` bytes are
    /// there - pass @sizeOf(PlatformInfo). Returns how many bytes it wrote,
    /// which is the lesser of `size` and its own idea of the structure: a
    /// program from the disk may have been built against another SDK than the
    /// ROM answering it, so check the count before trusting a field near the
    /// end. Nothing is written and 0 comes back for a `size` too small to hold
    /// anything.
    pub fn GetPlatformInfo(self: *PlatformBase, info: *platform.PlatformInfo, size: u32) u32 {
        return libraries.call(self, LVO.GetPlatformInfo, Fn.GetPlatformInfo, .{ info, size });
    }

    /// The chip's name, a C string ("ESP32-S3"). Never null.
    pub fn PlatformName(self: *PlatformBase) [*:0]const u8 {
        return libraries.call(self, LVO.PlatformName, Fn.PlatformName, .{});
    }

    /// The clock the system runs and times by, in Hz. It is the configured one
    /// while the measurement against the crystal agrees with it (within 5%),
    /// and the measured one when it does not - GetPlatformInfo's `cpu_hz` and
    /// `measured_cpu_hz` are both there to be compared. What a delay loop or a
    /// benchmark wants. 0 before the tick has been set up.
    pub fn CpuClock(self: *PlatformBase) u32 {
        return libraries.call(self, LVO.CpuClock, Fn.CpuClock, .{});
    }

    /// The kernel tick in Hz. Not timer.device's units, and not the 1/50 s
    /// Delay counts in.
    pub fn TickRate(self: *PlatformBase) u32 {
        return libraries.call(self, LVO.TickRate, Fn.TickRate, .{});
    }
};
