// SPDX-License-Identifier: MIT
//! rdb.library's functions: a disk's RigidDiskBlock and partitions read
//! into memory, changed there and written back. Open it with
//! OpenLibrary("rdb.library", 1); the structures are in sdk.rdb.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/rdb_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const rdb = @import("../libs/rdb/rdb.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "rdb.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const OpenRDB = libraries.lvo(4);
    pub const CloseRDB = libraries.lvo(5);
    pub const InitRDB = libraries.lvo(6);
    pub const NextPartition = libraries.lvo(7);
    pub const FindPartition = libraries.lvo(8);
    pub const AddPartition = libraries.lvo(9);
    pub const RemPartition = libraries.lvo(10);
    pub const WriteRDB = libraries.lvo(11);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const OpenRDB = *const fn (*RDBBase, [*:0]const u8, u32, ?*i32) callconv(.c) ?*rdb.RDBHandle;
    pub const CloseRDB = *const fn (*RDBBase, ?*rdb.RDBHandle) callconv(.c) void;
    pub const InitRDB = *const fn (*RDBBase, *rdb.RDBHandle) callconv(.c) i32;
    pub const NextPartition = *const fn (*RDBBase, *rdb.RDBHandle, ?*rdb.RDBPartition) callconv(.c) ?*rdb.RDBPartition;
    pub const FindPartition = *const fn (*RDBBase, *rdb.RDBHandle, [*:0]const u8) callconv(.c) ?*rdb.RDBPartition;
    pub const AddPartition = *const fn (*RDBBase, *rdb.RDBHandle, [*:0]const u8, u32, u32, u32) callconv(.c) i32;
    pub const RemPartition = *const fn (*RDBBase, *rdb.RDBHandle, *rdb.RDBPartition) callconv(.c) void;
    pub const WriteRDB = *const fn (*RDBBase, *rdb.RDBHandle) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const RDBBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *RDBBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The RigidDiskBlock and partitions of a unit of a block device, read
    /// into a handle; null, and why in `err`, when the device cannot be used.
    pub fn OpenRDB(self: *RDBBase, device: [*:0]const u8, unit: u32, err: ?*i32) ?*rdb.RDBHandle {
        return libraries.call(self, LVO.OpenRDB, Fn.OpenRDB, .{ device, unit, err });
    }

    /// The handle, its partitions and the device let go of.
    pub fn CloseRDB(self: *RDBBase, handle: ?*rdb.RDBHandle) void {
        return libraries.call(self, LVO.CloseRDB, Fn.CloseRDB, .{handle});
    }

    /// A fresh RigidDiskBlock for the whole medium in the handle, with no
    /// partitions: written by WriteRDB.
    pub fn InitRDB(self: *RDBBase, handle: *rdb.RDBHandle) i32 {
        return libraries.call(self, LVO.InitRDB, Fn.InitRDB, .{handle});
    }

    /// The partition after `previous` on the handle's list, or the first.
    pub fn NextPartition(self: *RDBBase, handle: *rdb.RDBHandle, previous: ?*rdb.RDBPartition) ?*rdb.RDBPartition {
        return libraries.call(self, LVO.NextPartition, Fn.NextPartition, .{ handle, previous });
    }

    /// The partition called `name`, in any case.
    pub fn FindPartition(self: *RDBBase, handle: *rdb.RDBHandle, name: [*:0]const u8) ?*rdb.RDBPartition {
        return libraries.call(self, LVO.FindPartition, Fn.FindPartition, .{ handle, name });
    }

    /// A new partition called `name` over cylinders `low_cyl` to `high_cyl`
    /// (0 and 0: the largest free run) for the file system `dos_type`.
    pub fn AddPartition(self: *RDBBase, handle: *rdb.RDBHandle, name: [*:0]const u8, low_cyl: u32, high_cyl: u32, dos_type: u32) i32 {
        return libraries.call(self, LVO.AddPartition, Fn.AddPartition, .{ handle, name, low_cyl, high_cyl, dos_type });
    }

    /// A partition taken off the handle's list and freed.
    pub fn RemPartition(self: *RDBBase, handle: *rdb.RDBHandle, partition: *rdb.RDBPartition) void {
        return libraries.call(self, LVO.RemPartition, Fn.RemPartition, .{ handle, partition });
    }

    /// The handle's table checked and written to the disk.
    pub fn WriteRDB(self: *RDBBase, handle: *rdb.RDBHandle) i32 {
        return libraries.call(self, LVO.WriteRDB, Fn.WriteRDB, .{handle});
    }
};
