// SPDX-License-Identifier: MIT
//! rtg.library's functions: the displays of this machine and the drivers
//! that drive them. A driver registers itself and a caller asks for a
//! board by the driver's name; what comes back has modes, display memory,
//! a buffer it is shown out of and a blanking. The library draws nothing
//! of its own - an operation a board's engine can do is offered through
//! the board, and a board that has not got it says so. Open it with
//! OpenLibrary("rtg.library", 1).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/rtg_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const utility = @import("../libs/utility/utility.zig");
const rtg = @import("../libs/rtg/rtg.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "rtg.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const AddRtgDriver = libraries.lvo(4);
    pub const RemRtgDriver = libraries.lvo(5);
    pub const FindRtgDriver = libraries.lvo(6);
    pub const LockRtgDrivers = libraries.lvo(7);
    pub const UnlockRtgDrivers = libraries.lvo(8);
    pub const NextRtgDriver = libraries.lvo(9);
    pub const CreateBoardTagList = libraries.lvo(10);
    pub const DeleteBoard = libraries.lvo(11);
    pub const NextBoard = libraries.lvo(12);
    pub const FindBoard = libraries.lvo(13);
    pub const GetBoardInfo = libraries.lvo(14);
    pub const GetBoardStats = libraries.lvo(15);
    pub const BoardControl = libraries.lvo(16);
    pub const NextBoardMode = libraries.lvo(17);
    pub const FindBoardMode = libraries.lvo(18);
    pub const SetBoardMode = libraries.lvo(19);
    pub const BoardMode = libraries.lvo(20);
    pub const AllocBitMap = libraries.lvo(21);
    pub const AttachBitMap = libraries.lvo(22);
    pub const FreeBitMap = libraries.lvo(23);
    pub const ShowBitMap = libraries.lvo(24);
    pub const BoardDisplayBitMap = libraries.lvo(25);
    pub const RefreshBitMap = libraries.lvo(26);
    pub const WaitVBlank = libraries.lvo(27);
    pub const SetBoardDisplay = libraries.lvo(28);
    pub const SetBoardBrightness = libraries.lvo(29);
    pub const BoardBrightness = libraries.lvo(30);
    pub const FillRect = libraries.lvo(31);
    pub const InvertRect = libraries.lvo(32);
    pub const CopyRect = libraries.lvo(33);
    pub const BlitTemplate = libraries.lvo(34);
    pub const BlitPattern = libraries.lvo(35);
    pub const WaitBlit = libraries.lvo(36);
    pub const PackRtgColor = libraries.lvo(37);
    pub const UnpackRtgColor = libraries.lvo(38);
    pub const AddRtgEventServer = libraries.lvo(39);
    pub const RemRtgEventServer = libraries.lvo(40);
    pub const SignalRtgEvent = libraries.lvo(41);
    pub const CreateTransportTagList = libraries.lvo(42);
    pub const DeleteTransport = libraries.lvo(43);
    pub const TxParam = libraries.lvo(44);
    pub const TxColor = libraries.lvo(45);
    pub const RxParam = libraries.lvo(46);
    pub const GetRtgTagData = libraries.lvo(47);
    pub const FindRtgTagItem = libraries.lvo(48);
    pub const RtgLastError = libraries.lvo(49);
    pub const RtgErrorText = libraries.lvo(50);
    pub const MirrorBoard = libraries.lvo(51);
    pub const SwapBoardAxes = libraries.lvo(52);
    pub const SetBoardGap = libraries.lvo(53);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const AddRtgDriver = *const fn (*RtgBase, *rtg.RtgDriver) callconv(.c) bool;
    pub const RemRtgDriver = *const fn (*RtgBase, *rtg.RtgDriver) callconv(.c) bool;
    pub const FindRtgDriver = *const fn (*RtgBase, [*:0]const u8) callconv(.c) ?*rtg.RtgDriver;
    pub const LockRtgDrivers = *const fn (*RtgBase) callconv(.c) void;
    pub const UnlockRtgDrivers = *const fn (*RtgBase) callconv(.c) void;
    pub const NextRtgDriver = *const fn (*RtgBase, ?*rtg.RtgDriver) callconv(.c) ?*rtg.RtgDriver;
    pub const CreateBoardTagList = *const fn (*RtgBase, [*:0]const u8, ?[*]const utility.TagItem) callconv(.c) ?*rtg.RtgBoard;
    pub const DeleteBoard = *const fn (*RtgBase, ?*rtg.RtgBoard) callconv(.c) void;
    pub const NextBoard = *const fn (*RtgBase, ?*rtg.RtgBoard) callconv(.c) ?*rtg.RtgBoard;
    pub const FindBoard = *const fn (*RtgBase, [*:0]const u8) callconv(.c) ?*rtg.RtgBoard;
    pub const GetBoardInfo = *const fn (*RtgBase, *rtg.RtgBoard, *rtg.RtgBoardInfo, u32) callconv(.c) u32;
    pub const GetBoardStats = *const fn (*RtgBase, *rtg.RtgBoard, *rtg.RtgBoardStats, u32) callconv(.c) u32;
    pub const BoardControl = *const fn (*RtgBase, *rtg.RtgBoard, u32, isize) callconv(.c) isize;
    pub const NextBoardMode = *const fn (*RtgBase, *rtg.RtgBoard, ?*rtg.RtgMode) callconv(.c) ?*rtg.RtgMode;
    pub const FindBoardMode = *const fn (*RtgBase, *rtg.RtgBoard, u32, u32, u32) callconv(.c) ?*rtg.RtgMode;
    pub const SetBoardMode = *const fn (*RtgBase, *rtg.RtgBoard, ?*rtg.RtgMode) callconv(.c) i32;
    pub const BoardMode = *const fn (*RtgBase, *rtg.RtgBoard) callconv(.c) ?*rtg.RtgMode;
    pub const AllocBitMap = *const fn (*RtgBase, *rtg.RtgBoard, u32, u32, u32, u32) callconv(.c) ?*rtg.RtgBitMap;
    pub const AttachBitMap = *const fn (*RtgBase, *rtg.RtgBoard, *const rtg.RtgBitMap) callconv(.c) ?*rtg.RtgBitMap;
    pub const FreeBitMap = *const fn (*RtgBase, ?*rtg.RtgBitMap) callconv(.c) void;
    pub const ShowBitMap = *const fn (*RtgBase, *rtg.RtgBoard, ?*rtg.RtgBitMap, u32, u32) callconv(.c) i32;
    pub const BoardDisplayBitMap = *const fn (*RtgBase, *rtg.RtgBoard) callconv(.c) ?*rtg.RtgBitMap;
    pub const RefreshBitMap = *const fn (*RtgBase, *rtg.RtgBitMap, u32, u32) callconv(.c) i32;
    pub const WaitVBlank = *const fn (*RtgBase, *rtg.RtgBoard, u32) callconv(.c) i32;
    pub const SetBoardDisplay = *const fn (*RtgBase, *rtg.RtgBoard, bool) callconv(.c) i32;
    pub const SetBoardBrightness = *const fn (*RtgBase, *rtg.RtgBoard, u32) callconv(.c) i32;
    pub const BoardBrightness = *const fn (*RtgBase, *rtg.RtgBoard) callconv(.c) u32;
    pub const FillRect = *const fn (*RtgBase, *rtg.RtgBitMap, *const rtg.RtgRect, u32) callconv(.c) i32;
    pub const InvertRect = *const fn (*RtgBase, *rtg.RtgBitMap, *const rtg.RtgRect) callconv(.c) i32;
    pub const CopyRect = *const fn (*RtgBase, *rtg.RtgBitMap, *rtg.RtgBitMap, *const rtg.RtgCopy) callconv(.c) i32;
    pub const BlitTemplate = *const fn (*RtgBase, *rtg.RtgBitMap, *const rtg.RtgRect, *const rtg.RtgTemplate) callconv(.c) i32;
    pub const BlitPattern = *const fn (*RtgBase, *rtg.RtgBitMap, *const rtg.RtgRect, *const rtg.RtgPattern) callconv(.c) i32;
    pub const WaitBlit = *const fn (*RtgBase, *rtg.RtgBoard) callconv(.c) void;
    pub const PackRtgColor = *const fn (*RtgBase, u32, u32, u32, u32) callconv(.c) u32;
    pub const UnpackRtgColor = *const fn (*RtgBase, u32, u32, *rtg.RtgRGB) callconv(.c) void;
    pub const AddRtgEventServer = *const fn (*RtgBase, *rtg.RtgBoard, u32, *exec.Interrupt) callconv(.c) bool;
    pub const RemRtgEventServer = *const fn (*RtgBase, *rtg.RtgBoard, u32, *exec.Interrupt) callconv(.c) void;
    pub const SignalRtgEvent = *const fn (*RtgBase, *rtg.RtgBoard, u32) callconv(.c) i32;
    pub const CreateTransportTagList = *const fn (*RtgBase, [*:0]const u8, ?[*]const utility.TagItem) callconv(.c) ?*rtg.RtgTransport;
    pub const DeleteTransport = *const fn (*RtgBase, ?*rtg.RtgTransport) callconv(.c) void;
    pub const TxParam = *const fn (*RtgBase, *rtg.RtgTransport, i32, ?*const anyopaque, u32) callconv(.c) i32;
    pub const TxColor = *const fn (*RtgBase, *rtg.RtgTransport, i32, ?*const anyopaque, u32) callconv(.c) i32;
    pub const RxParam = *const fn (*RtgBase, *rtg.RtgTransport, i32, ?*anyopaque, u32) callconv(.c) i32;
    pub const GetRtgTagData = *const fn (*RtgBase, utility.Tag, usize, ?[*]const utility.TagItem) callconv(.c) usize;
    pub const FindRtgTagItem = *const fn (*RtgBase, utility.Tag, ?[*]const utility.TagItem) callconv(.c) ?*const utility.TagItem;
    pub const RtgLastError = *const fn (*RtgBase) callconv(.c) i32;
    pub const RtgErrorText = *const fn (*RtgBase, i32) callconv(.c) [*:0]const u8;
    pub const MirrorBoard = *const fn (*RtgBase, *rtg.RtgBoard, bool, bool) callconv(.c) i32;
    pub const SwapBoardAxes = *const fn (*RtgBase, *rtg.RtgBoard, bool) callconv(.c) i32;
    pub const SetBoardGap = *const fn (*RtgBase, *rtg.RtgBoard, u32, u32) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const RtgBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *RtgBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Put a driver on the list. False for a name already there, or for ops
    /// that fill in neither create. Not from interrupts.
    pub fn AddRtgDriver(self: *RtgBase, driver: *rtg.RtgDriver) bool {
        return libraries.call(self, LVO.AddRtgDriver, Fn.AddRtgDriver, .{driver});
    }

    /// Take a driver off the list. False while a board or a transport it made
    /// is still alive. Not from interrupts.
    pub fn RemRtgDriver(self: *RtgBase, driver: *rtg.RtgDriver) bool {
        return libraries.call(self, LVO.RemRtgDriver, Fn.RemRtgDriver, .{driver});
    }

    /// The driver of that name, or null. Hold the list with LockRtgDrivers to
    /// use the answer.
    pub fn FindRtgDriver(self: *RtgBase, driver_name: [*:0]const u8) ?*rtg.RtgDriver {
        return libraries.call(self, LVO.FindRtgDriver, Fn.FindRtgDriver, .{driver_name});
    }

    /// Hold the driver list still so it can be walked. Nests.
    pub fn LockRtgDrivers(self: *RtgBase) void {
        return libraries.call(self, LVO.LockRtgDrivers, Fn.LockRtgDrivers, .{});
    }

    /// Let it go again.
    pub fn UnlockRtgDrivers(self: *RtgBase) void {
        return libraries.call(self, LVO.UnlockRtgDrivers, Fn.UnlockRtgDrivers, .{});
    }

    /// The next driver after `after`, or the first for null. The list must be
    /// locked.
    pub fn NextRtgDriver(self: *RtgBase, after: ?*rtg.RtgDriver) ?*rtg.RtgDriver {
        return libraries.call(self, LVO.NextRtgDriver, Fn.NextRtgDriver, .{after});
    }

    /// A board from that driver, set up by the tags (RTGA_*). It is in no mode
    /// and shows nothing yet. Null: RtgLastError says why.
    pub fn CreateBoardTagList(self: *RtgBase, driver_name: [*:0]const u8, tag_list: ?[*]const utility.TagItem) ?*rtg.RtgBoard {
        return libraries.call(self, LVO.CreateBoardTagList, Fn.CreateBoardTagList, .{ driver_name, tag_list });
    }

    /// Stop a board and give everything back. Free your buffers and remove
    /// your event servers first. Null does nothing.
    pub fn DeleteBoard(self: *RtgBase, board: ?*rtg.RtgBoard) void {
        return libraries.call(self, LVO.DeleteBoard, Fn.DeleteBoard, .{board});
    }

    /// The next board after `after`, or the first for null.
    pub fn NextBoard(self: *RtgBase, after: ?*rtg.RtgBoard) ?*rtg.RtgBoard {
        return libraries.call(self, LVO.NextBoard, Fn.NextBoard, .{after});
    }

    /// The board of that name, or null.
    pub fn FindBoard(self: *RtgBase, board_name: [*:0]const u8) ?*rtg.RtgBoard {
        return libraries.call(self, LVO.FindBoard, Fn.FindBoard, .{board_name});
    }

    /// Fill in `info`, of which `size` bytes are there - pass
    /// @sizeOf(RtgBoardInfo). Returns the bytes written; check it before
    /// trusting a field near the end.
    pub fn GetBoardInfo(self: *RtgBase, board: *rtg.RtgBoard, info: *rtg.RtgBoardInfo, size: u32) u32 {
        return libraries.call(self, LVO.GetBoardInfo, Fn.GetBoardInfo, .{ board, info, size });
    }

    /// What a board that refreshes itself has been through. Same rule as
    /// GetBoardInfo. All zeroes for a board that counts nothing.
    pub fn GetBoardStats(self: *RtgBase, board: *rtg.RtgBoard, stats: *rtg.RtgBoardStats, size: u32) u32 {
        return libraries.call(self, LVO.GetBoardStats, Fn.GetBoardStats, .{ board, stats, size });
    }

    /// Something only this driver knows about (RTGCTRL_*), or
    /// RTGCTRL_RESET_STATS, which every board takes. RTGERR_NOT_SUPPORTED for
    /// one it does not know.
    pub fn BoardControl(self: *RtgBase, board: *rtg.RtgBoard, what: u32, value: isize) isize {
        return libraries.call(self, LVO.BoardControl, Fn.BoardControl, .{ board, what, value });
    }

    /// The next mode of a board, or its first for null.
    pub fn NextBoardMode(self: *RtgBase, board: *rtg.RtgBoard, after: ?*rtg.RtgMode) ?*rtg.RtgMode {
        return libraries.call(self, LVO.NextBoardMode, Fn.NextBoardMode, .{ board, after });
    }

    /// The board's mode of that size and format, or null. A zero matches
    /// anything, so (0, 0, 0) is the board's default mode.
    pub fn FindBoardMode(self: *RtgBase, board: *rtg.RtgBoard, width: u32, height: u32, format: u32) ?*rtg.RtgMode {
        return libraries.call(self, LVO.FindBoardMode, Fn.FindBoardMode, .{ board, width, height, format });
    }

    /// Put the board in that mode, or in its default for null. Refused with
    /// RTGERR_IN_USE while a buffer that is not RTGBMF_VOLATILE is alive;
    /// volatile ones lose their memory and keep their handle.
    pub fn SetBoardMode(self: *RtgBase, board: *rtg.RtgBoard, mode: ?*rtg.RtgMode) i32 {
        return libraries.call(self, LVO.SetBoardMode, Fn.SetBoardMode, .{ board, mode });
    }

    /// The mode the board is in now, or null for none.
    pub fn BoardMode(self: *RtgBase, board: *rtg.RtgBoard) ?*rtg.RtgMode {
        return libraries.call(self, LVO.BoardMode, Fn.BoardMode, .{board});
    }

    /// A buffer in the board's display memory, its rows aligned as the board
    /// asks. RTGBMF_DISPLAYABLE makes one the board can be shown. Null:
    /// RtgLastError says why.
    pub fn AllocBitMap(self: *RtgBase, board: *rtg.RtgBoard, width: u32, height: u32, format: u32, flags: u32) ?*rtg.RtgBitMap {
        return libraries.call(self, LVO.AllocBitMap, Fn.AllocBitMap, .{ board, width, height, format, flags });
    }

    /// A buffer over memory the caller owns: the seven fields of a surface are
    /// read out of `described` and nothing is allocated. Null: RtgLastError.
    pub fn AttachBitMap(self: *RtgBase, board: *rtg.RtgBoard, described: *const rtg.RtgBitMap) ?*rtg.RtgBitMap {
        return libraries.call(self, LVO.AttachBitMap, Fn.AttachBitMap, .{ board, described });
    }

    /// Give a buffer back. Refused while the board is showing it. Null does
    /// nothing.
    pub fn FreeBitMap(self: *RtgBase, bitmap: ?*rtg.RtgBitMap) void {
        return libraries.call(self, LVO.FreeBitMap, Fn.FreeBitMap, .{bitmap});
    }

    /// Show that buffer, its pixel (x, y) at the top left; null shows nothing.
    /// A board that cannot pan answers RTGERR_NOT_SUPPORTED for an x or y that
    /// is not zero.
    pub fn ShowBitMap(self: *RtgBase, board: *rtg.RtgBoard, bitmap: ?*rtg.RtgBitMap, x: u32, y: u32) i32 {
        return libraries.call(self, LVO.ShowBitMap, Fn.ShowBitMap, .{ board, bitmap, x, y });
    }

    /// The buffer the board is showing, or null. Its first seven fields are a
    /// drawing surface.
    pub fn BoardDisplayBitMap(self: *RtgBase, board: *rtg.RtgBoard) ?*rtg.RtgBitMap {
        return libraries.call(self, LVO.BoardDisplayBitMap, Fn.BoardDisplayBitMap, .{board});
    }

    /// Rows y to y + rows of a buffer were written: hand them to the display.
    /// `rows` 0 is all of them. What a caller that wrote the pixels itself
    /// calls when it has finished.
    pub fn RefreshBitMap(self: *RtgBase, bitmap: *rtg.RtgBitMap, y: u32, rows: u32) i32 {
        return libraries.call(self, LVO.RefreshBitMap, Fn.RefreshBitMap, .{ bitmap, y, rows });
    }

    /// Wait for `frames` blankings; 0 is the next one. Not from interrupts.
    pub fn WaitVBlank(self: *RtgBase, board: *rtg.RtgBoard, frames: u32) i32 {
        return libraries.call(self, LVO.WaitVBlank, Fn.WaitVBlank, .{ board, frames });
    }

    /// The display enable. Not the backlight.
    pub fn SetBoardDisplay(self: *RtgBase, board: *rtg.RtgBoard, on: bool) i32 {
        return libraries.call(self, LVO.SetBoardDisplay, Fn.SetBoardDisplay, .{ board, on });
    }

    /// 0 to 100, the right way round whatever the part does.
    pub fn SetBoardBrightness(self: *RtgBase, board: *rtg.RtgBoard, percent: u32) i32 {
        return libraries.call(self, LVO.SetBoardBrightness, Fn.SetBoardBrightness, .{ board, percent });
    }

    /// What it is now, 0 to 100.
    pub fn BoardBrightness(self: *RtgBase, board: *rtg.RtgBoard) u32 {
        return libraries.call(self, LVO.BoardBrightness, Fn.BoardBrightness, .{board});
    }

    /// Fill a rectangle, in the buffer's format, right-aligned. The rectangle
    /// is cut down to the buffer first; nothing of it inside is RTGERR_OK and
    /// no work. RTGERR_NOT_SUPPORTED unless the board's engine fills - the
    /// library does not draw.
    pub fn FillRect(self: *RtgBase, dest: *rtg.RtgBitMap, area: *const rtg.RtgRect, color: u32) i32 {
        return libraries.call(self, LVO.FillRect, Fn.FillRect, .{ dest, area, color });
    }

    /// Complement every pixel of a rectangle. Same rules as FillRect.
    pub fn InvertRect(self: *RtgBase, dest: *rtg.RtgBitMap, area: *const rtg.RtgRect) i32 {
        return libraries.call(self, LVO.InvertRect, Fn.InvertRect, .{ dest, area });
    }

    /// Copy a rectangle. The two buffers may be one and the rectangles may
    /// overlap. Same rules as FillRect.
    pub fn CopyRect(self: *RtgBase, src: *rtg.RtgBitMap, dest: *rtg.RtgBitMap, copy: *const rtg.RtgCopy) i32 {
        return libraries.call(self, LVO.CopyRect, Fn.CopyRect, .{ src, dest, copy });
    }

    /// A one-bit shape in two colours. Same rules as FillRect.
    pub fn BlitTemplate(self: *RtgBase, dest: *rtg.RtgBitMap, area: *const rtg.RtgRect, shape: *const rtg.RtgTemplate) i32 {
        return libraries.call(self, LVO.BlitTemplate, Fn.BlitTemplate, .{ dest, area, shape });
    }

    /// A one-bit tile, anchored to the buffer. Same rules as FillRect.
    pub fn BlitPattern(self: *RtgBase, dest: *rtg.RtgBitMap, area: *const rtg.RtgRect, tile: *const rtg.RtgPattern) i32 {
        return libraries.call(self, LVO.BlitPattern, Fn.BlitPattern, .{ dest, area, tile });
    }

    /// Wait until the board's engine has finished what it was given. Returns
    /// at once for a board that has none.
    pub fn WaitBlit(self: *RtgBase, board: *rtg.RtgBoard) void {
        return libraries.call(self, LVO.WaitBlit, Fn.WaitBlit, .{board});
    }

    /// Three eight-bit channels into one pixel of that format, right-aligned.
    pub fn PackRtgColor(self: *RtgBase, format: u32, red: u32, green: u32, blue: u32) u32 {
        return libraries.call(self, LVO.PackRtgColor, Fn.PackRtgColor, .{ format, red, green, blue });
    }

    /// One pixel of that format back into three eight-bit channels.
    pub fn UnpackRtgColor(self: *RtgBase, format: u32, color: u32, out: *rtg.RtgRGB) void {
        return libraries.call(self, LVO.UnpackRtgColor, Fn.UnpackRtgColor, .{ format, color, out });
    }

    /// Hand an RTGEV_* event of that board to your Interrupt, highest ln_Pri
    /// first. is_Code is an RtgEventFn and runs in interrupt context. False
    /// for an event that does not exist.
    pub fn AddRtgEventServer(self: *RtgBase, board: *rtg.RtgBoard, event: u32, server: *exec.Interrupt) bool {
        return libraries.call(self, LVO.AddRtgEventServer, Fn.AddRtgEventServer, .{ board, event, server });
    }

    /// Take it off again.
    pub fn RemRtgEventServer(self: *RtgBase, board: *rtg.RtgBoard, event: u32, server: *exec.Interrupt) void {
        return libraries.call(self, LVO.RemRtgEventServer, Fn.RemRtgEventServer, .{ board, event, server });
    }

    /// Tell a board's servers that something happened. A driver calls it from
    /// its own interrupt; returns what the chain answered.
    pub fn SignalRtgEvent(self: *RtgBase, board: *rtg.RtgBoard, event: u32) i32 {
        return libraries.call(self, LVO.SignalRtgEvent, Fn.SignalRtgEvent, .{ board, event });
    }

    /// A bus from that driver, set up by the tags (RTGA_*). Null:
    /// RtgLastError says why.
    pub fn CreateTransportTagList(self: *RtgBase, driver_name: [*:0]const u8, tag_list: ?[*]const utility.TagItem) ?*rtg.RtgTransport {
        return libraries.call(self, LVO.CreateTransportTagList, Fn.CreateTransportTagList, .{ driver_name, tag_list });
    }

    /// Give a bus back. Refused while a board is still on it. Null does
    /// nothing.
    pub fn DeleteTransport(self: *RtgBase, io: ?*rtg.RtgTransport) void {
        return libraries.call(self, LVO.DeleteTransport, Fn.DeleteTransport, .{io});
    }

    /// A command and its parameters to the part. A command below zero sends
    /// the parameters alone.
    pub fn TxParam(self: *RtgBase, io: *rtg.RtgTransport, cmd: i32, param: ?*const anyopaque, size: u32) i32 {
        return libraries.call(self, LVO.TxParam, Fn.TxParam, .{ io, cmd, param, size });
    }

    /// A command and a run of pixels. It may come back before the bytes have
    /// gone; RTGEV_TX_DONE says when they have.
    pub fn TxColor(self: *RtgBase, io: *rtg.RtgTransport, cmd: i32, color: ?*const anyopaque, size: u32) i32 {
        return libraries.call(self, LVO.TxColor, Fn.TxColor, .{ io, cmd, color, size });
    }

    /// Send a command and read `size` bytes back, with nothing else reaching
    /// the bus in between.
    pub fn RxParam(self: *RtgBase, io: *rtg.RtgTransport, cmd: i32, buffer: ?*anyopaque, size: u32) i32 {
        return libraries.call(self, LVO.RxParam, Fn.RxParam, .{ io, cmd, buffer, size });
    }

    /// A tag's data, or `default_value` if it is not in the list. Here so a
    /// driver need open nothing but this library.
    pub fn GetRtgTagData(self: *RtgBase, tag_value: utility.Tag, default_value: usize, tag_list: ?[*]const utility.TagItem) usize {
        return libraries.call(self, LVO.GetRtgTagData, Fn.GetRtgTagData, .{ tag_value, default_value, tag_list });
    }

    /// The tag of that value in the list, or null. Follows TAG_MORE.
    pub fn FindRtgTagItem(self: *RtgBase, tag_value: utility.Tag, tag_list: ?[*]const utility.TagItem) ?*const utility.TagItem {
        return libraries.call(self, LVO.FindRtgTagItem, Fn.FindRtgTagItem, .{ tag_value, tag_list });
    }

    /// The error of the last call that had nowhere to return one: the calls
    /// that answer with a pointer. One word for the whole library, not one
    /// per task; RTGA_ErrorPtr gives a caller its own.
    pub fn RtgLastError(self: *RtgBase) i32 {
        return libraries.call(self, LVO.RtgLastError, Fn.RtgLastError, .{});
    }

    /// An error in words. Never null.
    pub fn RtgErrorText(self: *RtgBase, error_code: i32) [*:0]const u8 {
        return libraries.call(self, LVO.RtgErrorText, Fn.RtgErrorText, .{error_code});
    }

    /// Mirror the picture about each axis. RTGERR_NOT_SUPPORTED unless the
    /// board can do it itself, in which case turning the picture is the
    /// business of whoever draws it.
    pub fn MirrorBoard(self: *RtgBase, board: *rtg.RtgBoard, mirror_x: bool, mirror_y: bool) i32 {
        return libraries.call(self, LVO.MirrorBoard, Fn.MirrorBoard, .{ board, mirror_x, mirror_y });
    }

    /// Exchange the board's axes; with MirrorBoard that is every right-angle
    /// turn. GetBoardInfo's width and height follow, since they are what a
    /// caller draws on.
    pub fn SwapBoardAxes(self: *RtgBase, board: *rtg.RtgBoard, swap: bool) i32 {
        return libraries.call(self, LVO.SwapBoardAxes, Fn.SwapBoardAxes, .{ board, swap });
    }

    /// The offset added to every coordinate, for glass whose visible area does
    /// not start where the controller's does.
    pub fn SetBoardGap(self: *RtgBase, board: *rtg.RtgBoard, gap_x: u32, gap_y: u32) i32 {
        return libraries.call(self, LVO.SetBoardGap, Fn.SetBoardGap, .{ board, gap_x, gap_y });
    }
};
