// SPDX-License-Identifier: MIT
//! timer.device's functions, after BeginIO and AbortIO: time arithmetic,
//! the E-clock and the system time. The base is the device's: io_Device of an open request.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/timer_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const timer = @import("../devices/timer.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "timer.device";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const AddTime = libraries.lvo(6);
    pub const SubTime = libraries.lvo(7);
    pub const CmpTime = libraries.lvo(8);
    pub const ReadEClock = libraries.lvo(9);
    pub const GetSysTime = libraries.lvo(10);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const AddTime = *const fn (*TimerBase, *timer.TimeVal, *const timer.TimeVal) callconv(.c) void;
    pub const SubTime = *const fn (*TimerBase, *timer.TimeVal, *const timer.TimeVal) callconv(.c) void;
    pub const CmpTime = *const fn (*TimerBase, *const timer.TimeVal, *const timer.TimeVal) callconv(.c) i32;
    pub const ReadEClock = *const fn (*TimerBase, *timer.EClockVal) callconv(.c) u32;
    pub const GetSysTime = *const fn (*TimerBase, *timer.TimeVal) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const TimerBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *TimerBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// dest += src, the microseconds carried into the seconds.
    pub fn AddTime(self: *TimerBase, dest: *timer.TimeVal, src: *const timer.TimeVal) void {
        return libraries.call(self, LVO.AddTime, Fn.AddTime, .{ dest, src });
    }

    /// dest -= src, borrowing a second when needed.
    pub fn SubTime(self: *TimerBase, dest: *timer.TimeVal, src: *const timer.TimeVal) void {
        return libraries.call(self, LVO.SubTime, Fn.SubTime, .{ dest, src });
    }

    /// 0 if they are equal, -1 if dest is later than src, +1 if it is earlier.
    pub fn CmpTime(self: *TimerBase, dest: *const timer.TimeVal, src: *const timer.TimeVal) i32 {
        return libraries.call(self, LVO.CmpTime, Fn.CmpTime, .{ dest, src });
    }

    /// The E-clock count now into dest; returns the E-clock's rate in Hz.
    pub fn ReadEClock(self: *TimerBase, dest: *timer.EClockVal) u32 {
        return libraries.call(self, LVO.ReadEClock, Fn.ReadEClock, .{dest});
    }

    /// The system time into dest. It only ever rises and never repeats.
    pub fn GetSysTime(self: *TimerBase, dest: *timer.TimeVal) void {
        return libraries.call(self, LVO.GetSysTime, Fn.GetSysTime, .{dest});
    }
};
