// SPDX-License-Identifier: MIT
//! tls.library's functions: TLS 1.3 sessions over stream sockets a
//! program connected - the handshake, the server's certificates checked
//! against the trusted roots, then plain bytes read and written. Open it
//! with OpenLibrary("tls.library", 1); the structures are in sdk.tls.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/tls_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const tls = @import("../libs/tls/tls.zig");
const utility = @import("../libs/utility/utility.zig");
const bsdsocket = @import("../interface/bsdsocket.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "tls.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const OpenSession = libraries.lvo(4);
    pub const CloseSession = libraries.lvo(5);
    pub const ReadSession = libraries.lvo(6);
    pub const WriteSession = libraries.lvo(7);
    pub const SessionPending = libraries.lvo(8);
    pub const GetSessionAttr = libraries.lvo(9);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const OpenSession = *const fn (*TLSBase, *bsdsocket.SocketBase, i32, ?[*]const utility.TagItem, ?*i32) callconv(.c) ?*tls.Session;
    pub const CloseSession = *const fn (*TLSBase, ?*tls.Session) callconv(.c) void;
    pub const ReadSession = *const fn (*TLSBase, *tls.Session, *anyopaque, u32) callconv(.c) i32;
    pub const WriteSession = *const fn (*TLSBase, *tls.Session, *const anyopaque, u32) callconv(.c) i32;
    pub const SessionPending = *const fn (*TLSBase, *tls.Session) callconv(.c) u32;
    pub const GetSessionAttr = *const fn (*TLSBase, *tls.Session, utility.Tag) callconv(.c) usize;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const TLSBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *TLSBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// A session over `socket`, a connected stream socket of the program's
    /// `socket_base`: the handshake done and the server checked. Null, and
    /// why in `err` (TLSERR_*), when it failed.
    pub fn OpenSession(self: *TLSBase, socket_base: *bsdsocket.SocketBase, socket: i32, tags: ?[*]const utility.TagItem, err: ?*i32) ?*tls.Session {
        return libraries.call(self, LVO.OpenSession, Fn.OpenSession, .{ socket_base, socket, tags, err });
    }

    /// The session ended - close_notify sent - and freed. The socket stays
    /// the program's, to close.
    pub fn CloseSession(self: *TLSBase, session: ?*tls.Session) void {
        return libraries.call(self, LVO.CloseSession, Fn.CloseSession, .{session});
    }

    /// Up to `length` bytes from the server into `buffer`: how many, 0 when
    /// it closed the session, a TLSERR_* below 0.
    pub fn ReadSession(self: *TLSBase, session: *tls.Session, buffer: *anyopaque, length: u32) i32 {
        return libraries.call(self, LVO.ReadSession, Fn.ReadSession, .{ session, buffer, length });
    }

    /// `length` bytes to the server: `length`, or a TLSERR_* below 0.
    pub fn WriteSession(self: *TLSBase, session: *tls.Session, data: *const anyopaque, length: u32) i32 {
        return libraries.call(self, LVO.WriteSession, Fn.WriteSession, .{ session, data, length });
    }

    /// How many bytes ReadSession has decrypted and waiting: WaitSelect sees
    /// only the socket, not these.
    pub fn SessionPending(self: *TLSBase, session: *tls.Session) u32 {
        return libraries.call(self, LVO.SessionPending, Fn.SessionPending, .{session});
    }

    /// One of the session's attributes (TLS_Version, TLS_Suite, TLS_Verdict,
    /// TLS_Alert, TLS_Error, TLS_Protocol); 0 for one it does not know.
    pub fn GetSessionAttr(self: *TLSBase, session: *tls.Session, attr: utility.Tag) usize {
        return libraries.call(self, LVO.GetSessionAttr, Fn.GetSessionAttr, .{ session, attr });
    }
};
