// SPDX-License-Identifier: MIT
//! truetype.library's functions: a TrueType file rendered into font
//! images, one size at a time. Open it with
//! OpenLibrary("truetype.library", 1).
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/truetype_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const graphics = @import("../libs/graphics/graphics.zig");
const truetype = @import("../libs/truetype/truetype.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "truetype.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const OpenOutline = libraries.lvo(4);
    pub const RenderFontImage = libraries.lvo(5);
    pub const CloseOutline = libraries.lvo(6);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const OpenOutline = *const fn (*TrueTypeBase, [*]const u8, u32) callconv(.c) ?*truetype.Outline;
    pub const RenderFontImage = *const fn (*TrueTypeBase, *truetype.Outline, u32, u32, u32) callconv(.c) ?*graphics.fontimage.FontImage;
    pub const CloseOutline = *const fn (*TrueTypeBase, ?*truetype.Outline) callconv(.c) void;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const TrueTypeBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *TrueTypeBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// The font in `size` bytes at `file`, its tables found and checked; null
    /// if it is not a TrueType font this library reads. The bytes must stay
    /// until CloseOutline.
    pub fn OpenOutline(self: *TrueTypeBase, file: [*]const u8, size: u32) ?*truetype.Outline {
        return libraries.call(self, LVO.OpenOutline, Fn.OpenOutline, .{ file, size });
    }

    /// The outline rendered `rows` rows tall, codes `first` to `last` and a
    /// default glyph, as a font image; the caller frees it with FreeVec. Null
    /// for a height of 0 or no memory.
    pub fn RenderFontImage(self: *TrueTypeBase, outline: *truetype.Outline, rows: u32, first: u32, last: u32) ?*graphics.fontimage.FontImage {
        return libraries.call(self, LVO.RenderFontImage, Fn.RenderFontImage, .{ outline, rows, first, last });
    }

    /// What OpenOutline made, given back. Null does nothing.
    pub fn CloseOutline(self: *TrueTypeBase, outline: ?*truetype.Outline) void {
        return libraries.call(self, LVO.CloseOutline, Fn.CloseOutline, .{outline});
    }
};
