// SPDX-License-Identifier: MIT
//! utility.library's jump table: tag lists, hooks, dates, 32- and 64-bit
//! multiplication and division, Latin-1 case, pack tables, named objects,
//! unique IDs, pattern matching, strings and alignment. The reserved slots
//! are kept free so that the slots after them stay where they are.
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/utility_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const exec = @import("../libs/exec/exec.zig");
const utility = @import("../libs/utility/utility.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "utility.library";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const FindTagItem = libraries.lvo(4);
    pub const GetTagData = libraries.lvo(5);
    pub const PackBoolTags = libraries.lvo(6);
    pub const NextTagItem = libraries.lvo(7);
    pub const FilterTagChanges = libraries.lvo(8);
    pub const MapTags = libraries.lvo(9);
    pub const AllocateTagItems = libraries.lvo(10);
    pub const CloneTagItems = libraries.lvo(11);
    pub const FreeTagItems = libraries.lvo(12);
    pub const RefreshTagItemClones = libraries.lvo(13);
    pub const TagInArray = libraries.lvo(14);
    pub const FilterTagItems = libraries.lvo(15);
    pub const CallHookPkt = libraries.lvo(16);
    pub const Amiga2Date = libraries.lvo(19);
    pub const Date2Amiga = libraries.lvo(20);
    pub const CheckDate = libraries.lvo(21);
    pub const SMult32 = libraries.lvo(22);
    pub const UMult32 = libraries.lvo(23);
    pub const SDivMod32 = libraries.lvo(24);
    pub const UDivMod32 = libraries.lvo(25);
    pub const Stricmp = libraries.lvo(26);
    pub const Strnicmp = libraries.lvo(27);
    pub const ToUpper = libraries.lvo(28);
    pub const ToLower = libraries.lvo(29);
    pub const ApplyTagChanges = libraries.lvo(30);
    pub const SMult64 = libraries.lvo(32);
    pub const UMult64 = libraries.lvo(33);
    pub const PackStructureTags = libraries.lvo(34);
    pub const UnpackStructureTags = libraries.lvo(35);
    pub const AddNamedObject = libraries.lvo(36);
    pub const AllocNamedObjectA = libraries.lvo(37);
    pub const AttemptRemNamedObject = libraries.lvo(38);
    pub const FindNamedObject = libraries.lvo(39);
    pub const FreeNamedObject = libraries.lvo(40);
    pub const NamedObjectName = libraries.lvo(41);
    pub const ReleaseNamedObject = libraries.lvo(42);
    pub const RemNamedObject = libraries.lvo(43);
    pub const GetUniqueID = libraries.lvo(44);
    pub const ParsePattern = libraries.lvo(49);
    pub const ParsePatternNoCase = libraries.lvo(50);
    pub const MatchPattern = libraries.lvo(51);
    pub const MatchPatternNoCase = libraries.lvo(52);
    pub const SetWildStar = libraries.lvo(53);
    pub const Strcmp = libraries.lvo(54);
    pub const Strlen = libraries.lvo(55);
    pub const AlignUp = libraries.lvo(56);
    pub const AlignDown = libraries.lvo(57);
    pub const Strlcpy = libraries.lvo(58);
    pub const Strchr = libraries.lvo(59);
    pub const Strrchr = libraries.lvo(60);
    pub const DateSplit = libraries.lvo(61);
    pub const DateJoin = libraries.lvo(62);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const FindTagItem = *const fn (*UtilityBase, utility.Tag, ?[*]const utility.TagItem) callconv(.c) ?*const utility.TagItem;
    pub const GetTagData = *const fn (*UtilityBase, utility.Tag, usize, ?[*]const utility.TagItem) callconv(.c) usize;
    pub const PackBoolTags = *const fn (*UtilityBase, u32, ?[*]const utility.TagItem, ?[*]const utility.TagItem) callconv(.c) u32;
    pub const NextTagItem = *const fn (*UtilityBase, *?[*]const utility.TagItem) callconv(.c) ?*const utility.TagItem;
    pub const FilterTagChanges = *const fn (*UtilityBase, ?[*]utility.TagItem, ?[*]utility.TagItem, u32) callconv(.c) void;
    pub const MapTags = *const fn (*UtilityBase, ?[*]utility.TagItem, ?[*]const utility.TagItem, u32) callconv(.c) void;
    pub const AllocateTagItems = *const fn (*UtilityBase, u32) callconv(.c) ?[*]utility.TagItem;
    pub const CloneTagItems = *const fn (*UtilityBase, ?[*]const utility.TagItem) callconv(.c) ?[*]utility.TagItem;
    pub const FreeTagItems = *const fn (*UtilityBase, ?[*]utility.TagItem) callconv(.c) void;
    pub const RefreshTagItemClones = *const fn (*UtilityBase, ?[*]utility.TagItem, ?[*]const utility.TagItem) callconv(.c) void;
    pub const TagInArray = *const fn (*UtilityBase, utility.Tag, ?[*]const utility.Tag) callconv(.c) bool;
    pub const FilterTagItems = *const fn (*UtilityBase, ?[*]utility.TagItem, ?[*]const utility.Tag, u32) callconv(.c) u32;
    pub const CallHookPkt = *const fn (*UtilityBase, *utility.Hook, ?*anyopaque, ?*anyopaque) callconv(.c) usize;
    pub const Amiga2Date = *const fn (*UtilityBase, u32, *utility.ClockData) callconv(.c) void;
    pub const Date2Amiga = *const fn (*UtilityBase, *const utility.ClockData) callconv(.c) u32;
    pub const CheckDate = *const fn (*UtilityBase, *const utility.ClockData) callconv(.c) u32;
    pub const SMult32 = *const fn (*UtilityBase, i32, i32) callconv(.c) i32;
    pub const UMult32 = *const fn (*UtilityBase, u32, u32) callconv(.c) u32;
    pub const SDivMod32 = *const fn (*UtilityBase, i32, i32) callconv(.c) utility.SDivMod32Result;
    pub const UDivMod32 = *const fn (*UtilityBase, u32, u32) callconv(.c) utility.UDivMod32Result;
    pub const Stricmp = *const fn (*UtilityBase, [*:0]const u8, [*:0]const u8) callconv(.c) i32;
    pub const Strnicmp = *const fn (*UtilityBase, [*:0]const u8, [*:0]const u8, i32) callconv(.c) i32;
    pub const ToUpper = *const fn (*UtilityBase, u32) callconv(.c) u8;
    pub const ToLower = *const fn (*UtilityBase, u32) callconv(.c) u8;
    pub const ApplyTagChanges = *const fn (*UtilityBase, ?[*]utility.TagItem, ?[*]const utility.TagItem) callconv(.c) void;
    pub const SMult64 = *const fn (*UtilityBase, i32, i32) callconv(.c) i64;
    pub const UMult64 = *const fn (*UtilityBase, u32, u32) callconv(.c) u64;
    pub const PackStructureTags = *const fn (*UtilityBase, ?*anyopaque, ?[*]const u32, ?[*]const utility.TagItem) callconv(.c) u32;
    pub const UnpackStructureTags = *const fn (*UtilityBase, ?*const anyopaque, ?[*]const u32, ?[*]const utility.TagItem) callconv(.c) u32;
    pub const AddNamedObject = *const fn (*UtilityBase, ?*utility.NamedObject, ?*utility.NamedObject) callconv(.c) bool;
    pub const AllocNamedObjectA = *const fn (*UtilityBase, ?[*:0]const u8, ?[*]const utility.TagItem) callconv(.c) ?*utility.NamedObject;
    pub const AttemptRemNamedObject = *const fn (*UtilityBase, ?*utility.NamedObject) callconv(.c) i32;
    pub const FindNamedObject = *const fn (*UtilityBase, ?*utility.NamedObject, ?[*:0]const u8, ?*utility.NamedObject) callconv(.c) ?*utility.NamedObject;
    pub const FreeNamedObject = *const fn (*UtilityBase, ?*utility.NamedObject) callconv(.c) void;
    pub const NamedObjectName = *const fn (*UtilityBase, ?*utility.NamedObject) callconv(.c) ?[*:0]const u8;
    pub const ReleaseNamedObject = *const fn (*UtilityBase, ?*utility.NamedObject) callconv(.c) void;
    pub const RemNamedObject = *const fn (*UtilityBase, ?*utility.NamedObject, ?*exec.Message) callconv(.c) void;
    pub const GetUniqueID = *const fn (*UtilityBase) callconv(.c) u32;
    pub const ParsePattern = *const fn (*UtilityBase, [*:0]const u8, [*]u8, usize) callconv(.c) isize;
    pub const ParsePatternNoCase = *const fn (*UtilityBase, [*:0]const u8, [*]u8, usize) callconv(.c) isize;
    pub const MatchPattern = *const fn (*UtilityBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const MatchPatternNoCase = *const fn (*UtilityBase, [*:0]const u8, [*:0]const u8) callconv(.c) bool;
    pub const SetWildStar = *const fn (*UtilityBase, bool) callconv(.c) bool;
    pub const Strcmp = *const fn (*UtilityBase, [*:0]const u8, [*:0]const u8) callconv(.c) i32;
    pub const Strlen = *const fn (*UtilityBase, [*:0]const u8) callconv(.c) usize;
    pub const AlignUp = *const fn (*UtilityBase, usize, usize) callconv(.c) usize;
    pub const AlignDown = *const fn (*UtilityBase, usize, usize) callconv(.c) usize;
    pub const Strlcpy = *const fn (*UtilityBase, [*]u8, usize, [*:0]const u8) callconv(.c) usize;
    pub const Strchr = *const fn (*UtilityBase, [*:0]const u8, u8) callconv(.c) ?[*:0]const u8;
    pub const Strrchr = *const fn (*UtilityBase, [*:0]const u8, u8) callconv(.c) ?[*:0]const u8;
    pub const DateSplit = *const fn (*UtilityBase, u32, *utility.ClockData) callconv(.c) void;
    pub const DateJoin = *const fn (*UtilityBase, *const utility.ClockData) callconv(.c) i32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const UtilityBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *UtilityBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    pub fn FindTagItem(self: *UtilityBase, tag_val: utility.Tag, tag_list: ?[*]const utility.TagItem) ?*const utility.TagItem {
        return libraries.call(self, LVO.FindTagItem, Fn.FindTagItem, .{ tag_val, tag_list });
    }

    pub fn GetTagData(self: *UtilityBase, tag_val: utility.Tag, default_value: usize, tag_list: ?[*]const utility.TagItem) usize {
        return libraries.call(self, LVO.GetTagData, Fn.GetTagData, .{ tag_val, default_value, tag_list });
    }

    pub fn PackBoolTags(self: *UtilityBase, initial_flags: u32, tag_list: ?[*]const utility.TagItem, bool_map: ?[*]const utility.TagItem) u32 {
        return libraries.call(self, LVO.PackBoolTags, Fn.PackBoolTags, .{ initial_flags, tag_list, bool_map });
    }

    pub fn NextTagItem(self: *UtilityBase, tag_list_ptr: *?[*]const utility.TagItem) ?*const utility.TagItem {
        return libraries.call(self, LVO.NextTagItem, Fn.NextTagItem, .{tag_list_ptr});
    }

    pub fn FilterTagChanges(self: *UtilityBase, change_list: ?[*]utility.TagItem, original_list: ?[*]utility.TagItem, apply: u32) void {
        return libraries.call(self, LVO.FilterTagChanges, Fn.FilterTagChanges, .{ change_list, original_list, apply });
    }

    pub fn MapTags(self: *UtilityBase, tag_list: ?[*]utility.TagItem, map_list: ?[*]const utility.TagItem, map_type: u32) void {
        return libraries.call(self, LVO.MapTags, Fn.MapTags, .{ tag_list, map_list, map_type });
    }

    pub fn AllocateTagItems(self: *UtilityBase, num_tags: u32) ?[*]utility.TagItem {
        return libraries.call(self, LVO.AllocateTagItems, Fn.AllocateTagItems, .{num_tags});
    }

    pub fn CloneTagItems(self: *UtilityBase, tag_list: ?[*]const utility.TagItem) ?[*]utility.TagItem {
        return libraries.call(self, LVO.CloneTagItems, Fn.CloneTagItems, .{tag_list});
    }

    pub fn FreeTagItems(self: *UtilityBase, tag_list: ?[*]utility.TagItem) void {
        return libraries.call(self, LVO.FreeTagItems, Fn.FreeTagItems, .{tag_list});
    }

    pub fn RefreshTagItemClones(self: *UtilityBase, clone: ?[*]utility.TagItem, original: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.RefreshTagItemClones, Fn.RefreshTagItemClones, .{ clone, original });
    }

    pub fn TagInArray(self: *UtilityBase, tag_val: utility.Tag, tag_array: ?[*]const utility.Tag) bool {
        return libraries.call(self, LVO.TagInArray, Fn.TagInArray, .{ tag_val, tag_array });
    }

    pub fn FilterTagItems(self: *UtilityBase, tag_list: ?[*]utility.TagItem, filter_array: ?[*]const utility.Tag, logic: u32) u32 {
        return libraries.call(self, LVO.FilterTagItems, Fn.FilterTagItems, .{ tag_list, filter_array, logic });
    }

    pub fn CallHookPkt(self: *UtilityBase, hook: *utility.Hook, object: ?*anyopaque, param_packet: ?*anyopaque) usize {
        return libraries.call(self, LVO.CallHookPkt, Fn.CallHookPkt, .{ hook, object, param_packet });
    }

    pub fn Amiga2Date(self: *UtilityBase, seconds: u32, result: *utility.ClockData) void {
        return libraries.call(self, LVO.Amiga2Date, Fn.Amiga2Date, .{ seconds, result });
    }

    pub fn Date2Amiga(self: *UtilityBase, clock_data: *const utility.ClockData) u32 {
        return libraries.call(self, LVO.Date2Amiga, Fn.Date2Amiga, .{clock_data});
    }

    pub fn CheckDate(self: *UtilityBase, clock_data: *const utility.ClockData) u32 {
        return libraries.call(self, LVO.CheckDate, Fn.CheckDate, .{clock_data});
    }

    pub fn SMult32(self: *UtilityBase, arg1: i32, arg2: i32) i32 {
        return libraries.call(self, LVO.SMult32, Fn.SMult32, .{ arg1, arg2 });
    }

    pub fn UMult32(self: *UtilityBase, arg1: u32, arg2: u32) u32 {
        return libraries.call(self, LVO.UMult32, Fn.UMult32, .{ arg1, arg2 });
    }

    pub fn SDivMod32(self: *UtilityBase, dividend: i32, divisor: i32) utility.SDivMod32Result {
        return libraries.call(self, LVO.SDivMod32, Fn.SDivMod32, .{ dividend, divisor });
    }

    pub fn UDivMod32(self: *UtilityBase, dividend: u32, divisor: u32) utility.UDivMod32Result {
        return libraries.call(self, LVO.UDivMod32, Fn.UDivMod32, .{ dividend, divisor });
    }

    pub fn Stricmp(self: *UtilityBase, string1: [*:0]const u8, string2: [*:0]const u8) i32 {
        return libraries.call(self, LVO.Stricmp, Fn.Stricmp, .{ string1, string2 });
    }

    pub fn Strnicmp(self: *UtilityBase, string1: [*:0]const u8, string2: [*:0]const u8, length: i32) i32 {
        return libraries.call(self, LVO.Strnicmp, Fn.Strnicmp, .{ string1, string2, length });
    }

    pub fn ToUpper(self: *UtilityBase, character: u32) u8 {
        return libraries.call(self, LVO.ToUpper, Fn.ToUpper, .{character});
    }

    pub fn ToLower(self: *UtilityBase, character: u32) u8 {
        return libraries.call(self, LVO.ToLower, Fn.ToLower, .{character});
    }

    pub fn ApplyTagChanges(self: *UtilityBase, list: ?[*]utility.TagItem, change_list: ?[*]const utility.TagItem) void {
        return libraries.call(self, LVO.ApplyTagChanges, Fn.ApplyTagChanges, .{ list, change_list });
    }

    pub fn SMult64(self: *UtilityBase, arg1: i32, arg2: i32) i64 {
        return libraries.call(self, LVO.SMult64, Fn.SMult64, .{ arg1, arg2 });
    }

    pub fn UMult64(self: *UtilityBase, arg1: u32, arg2: u32) u64 {
        return libraries.call(self, LVO.UMult64, Fn.UMult64, .{ arg1, arg2 });
    }

    pub fn PackStructureTags(self: *UtilityBase, structure: ?*anyopaque, pack_table: ?[*]const u32, tag_list: ?[*]const utility.TagItem) u32 {
        return libraries.call(self, LVO.PackStructureTags, Fn.PackStructureTags, .{ structure, pack_table, tag_list });
    }

    pub fn UnpackStructureTags(self: *UtilityBase, structure: ?*const anyopaque, pack_table: ?[*]const u32, tag_list: ?[*]const utility.TagItem) u32 {
        return libraries.call(self, LVO.UnpackStructureTags, Fn.UnpackStructureTags, .{ structure, pack_table, tag_list });
    }

    pub fn AddNamedObject(self: *UtilityBase, name_space: ?*utility.NamedObject, object: ?*utility.NamedObject) bool {
        return libraries.call(self, LVO.AddNamedObject, Fn.AddNamedObject, .{ name_space, object });
    }

    pub fn AllocNamedObjectA(self: *UtilityBase, name: ?[*:0]const u8, tag_list: ?[*]const utility.TagItem) ?*utility.NamedObject {
        return libraries.call(self, LVO.AllocNamedObjectA, Fn.AllocNamedObjectA, .{ name, tag_list });
    }

    pub fn AttemptRemNamedObject(self: *UtilityBase, object: ?*utility.NamedObject) i32 {
        return libraries.call(self, LVO.AttemptRemNamedObject, Fn.AttemptRemNamedObject, .{object});
    }

    pub fn FindNamedObject(self: *UtilityBase, name_space: ?*utility.NamedObject, name: ?[*:0]const u8, last_object: ?*utility.NamedObject) ?*utility.NamedObject {
        return libraries.call(self, LVO.FindNamedObject, Fn.FindNamedObject, .{ name_space, name, last_object });
    }

    pub fn FreeNamedObject(self: *UtilityBase, object: ?*utility.NamedObject) void {
        return libraries.call(self, LVO.FreeNamedObject, Fn.FreeNamedObject, .{object});
    }

    pub fn NamedObjectName(self: *UtilityBase, object: ?*utility.NamedObject) ?[*:0]const u8 {
        return libraries.call(self, LVO.NamedObjectName, Fn.NamedObjectName, .{object});
    }

    pub fn ReleaseNamedObject(self: *UtilityBase, object: ?*utility.NamedObject) void {
        return libraries.call(self, LVO.ReleaseNamedObject, Fn.ReleaseNamedObject, .{object});
    }

    pub fn RemNamedObject(self: *UtilityBase, object: ?*utility.NamedObject, message: ?*exec.Message) void {
        return libraries.call(self, LVO.RemNamedObject, Fn.RemNamedObject, .{ object, message });
    }

    pub fn GetUniqueID(self: *UtilityBase) u32 {
        return libraries.call(self, LVO.GetUniqueID, Fn.GetUniqueID, .{});
    }

    /// Make a pattern into tokens for MatchPattern, in `dest` of `size` bytes
    /// (utility.parsedSize(len) is always enough). 1 if it has wildcards, 0
    /// if not; -1 with IoErr() ERROR_BAD_TEMPLATE or ERROR_LINE_TOO_LONG, and
    /// an empty pattern in dest.
    pub fn ParsePattern(self: *UtilityBase, source: [*:0]const u8, dest: [*]u8, size: usize) isize {
        return libraries.call(self, LVO.ParsePattern, Fn.ParsePattern, .{ source, dest, size });
    }

    /// ParsePattern, upper-cased for MatchPatternNoCase (Latin-1).
    pub fn ParsePatternNoCase(self: *UtilityBase, source: [*:0]const u8, dest: [*]u8, size: usize) isize {
        return libraries.call(self, LVO.ParsePatternNoCase, Fn.ParsePatternNoCase, .{ source, dest, size });
    }

    /// Whether the string matches a pattern from ParsePattern. False also on
    /// IoErr() ERROR_TOO_MANY_LEVELS or ERROR_NO_FREE_STORE.
    pub fn MatchPattern(self: *UtilityBase, pattern: [*:0]const u8, string: [*:0]const u8) bool {
        return libraries.call(self, LVO.MatchPattern, Fn.MatchPattern, .{ pattern, string });
    }

    /// MatchPattern without case, for a pattern from ParsePatternNoCase.
    pub fn MatchPatternNoCase(self: *UtilityBase, pattern: [*:0]const u8, string: [*:0]const u8) bool {
        return libraries.call(self, LVO.MatchPatternNoCase, Fn.MatchPatternNoCase, .{ pattern, string });
    }

    /// Make `*` a wildcard (like `#?`) for the patterns parsed from now on, or
    /// a character again; returns the old setting. Off at first.
    pub fn SetWildStar(self: *UtilityBase, on: bool) bool {
        return libraries.call(self, LVO.SetWildStar, Fn.SetWildStar, .{on});
    }

    /// Compare two strings, case included: < 0, 0 or > 0 as string1 sorts
    /// before, the same as or after string2.
    pub fn Strcmp(self: *UtilityBase, string1: [*:0]const u8, string2: [*:0]const u8) i32 {
        return libraries.call(self, LVO.Strcmp, Fn.Strcmp, .{ string1, string2 });
    }

    /// The length of a string, without its NUL.
    pub fn Strlen(self: *UtilityBase, string: [*:0]const u8) usize {
        return libraries.call(self, LVO.Strlen, Fn.Strlen, .{string});
    }

    /// `offset` rounded up to the next multiple of `alignment`, a power of two.
    pub fn AlignUp(self: *UtilityBase, offset: usize, alignment: usize) usize {
        return libraries.call(self, LVO.AlignUp, Fn.AlignUp, .{ offset, alignment });
    }

    /// `offset` rounded down to a multiple of `alignment`, a power of two.
    pub fn AlignDown(self: *UtilityBase, offset: usize, alignment: usize) usize {
        return libraries.call(self, LVO.AlignDown, Fn.AlignDown, .{ offset, alignment });
    }

    /// Copy `source` into `dest` of `size` bytes: at most size - 1 of them,
    /// then a NUL. Returns the length of `source`, so a copy that was cut
    /// short answers size or more.
    pub fn Strlcpy(self: *UtilityBase, dest: [*]u8, size: usize, source: [*:0]const u8) usize {
        return libraries.call(self, LVO.Strlcpy, Fn.Strlcpy, .{ dest, size, source });
    }

    /// The first `character` in `string`, or null; 0 finds the NUL.
    pub fn Strchr(self: *UtilityBase, string: [*:0]const u8, character: u8) ?[*:0]const u8 {
        return libraries.call(self, LVO.Strchr, Fn.Strchr, .{ string, character });
    }

    /// The last `character` in `string`, or null; 0 finds the NUL.
    pub fn Strrchr(self: *UtilityBase, string: [*:0]const u8, character: u8) ?[*:0]const u8 {
        return libraries.call(self, LVO.Strrchr, Fn.Strrchr, .{ string, character });
    }

    /// A day number as a date: the year, the month (1-12), the day of the
    /// month and the weekday, with the time fields zeroed. The count is days
    /// since 1 January 1978, so it reaches far past the year the seconds of
    /// `Amiga2Date` stop at.
    pub fn DateSplit(self: *UtilityBase, days: u32, result: *utility.ClockData) void {
        return libraries.call(self, LVO.DateSplit, Fn.DateSplit, .{ days, result });
    }

    /// The day number a date comes to, counting from 1 January 1978, or -1
    /// when it is no date. Only the year, the month and the day of the month
    /// are read.
    pub fn DateJoin(self: *UtilityBase, date: *const utility.ClockData) i32 {
        return libraries.call(self, LVO.DateJoin, Fn.DateJoin, .{date});
    }
};
