// SPDX-License-Identifier: MIT
//! watchdog.resource's functions: the chip's watchdog timer (TIMG0's MWDT),
//! armed, fed and disarmed by programs. A resource: no Open or Close, its
//! first function in the first slot. The base comes from
//! OpenResource("watchdog.resource").
//!
//! Generated by sdk/tools/fd2zig from sdk/fd/watchdog_lib.fd: change that file
//! and run `zig build fd`, not this one.

const libraries = @import("../libs/exec/libraries.zig");
const watchdog = @import("../resources/watchdog.zig");

/// The name to open it by (OpenLibrary, OpenDevice).
pub const NAME = "watchdog.resource";

/// Each function's offset in the jump table (its LVO).
pub const LVO = struct {
    pub const ArmWatchdog = libraries.lvo(0);
    pub const FeedWatchdog = libraries.lvo(1);
    pub const DisarmWatchdog = libraries.lvo(2);
    pub const ReadWatchdog = libraries.lvo(3);
};

/// Each function's type, by its name in LVO. The first argument is the
/// library's base.
pub const Fn = struct {
    pub const ArmWatchdog = *const fn (*WatchdogBase, u32, u32) callconv(.c) bool;
    pub const FeedWatchdog = *const fn (*WatchdogBase) callconv(.c) void;
    pub const DisarmWatchdog = *const fn (*WatchdogBase) callconv(.c) void;
    pub const ReadWatchdog = *const fn (*WatchdogBase) callconv(.c) u32;
};

/// The library's base. Its methods are the library's functions, and
/// each calls through the jump table.
pub const WatchdogBase = opaque {
    /// The Library header at the base.
    pub fn lib(self: *WatchdogBase) *libraries.Library {
        return @ptrCast(@alignCast(self));
    }

    /// Arm the watchdog: after `millis` ms without a FeedWatchdog it does
    /// `action` (WATCHDOG_RESET_SYSTEM or WATCHDOG_RESET_CPU). Armed again, it
    /// starts over. False for 0 ms, too long a time, or another action.
    pub fn ArmWatchdog(self: *WatchdogBase, millis: u32, action: u32) bool {
        return libraries.call(self, LVO.ArmWatchdog, Fn.ArmWatchdog, .{ millis, action });
    }

    /// Start the armed time over.
    pub fn FeedWatchdog(self: *WatchdogBase) void {
        return libraries.call(self, LVO.FeedWatchdog, Fn.FeedWatchdog, .{});
    }

    /// Stop the watchdog.
    pub fn DisarmWatchdog(self: *WatchdogBase) void {
        return libraries.call(self, LVO.DisarmWatchdog, Fn.DisarmWatchdog, .{});
    }

    /// The armed time in ms, 0 while it is disarmed.
    pub fn ReadWatchdog(self: *WatchdogBase) u32 {
        return libraries.call(self, LVO.ReadWatchdog, Fn.ReadWatchdog, .{});
    }
};
